antioch-0.4.0: Antioch::KineticsConditions< StateType, VectorStateType > Class Template Reference
Antioch::KineticsConditions< StateType, VectorStateType > Class Template Reference
This class contains the conditions of the chemistry.
#include <kinetics_conditions.h>
Public Member Functions
KineticsConditions (const StateType &temperature)
~KineticsConditions ()
void add_particle_flux (const ParticleFlux< VectorStateType > &pf, unsigned int nr)
const StateType & T () const
const StateType & Tvib () const
returns the temperature T,
const TempCache< StateType > & temp_cache () const
const ParticleFlux
< VectorStateType > & particle_flux (int nr) const
Private Member Functions
KineticsConditions ()
Private Attributes
TempCache< StateType > _temperature
std::map< unsigned int,
ParticleFlux< VectorStateType >
const *const > _map_pf
Detailed Description
template<typename StateType, typename VectorStateType = std::vector<StateType>>
class Antioch::KineticsConditions< StateType, VectorStateType >
This class contains the conditions of the chemistry.
Conditions are:
Temperature(s)
particle flux
any other not yet implemented conditions (catalysis for instance)
Pressure is given by the molecular composition of the mixture, we are in a gaz phase, so the state equation will give pressure (typically ideal gas).
The idea is to avoid any copy of anything as much as we can, we store pointers but deal only with references. Nothing belongs to this object, if there is any cleaning to do, it must be done elsewhere.
Might be interesting to see about the "double" case for temperature: faster to copy instead of copying the reference, and it's expected to be the classic case.
Definition at line 64 of file kinetics_conditions.h.
Constructor & Destructor Documentation
template<typename StateType , typename VectorStateType > Antioch::KineticsConditions< StateType, VectorStateType >::KineticsConditions (const StateType & temperature) inline
Definition at line 98 of file kinetics_conditions.h.
                                                                                                 :
         _temperature(temperature)
   {
     return;
   }
template<typename StateType , typename VectorStateType > Antioch::KineticsConditions< StateType, VectorStateType >::~KineticsConditions () inline
Definition at line 106 of file kinetics_conditions.h.
   {
     return;
   }
template<typename StateType, typename VectorStateType = std::vector<StateType>> Antioch::KineticsConditions< StateType, VectorStateType >::KineticsConditions () private
Member Function Documentation
template<typename StateType , typename VectorStateType > void Antioch::KineticsConditions< StateType, VectorStateType >::add_particle_flux (const ParticleFlux< VectorStateType > & pf, unsigned int nr) inline
Definition at line 113 of file kinetics_conditions.h.
Referenced by tester().
   {
      _map_pf.insert(std::make_pair(nr, &pf));
   }
template<typename StateType , typename VectorStateType > const ParticleFlux< VectorStateType > & Antioch::KineticsConditions< StateType, VectorStateType >::particle_flux (int nr) const inline
Definition at line 134 of file kinetics_conditions.h.
References antioch_assert.
Referenced by Antioch::KineticsType< CoeffType, VectorCoeffType >::compute_rate_and_derivative(), Antioch::KineticsType< CoeffType, VectorCoeffType >::derivative(), and Antioch::KineticsType< CoeffType, VectorCoeffType >::operator()().
   {
      antioch_assert(_map_pf.count(nr));
      return *(_map_pf.at(nr));
   }
template<typename StateType , typename VectorStateType > const StateType & Antioch::KineticsConditions< StateType, VectorStateType >::T () const inline
Definition at line 120 of file kinetics_conditions.h.
Referenced by Antioch::FalloffReaction< CoeffType, FalloffType >::compute_forward_rate_coefficient(), Antioch::FalloffThreeBodyReaction< CoeffType, FalloffType >::compute_forward_rate_coefficient(), Antioch::Reaction< CoeffType, VectorCoeffType >::compute_forward_rate_coefficient(), Antioch::DuplicateReaction< CoeffType >::compute_forward_rate_coefficient_and_derivatives(), Antioch::FalloffReaction< CoeffType, FalloffType >::compute_forward_rate_coefficient_and_derivatives(), Antioch::FalloffThreeBodyReaction< CoeffType, FalloffType >::compute_forward_rate_coefficient_and_derivatives(), Antioch::Reaction< CoeffType, VectorCoeffType >::compute_rate_of_progress_and_derivatives(), Antioch::ReactionSet< CoeffType >::compute_reaction_rates(), Antioch::ReactionSet< CoeffType >::compute_reaction_rates_and_derivs(), Antioch::KineticsType< CoeffType, VectorCoeffType >::derivative(), Antioch::ReactionSet< CoeffType >::get_reactive_scheme(), and Antioch::KineticsType< CoeffType, VectorCoeffType >::operator()().
   {
      return _temperature.T;
   }
template<typename StateType , typename VectorStateType > const TempCache< StateType > & Antioch::KineticsConditions< StateType, VectorStateType >::temp_cache () const inline
Definition at line 142 of file kinetics_conditions.h.
   {
      return _temperature;
   }
template<typename StateType , typename VectorStateType > const StateType & Antioch::KineticsConditions< StateType, VectorStateType >::Tvib () const inline
returns the temperature T,
Definition at line 127 of file kinetics_conditions.h.
   {
      return _temperature.T;
   }
Member Data Documentation
template<typename StateType, typename VectorStateType = std::vector<StateType>> std::map<unsigned int,ParticleFlux<VectorStateType> const * const > Antioch::KineticsConditions< StateType, VectorStateType >::_map_pf private
Definition at line 91 of file kinetics_conditions.h.
template<typename StateType, typename VectorStateType = std::vector<StateType>> TempCache<StateType> Antioch::KineticsConditions< StateType, VectorStateType >::_temperature private
Definition at line 88 of file kinetics_conditions.h.
The documentation for this class was generated from the following file:
src/core/include/antioch/kinetics_conditions.h