antioch-0.4.0: Antioch::ChemicalSpecies< CoeffType > Class Template Reference
Antioch::ChemicalSpecies< CoeffType > Class Template Reference
Class to encapsulate data for each chemical species.
#include <chemical_species.h>
Public Member Functions
ChemicalSpecies (const std::string &name, const CoeffType mol_wght, const CoeffType h_form, const CoeffType n_tr_dofs, const int charge)
Constrctor.
ChemicalSpecies ()
Default constructor.
~ChemicalSpecies ()
Destructor.
const std::string & species () const
Returns a descriptive name for this species.
CoeffType molar_mass () const
Returns the molar mass in (kg/mol)
CoeffType gas_constant () const
Returns the species ideal gas constant in [J/kg-K].
CoeffType formation_enthalpy () const
Returns formation enthalpy in units of [J/kg].
CoeffType n_tr_dofs () const
Returns number of translational degrees of freedom.
int charge () const
Returns electrical charge number.
bool has_vibrational_modes () const
Returns true if the chemical species has vibrational degrees.
unsigned int n_vibrational_modes () const
Returns true if the chemical species has vibrational degrees of freedom.
const std::vector< CoeffType > & theta_v () const
Characteristic vibrational temperature [K].
const std::vector< unsigned int > & ndg_v () const
Degeneracies for each vibrational mode.
const std::vector< CoeffType > & theta_e () const
Characteristic electronic excitation temperatures [K].
const std::vector< unsigned int > & ndg_e () const
Degeneracies for each electronic modes.
void add_vibrational_data (const CoeffType theta_v, const CoeffType ndg_v)
Supply vibrational data.
void add_electronic_data (const CoeffType theta_e, const CoeffType ndg_e)
Supply electronic data.
void print (std::ostream &os=std::cout) const
Formatted print.
Protected Attributes
const std::string _name
Name of chemical species.
const CoeffType _mol_wght
Molecular weight (or molar mass) in units of [kg/mol].
const CoeffType _R
Gas constant in units of [J/kg-K].
const CoeffType _h_form
Formation enthalpy in units of [J/kg].
const CoeffType _n_tr_dofs
Number of translational degrees of freedom.
const int _charge
Electrical charge number.
std::vector< CoeffType > _theta_v
Characteristic vibrational temperature in units of [K].
std::vector< unsigned int > _ndg_v
Degeneracies for each vibrational mode.
std::vector< CoeffType > _theta_e
Characteristic electronic temperature in units of [K].
std::vector< unsigned int > _ndg_e
Degeneracies for each electronic mode.
Friends
std::ostream & operator<< (std::ostream &os, const ChemicalSpecies< CoeffType > &species)
Formatted print.
Detailed Description
template<typename CoeffType = double>
class Antioch::ChemicalSpecies< CoeffType >
Class to encapsulate data for each chemical species.
This class is designed to store information relevant to a chemical species. All the data stored is constant for each species, so we store const for each variable. The idea is that this will be placed inside ChemicalMixture, which will be a singleton. This is stolen from the FIN-S class SpeciesChemistry.
Definition at line 54 of file chemical_species.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::ChemicalSpecies< CoeffType >::ChemicalSpecies (const std::string & name, const CoeffType mol_wght, const CoeffType h_form, const CoeffType n_tr_dofs, const int charge) inline
Constrctor.
Definition at line 268 of file chemical_species.h.
     : _name      (name),
       _mol_wght  (mol_wght),
       _R         (Constants::R_universal<CoeffType>()/mol_wght),
       _h_form    (h_form),
       _n_tr_dofs (n_tr_dofs),
       _charge    (charge)
   {
     return;
   }
template<typename CoeffType > Antioch::ChemicalSpecies< CoeffType >::ChemicalSpecies () inline
Default constructor.
This is technically required for any std::map value type (or operator[] breaks, at least). But, we never actually want to create a SpeciesChemistry implicitly, so we throw an error if this is ever used.
Definition at line 286 of file chemical_species.h.
References antioch_error.
     : _name("Err"),
       _mol_wght(0),
       _R(0),
       _h_form(0),
       _n_tr_dofs(0),
       _charge(0)
   {
     antioch_error();
     return;
   }
template<typename CoeffType > Antioch::ChemicalSpecies< CoeffType >::~ChemicalSpecies () inline
Destructor.
Definition at line 301 of file chemical_species.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType > void Antioch::ChemicalSpecies< CoeffType >::add_electronic_data (const CoeffType theta_e, const CoeffType ndg_e) inline
Supply electronic data.
Definition at line 259 of file chemical_species.h.
   {
     _theta_e.push_back(theta_e);
     _ndg_e.push_back(ndg_e);
   }
template<typename CoeffType > void Antioch::ChemicalSpecies< CoeffType >::add_vibrational_data (const CoeffType theta_v, const CoeffType ndg_v) inline
Supply vibrational data.
Definition at line 250 of file chemical_species.h.
   {
     _theta_v.push_back(theta_v);
     _ndg_v.push_back(ndg_v);
   }
template<typename CoeffType > int Antioch::ChemicalSpecies< CoeffType >::charge () const inline
Returns electrical charge number.
Definition at line 211 of file chemical_species.h.
Referenced by test_species().
   { return _charge; }
template<typename CoeffType > CoeffType Antioch::ChemicalSpecies< CoeffType >::formation_enthalpy () const inline
Returns formation enthalpy in units of [J/kg].
Definition at line 201 of file chemical_species.h.
Referenced by Antioch::StatMechThermodynamics< CoeffType >::e_0(), and test_species().
   { return _h_form; }
template<typename CoeffType > CoeffType Antioch::ChemicalSpecies< CoeffType >::gas_constant () const inline
Returns the species ideal gas constant in [J/kg-K].
where is the universal gas constant and is the species molar mass.
Definition at line 196 of file chemical_species.h.
Referenced by Antioch::StatMechThermodynamics< CoeffType >::cv_el(), Antioch::StatMechThermodynamics< CoeffType >::e_el(), Antioch::StatMechThermodynamics< CoeffType >::e_vib(), Antioch::StatMechThermodynamics< CoeffType >::h_tot(), and test_species().
   { return _R; }
template<typename CoeffType > bool Antioch::ChemicalSpecies< CoeffType >::has_vibrational_modes () const inline
Returns true if the chemical species has vibrational degrees.
Definition at line 216 of file chemical_species.h.
   { return !_theta_v.empty(); }
template<typename CoeffType > CoeffType Antioch::ChemicalSpecies< CoeffType >::molar_mass () const inline
Returns the molar mass in (kg/mol)
Definition at line 191 of file chemical_species.h.
Referenced by test_species().
   { return _mol_wght; }
template<typename CoeffType > CoeffType Antioch::ChemicalSpecies< CoeffType >::n_tr_dofs () const inline
Returns number of translational degrees of freedom.
Definition at line 206 of file chemical_species.h.
Referenced by test_species().
   { return _n_tr_dofs; }
template<typename CoeffType > unsigned int Antioch::ChemicalSpecies< CoeffType >::n_vibrational_modes () const inline
Returns true if the chemical species has vibrational degrees of freedom.
Definition at line 221 of file chemical_species.h.
References antioch_assert_equal_to.
   {
     antioch_assert_equal_to(_theta_v.size(), _ndg_v.size());
     return _theta_v.size();
   }
template<typename CoeffType > const std::vector< unsigned int > & Antioch::ChemicalSpecies< CoeffType >::ndg_e () const inline
Degeneracies for each electronic modes.
Definition at line 244 of file chemical_species.h.
Referenced by Antioch::StatMechThermodynamics< CoeffType >::cv_el(), and Antioch::StatMechThermodynamics< CoeffType >::e_el().
   { return _ndg_e; }
template<typename CoeffType > const std::vector< unsigned int > & Antioch::ChemicalSpecies< CoeffType >::ndg_v () const inline
Degeneracies for each vibrational mode.
Definition at line 234 of file chemical_species.h.
Referenced by Antioch::StatMechThermodynamics< CoeffType >::cv_vib_over_R(), and Antioch::StatMechThermodynamics< CoeffType >::e_vib().
   { return _ndg_v; }
template<typename CoeffType > void Antioch::ChemicalSpecies< CoeffType >::print (std::ostream & os = std::cout) const inline
Formatted print.
Defaults to std::cout.
Definition at line 309 of file chemical_species.h.
   {
     os << " -----------------------------\n"
        << "| Species " << this->species() << '\n'
        << " -----------------------------\n"
        << std::scientific
        << "  Mol Wgt = " << this->molar_mass() << '\n'
        << "  R       = " << this->gas_constant()     << '\n'
        << "  h0      = " << this->formation_enthalpy() << '\n'
        << "  n_tr    = " << this->n_tr_dofs() << '\n'
        << "  charge  = " << this->charge() << '\n';
     for (unsigned int l=0; l<this->theta_v().size(); l++)
       os << "  theta_v_" << l << " = " << this->theta_v()[l]
          << ", ndg = " << this->ndg_v()[l] << "\n";
     for (unsigned int l=0; l<this->theta_e().size(); l++)
       os << "  theta_e_" << l << " = " << this->theta_e()[l]
          << ", ndg = " << this->ndg_e()[l] << "\n";
     os << '\n';
     return;
   }
template<typename CoeffType > const std::string & Antioch::ChemicalSpecies< CoeffType >::species () const inline
Returns a descriptive name for this species.
Definition at line 186 of file chemical_species.h.
Referenced by test_species().
   { return _name; }
template<typename CoeffType > const std::vector< CoeffType > & Antioch::ChemicalSpecies< CoeffType >::theta_e () const inline
Characteristic electronic excitation temperatures [K].
Definition at line 239 of file chemical_species.h.
Referenced by Antioch::StatMechThermodynamics< CoeffType >::cv_el(), and Antioch::StatMechThermodynamics< CoeffType >::e_el().
   { return _theta_e; }
template<typename CoeffType > const std::vector< CoeffType > & Antioch::ChemicalSpecies< CoeffType >::theta_v () const inline
Characteristic vibrational temperature [K].
Definition at line 229 of file chemical_species.h.
Referenced by Antioch::StatMechThermodynamics< CoeffType >::cv_vib_over_R(), and Antioch::StatMechThermodynamics< CoeffType >::e_vib().
   { return _theta_v; }
Friends And Related Function Documentation
template<typename CoeffType = double> std::ostream& operator<< (std::ostream & os, const ChemicalSpecies< CoeffType > & species) friend
Formatted print.
Allows you to do std::cout << object << std::endl;
Definition at line 136 of file chemical_species.h.
     {
       species.print(os);
       return os;
     }
Member Data Documentation
template<typename CoeffType = double> const int Antioch::ChemicalSpecies< CoeffType >::_charge protected
Electrical charge number.
Definition at line 161 of file chemical_species.h.
template<typename CoeffType = double> const CoeffType Antioch::ChemicalSpecies< CoeffType >::_h_form protected
Formation enthalpy in units of [J/kg].
Definition at line 155 of file chemical_species.h.
template<typename CoeffType = double> const CoeffType Antioch::ChemicalSpecies< CoeffType >::_mol_wght protected
Molecular weight (or molar mass) in units of [kg/mol].
Definition at line 149 of file chemical_species.h.
template<typename CoeffType = double> const CoeffType Antioch::ChemicalSpecies< CoeffType >::_n_tr_dofs protected
Number of translational degrees of freedom.
Definition at line 158 of file chemical_species.h.
template<typename CoeffType = double> const std::string Antioch::ChemicalSpecies< CoeffType >::_name protected
Name of chemical species.
Definition at line 146 of file chemical_species.h.
template<typename CoeffType = double> std::vector<unsigned int> Antioch::ChemicalSpecies< CoeffType >::_ndg_e protected
Degeneracies for each electronic mode.
Definition at line 173 of file chemical_species.h.
template<typename CoeffType = double> std::vector<unsigned int> Antioch::ChemicalSpecies< CoeffType >::_ndg_v protected
Degeneracies for each vibrational mode.
Definition at line 167 of file chemical_species.h.
template<typename CoeffType = double> const CoeffType Antioch::ChemicalSpecies< CoeffType >::_R protected
Gas constant in units of [J/kg-K].
Definition at line 152 of file chemical_species.h.
template<typename CoeffType = double> std::vector<CoeffType> Antioch::ChemicalSpecies< CoeffType >::_theta_e protected
Characteristic electronic temperature in units of [K].
Definition at line 170 of file chemical_species.h.
template<typename CoeffType = double> std::vector<CoeffType> Antioch::ChemicalSpecies< CoeffType >::_theta_v protected
Characteristic vibrational temperature in units of [K].
Definition at line 164 of file chemical_species.h.
The documentation for this class was generated from the following file:
src/core/include/antioch/chemical_species.h