antioch-0.4.0: AntiochTesting::ArrheniusRateFloatTest Class Reference
AntiochTesting::ArrheniusRateFloatTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (ArrheniusRateFloatTest)
CPPUNIT_TEST (test_standard)
CPPUNIT_TEST (test_reset_scalar_params)
CPPUNIT_TEST (test_reset_vector_params2)
CPPUNIT_TEST (test_reset_vector_params3)
CPPUNIT_TEST_SUITE_END ()
void setUp ()
void tearDown ()
void test_standard ()
void test_reset_scalar_params ()
void test_reset_vector_params2 ()
void test_reset_vector_params3 ()
void test_rate (const Antioch::ArrheniusRate< float > &reaction_rate, floattol)
void test_deriv (const Antioch::ArrheniusRate< float > &reaction_rate, floattol)
void test_rate_and_deriv (const Antioch::ArrheniusRate< float > &reaction_rate, floattol)
Protected Member Functions
virtual float exact_rate (floatT)
virtual float exact_deriv (floatT)
void reset_params (floatCf, floatEa)
void reset_params (floatCf, floatEa, floatR)
float value (floatT)
float deriv (floatT)
Protected Attributes
Antioch::ArrheniusRate< float > * _rate
float _Cf
float _Ea
float _R
Detailed Description
Definition at line 148 of file arrhenius_rate_test.C.
Member Function Documentation
AntiochTesting::ArrheniusRateFloatTest::CPPUNIT_TEST (test_standard)
AntiochTesting::ArrheniusRateFloatTest::CPPUNIT_TEST (test_reset_scalar_params)
AntiochTesting::ArrheniusRateFloatTest::CPPUNIT_TEST (test_reset_vector_params2)
AntiochTesting::ArrheniusRateFloatTest::CPPUNIT_TEST (test_reset_vector_params3)
AntiochTesting::ArrheniusRateFloatTest::CPPUNIT_TEST_SUITE (ArrheniusRateFloatTest)
AntiochTesting::ArrheniusRateFloatTest::CPPUNIT_TEST_SUITE_END ()
float AntiochTesting::ArrheniusRateTestHelper< float >::deriv (float T) inline protected inherited
Definition at line 65 of file arrhenius_rate_test_helper.h.
     {
       using std::exp;
       return _Ea/(_R*T*T)*_Cf *exp(-_Ea/(_R*T));
     }
virtual float AntiochTesting::ArrheniusRateTest< float >::exact_deriv (float T) inline protected virtual inherited
Implements AntiochTesting::ReactionRateTestBase< Antioch::ArrheniusRate< float >, float >.
Definition at line 141 of file arrhenius_rate_test.C.
     {
       return this->deriv(T);
     }
virtual float AntiochTesting::ArrheniusRateTest< float >::exact_rate (float T) inline protected virtual inherited
Implements AntiochTesting::ReactionRateTestBase< Antioch::ArrheniusRate< float >, float >.
Definition at line 136 of file arrhenius_rate_test.C.
     {
       return this->value(T);
     }
void AntiochTesting::ArrheniusRateTestHelper< float >::reset_params (float Cf, float Ea) inline protected inherited
Definition at line 46 of file arrhenius_rate_test_helper.h.
     {
       _Cf = Cf;
       _Ea = Ea;
     }
void AntiochTesting::ArrheniusRateTestHelper< float >::reset_params (float Cf, float Ea, float R) inline protected inherited
Definition at line 52 of file arrhenius_rate_test_helper.h.
     {
       _Cf = Cf;
       _Ea = Ea;
       _R = R;
     }
void AntiochTesting::ArrheniusRateTest< float >::setUp () inline inherited
Definition at line 49 of file arrhenius_rate_test.C.
     {
       Scalar Cf = 1.4L;
       Scalar Ea = 298.0L;
       Scalar R = 1.0L; // Ea in K
       this->reset_params(Cf,Ea,R);
       _rate = new Antioch::ArrheniusRate<Scalar>(Cf,Ea,R);
     }
void AntiochTesting::ArrheniusRateTest< float >::tearDown () inline inherited
Definition at line 59 of file arrhenius_rate_test.C.
     {
       delete _rate;
     }
void AntiochTesting::ReactionRateTestBase< Antioch::ArrheniusRate< float > , float >::test_deriv (const Antioch::ArrheniusRate< float > & reaction_rate, float tol) inline inherited
Definition at line 70 of file reaction_rate_test_base.h.
References AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar >::exact_deriv().
     {
       for(Scalar T = 300.1; T <= 2500.1; T += 10.)
         {
           {
             Scalar deriv = reaction_rate.derivative(T);
             Scalar exact_deriv = this->exact_deriv(T);
             CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv,
                                           exact_deriv,
                                           tol );
           }
           {
             Antioch::KineticsConditions<Scalar> cond(T);
             Scalar deriv = reaction_rate.derivative(cond);
             Scalar exact_deriv = this->exact_deriv(T);
             CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv,
                                           exact_deriv,
                                           tol );
           }
         }
     }
void AntiochTesting::ReactionRateTestBase< Antioch::ArrheniusRate< float > , float >::test_rate (const Antioch::ArrheniusRate< float > & reaction_rate, float tol) inline inherited
Definition at line 43 of file reaction_rate_test_base.h.
References AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar >::exact_rate().
     {
       for(Scalar T = 300.1; T <= 2500.1; T += 10.)
         {
           {
             Scalar rate = reaction_rate(T);
             Scalar exact_rate = this->exact_rate(T);
             CPPUNIT_ASSERT_DOUBLES_EQUAL( rate,
                                           exact_rate,
                                           tol );
           }
           {
             Antioch::KineticsConditions<Scalar> cond(T);
             Scalar rate = reaction_rate(cond);
             Scalar exact_rate = this->exact_rate(T);
             CPPUNIT_ASSERT_DOUBLES_EQUAL( rate,
                                           exact_rate,
                                           tol );
           }
         }
     }
void AntiochTesting::ReactionRateTestBase< Antioch::ArrheniusRate< float > , float >::test_rate_and_deriv (const Antioch::ArrheniusRate< float > & reaction_rate, float tol) inline inherited
Definition at line 96 of file reaction_rate_test_base.h.
References AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar >::exact_deriv(), and AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar >::exact_rate().
     {
       for(Scalar T = 300.1; T <= 2500.1; T += 10.)
         {
           {
             Scalar rate;
             Scalar deriv;
             Antioch::KineticsConditions<Scalar> cond(T);
             reaction_rate.rate_and_derivative(cond,rate,deriv);
             Scalar exact_rate = this->exact_rate(T);
             Scalar exact_deriv = this->exact_deriv(T);
             CPPUNIT_ASSERT_DOUBLES_EQUAL( rate,
                                           exact_rate,
                                           tol );
             CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv,
                                           exact_deriv,
                                           tol );
           }
         }
     }
void AntiochTesting::ArrheniusRateTest< float >::test_reset_scalar_params () inline inherited
Definition at line 73 of file arrhenius_rate_test.C.
     {
       Scalar Cf = 1e-7L;
       Scalar Ea = 36000.L;
       Scalar R = Antioch::Constants::R_universal<Scalar>()*Antioch::Units<Scalar>("cal").get_SI_factor();
       this->reset_params( Cf, Ea, R );
       _rate->set_Cf(Cf);
       _rate->set_Ea(Ea);
       _rate->set_rscale(R);
       const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 100;
       this->test_rate( *_rate, tol );
       this->test_deriv( *_rate, tol );
       this->test_rate_and_deriv( *_rate, tol );
     }
void AntiochTesting::ArrheniusRateTest< float >::test_reset_vector_params2 () inline inherited
Definition at line 92 of file arrhenius_rate_test.C.
     {
       Scalar Cf = 2.5e-7L;
       Scalar Ea = 43000.L; //still in cal
       this->reset_params( Cf, Ea );
       std::vector<Scalar> values(2);
       values[0] = Cf;
       values[1] = Ea;
       _rate->reset_coefs(values);
       const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 100;
       this->test_rate( *_rate, tol );
       this->test_deriv( *_rate, tol );
       this->test_rate_and_deriv( *_rate, tol );
     }
void AntiochTesting::ArrheniusRateTest< float >::test_reset_vector_params3 () inline inherited
Definition at line 111 of file arrhenius_rate_test.C.
     {
       Scalar Cf = 2.1e-11L;
       Scalar Ea = 100000.L;
       Scalar R = Antioch::Constants::R_universal<Scalar>();
       this->reset_params( Cf, Ea, R );
       std::vector<Scalar> values(3);
       values[0] = Cf;
       values[1] = Ea;
       values[2] = R;
       _rate->reset_coefs(values);
       const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 100;
       this->test_rate( *_rate, tol );
       this->test_deriv( *_rate, tol );
       this->test_rate_and_deriv( *_rate, tol );
     }
void AntiochTesting::ArrheniusRateTest< float >::test_standard () inline inherited
Definition at line 64 of file arrhenius_rate_test.C.
     {
       const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 100;
       this->test_rate( *_rate, tol );
       this->test_deriv( *_rate, tol );
       this->test_rate_and_deriv( *_rate, tol );
     }
float AntiochTesting::ArrheniusRateTestHelper< float >::value (float T) inline protected inherited
Definition at line 59 of file arrhenius_rate_test_helper.h.
     {
       using std::exp;
       return _Cf*exp(-_Ea/(_R*T));
     }
Member Data Documentation
float AntiochTesting::ArrheniusRateTestHelper< float >::_Cf protected inherited
Definition at line 44 of file arrhenius_rate_test_helper.h.
float AntiochTesting::ArrheniusRateTestHelper< float >::_Ea protected inherited
Definition at line 44 of file arrhenius_rate_test_helper.h.
float AntiochTesting::ArrheniusRateTestHelper< float >::_R protected inherited
Definition at line 44 of file arrhenius_rate_test_helper.h.
Antioch::ArrheniusRate<float >* AntiochTesting::ArrheniusRateTest< float >::_rate protected inherited
Definition at line 134 of file arrhenius_rate_test.C.
The documentation for this class was generated from the following file:
test/standard_unit/arrhenius_rate_test.C