antioch-0.4.0: Antioch::KooijRate< CoeffType > Class Template Reference
Antioch::KooijRate< CoeffType > Class Template Reference
Kooij rate equation.
#include <kinetics_type.h>
Public Member Functions
KooijRate (const CoeffType Cf=0., const CoeffType eta=0., const CoeffType Ea=0., const CoeffType Tref=1., const CoeffType rscale=Constants::R_universal< CoeffType >())
~KooijRate ()
void set_Cf (const CoeffType Cf)
void set_eta (const CoeffType eta)
void set_Ea (const CoeffType Ea)
set _raw_Ea, unit is known (cal.mol-1, J.mol-1, whatever), _Ea is computed
void reset_Ea (const CoeffType Ea)
set _Ea, unit is K, _raw_Ea is computed
void set_Tref (const CoeffType Tref)
void set_rscale (const CoeffType scale)
void set_parameter (KineticsModel::Parameters parameter, CoeffType new_value)
set one parameter, characterized by enum
CoeffType get_parameter (KineticsModel::Parameters parameter) const
get one parameter, characterized by enum
template<typename VectorCoeffType >
void set_parameter (KineticsModel::Parameters parameter, VectorCoeffType new_value)
for compatibility purpose with photochemistry (particle flux reactions)
template<typename VectorCoeffType >
void reset_coefs (const VectorCoeffType &coefficients)
reset the coeffs
CoeffType Cf () const
CoeffType eta () const
CoeffType Ea () const
CoeffType Ea_K () const
CoeffType Tref () const
CoeffType rscale () const
template<typename StateType >
rate (const StateType &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_exp (_eta *ant_log(T)-_Ea/T))) template< typename StateType > operator()(const StateType &T) const template< typename StateType > derivative(const StateType &T) const ANTIOCH_AUTOFUNC(StateType
template<typename StateType , typename VectorStateType >
rate (const KineticsConditions< StateType, VectorStateType > &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_exp (_eta *T.temp_cache().lnT-_Ea/T.T())) template< typename StateType
_Cf VectorStateType operator() (const KineticsConditions< StateType, VectorStateType > &T) const template< typename StateType
_Cf VectorStateType VectorStateType derivative (const KineticsConditions< StateType, VectorStateType > &T) const ANTIOCH_AUTOFUNC(StateType
const std::string numeric () const
print equation
KineticsModel::KineticsModel type () const
StateType operator() (const StateType &temp) const
StateType derivative (const StateType &conditions) const
CoeffType get_parameter (KineticsModel::Parameters parameter, int l) const
get one parameter, characterized by enum, for vectorized parameter
void compute_rate_and_derivative (const KineticsConditions< StateType, VectorStateType > &conditions, StateType &rate, StateType &drate_dT) const
void compute_rate_and_derivative (const StateType &temp, StateType &rate, StateType &drate_dT) const
void set_index (unsigned int nr)
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Public Attributes
_Cf(* this)(T)/T *(_eta+_Ea/T)) template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
_Cf(*) StateType rate)
_Cf(*) StateType StateType &drate_d const)
_Cf VectorStateType
VectorStateType(* this)(T)/T.T()*(_eta+_Ea/T.T())) template< typename StateType
Simultaneously evaluate the rate and its derivative at T.
_Cf VectorStateType
VectorStateType(*)
VectorStateType voi rate_and_derivative)(const KineticsConditions< StateType, VectorStateType > &T, StateType &rate, StateType &drate_dT) const
Private Member Functions
void compute_cf ()
Private Attributes
CoeffType _raw_Cf
CoeffType _Cf
CoeffType _eta
CoeffType _raw_Ea
CoeffType _Ea
CoeffType _Tref
CoeffType _rscale
Detailed Description
template<typename CoeffType = double>
class Antioch::KooijRate< CoeffType >
Kooij rate equation.
The Kooij kinetics model is of the form:
thus
Internally, we use the reduced pre-exponential parameter and the reduced activation energy
Definition at line 59 of file kinetics_type.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::KooijRate< CoeffType >::KooijRate (const CoeffType Cf = 0., const CoeffType eta = 0., const CoeffType Ea = 0., const CoeffType Tref = 1., const CoeffType rscale = Constants::R_universal<CoeffType>())
Definition at line 175 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::_rscale, and Antioch::KooijRate< CoeffType >::compute_cf().
     : KineticsType<CoeffType>(KineticsModel::KOOIJ),
       _raw_Cf(Cf),
       _eta(eta),
       _raw_Ea(Ea),
       _Tref(Tref),
       _rscale(rscale)
   {
     _Ea = _raw_Ea / _rscale;
     this->compute_cf();
     return;
   }
template<typename CoeffType > Antioch::KooijRate< CoeffType >::~KooijRate ()
Definition at line 191 of file kooij_rate.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType = double> _Cf* Antioch::KooijRate< CoeffType >::ant_exp (_eta *ant_log(T)-_Ea/ T) const
Returns
the rate evaluated at T.
the derivative with respect to temperature evaluated at T.
template<typename CoeffType = double> _Cf* Antioch::KooijRate< CoeffType >::ant_exp (_eta *T. temp_cache).lnT-_Ea/T.T()
Returns
the rate evaluated at T.
template<typename CoeffType > CoeffType Antioch::KooijRate< CoeffType >::Cf () const inline
Definition at line 366 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::_Cf.
Referenced by Antioch::KooijRate< CoeffType >::get_parameter(), and Antioch::KooijRate< CoeffType >::set_Cf().
   { return _Cf; }
template<typename CoeffType > void Antioch::KooijRate< CoeffType >::compute_cf () inline private
Definition at line 422 of file kooij_rate.h.
Referenced by Antioch::KooijRate< CoeffType >::KooijRate(), Antioch::KooijRate< CoeffType >::set_Cf(), Antioch::KooijRate< CoeffType >::set_eta(), and Antioch::KooijRate< CoeffType >::set_Tref().
   {
     _Cf = _raw_Cf * ant_pow(KineticsModel::Tref<CoeffType>()/_Tref,_eta);
     return;
   }
void Antioch::KineticsType< CoeffType, VectorCoeffType >::compute_rate_and_derivative (const KineticsConditions< StateType, VectorStateType > & conditions, StateType & rate, StateType & drate_dT) const inherited
void Antioch::KineticsType< CoeffType, VectorCoeffType >::compute_rate_and_derivative (const StateType & temp, StateType & rate, StateType & drate_dT) const inherited
StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::derivative (const StateType & conditions) const inherited
template<typename CoeffType = double> _Cf VectorStateType VectorStateType Antioch::KooijRate< CoeffType >::derivative (const KineticsConditions< StateType, VectorStateType > & T) const
Referenced by test_values(), and vectester().
template<typename CoeffType > CoeffType Antioch::KooijRate< CoeffType >::Ea () const inline
Definition at line 376 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::_raw_Ea.
Referenced by Antioch::KooijRate< CoeffType >::get_parameter(), Antioch::KooijRate< CoeffType >::reset_Ea(), and Antioch::KooijRate< CoeffType >::set_Ea().
   { return _raw_Ea; }
template<typename CoeffType > CoeffType Antioch::KooijRate< CoeffType >::Ea_K () const inline
Definition at line 381 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::_Ea.
   { return _Ea; }
template<typename CoeffType > CoeffType Antioch::KooijRate< CoeffType >::eta () const inline
Definition at line 371 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::_eta.
Referenced by Antioch::KooijRate< CoeffType >::get_parameter(), and Antioch::KooijRate< CoeffType >::set_eta().
   { return _eta; }
template<typename CoeffType > CoeffType Antioch::KooijRate< CoeffType >::get_parameter (KineticsModel::Parameters parameter) const inline
get one parameter, characterized by enum
Definition at line 325 of file kooij_rate.h.
References Antioch::KineticsModel::A, antioch_error, Antioch::KineticsModel::B, Antioch::KooijRate< CoeffType >::Cf(), Antioch::KineticsModel::E, Antioch::KooijRate< CoeffType >::Ea(), Antioch::KooijRate< CoeffType >::eta(), Antioch::KineticsModel::R_SCALE, Antioch::KooijRate< CoeffType >::rscale(), Antioch::KineticsModel::T_REF, and Antioch::KooijRate< CoeffType >::Tref().
   {
     switch(parameter)
     {
        case KineticsModel::Parameters::R_SCALE:
        {
           return this->rscale();
        }
         break;
        case KineticsModel::Parameters::T_REF:
        {
          return this->Tref();
        }
         break;
        case KineticsModel::Parameters::A:
        {
          return this->Cf();
        }
         break;
        case KineticsModel::Parameters::B:
        {
          return this->eta();
        }
         break;
        case KineticsModel::Parameters::E:
        {
          return this->Ea();
        }
         break;
        default:
        {
          antioch_error();
        }
         break;
     }
     return 0;
   }
CoeffType Antioch::KineticsType< CoeffType, VectorCoeffType >::get_parameter (KineticsModel::Parameters parameter, int l) const inherited
get one parameter, characterized by enum, for vectorized parameter
template<typename CoeffType > const std::string Antioch::KooijRate< CoeffType >::numeric () const virtual
print equation
Implements Antioch::KineticsType< CoeffType >.
Definition at line 197 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::_eta, and Antioch::KooijRate< CoeffType >::_raw_Cf.
   {
     std::stringstream os;
     os << _raw_Cf;
     if (_eta != 0.) os << "*(T/" << _Tref << ")^" << _eta;
     os << "*exp(-" << _raw_Ea << "/(R*T))";
     return os.str();
   }
StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::operator() (const StateType & temp) const inherited
template<typename CoeffType = double> _Cf VectorStateType Antioch::KooijRate< CoeffType >::operator() (const KineticsConditions< StateType, VectorStateType > & T) const
Returns
the derivative with respect to temperature evaluated at T.
void Antioch::KineticsType< CoeffType, VectorCoeffType >::print (std::ostream & os = std::cout) const inherited
Formatted print, by default to std::cout.
template<typename CoeffType = double> template<typename StateType > Antioch::KooijRate< CoeffType >::rate (const StateType & T) const
Returns
the rate evaluated at T.
template<typename CoeffType = double> template<typename StateType , typename VectorStateType > Antioch::KooijRate< CoeffType >::rate (const KineticsConditions< StateType, VectorStateType > & T) const
Returns
the rate evaluated at T.
template<typename CoeffType > template<typename VectorCoeffType > void Antioch::KooijRate< CoeffType >::reset_coefs (const VectorCoeffType & coefficients) inline
reset the coeffs
Two ways of modifying your rate:
you change totally the rate, thus you require exactly five parameters, the order assumed is Cf, eta, Ea, Tref, rscale
you just change the value, thus Tref and rscale are not modified. You require exactly three parameters, the order assumed is Cf, eta, Ea
Definition at line 267 of file kooij_rate.h.
References antioch_assert_greater, antioch_assert_less, antioch_assert_not_equal_to, Antioch::KooijRate< CoeffType >::set_Cf(), Antioch::KooijRate< CoeffType >::set_Ea(), Antioch::KooijRate< CoeffType >::set_eta(), Antioch::KooijRate< CoeffType >::set_rscale(), and Antioch::KooijRate< CoeffType >::set_Tref().
Referenced by tester().
   {
        // 3 or 5
      antioch_assert_greater(coefficients.size(),2);
      antioch_assert_less(coefficients.size(),6);
      antioch_assert_not_equal_to(coefficients.size(),4);
      if(coefficients.size() == 5)
      {
         this->set_rscale(coefficients[4]);
         this->set_Tref(coefficients[3]);
      }
      this->set_Cf(coefficients[0]);
      this->set_eta(coefficients[1]);
      this->set_Ea(coefficients[2]);
   }
template<typename CoeffType > void Antioch::KooijRate< CoeffType >::reset_Ea (const CoeffType Ea) inline
set _Ea, unit is K, _raw_Ea is computed
Definition at line 248 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::_rscale, and Antioch::KooijRate< CoeffType >::Ea().
Referenced by Antioch::KooijRate< CoeffType >::set_parameter().
   {
     _Ea = Ea;
     _raw_Ea = _Ea * _rscale;
     return;
   }
template<typename CoeffType > CoeffType Antioch::KooijRate< CoeffType >::rscale () const inline
Definition at line 391 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::_rscale.
Referenced by Antioch::KooijRate< CoeffType >::get_parameter(), and Antioch::KooijRate< CoeffType >::set_rscale().
   { return _rscale; }
template<typename CoeffType > void Antioch::KooijRate< CoeffType >::set_Cf (const CoeffType Cf) inline
Definition at line 210 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::Cf(), and Antioch::KooijRate< CoeffType >::compute_cf().
Referenced by Antioch::KooijRate< CoeffType >::reset_coefs(), Antioch::KooijRate< CoeffType >::set_parameter(), and tester().
   {
     _raw_Cf = Cf;
     this->compute_cf();
     return;
   }
template<typename CoeffType > void Antioch::KooijRate< CoeffType >::set_Ea (const CoeffType Ea) inline
set _raw_Ea, unit is known (cal.mol-1, J.mol-1, whatever), _Ea is computed
Definition at line 239 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::_rscale, and Antioch::KooijRate< CoeffType >::Ea().
Referenced by Antioch::KooijRate< CoeffType >::reset_coefs(), and tester().
   {
     _raw_Ea = Ea;
     _Ea = _raw_Ea / _rscale;
     return;
   }
template<typename CoeffType > void Antioch::KooijRate< CoeffType >::set_eta (const CoeffType eta) inline
Definition at line 230 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::compute_cf(), and Antioch::KooijRate< CoeffType >::eta().
Referenced by Antioch::KooijRate< CoeffType >::reset_coefs(), Antioch::KooijRate< CoeffType >::set_parameter(), and tester().
   {
     _eta = eta;
     this->compute_cf();
     return;
   }
void Antioch::KineticsType< CoeffType, VectorCoeffType >::set_index (unsigned int nr) inherited
template<typename CoeffType > void Antioch::KooijRate< CoeffType >::set_parameter (KineticsModel::Parameters parameter, CoeffType new_value) inline
set one parameter, characterized by enum
Definition at line 286 of file kooij_rate.h.
References Antioch::KineticsModel::A, antioch_error, Antioch::KineticsModel::B, Antioch::KineticsModel::E, Antioch::KineticsModel::R_SCALE, Antioch::KooijRate< CoeffType >::reset_Ea(), Antioch::KooijRate< CoeffType >::set_Cf(), Antioch::KooijRate< CoeffType >::set_eta(), Antioch::KooijRate< CoeffType >::set_rscale(), Antioch::KooijRate< CoeffType >::set_Tref(), and Antioch::KineticsModel::T_REF.
   {
     switch(parameter)
     {
        case KineticsModel::Parameters::R_SCALE:
        {
           this->set_rscale(new_value);
        }
         break;
        case KineticsModel::Parameters::T_REF:
        {
          this->set_Tref(new_value);
        }
         break;
        case KineticsModel::Parameters::A:
        {
         this->set_Cf(new_value);
        }
         break;
        case KineticsModel::Parameters::B:
        {
         this->set_eta(new_value);
        }
         break;
        case KineticsModel::Parameters::E:
        {
         this->reset_Ea(new_value);
        }
         break;
        default:
        {
          antioch_error();
        }
         break;
     }
   }
template<typename CoeffType = double> template<typename VectorCoeffType > void Antioch::KooijRate< CoeffType >::set_parameter (KineticsModel::Parameters parameter, VectorCoeffType new_value) inline
for compatibility purpose with photochemistry (particle flux reactions)
Definition at line 97 of file kooij_rate.h.
References antioch_error.
 {antioch_error();}
template<typename CoeffType > void Antioch::KooijRate< CoeffType >::set_rscale (const CoeffType scale) inline
Definition at line 257 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::_rscale, and Antioch::KooijRate< CoeffType >::rscale().
Referenced by Antioch::KooijRate< CoeffType >::reset_coefs(), Antioch::KooijRate< CoeffType >::set_parameter(), and tester().
   {
     _rscale = rscale;
     _Ea = _raw_Ea / _rscale;
     return;
   }
template<typename CoeffType > void Antioch::KooijRate< CoeffType >::set_Tref (const CoeffType Tref) inline
Definition at line 220 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::compute_cf(), and Antioch::KooijRate< CoeffType >::Tref().
Referenced by Antioch::KooijRate< CoeffType >::reset_coefs(), Antioch::KooijRate< CoeffType >::set_parameter(), and tester().
   {
     _Tref = Tref;
     this->compute_cf();
     return;
   }
template<typename CoeffType > CoeffType Antioch::KooijRate< CoeffType >::Tref () const inline
Definition at line 386 of file kooij_rate.h.
References Antioch::KooijRate< CoeffType >::_Tref.
Referenced by Antioch::KooijRate< CoeffType >::get_parameter(), and Antioch::KooijRate< CoeffType >::set_Tref().
   { return _Tref; }
KineticsModel::KineticsModel Antioch::KineticsType< CoeffType, VectorCoeffType >::type () const inherited
Member Data Documentation
template<typename CoeffType = double> CoeffType Antioch::KooijRate< CoeffType >::_Cf private
Definition at line 65 of file kooij_rate.h.
Referenced by Antioch::KooijRate< CoeffType >::Cf().
template<typename CoeffType = double> CoeffType Antioch::KooijRate< CoeffType >::_Ea private
Definition at line 68 of file kooij_rate.h.
Referenced by Antioch::KooijRate< CoeffType >::Ea_K().
template<typename CoeffType = double> CoeffType Antioch::KooijRate< CoeffType >::_eta private
Definition at line 66 of file kooij_rate.h.
Referenced by Antioch::KooijRate< CoeffType >::eta(), and Antioch::KooijRate< CoeffType >::numeric().
template<typename CoeffType = double> CoeffType Antioch::KooijRate< CoeffType >::_raw_Cf private
Definition at line 64 of file kooij_rate.h.
Referenced by Antioch::KooijRate< CoeffType >::numeric().
template<typename CoeffType = double> CoeffType Antioch::KooijRate< CoeffType >::_raw_Ea private
Definition at line 67 of file kooij_rate.h.
Referenced by Antioch::KooijRate< CoeffType >::Ea().
template<typename CoeffType = double> CoeffType Antioch::KooijRate< CoeffType >::_rscale private
Definition at line 70 of file kooij_rate.h.
Referenced by Antioch::KooijRate< CoeffType >::KooijRate(), Antioch::KooijRate< CoeffType >::reset_Ea(), Antioch::KooijRate< CoeffType >::rscale(), Antioch::KooijRate< CoeffType >::set_Ea(), and Antioch::KooijRate< CoeffType >::set_rscale().
template<typename CoeffType = double> CoeffType Antioch::KooijRate< CoeffType >::_Tref private
Definition at line 69 of file kooij_rate.h.
Referenced by Antioch::KooijRate< CoeffType >::Tref().
template<typename CoeffType = double> _Cf(*) StateType StateType& drate_d Antioch::KooijRate< CoeffType >::const)
Definition at line 139 of file kooij_rate.h.
template<typename CoeffType = double> _Cf(*) StateType Antioch::KooijRate< CoeffType >::rate)
Definition at line 139 of file kooij_rate.h.
template<typename CoeffType = double> void Antioch::KooijRate< CoeffType >::rate_and_derivative inline
Definition at line 163 of file kooij_rate.h.
Referenced by test_values(), and vectester().
template<typename CoeffType = double> _Cf(* Antioch::KooijRate< CoeffType >::this)(T)/T *(_eta+_Ea/T))template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
Definition at line 135 of file kooij_rate.h.
template<typename CoeffType = double> _Cf VectorStateType VectorStateType(* Antioch::KooijRate< CoeffType >::this)(T)/T.T()*(_eta+_Ea/T.T()))template< typename StateType
Simultaneously evaluate the rate and its derivative at T.
Definition at line 159 of file kooij_rate.h.
The documentation for this class was generated from the following files:
src/kinetics/include/antioch/kinetics_type.h
src/kinetics/include/antioch/kooij_rate.h