antioch-0.4.0: Antioch::InSI Class Reference
Antioch::InSI Class Reference
Seven integers to characterize the power vector.
#include <insi.h>
Public Member Functions
InSI (int i0=0, int i1=0, int i2=0, int i3=0, int i4=0, int i5=0, int i6=0, int i7=0)
Building constructor, fully descriptive, with zeros as default values to simplify coder's interface.
bool operator== (const InSI &rhs) const
Bool equalize operator, true if all the powers are equal.
bool operator!= (const InSI &rhs) const
Not bool const operator==(const InSI&)
InSI & operator= (const InSI &rhs)
Assignement operator, equalize all the powers.
InSI & operator+= (const InSI &rhs)
Adding operator, add all the powers.
InSI & operator-= (const InSI &rhs)
Substracting operator, substract all the powers.
InSI & operator*= (int rhs)
Multiplying operator, multiply all the powers.
InSI & operator/= (int rhs)
Dividing operator.
InSI operator+ (const InSI &rhs) const
Adding operator, add all the powers.
InSI operator- (const InSI &rhs) const
Substracting operator, substract all the powers.
InSI operator* (int rhs) const
Multiplying operator, multiply all the powers.
InSI operator/ (int rhs) const
Dividing operator, see InSi & operator/=(int) for details.
void clear ()
Set all the powers to zeros.
int get_m () const
meter power getter
int get_kg () const
kilogramme power getter
int get_s () const
second power getter
int get_A () const
ampere power getter
int get_K () const
kelvin power getter
int get_mol () const
mol power getter
int get_cd () const
candela power getter
int get_rad () const
radian power getter
bool empty () const
Check if empty (all values to zero)
Private Attributes
int m
int kg
int s
int A
int K
int mol
int cd
int rad
Friends
std::ostream & operator<< (std::ostream &out, const InSI &rhs)
<< operator, to format the power vector
Detailed Description
Seven integers to characterize the power vector.
A unit is caracterize by the power associated to every base unit, this class stores those power.
Definition at line 43 of file insi.h.
Constructor & Destructor Documentation
Antioch::InSI::InSI (int i0 = 0, int i1 = 0, int i2 = 0, int i3 = 0, int i4 = 0, int i5 = 0, int i6 = 0, int i7 = 0) inline
Building constructor, fully descriptive, with zeros as default values to simplify coder's interface.
Definition at line 48 of file insi.h.
Referenced by operator*(), operator+(), operator-(), and operator/().
                                                                                          :
         m(i0),kg(i1),s(i2),A(i3),K(i4),mol(i5),cd(i6),rad(i7){}
Member Function Documentation
void Antioch::InSI::clear () inline
Set all the powers to zeros.
Definition at line 276 of file insi.h.
References A, cd, K, kg, m, mol, rad, and s.
Referenced by Antioch::Units< T >::clear().
 {
   m   = 0;
   kg  = 0;
   s   = 0;
   A   = 0;
   K   = 0;
   mol = 0;
   cd  = 0;
   rad = 0;
 }
bool Antioch::InSI::empty () const inline
Check if empty (all values to zero)
Definition at line 289 of file insi.h.
References A, cd, K, kg, m, mol, rad, and s.
Referenced by Antioch::Units< T >::is_united().
 {
   return (m   == 0 &&
           kg  == 0 &&
           s   == 0 &&
           A   == 0 &&
           K   == 0 &&
           mol == 0 &&
           cd  == 0 &&
           rad == 0);
 }
int Antioch::InSI::get_A () const inline
ampere power getter
Definition at line 106 of file insi.h.
References A.
Referenced by operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
 {return A;}
int Antioch::InSI::get_cd () const inline
candela power getter
Definition at line 112 of file insi.h.
References cd.
Referenced by operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
 {return cd;}
int Antioch::InSI::get_K () const inline
kelvin power getter
Definition at line 108 of file insi.h.
References K.
Referenced by operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
 {return K;}
int Antioch::InSI::get_kg () const inline
kilogramme power getter
Definition at line 102 of file insi.h.
References kg.
Referenced by operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
 {return kg;}
int Antioch::InSI::get_m () const inline
meter power getter
Definition at line 100 of file insi.h.
References m.
Referenced by operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
 {return m;}
int Antioch::InSI::get_mol () const inline
mol power getter
Definition at line 110 of file insi.h.
References mol.
Referenced by operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
 {return mol;}
int Antioch::InSI::get_rad () const inline
radian power getter
Definition at line 114 of file insi.h.
References rad.
Referenced by operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
 {return rad;}
int Antioch::InSI::get_s () const inline
second power getter
Definition at line 104 of file insi.h.
References s.
Referenced by operator+(), operator+=(), operator-(), operator-=(), operator=(), and operator==().
 {return s;}
bool Antioch::InSI::operator!= (const InSI & rhs) const inline
Not bool const operator==(const InSI&)
Definition at line 139 of file insi.h.
 {
   return (!(*this == rhs));
 }
InSI Antioch::InSI::operator* (int rhs) const inline
Multiplying operator, multiply all the powers.
Definition at line 255 of file insi.h.
References A, cd, InSI(), K, kg, m, mol, rad, and s.
 {
   return InSI(
                m * rhs,
                kg * rhs,
                s * rhs,
                A * rhs,
                K * rhs,
                mol * rhs,
                cd * rhs,
                rad * rhs
               );
 }
InSI & Antioch::InSI::operator*= (int rhs) inline
Multiplying operator, multiply all the powers.
Definition at line 218 of file insi.h.
References A, cd, K, kg, m, mol, rad, and s.
 {
   m   *= rhs;
   kg  *= rhs;
   s   *= rhs;
   A   *= rhs;
   K   *= rhs;
   mol *= rhs;
   cd  *= rhs;
   rad *= rhs;
   return *this;
 }
InSI Antioch::InSI::operator+ (const InSI & rhs) const inline
Adding operator, add all the powers.
Definition at line 160 of file insi.h.
References A, cd, get_A(), get_cd(), get_K(), get_kg(), get_m(), get_mol(), get_rad(), get_s(), InSI(), K, kg, m, mol, rad, and s.
 {
   return InSI(
               m   + rhs.get_m()  ,
               kg  + rhs.get_kg() ,
               s   + rhs.get_s()  ,
               A   + rhs.get_A()  ,
               K   + rhs.get_K()  ,
               mol + rhs.get_mol(),
               cd  + rhs.get_cd() ,
               rad + rhs.get_rad()
              );
 }
InSI & Antioch::InSI::operator+= (const InSI & rhs) inline
Adding operator, add all the powers.
Definition at line 190 of file insi.h.
References A, cd, get_A(), get_cd(), get_K(), get_kg(), get_m(), get_mol(), get_rad(), get_s(), K, kg, m, mol, rad, and s.
 {
    m   += rhs.get_m();
    kg  += rhs.get_kg();
    s   += rhs.get_s();
    A   += rhs.get_A();
    K   += rhs.get_K();
    mol += rhs.get_mol();
    cd  += rhs.get_cd();
    rad += rhs.get_rad();
    return *this;
 }
InSI Antioch::InSI::operator- (const InSI & rhs) const inline
Substracting operator, substract all the powers.
Definition at line 175 of file insi.h.
References A, cd, get_A(), get_cd(), get_K(), get_kg(), get_m(), get_mol(), get_rad(), get_s(), InSI(), K, kg, m, mol, rad, and s.
 {
    return InSI(
                 m   - rhs.get_m()  ,
                 kg  - rhs.get_kg() ,
                 s   - rhs.get_s()  ,
                 A   - rhs.get_A()  ,
                 K   - rhs.get_K()  ,
                 mol - rhs.get_mol(),
                 cd  - rhs.get_cd() ,
                 rad - rhs.get_rad()
                );
 }
InSI & Antioch::InSI::operator-= (const InSI & rhs) inline
Substracting operator, substract all the powers.
Definition at line 204 of file insi.h.
References A, cd, get_A(), get_cd(), get_K(), get_kg(), get_m(), get_mol(), get_rad(), get_s(), K, kg, m, mol, rad, and s.
 {
   m   -= rhs.get_m();
   kg  -= rhs.get_kg();
   s   -= rhs.get_s();
   A   -= rhs.get_A();
   K   -= rhs.get_K();
   mol -= rhs.get_mol();
   cd  -= rhs.get_cd();
   rad -= rhs.get_rad();
   return *this;
 }
InSI Antioch::InSI::operator/ (int rhs) const inline
Dividing operator, see InSi & operator/=(int) for details.
Definition at line 270 of file insi.h.
References InSI().
 {
   return (InSI(*this) /= rhs);
 }
InSI & Antioch::InSI::operator/= (int rhs) inline
Dividing operator.
Dividing a power needs first to check that the division is possible, i.e. if the power is not null, it must be a multiple of the divider. If not it sends back an error and stops. This division exist for root purposes.
Definition at line 232 of file insi.h.
References A, antioch_unit_error, cd, K, kg, m, mol, rad, and s.
 {
   if(m  %rhs != 0)antioch_unit_error("Cannot have non integer power (m).");
   if(kg %rhs != 0)antioch_unit_error("Cannot have non integer power (kg).");
   if(s  %rhs != 0)antioch_unit_error("Cannot have non integer power (s).");
   if(A  %rhs != 0)antioch_unit_error("Cannot have non integer power (A).");
   if(K  %rhs != 0)antioch_unit_error("Cannot have non integer power (K).");
   if(mol%rhs != 0)antioch_unit_error("Cannot have non integer power (mol).");
   if(cd %rhs != 0)antioch_unit_error("Cannot have non integer power (cd).");
   if(rad%rhs != 0)antioch_unit_error("Cannot have non integer power (rad).");
   m   /= rhs;
   kg  /= rhs;
   s   /= rhs;
   A   /= rhs;
   K   /= rhs;
   mol /= rhs;
   cd  /= rhs;
   rad /= rhs;
   return *this;
 }
InSI & Antioch::InSI::operator= (const InSI & rhs) inline
Assignement operator, equalize all the powers.
Definition at line 145 of file insi.h.
References A, cd, get_A(), get_cd(), get_K(), get_kg(), get_m(), get_mol(), get_rad(), get_s(), K, kg, m, mol, rad, and s.
 {
   if(this == &rhs){return *this;}
   m   = rhs.get_m();
   kg  = rhs.get_kg();
   s   = rhs.get_s();
   A   = rhs.get_A();
   K   = rhs.get_K();
   mol = rhs.get_mol();
   cd  = rhs.get_cd();
   rad = rhs.get_rad();
   return *this;
 }
bool Antioch::InSI::operator== (const InSI & rhs) const inline
Bool equalize operator, true if all the powers are equal.
Definition at line 124 of file insi.h.
References A, cd, get_A(), get_cd(), get_K(), get_kg(), get_m(), get_mol(), get_rad(), get_s(), K, kg, m, mol, rad, and s.
 {
   return (
            m   == rhs.get_m()   &&
            kg  == rhs.get_kg()  &&
            s   == rhs.get_s()   &&
            A   == rhs.get_A()   &&
            K   == rhs.get_K()   &&
            mol == rhs.get_mol() &&
            cd  == rhs.get_cd()  &&
            rad == rhs.get_rad()
          );
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const InSI & rhs) friend
<< operator, to format the power vector
Definition at line 52 of file insi.h.
         {
           out << "["
               << rhs.get_m()   << "(m),"
               << rhs.get_kg()  << "(kg),"
               << rhs.get_s()   << "(s),"
               << rhs.get_A()   << "(A),"
               << rhs.get_K()   << "(K),"
               << rhs.get_mol() << "(mol),"
               << rhs.get_cd()  << "(cd),"
               << rhs.get_rad() << "(rad)]";
           return out;
         }
Member Data Documentation
int Antioch::InSI::A private
Definition at line 120 of file insi.h.
Referenced by clear(), empty(), get_A(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), and operator==().
int Antioch::InSI::cd private
Definition at line 120 of file insi.h.
Referenced by clear(), empty(), get_cd(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), and operator==().
int Antioch::InSI::K private
Definition at line 120 of file insi.h.
Referenced by clear(), empty(), get_K(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), and operator==().
int Antioch::InSI::kg private
Definition at line 120 of file insi.h.
Referenced by clear(), empty(), get_kg(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), and operator==().
int Antioch::InSI::m private
Definition at line 120 of file insi.h.
Referenced by clear(), empty(), get_m(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), and operator==().
int Antioch::InSI::mol private
Definition at line 120 of file insi.h.
Referenced by clear(), empty(), get_mol(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), and operator==().
int Antioch::InSI::rad private
Definition at line 120 of file insi.h.
Referenced by clear(), empty(), get_rad(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), and operator==().
int Antioch::InSI::s private
Definition at line 120 of file insi.h.
Referenced by clear(), empty(), get_s(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), and operator==().
The documentation for this class was generated from the following file:
src/units/include/antioch/insi.h