antioch-0.4.0: Antioch::HercourtEssenRate< CoeffType > Class Template Reference
Antioch::HercourtEssenRate< CoeffType > Class Template Reference
Hercourt-Essen rate equation.
#include <hercourtessen_rate.h>
Public Member Functions
HercourtEssenRate (const CoeffType Cf=0., const CoeffType eta=0., const CoeffType Tref=1.)
~HercourtEssenRate ()
void set_Cf (const CoeffType Cf)
void set_eta (const CoeffType eta)
void set_Tref (const CoeffType Tref)
void set_parameter (KineticsModel::Parameters parameter, CoeffType new_value)
set one parameter, characterized by enum
CoeffType get_parameter (KineticsModel::Parameters parameter) const
get one parameter, characterized by enum
template<typename VectorCoeffType >
void set_parameter (KineticsModel::Parameters parameter, VectorCoeffType new_value)
for compatibility purpose with photochemistry (particle flux reactions)
template<typename VectorCoeffType >
void reset_coefs (const VectorCoeffType &coefficients)
reset the coeffs
CoeffType Cf () const
CoeffType eta () const
CoeffType Tref () const
template<typename StateType >
rate (const StateType &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_pow (T, _eta))) template< typename StateType > operator()(const StateType &T) const template< typename StateType > derivative(const StateType &T) const ANTIOCH_AUTOFUNC(StateType
template<typename StateType , typename VectorStateType >
rate (const KineticsConditions< StateType, VectorStateType > &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_exp (_eta *T.temp_cache().lnT)) template< typename StateType
_Cf VectorStateType operator() (const KineticsConditions< StateType, VectorStateType > &T) const template< typename StateType
_Cf VectorStateType VectorStateType derivative (const KineticsConditions< StateType, VectorStateType > &T) const ANTIOCH_AUTOFUNC(StateType
const std::string numeric () const
print equation
KineticsModel::KineticsModel type () const
StateType operator() (const StateType &temp) const
StateType derivative (const StateType &conditions) const
CoeffType get_parameter (KineticsModel::Parameters parameter, int l) const
get one parameter, characterized by enum, for vectorized parameter
void compute_rate_and_derivative (const KineticsConditions< StateType, VectorStateType > &conditions, StateType &rate, StateType &drate_dT) const
void compute_rate_and_derivative (const StateType &temp, StateType &rate, StateType &drate_dT) const
void set_index (unsigned int nr)
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Public Attributes
_Cf(* this)(T)/T *(_eta)) template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
_Cf(*) StateType rate)
_Cf(*) StateType StateType &drate_d const)
_Cf VectorStateType
VectorStateType(* this)(T)/T.T()*(_eta)) template< typename StateType
Simultaneously evaluate the rate and its derivative at T.
_Cf VectorStateType
VectorStateType(*)
VectorStateType voi rate_and_derivative)(const KineticsConditions< StateType, VectorStateType > &T, StateType &rate, StateType &drate_dT) const
Private Member Functions
void compute_cf ()
Private Attributes
CoeffType _raw_Cf
CoeffType _Cf
CoeffType _eta
CoeffType _Tref
Detailed Description
template<typename CoeffType = double>
class Antioch::HercourtEssenRate< CoeffType >
Hercourt-Essen rate equation.
Hercourt-Essen is a kinetics model of the form:
Thus
Internally, we use the reduced pre-exponential factor
Definition at line 57 of file hercourtessen_rate.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::HercourtEssenRate< CoeffType >::HercourtEssenRate (const CoeffType Cf = 0., const CoeffType eta = 0., const CoeffType Tref = 1.)
Definition at line 161 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::compute_cf().
     : KineticsType<CoeffType>(KineticsModel::HERCOURT_ESSEN),
       _raw_Cf(Cf),
       _eta(eta),
       _Tref(Tref)
   {
     this->compute_cf();
     return;
   }
template<typename CoeffType > Antioch::HercourtEssenRate< CoeffType >::~HercourtEssenRate ()
Definition at line 173 of file hercourtessen_rate.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType = double> _Cf* Antioch::HercourtEssenRate< CoeffType >::ant_exp (_eta *T.temp_cache(). lnT)
Returns
the rate evaluated at T.
template<typename CoeffType = double> _Cf* Antioch::HercourtEssenRate< CoeffType >::ant_pow (T , _eta) const
Returns
the rate evaluated at T.
the derivative with respect to temperature evaluated at T.
Referenced by Antioch::HercourtEssenRate< CoeffType >::compute_cf().
template<typename CoeffType > CoeffType Antioch::HercourtEssenRate< CoeffType >::Cf () const inline
Definition at line 292 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_Cf.
Referenced by Antioch::HercourtEssenRate< CoeffType >::get_parameter(), and Antioch::HercourtEssenRate< CoeffType >::set_Cf().
   { return _Cf; }
template<typename CoeffType > void Antioch::HercourtEssenRate< CoeffType >::compute_cf () inline private
Definition at line 319 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::ant_pow().
Referenced by Antioch::HercourtEssenRate< CoeffType >::HercourtEssenRate(), Antioch::HercourtEssenRate< CoeffType >::set_Cf(), Antioch::HercourtEssenRate< CoeffType >::set_eta(), and Antioch::HercourtEssenRate< CoeffType >::set_Tref().
   {
     _Cf = _raw_Cf * ant_pow(KineticsModel::Tref<CoeffType>()/_Tref,_eta);
     return;
   }
void Antioch::KineticsType< CoeffType, VectorCoeffType >::compute_rate_and_derivative (const KineticsConditions< StateType, VectorStateType > & conditions, StateType & rate, StateType & drate_dT) const inherited
void Antioch::KineticsType< CoeffType, VectorCoeffType >::compute_rate_and_derivative (const StateType & temp, StateType & rate, StateType & drate_dT) const inherited
StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::derivative (const StateType & conditions) const inherited
template<typename CoeffType = double> _Cf VectorStateType VectorStateType Antioch::HercourtEssenRate< CoeffType >::derivative (const KineticsConditions< StateType, VectorStateType > & T) const
Referenced by test_values(), and vectester().
template<typename CoeffType > CoeffType Antioch::HercourtEssenRate< CoeffType >::eta () const inline
Definition at line 297 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_eta.
Referenced by Antioch::HercourtEssenRate< CoeffType >::get_parameter(), and Antioch::HercourtEssenRate< CoeffType >::set_eta().
   { return _eta; }
template<typename CoeffType > CoeffType Antioch::HercourtEssenRate< CoeffType >::get_parameter (KineticsModel::Parameters parameter) const inline
get one parameter, characterized by enum
Definition at line 261 of file hercourtessen_rate.h.
References Antioch::KineticsModel::A, antioch_error, Antioch::KineticsModel::B, Antioch::HercourtEssenRate< CoeffType >::Cf(), Antioch::HercourtEssenRate< CoeffType >::eta(), Antioch::KineticsModel::T_REF, and Antioch::HercourtEssenRate< CoeffType >::Tref().
   {
      switch(parameter)
      {
         case KineticsModel::Parameters::A:
         {
           return this->Cf();
         }
           break;
         case KineticsModel::Parameters::B:
         {
           return this->eta();
         }
           break;
         case KineticsModel::Parameters::T_REF:
         {
           return this->Tref();
         }
           break;
         default:
         {
           antioch_error();
         }
         break;
      }
      return 0;
   }
CoeffType Antioch::KineticsType< CoeffType, VectorCoeffType >::get_parameter (KineticsModel::Parameters parameter, int l) const inherited
get one parameter, characterized by enum, for vectorized parameter
template<typename CoeffType > const std::string Antioch::HercourtEssenRate< CoeffType >::numeric () const virtual
print equation
Implements Antioch::KineticsType< CoeffType >.
Definition at line 179 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_eta, and Antioch::HercourtEssenRate< CoeffType >::_raw_Cf.
   {
     std::stringstream os;
     os << _raw_Cf;
     os << "*(T/" << _Tref << ")^" << _eta;
     return os.str();
   }
StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::operator() (const StateType & temp) const inherited
template<typename CoeffType = double> _Cf VectorStateType Antioch::HercourtEssenRate< CoeffType >::operator() (const KineticsConditions< StateType, VectorStateType > & T) const
Returns
the derivative with respect to temperature evaluated at T.
void Antioch::KineticsType< CoeffType, VectorCoeffType >::print (std::ostream & os = std::cout) const inherited
Formatted print, by default to std::cout.
template<typename CoeffType = double> template<typename StateType > Antioch::HercourtEssenRate< CoeffType >::rate (const StateType & T) const
Returns
the rate evaluated at T.
template<typename CoeffType = double> template<typename StateType , typename VectorStateType > Antioch::HercourtEssenRate< CoeffType >::rate (const KineticsConditions< StateType, VectorStateType > & T) const
Returns
the rate evaluated at T.
template<typename CoeffType > template<typename VectorCoeffType > void Antioch::HercourtEssenRate< CoeffType >::reset_coefs (const VectorCoeffType & coefficients) inline
reset the coeffs
Two ways of modifying your rate:
you change totally the rate, thus you require exactly three parameters, the order assumed is Cf, eta, Tref
you just change the value, thus Tref is not modified. You require exactly two parameters, the order assumed is Cf, eta
Definition at line 221 of file hercourtessen_rate.h.
References antioch_assert_greater, antioch_assert_less, Antioch::HercourtEssenRate< CoeffType >::set_Cf(), Antioch::HercourtEssenRate< CoeffType >::set_eta(), and Antioch::HercourtEssenRate< CoeffType >::set_Tref().
Referenced by tester().
   {
       antioch_assert_greater(coefficients.size(),1);
       antioch_assert_less(coefficients.size(),4);
       if(coefficients.size() == 3)this->set_Tref(coefficients[2]);
       this->set_Cf(coefficients[0]);
       this->set_eta(coefficients[1]);
   }
template<typename CoeffType > void Antioch::HercourtEssenRate< CoeffType >::set_Cf (const CoeffType Cf) inline
Definition at line 191 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::Cf(), and Antioch::HercourtEssenRate< CoeffType >::compute_cf().
Referenced by Antioch::HercourtEssenRate< CoeffType >::reset_coefs(), Antioch::HercourtEssenRate< CoeffType >::set_parameter(), and tester().
   {
     _raw_Cf = Cf;
     this->compute_cf();
     return;
   }
template<typename CoeffType > void Antioch::HercourtEssenRate< CoeffType >::set_eta (const CoeffType eta) inline
Definition at line 201 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::compute_cf(), and Antioch::HercourtEssenRate< CoeffType >::eta().
Referenced by Antioch::HercourtEssenRate< CoeffType >::reset_coefs(), Antioch::HercourtEssenRate< CoeffType >::set_parameter(), and tester().
   {
     _eta = eta;
     this->compute_cf();
     return;
   }
void Antioch::KineticsType< CoeffType, VectorCoeffType >::set_index (unsigned int nr) inherited
template<typename CoeffType > void Antioch::HercourtEssenRate< CoeffType >::set_parameter (KineticsModel::Parameters parameter, CoeffType new_value) inline
set one parameter, characterized by enum
Definition at line 232 of file hercourtessen_rate.h.
References Antioch::KineticsModel::A, antioch_error, Antioch::KineticsModel::B, Antioch::HercourtEssenRate< CoeffType >::set_Cf(), Antioch::HercourtEssenRate< CoeffType >::set_eta(), Antioch::HercourtEssenRate< CoeffType >::set_Tref(), and Antioch::KineticsModel::T_REF.
   {
      switch(parameter)
      {
         case KineticsModel::Parameters::A:
         {
           this->set_Cf(new_value);
         }
           break;
         case KineticsModel::Parameters::B:
         {
           this->set_eta(new_value);
         }
           break;
         case KineticsModel::Parameters::T_REF:
         {
           this->set_Tref(new_value);
         }
           break;
         default:
         {
           antioch_error();
         }
         break;
      }
   }
template<typename CoeffType = double> template<typename VectorCoeffType > void Antioch::HercourtEssenRate< CoeffType >::set_parameter (KineticsModel::Parameters parameter, VectorCoeffType new_value) inline
for compatibility purpose with photochemistry (particle flux reactions)
Definition at line 86 of file hercourtessen_rate.h.
References antioch_error.
 {antioch_error();}
template<typename CoeffType > void Antioch::HercourtEssenRate< CoeffType >::set_Tref (const CoeffType Tref) inline
Definition at line 210 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::compute_cf(), and Antioch::HercourtEssenRate< CoeffType >::Tref().
Referenced by Antioch::HercourtEssenRate< CoeffType >::reset_coefs(), Antioch::HercourtEssenRate< CoeffType >::set_parameter(), and tester().
   {
     _Tref = Tref;
     this->compute_cf();
     return;
   }
template<typename CoeffType > CoeffType Antioch::HercourtEssenRate< CoeffType >::Tref () const inline
Definition at line 302 of file hercourtessen_rate.h.
References Antioch::HercourtEssenRate< CoeffType >::_Tref.
Referenced by Antioch::HercourtEssenRate< CoeffType >::get_parameter(), and Antioch::HercourtEssenRate< CoeffType >::set_Tref().
   { return _Tref; }
KineticsModel::KineticsModel Antioch::KineticsType< CoeffType, VectorCoeffType >::type () const inherited
Member Data Documentation
template<typename CoeffType = double> CoeffType Antioch::HercourtEssenRate< CoeffType >::_Cf private
Definition at line 63 of file hercourtessen_rate.h.
Referenced by Antioch::HercourtEssenRate< CoeffType >::Cf().
template<typename CoeffType = double> CoeffType Antioch::HercourtEssenRate< CoeffType >::_eta private
Definition at line 64 of file hercourtessen_rate.h.
Referenced by Antioch::HercourtEssenRate< CoeffType >::eta(), and Antioch::HercourtEssenRate< CoeffType >::numeric().
template<typename CoeffType = double> CoeffType Antioch::HercourtEssenRate< CoeffType >::_raw_Cf private
Definition at line 62 of file hercourtessen_rate.h.
Referenced by Antioch::HercourtEssenRate< CoeffType >::numeric().
template<typename CoeffType = double> CoeffType Antioch::HercourtEssenRate< CoeffType >::_Tref private
Definition at line 65 of file hercourtessen_rate.h.
Referenced by Antioch::HercourtEssenRate< CoeffType >::Tref().
template<typename CoeffType = double> _Cf(*) StateType StateType& drate_d Antioch::HercourtEssenRate< CoeffType >::const)
Definition at line 125 of file hercourtessen_rate.h.
template<typename CoeffType = double> _Cf(*) StateType Antioch::HercourtEssenRate< CoeffType >::rate)
Definition at line 125 of file hercourtessen_rate.h.
template<typename CoeffType = double> void Antioch::HercourtEssenRate< CoeffType >::rate_and_derivative inline
Definition at line 149 of file hercourtessen_rate.h.
Referenced by test_values(), and vectester().
template<typename CoeffType = double> _Cf(* Antioch::HercourtEssenRate< CoeffType >::this)(T)/T *(_eta))template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
Definition at line 121 of file hercourtessen_rate.h.
template<typename CoeffType = double> _Cf VectorStateType VectorStateType(* Antioch::HercourtEssenRate< CoeffType >::this)(T)/T.T()*(_eta))template< typename StateType
Simultaneously evaluate the rate and its derivative at T.
Definition at line 145 of file hercourtessen_rate.h.
The documentation for this class was generated from the following file:
src/kinetics/include/antioch/hercourtessen_rate.h