antioch-0.4.0: AntiochTesting::ArrheniusRateTestHelper< Scalar > Class Template Reference
AntiochTesting::ArrheniusRateTestHelper< Scalar > Class Template Reference
#include <arrhenius_rate_test_helper.h>
Protected Member Functions
void reset_params (Scalar Cf, Scalar Ea)
void reset_params (Scalar Cf, Scalar Ea, Scalar R)
Scalar value (Scalar T)
Scalar deriv (Scalar T)
Protected Attributes
Scalar _Cf
Scalar _Ea
Scalar _R
Detailed Description
template<typename Scalar>
class AntiochTesting::ArrheniusRateTestHelper< Scalar >
Definition at line 41 of file arrhenius_rate_test_helper.h.
Member Function Documentation
template<typename Scalar> Scalar AntiochTesting::ArrheniusRateTestHelper< Scalar >::deriv (Scalar T) inline protected
Definition at line 65 of file arrhenius_rate_test_helper.h.
Referenced by AntiochTesting::ArrheniusRateTest< long double >::exact_deriv().
     {
       using std::exp;
       return _Ea/(_R*T*T)*_Cf *exp(-_Ea/(_R*T));
     }
template<typename Scalar> void AntiochTesting::ArrheniusRateTestHelper< Scalar >::reset_params (Scalar Cf, Scalar Ea) inline protected
Definition at line 46 of file arrhenius_rate_test_helper.h.
Referenced by AntiochTesting::ArrheniusRateTest< long double >::setUp(), AntiochTesting::ArrheniusRateTest< long double >::test_reset_scalar_params(), AntiochTesting::ArrheniusRateTest< long double >::test_reset_vector_params2(), and AntiochTesting::ArrheniusRateTest< long double >::test_reset_vector_params3().
     {
       _Cf = Cf;
       _Ea = Ea;
     }
template<typename Scalar> void AntiochTesting::ArrheniusRateTestHelper< Scalar >::reset_params (Scalar Cf, Scalar Ea, Scalar R) inline protected
Definition at line 52 of file arrhenius_rate_test_helper.h.
     {
       _Cf = Cf;
       _Ea = Ea;
       _R = R;
     }
template<typename Scalar> Scalar AntiochTesting::ArrheniusRateTestHelper< Scalar >::value (Scalar T) inline protected
Definition at line 59 of file arrhenius_rate_test_helper.h.
Referenced by AntiochTesting::ArrheniusRateTest< long double >::exact_rate().
     {
       using std::exp;
       return _Cf*exp(-_Ea/(_R*T));
     }
Member Data Documentation
template<typename Scalar> Scalar AntiochTesting::ArrheniusRateTestHelper< Scalar >::_Cf protected
Definition at line 44 of file arrhenius_rate_test_helper.h.
template<typename Scalar> Scalar AntiochTesting::ArrheniusRateTestHelper< Scalar >::_Ea protected
Definition at line 44 of file arrhenius_rate_test_helper.h.
template<typename Scalar> Scalar AntiochTesting::ArrheniusRateTestHelper< Scalar >::_R protected
Definition at line 44 of file arrhenius_rate_test_helper.h.
The documentation for this class was generated from the following file:
test/standard_unit/arrhenius_rate_test_helper.h