antioch-0.4.0: Antioch::BerthelotHercourtEssenRate< CoeffType > Class Template Reference
Antioch::BerthelotHercourtEssenRate< CoeffType > Class Template Reference
Berthelot Hercourt-Essen rate equation.
#include <berthelothercourtessen_rate.h>
Public Member Functions
BerthelotHercourtEssenRate (const CoeffType Cf=0., const CoeffType eta=0., const CoeffType D=0., const CoeffType Tref=1.)
~BerthelotHercourtEssenRate ()
void set_Cf (const CoeffType Cf)
void set_eta (const CoeffType eta)
void set_D (const CoeffType D)
void set_Tref (const CoeffType Tref)
void set_parameter (KineticsModel::Parameters parameter, CoeffType new_value)
set one parameter, characterized by enum
CoeffType get_parameter (KineticsModel::Parameters parameter) const
get one parameter, characterized by enum
template<typename VectorCoeffType >
void set_parameter (KineticsModel::Parameters parameter, VectorCoeffType new_value)
for compatibility purpose with photochemistry (particle flux reactions)
template<typename VectorCoeffType >
void reset_coefs (const VectorCoeffType &coefficients)
reset the coeffs
CoeffType Cf () const
CoeffType eta () const
CoeffType D () const
CoeffType Tref () const
template<typename StateType >
rate (const StateType &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_pow (T, _eta)*ant_exp(_D *T))) template< typename StateType > operator()(const StateType &T) const template< typename StateType > derivative(const StateType &T) const ANTIOCH_AUTOFUNC(StateType
template<typename StateType , typename VectorStateType >
rate (const KineticsConditions< StateType, VectorStateType > &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_exp (_eta *T.temp_cache().lnT+_D *T.T())) template< typename StateType
_Cf VectorStateType operator() (const KineticsConditions< StateType, VectorStateType > &T) const template< typename StateType
_Cf VectorStateType VectorStateType derivative (const KineticsConditions< StateType, VectorStateType > &T) const ANTIOCH_AUTOFUNC(StateType
const std::string numeric () const
print equation
KineticsModel::KineticsModel type () const
StateType operator() (const StateType &temp) const
StateType derivative (const StateType &conditions) const
CoeffType get_parameter (KineticsModel::Parameters parameter, int l) const
get one parameter, characterized by enum, for vectorized parameter
void compute_rate_and_derivative (const KineticsConditions< StateType, VectorStateType > &conditions, StateType &rate, StateType &drate_dT) const
void compute_rate_and_derivative (const StateType &temp, StateType &rate, StateType &drate_dT) const
void set_index (unsigned int nr)
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Public Attributes
_Cf(* this)(T)*(_eta/T+_D)) template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
_Cf(*) StateType rate)
_Cf(*) StateType StateType &drate_d const)
_Cf VectorStateType
VectorStateType(* this)(T)*(_eta/T.T()+_D)) template< typename StateType
Simultaneously evaluate the rate and its derivative at T.
_Cf VectorStateType
VectorStateType(*)
VectorStateType voi rate_and_derivative)(const KineticsConditions< StateType, VectorStateType > &T, StateType &rate, StateType &drate_dT) const
Private Member Functions
void compute_cf ()
Private Attributes
CoeffType _raw_Cf
CoeffType _Cf
CoeffType _eta
CoeffType _D
CoeffType _Tref
Detailed Description
template<typename CoeffType = double>
class Antioch::BerthelotHercourtEssenRate< CoeffType >
Berthelot Hercourt-Essen rate equation.
The Berthelot Hercourt Essen kinetics model is of the form:
thus
Internally, we use the reduced temperature .
Definition at line 57 of file berthelothercourtessen_rate.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::BerthelotHercourtEssenRate< CoeffType >::BerthelotHercourtEssenRate (const CoeffType Cf = 0., const CoeffType eta = 0., const CoeffType D = 0., const CoeffType Tref = 1.)
Definition at line 163 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf().
     : KineticsType<CoeffType>(KineticsModel::BHE),
       _raw_Cf(Cf),
       _eta(eta),
       _D(D),
       _Tref(Tref)
   {
     this->compute_cf();
     return;
   }
template<typename CoeffType > Antioch::BerthelotHercourtEssenRate< CoeffType >::~BerthelotHercourtEssenRate ()
Definition at line 175 of file berthelothercourtessen_rate.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType = double> _Cf* Antioch::BerthelotHercourtEssenRate< CoeffType >::ant_exp (_eta *T. temp_cache).lnT+_D *T.T()
Returns
the rate evaluated at T.
template<typename CoeffType = double> _Cf* Antioch::BerthelotHercourtEssenRate< CoeffType >::ant_pow (T , _eta) const
Returns
the rate evaluated at T.
the derivative with respect to temperature evaluated at T.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf().
template<typename CoeffType > CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::Cf () const inline
Definition at line 312 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_Cf.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::get_parameter(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Cf().
   { return _Cf; }
template<typename CoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf () inline private
Definition at line 356 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::ant_pow().
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::BerthelotHercourtEssenRate(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Cf(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_eta(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Tref().
   {
     _Cf = _raw_Cf * ant_pow(KineticsModel::Tref<CoeffType>()/_Tref,_eta);
     return;
   }
void Antioch::KineticsType< CoeffType, VectorCoeffType >::compute_rate_and_derivative (const KineticsConditions< StateType, VectorStateType > & conditions, StateType & rate, StateType & drate_dT) const inherited
void Antioch::KineticsType< CoeffType, VectorCoeffType >::compute_rate_and_derivative (const StateType & temp, StateType & rate, StateType & drate_dT) const inherited
template<typename CoeffType > CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::D () const inline
Definition at line 322 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_D.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::get_parameter(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::set_D().
   { return _D; }
StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::derivative (const StateType & conditions) const inherited
template<typename CoeffType = double> _Cf VectorStateType VectorStateType Antioch::BerthelotHercourtEssenRate< CoeffType >::derivative (const KineticsConditions< StateType, VectorStateType > & T) const
Referenced by test_values(), and vectester().
template<typename CoeffType > CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::eta () const inline
Definition at line 317 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_eta.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::get_parameter(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::set_eta().
   { return _eta; }
template<typename CoeffType > CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::get_parameter (KineticsModel::Parameters parameter) const inline
get one parameter, characterized by enum
Definition at line 277 of file berthelothercourtessen_rate.h.
References Antioch::KineticsModel::A, antioch_error, Antioch::KineticsModel::B, Antioch::BerthelotHercourtEssenRate< CoeffType >::Cf(), Antioch::KineticsModel::D, Antioch::BerthelotHercourtEssenRate< CoeffType >::D(), Antioch::BerthelotHercourtEssenRate< CoeffType >::eta(), Antioch::KineticsModel::T_REF, and Antioch::BerthelotHercourtEssenRate< CoeffType >::Tref().
   {
     switch(parameter)
     {
      case KineticsModel::Parameters::A:
      {
        return this->Cf();
      }
       break;
      case KineticsModel::Parameters::B:
      {
        return this->eta();
      }
       break;
      case KineticsModel::Parameters::D:
      {
        return this->D();
      }
       break;
      case KineticsModel::Parameters::T_REF:
      {
        return this->Tref();
      }
       break;
      default:
      {
        antioch_error();
      }
       break;
      }
      return 0;
   }
CoeffType Antioch::KineticsType< CoeffType, VectorCoeffType >::get_parameter (KineticsModel::Parameters parameter, int l) const inherited
get one parameter, characterized by enum, for vectorized parameter
template<typename CoeffType > const std::string Antioch::BerthelotHercourtEssenRate< CoeffType >::numeric () const virtual
print equation
Implements Antioch::KineticsType< CoeffType >.
Definition at line 181 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_eta, and Antioch::BerthelotHercourtEssenRate< CoeffType >::_raw_Cf.
   {
     std::stringstream os;
     os << _raw_Cf;
     if (_eta != 0.) os << "*(T/" << _Tref << ")^" << _eta;
     os << "*exp(" << _D << "*T)";
     return os.str();
   }
StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::operator() (const StateType & temp) const inherited
template<typename CoeffType = double> _Cf VectorStateType Antioch::BerthelotHercourtEssenRate< CoeffType >::operator() (const KineticsConditions< StateType, VectorStateType > & T) const
Returns
the derivative with respect to temperature evaluated at T.
void Antioch::KineticsType< CoeffType, VectorCoeffType >::print (std::ostream & os = std::cout) const inherited
Formatted print, by default to std::cout.
template<typename CoeffType = double> template<typename StateType > Antioch::BerthelotHercourtEssenRate< CoeffType >::rate (const StateType & T) const
Returns
the rate evaluated at T.
template<typename CoeffType = double> template<typename StateType , typename VectorStateType > Antioch::BerthelotHercourtEssenRate< CoeffType >::rate (const KineticsConditions< StateType, VectorStateType > & T) const
Returns
the rate evaluated at T.
template<typename CoeffType > template<typename VectorCoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::reset_coefs (const VectorCoeffType & coefficients) inline
reset the coeffs
Two ways of modifying your rate:
you change totally the rate, thus you require exactly four parameters, the order assumed is Cf, eta, D, Tref
you just change the value, thus Tref is not modified. You require exactly three parameters, the order assumed is Cf, eta, D
Definition at line 230 of file berthelothercourtessen_rate.h.
References antioch_assert_greater, antioch_assert_less, Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Cf(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_D(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_eta(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Tref().
Referenced by tester().
   {
     antioch_assert_greater(coefficients.size(),2);
     antioch_assert_less(coefficients.size(),5);
     if(coefficients.size() == 4)this->set_Tref(coefficients[3]);
     this->set_Cf(coefficients[0]);
     this->set_eta(coefficients[1]);
     this->set_D(coefficients[2]);
   }
template<typename CoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Cf (const CoeffType Cf) inline
Definition at line 194 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::Cf(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf().
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::reset_coefs(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_parameter(), and tester().
   {
     _raw_Cf = Cf;
     this->compute_cf();
     return;
   }
template<typename CoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::set_D (const CoeffType D) inline
Definition at line 221 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::D().
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::reset_coefs(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_parameter(), and tester().
   {
     _D = D;
     return;
   }
template<typename CoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::set_eta (const CoeffType eta) inline
Definition at line 212 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::eta().
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::reset_coefs(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_parameter(), and tester().
   {
     _eta = eta;
     this->compute_cf();
     return;
   }
void Antioch::KineticsType< CoeffType, VectorCoeffType >::set_index (unsigned int nr) inherited
template<typename CoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::set_parameter (KineticsModel::Parameters parameter, CoeffType new_value) inline
set one parameter, characterized by enum
Definition at line 243 of file berthelothercourtessen_rate.h.
References Antioch::KineticsModel::A, antioch_error, Antioch::KineticsModel::B, Antioch::KineticsModel::D, Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Cf(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_D(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_eta(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Tref(), and Antioch::KineticsModel::T_REF.
   {
     switch(parameter)
     {
      case KineticsModel::Parameters::A:
      {
        this->set_Cf(new_value);
      }
       break;
      case KineticsModel::Parameters::B:
      {
        this->set_eta(new_value);
      }
       break;
      case KineticsModel::Parameters::D:
      {
        this->set_D(new_value);
      }
       break;
      case KineticsModel::Parameters::T_REF:
      {
        this->set_Tref(new_value);
      }
       break;
      default:
      {
        antioch_error();
      }
       break;
      }
   }
template<typename CoeffType = double> template<typename VectorCoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::set_parameter (KineticsModel::Parameters parameter, VectorCoeffType new_value) inline
for compatibility purpose with photochemistry (particle flux reactions)
Definition at line 88 of file berthelothercourtessen_rate.h.
References antioch_error.
 {antioch_error();}
template<typename CoeffType > void Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Tref (const CoeffType Tref) inline
Definition at line 203 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::compute_cf(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::Tref().
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::reset_coefs(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_parameter(), and tester().
   {
     _Tref = Tref;
     this->compute_cf();
     return;
   }
template<typename CoeffType > CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::Tref () const inline
Definition at line 327 of file berthelothercourtessen_rate.h.
References Antioch::BerthelotHercourtEssenRate< CoeffType >::_Tref.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::get_parameter(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Tref().
   { return _Tref; }
KineticsModel::KineticsModel Antioch::KineticsType< CoeffType, VectorCoeffType >::type () const inherited
Member Data Documentation
template<typename CoeffType = double> CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::_Cf private
Definition at line 63 of file berthelothercourtessen_rate.h.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::Cf().
template<typename CoeffType = double> CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::_D private
Definition at line 65 of file berthelothercourtessen_rate.h.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::D().
template<typename CoeffType = double> CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::_eta private
Definition at line 64 of file berthelothercourtessen_rate.h.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::eta(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::numeric().
template<typename CoeffType = double> CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::_raw_Cf private
Definition at line 62 of file berthelothercourtessen_rate.h.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::numeric().
template<typename CoeffType = double> CoeffType Antioch::BerthelotHercourtEssenRate< CoeffType >::_Tref private
Definition at line 66 of file berthelothercourtessen_rate.h.
Referenced by Antioch::BerthelotHercourtEssenRate< CoeffType >::Tref().
template<typename CoeffType = double> _Cf(*) StateType StateType& drate_d Antioch::BerthelotHercourtEssenRate< CoeffType >::const)
Definition at line 128 of file berthelothercourtessen_rate.h.
template<typename CoeffType = double> _Cf(*) StateType Antioch::BerthelotHercourtEssenRate< CoeffType >::rate)
Definition at line 128 of file berthelothercourtessen_rate.h.
template<typename CoeffType = double> void Antioch::BerthelotHercourtEssenRate< CoeffType >::rate_and_derivative inline
Definition at line 152 of file berthelothercourtessen_rate.h.
Referenced by test_values(), and vectester().
template<typename CoeffType = double> _Cf(* Antioch::BerthelotHercourtEssenRate< CoeffType >::this)(T)*(_eta/T+_D))template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
Definition at line 124 of file berthelothercourtessen_rate.h.
template<typename CoeffType = double> _Cf VectorStateType VectorStateType(* Antioch::BerthelotHercourtEssenRate< CoeffType >::this)(T)*(_eta/T.T()+_D))template< typename StateType
Simultaneously evaluate the rate and its derivative at T.
Definition at line 148 of file berthelothercourtessen_rate.h.
The documentation for this class was generated from the following file:
src/kinetics/include/antioch/berthelothercourtessen_rate.h