antioch-0.4.0: AntiochTesting::ArrheniusRateVexCLDoubleTest Class Reference
AntiochTesting::ArrheniusRateVexCLDoubleTest Class Reference
Public Member Functions
CPPUNIT_TEST_SUITE (ArrheniusRateVexCLDoubleTest)
CPPUNIT_TEST (test_standard_rate)
CPPUNIT_TEST (test_standard_deriv)
CPPUNIT_TEST (test_standard_rate_and_deriv)
CPPUNIT_TEST_SUITE_END ()
virtual void setUp ()
virtual void tearDown ()
virtual void init ()
virtual void clear ()
void test_standard_rate ()
void test_standard_deriv ()
void test_standard_rate_and_deriv ()
void test_rate (const Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type > &reaction_rate, const vex::vector< double > &T, typename Antioch::value_type< vex::vector< double > >::typetol)
void test_deriv (const Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type > &reaction_rate, const vex::vector< double > &T, typename Antioch::value_type< vex::vector< double > >::typetol)
void test_rate_and_deriv (const Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type > &reaction_rate, const vex::vector< double > &T, typename Antioch::value_type< vex::vector< double > >::typetol)
Protected Member Functions
virtual vex::vector< double > exact_rate (vex::vector< double >T)
virtual vex::vector< double > exact_deriv (vex::vector< double >T)
void reset_params (Antioch::value_type< vex::vector< double > >::typeCf, Antioch::value_type< vex::vector< double > >::typeEa)
void reset_params (Antioch::value_type< vex::vector< double > >::typeCf, Antioch::value_type< vex::vector< double > >::typeEa, Antioch::value_type< vex::vector< double > >::typeR)
Antioch::value_type
< vex::vector< double >
>::type value (Antioch::value_type< vex::vector< double > >::typeT)
Antioch::value_type
< vex::vector< double >
>::type deriv (Antioch::value_type< vex::vector< double > >::typeT)
vex::vector< double > setup_T (const vex::vector< double > &example)
Protected Attributes
Antioch::ArrheniusRate
< typename Antioch::value_type
< vex::vector< double >
>::type > * _rate
Antioch::value_type
< vex::vector< double >
>::type _Cf
Antioch::value_type
< vex::vector< double >
>::type _Ea
Antioch::value_type
< vex::vector< double >
>::type _R
vex::vector< double > * _example
Private Attributes
vex::Context * _ctx
Detailed Description
Definition at line 79 of file arrhenius_rate_vexcl_test.C.
Member Function Documentation
virtual void AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >::clear () inline virtual inherited
Definition at line 64 of file arrhenius_rate_vector_test_base.h.
Referenced by tearDown().
     {
       delete _rate;
     }
AntiochTesting::ArrheniusRateVexCLDoubleTest::CPPUNIT_TEST (test_standard_rate)
AntiochTesting::ArrheniusRateVexCLDoubleTest::CPPUNIT_TEST (test_standard_deriv)
AntiochTesting::ArrheniusRateVexCLDoubleTest::CPPUNIT_TEST (test_standard_rate_and_deriv)
AntiochTesting::ArrheniusRateVexCLDoubleTest::CPPUNIT_TEST_SUITE (ArrheniusRateVexCLDoubleTest)
AntiochTesting::ArrheniusRateVexCLDoubleTest::CPPUNIT_TEST_SUITE_END ()
Antioch::value_type< vex::vector< double > >::type AntiochTesting::ArrheniusRateTestHelper< Antioch::value_type< vex::vector< double > >::type >::deriv (Antioch::value_type< vex::vector< double > >::type T) inline protected inherited
Definition at line 65 of file arrhenius_rate_test_helper.h.
     {
       using std::exp;
       return _Ea/(_R*T*T)*_Cf *exp(-_Ea/(_R*T));
     }
virtual vex::vector< double > AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >::exact_deriv (vex::vector< double > T) inline protected virtual inherited
Implements AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type >, vex::vector< double > >.
Definition at line 111 of file arrhenius_rate_vector_test_base.h.
     {
       PairScalars e_deriv = *(this->_example);
       for (unsigned int tuple=0; tuple != ANTIOCH_N_TUPLES; ++tuple)
         {
           e_deriv[2*tuple]   =  this->deriv(T[2*tuple]);
           e_deriv[2*tuple+1] =  this->deriv(T[2*tuple+1]);
         }
       return e_deriv;
     }
virtual vex::vector< double > AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >::exact_rate (vex::vector< double > T) inline protected virtual inherited
Implements AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type >, vex::vector< double > >.
Definition at line 100 of file arrhenius_rate_vector_test_base.h.
     {
       PairScalars e_rate = *(this->_example);
       for (unsigned int tuple=0; tuple != ANTIOCH_N_TUPLES; ++tuple)
         {
           e_rate[2*tuple]   =  this->value(T[2*tuple]);
           e_rate[2*tuple+1] =  this->value(T[2*tuple+1]);
         }
       return e_rate;
     }
virtual void AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >::init () inline virtual inherited
Definition at line 52 of file arrhenius_rate_vector_test_base.h.
Referenced by setUp().
     {
       typedef typename Antioch::value_type<PairScalars>::type Scalar;
       Scalar Cf = 1.4L;
       Scalar Ea = 5.0L;
       Scalar R = 1.0L; // Ea in K
       this->reset_params(Cf,Ea,R);
       _rate = new Antioch::ArrheniusRate<Scalar>(Cf,Ea,R);
     }
void AntiochTesting::ArrheniusRateTestHelper< Antioch::value_type< vex::vector< double > >::type >::reset_params (Antioch::value_type< vex::vector< double > >::type Cf, Antioch::value_type< vex::vector< double > >::type Ea) inline protected inherited
Definition at line 46 of file arrhenius_rate_test_helper.h.
     {
       _Cf = Cf;
       _Ea = Ea;
     }
void AntiochTesting::ArrheniusRateTestHelper< Antioch::value_type< vex::vector< double > >::type >::reset_params (Antioch::value_type< vex::vector< double > >::type Cf, Antioch::value_type< vex::vector< double > >::type Ea, Antioch::value_type< vex::vector< double > >::type R) inline protected inherited
Definition at line 52 of file arrhenius_rate_test_helper.h.
     {
       _Cf = Cf;
       _Ea = Ea;
       _R = R;
     }
virtual void AntiochTesting::ArrheniusRateVexCLDoubleTest::setUp () inline virtual
Definition at line 97 of file arrhenius_rate_vexcl_test.C.
References _ctx, AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type >, vex::vector< double > >::_example, and AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >::init().
     {
       this->init();
       _ctx = new vex::Context(vex::Filter::DoublePrecision);
       this->_example = new vex::vector<double>(*_ctx, 2*ANTIOCH_N_TUPLES);
     }
vex::vector< double > AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type > , vex::vector< double > >::setup_T (const vex::vector< double > & example) inline protected inherited
Definition at line 123 of file reaction_rate_vector_test_base.h.
     {
       // Construct from example to avoid resizing issues
       PairScalars T = example;
       for (unsigned int tuple=0; tuple != ANTIOCH_N_TUPLES; ++tuple)
         {
           T[2*tuple]   = 1500.1;
           T[2*tuple+1] = 1600.1;
         }
       return T;
     }
virtual void AntiochTesting::ArrheniusRateVexCLDoubleTest::tearDown () inline virtual
Definition at line 104 of file arrhenius_rate_vexcl_test.C.
References _ctx, AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type >, vex::vector< double > >::_example, and AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >::clear().
     {
       this->clear();
       delete _ctx;
       delete this->_example;
     }
void AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type > , vex::vector< double > >::test_deriv (const Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type > & reaction_rate, const vex::vector< double > & T, typename Antioch::value_type< vex::vector< double > >::type tol) inline inherited
Definition at line 64 of file reaction_rate_vector_test_base.h.
     {
       const PairScalars deriv = reaction_rate.derivative(T);
       const PairScalars exact_deriv = this->exact_deriv(T);
       for (unsigned int tuple=0; tuple != ANTIOCH_N_TUPLES; ++tuple)
         {
           CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv[2*tuple],
                                         exact_deriv[0],
                                         tol );
           CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv[2*tuple+1],
                                         exact_deriv[1],
                                         tol );
         }
     }
void AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type > , vex::vector< double > >::test_rate (const Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type > & reaction_rate, const vex::vector< double > & T, typename Antioch::value_type< vex::vector< double > >::type tol) inline inherited
Definition at line 44 of file reaction_rate_vector_test_base.h.
     {
       const PairScalars rate = reaction_rate(T);
       const PairScalars exact_rate = this->exact_rate(T);
       for (unsigned int tuple=0; tuple != ANTIOCH_N_TUPLES; ++tuple)
         {
           CPPUNIT_ASSERT_DOUBLES_EQUAL( rate[2*tuple],
                                         exact_rate[0],
                                         tol );
           CPPUNIT_ASSERT_DOUBLES_EQUAL( rate[2*tuple+1],
                                         exact_rate[1],
                                         tol );
         }
     }
void AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type > , vex::vector< double > >::test_rate_and_deriv (const Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type > & reaction_rate, const vex::vector< double > & T, typename Antioch::value_type< vex::vector< double > >::type tol) inline inherited
Definition at line 84 of file reaction_rate_vector_test_base.h.
     {
       // Init using T as the "example"
       PairScalars rate = T;
       PairScalars deriv = T;
       reaction_rate.rate_and_derivative(T,rate,deriv);
       const PairScalars exact_rate = this->exact_rate(T);
       const PairScalars exact_deriv = this->exact_deriv(T);
       for (unsigned int tuple=0; tuple != ANTIOCH_N_TUPLES; ++tuple)
         {
           CPPUNIT_ASSERT_DOUBLES_EQUAL( rate[2*tuple],
                                         exact_rate[0],
                                         tol );
           CPPUNIT_ASSERT_DOUBLES_EQUAL( rate[2*tuple+1],
                                         exact_rate[1],
                                         tol );
           CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv[2*tuple],
                                         exact_deriv[0],
                                         tol );
           CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv[2*tuple+1],
                                         exact_deriv[1],
                                         tol );
         }
     }
void AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >::test_standard_deriv () inline inherited
Definition at line 78 of file arrhenius_rate_vector_test_base.h.
     {
       typedef typename Antioch::value_type<PairScalars>::type Scalar;
       const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 100;
       PairScalars T = this->setup_T(*(this->_example));
       this->test_deriv( *_rate, T, tol );
     }
void AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >::test_standard_rate () inline inherited
Definition at line 69 of file arrhenius_rate_vector_test_base.h.
     {
       typedef typename Antioch::value_type<PairScalars>::type Scalar;
       const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 100;
       PairScalars T = this->setup_T(*(this->_example));
       this->test_rate( *_rate, T, tol );
     }
void AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >::test_standard_rate_and_deriv () inline inherited
Definition at line 87 of file arrhenius_rate_vector_test_base.h.
     {
       typedef typename Antioch::value_type<PairScalars>::type Scalar;
       const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 100;
       PairScalars T = this->setup_T(*(this->_example));
       this->test_rate_and_deriv( *_rate, T, tol );
     }
Antioch::value_type< vex::vector< double > >::type AntiochTesting::ArrheniusRateTestHelper< Antioch::value_type< vex::vector< double > >::type >::value (Antioch::value_type< vex::vector< double > >::type T) inline protected inherited
Definition at line 59 of file arrhenius_rate_test_helper.h.
     {
       using std::exp;
       return _Cf*exp(-_Ea/(_R*T));
     }
Member Data Documentation
Antioch::value_type< vex::vector< double > >::type AntiochTesting::ArrheniusRateTestHelper< Antioch::value_type< vex::vector< double > >::type >::_Cf protected inherited
Definition at line 44 of file arrhenius_rate_test_helper.h.
vex::Context* AntiochTesting::ArrheniusRateVexCLDoubleTest::_ctx private
Definition at line 93 of file arrhenius_rate_vexcl_test.C.
Referenced by setUp(), and tearDown().
Antioch::value_type< vex::vector< double > >::type AntiochTesting::ArrheniusRateTestHelper< Antioch::value_type< vex::vector< double > >::type >::_Ea protected inherited
Definition at line 44 of file arrhenius_rate_test_helper.h.
vex::vector< double > * AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< vex::vector< double > >::type > , vex::vector< double > >::_example protected inherited
Definition at line 121 of file reaction_rate_vector_test_base.h.
Referenced by setUp(), and tearDown().
Antioch::value_type< vex::vector< double > >::type AntiochTesting::ArrheniusRateTestHelper< Antioch::value_type< vex::vector< double > >::type >::_R protected inherited
Definition at line 44 of file arrhenius_rate_test_helper.h.
Antioch::ArrheniusRate<typename Antioch::value_type<vex::vector< double > >::type>* AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >::_rate protected inherited
Definition at line 98 of file arrhenius_rate_vector_test_base.h.
The documentation for this class was generated from the following file:
test/vexcl_unit/arrhenius_rate_vexcl_test.C