antioch-0.4.0: Antioch::DefaultSourceFilename Class Reference
Antioch::DefaultSourceFilename Class Reference
Default filenames in the source tree.
#include <default_filename.h>
Static Public Member Functions
static const std::string & species_list ()
static const std::string & chemical_mixture ()
static const std::string & vibrational_data ()
static const std::string & electronic_data ()
static const std::string & thermo_data ()
static const std::string & sutherland_data ()
static const std::string & blottner_data ()
static const std::string & transport_mixture ()
Detailed Description
Default filenames in the source tree.
These include the full path to default files in in the Antioch source tree. If you decide to use these in your application, you must not delete the source tree.
Definition at line 46 of file default_filename.h.
Member Function Documentation
static const std::string& Antioch::DefaultSourceFilename::blottner_data () inline static
Definition at line 90 of file default_filename.h.
Referenced by Antioch::read_blottner_data_ascii_default(), tester(), and vectester().
{
     static const std::string filename =
       std::string(ANTIOCH_DEFAULT_FILES_SOURCE_PATH) +
       std::string(ANTIOCH_DEFAULT_BLOTTNER_DATA);
     return filename;
   }
static const std::string& Antioch::DefaultSourceFilename::chemical_mixture () inline static
Definition at line 55 of file default_filename.h.
Referenced by Antioch::ASCIIParser< NumericType >::ASCIIParser(), and Antioch::ASCIIParser< NumericType >::change_file().
{
     static const std::string filename =
       std::string(ANTIOCH_DEFAULT_FILES_SOURCE_PATH) +
       std::string(ANTIOCH_DEFAULT_CHEMICAL_MIXTURE);
     return filename;
   }
static const std::string& Antioch::DefaultSourceFilename::electronic_data () inline static
Definition at line 69 of file default_filename.h.
{
     static const std::string filename =
       std::string(ANTIOCH_DEFAULT_FILES_SOURCE_PATH) +
       std::string(ANTIOCH_DEFAULT_ELECTRONIC_DATA);
     return filename;
   }
static const std::string& Antioch::DefaultSourceFilename::species_list () inline static
Definition at line 48 of file default_filename.h.
{
     static const std::string filename =
       std::string(ANTIOCH_DEFAULT_FILES_SOURCE_PATH) +
       std::string(ANTIOCH_DEFAULT_SPECIES_LIST);
     return filename;
   }
static const std::string& Antioch::DefaultSourceFilename::sutherland_data () inline static
Definition at line 83 of file default_filename.h.
Referenced by Antioch::read_sutherland_data_ascii_default(), tester(), and vectester().
{
     static const std::string filename =
       std::string(ANTIOCH_DEFAULT_FILES_SOURCE_PATH) +
       std::string(ANTIOCH_DEFAULT_SUTHERLAND_DATA);
     return filename;
   }
static const std::string& Antioch::DefaultSourceFilename::thermo_data () inline static
Definition at line 76 of file default_filename.h.
Referenced by Antioch::read_cea_mixture_data_ascii_default(), tester(), and vectester().
{
     static const std::string filename =
       std::string(ANTIOCH_DEFAULT_FILES_SOURCE_PATH) +
       std::string(ANTIOCH_DEFAULT_THERMO_DATA);
     return filename;
   }
static const std::string& Antioch::DefaultSourceFilename::transport_mixture () inline static
Definition at line 97 of file default_filename.h.
{
     static const std::string filename =
       std::string(ANTIOCH_DEFAULT_FILES_SOURCE_PATH) +
       std::string(ANTIOCH_DEFAULT_TRANSPORT_DATA);
     return filename;
   }
static const std::string& Antioch::DefaultSourceFilename::vibrational_data () inline static
Definition at line 62 of file default_filename.h.
{
     static const std::string filename =
       std::string(ANTIOCH_DEFAULT_FILES_SOURCE_PATH) +
       std::string(ANTIOCH_DEFAULT_VIBRATIONAL_DATA);
     return filename;
   }
The documentation for this class was generated from the following file:
src/utilities/include/antioch/default_filename.h