antioch-0.4.0: Antioch::KineticsType< CoeffType, VectorCoeffType > Class Template Reference
Antioch::KineticsType< CoeffType, VectorCoeffType > Class Template Reference abstract
base class for kinetics models
#include <kinetics_type.h>
Public Member Functions
KineticsType (const KineticsModel::KineticsModel type)
virtual ~KineticsType ()
KineticsModel::KineticsModel type () const
template<typename StateType , typename VectorStateType >
StateType operator() (const KineticsConditions< StateType, VectorStateType > &conditions) const
template<typename StateType >
StateType operator() (const StateType &temp) const
template<typename StateType , typename VectorStateType >
StateType derivative (const KineticsConditions< StateType, VectorStateType > &conditions) const
CoeffType get_parameter (KineticsModel::Parameters parameter) const
get one parameter, characterized by enum
CoeffType get_parameter (KineticsModel::Parameters parameter, int l) const
get one parameter, characterized by enum, for vectorized parameter
template<typename StateType >
StateType derivative (const StateType &conditions) const
template<typename StateType , typename VectorStateType >
void compute_rate_and_derivative (const KineticsConditions< StateType, VectorStateType > &conditions, StateType &rate, StateType &drate_dT) const
template<typename StateType >
void compute_rate_and_derivative (const StateType &temp, StateType &rate, StateType &drate_dT) const
void set_index (unsigned int nr)
virtual const std::string numeric () const =0
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Private Attributes
KineticsModel::KineticsModel my_type
unsigned int my_index
Friends
std::ostream & operator<< (std::ostream &os, const KineticsType &rate)
Formatted print.
Detailed Description
template<typename CoeffType, typename VectorCoeffType = std::vector<CoeffType>>
class Antioch::KineticsType< CoeffType, VectorCoeffType >
base class for kinetics models
Kinetics models are:
constant (ConstantRate)
Hercourt Essen (HercourtEssenRate)
Berthelot (BerthelotRate)
Arrhenius (ArrheniusRate)
Berthelot Hercourt Essen (BerthelotHercourtEssenRate)
Kooij (KooijRate)
Van't Hoff (VantHoffRate)
photochemical model (PhotochemicalRate)
Definition at line 82 of file kinetics_type.h.
Constructor & Destructor Documentation
template<typename CoeffType , typename VectorCoeffType > Antioch::KineticsType< CoeffType, VectorCoeffType >::KineticsType (const KineticsModel::KineticsModel type) inline
Definition at line 151 of file kinetics_type.h.
                                                                                             :
     my_type(type),
     my_index(0)
   {
     return;
   }
template<typename CoeffType , typename VectorCoeffType > Antioch::KineticsType< CoeffType, VectorCoeffType >::~KineticsType () inline virtual
Definition at line 167 of file kinetics_type.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType , typename VectorCoeffType > template<typename StateType , typename VectorStateType > void Antioch::KineticsType< CoeffType, VectorCoeffType >::compute_rate_and_derivative (const KineticsConditions< StateType, VectorStateType > & conditions, StateType & rate, StateType & drate_dT) const inline
Definition at line 336 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::CONSTANT, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsConditions< StateType, VectorStateType >::particle_flux(), Antioch::KineticsModel::PHOTOCHEM, and Antioch::KineticsModel::VANTHOFF.
Referenced by test_values().
   {
     switch (my_type)
       {
       case(KineticsModel::CONSTANT):
         {
           (static_cast<const ConstantRate<CoeffType>*>(this))->rate_and_derivative(conditions,rate,drate_dT);
         }
         break;
       case(KineticsModel::HERCOURT_ESSEN):
         {
           (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(conditions,rate,drate_dT);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           (static_cast<const BerthelotRate<CoeffType>*>(this))->rate_and_derivative(conditions,rate,drate_dT);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate_and_derivative(conditions,rate,drate_dT);
         }
         break;
       case(KineticsModel::BHE):
         {
           (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate_and_derivative(conditions,rate,drate_dT);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           (static_cast<const KooijRate<CoeffType>*>(this))->rate_and_derivative(conditions,rate,drate_dT);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           (static_cast<const VantHoffRate<CoeffType>*>(this))->rate_and_derivative(conditions,rate,drate_dT);
         }
         break;
       case(KineticsModel::PHOTOCHEM):
         {
           (static_cast<const PhotochemicalRate<CoeffType,VectorCoeffType>*>(this))->rate_and_derivative(conditions.particle_flux(my_index),rate,drate_dT);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     return;
   }
template<typename CoeffType , typename VectorCoeffType > template<typename StateType > void Antioch::KineticsType< CoeffType, VectorCoeffType >::compute_rate_and_derivative (const StateType & temp, StateType & rate, StateType & drate_dT) const inline
Definition at line 482 of file kinetics_type.h.
References antioch_deprecated.
   {
     antioch_deprecated();
     return compute_rate_and_derivative
       (KineticsConditions<StateType> (temp), rate, drate_dT);
   }
template<typename CoeffType , typename VectorCoeffType > template<typename StateType , typename VectorStateType > StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::derivative (const KineticsConditions< StateType, VectorStateType > & conditions) const inline
Definition at line 259 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::CONSTANT, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsConditions< StateType, VectorStateType >::particle_flux(), Antioch::KineticsModel::PHOTOCHEM, Antioch::KineticsConditions< StateType, VectorStateType >::T(), Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
Referenced by test_values().
   {
     switch(my_type)
       {
       case(KineticsModel::CONSTANT):
         {
           return (static_cast<const ConstantRate<CoeffType>*>(this))->derivative(conditions);
         }
         break;
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->derivative(conditions);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->derivative(conditions);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->derivative(conditions);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->derivative(conditions);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->derivative(conditions);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->derivative(conditions);
         }
         break;
       case(KineticsModel::PHOTOCHEM):
         {
           return (static_cast<const PhotochemicalRate<CoeffType,VectorCoeffType>*>(this))->derivative(conditions.particle_flux(my_index));
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(conditions.T());
   }
template<typename CoeffType , typename VectorCoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::derivative (const StateType & conditions) const inline
Definition at line 326 of file kinetics_type.h.
References antioch_deprecated.
   {
     antioch_deprecated();
     return derivative
       ( KineticsConditions<StateType> (temp) );
   }
template<typename CoeffType , typename VectorCoeffType > CoeffType Antioch::KineticsType< CoeffType, VectorCoeffType >::get_parameter (KineticsModel::Parameters parameter) const
get one parameter, characterized by enum
Definition at line 400 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::CONSTANT, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, and Antioch::KineticsModel::VANTHOFF.
   {
     switch (my_type)
       {
       case(KineticsModel::CONSTANT):
         {
           return (static_cast<const ConstantRate<CoeffType>*>(this))->get_parameter(parameter);
         }
         break;
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->get_parameter(parameter);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->get_parameter(parameter);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->get_parameter(parameter);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->get_parameter(parameter);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->get_parameter(parameter);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->get_parameter(parameter);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
       return 0;
   }
template<typename CoeffType , typename VectorCoeffType > CoeffType Antioch::KineticsType< CoeffType, VectorCoeffType >::get_parameter (KineticsModel::Parameters parameter, int l) const
get one parameter, characterized by enum, for vectorized parameter
Definition at line 458 of file kinetics_type.h.
References antioch_error, and Antioch::KineticsModel::PHOTOCHEM.
   {
     switch(my_type)
       {
       case(KineticsModel::PHOTOCHEM):
         {
           return (static_cast<const PhotochemicalRate<CoeffType,VectorCoeffType>*>(this))->get_parameter(parameter,l);
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
       return 0;
   }
template<typename CoeffType, typename VectorCoeffType = std::vector<CoeffType>> virtual const std::string Antioch::KineticsType< CoeffType, VectorCoeffType >::numeric () const pure virtual
Implemented in Antioch::VantHoffRate< CoeffType >, Antioch::KooijRate< CoeffType >, Antioch::ArrheniusRate< CoeffType >, Antioch::ArrheniusRate< typename Antioch::value_type< MetaPhysicL::NumberArray< 2 *ANTIOCH_N_TUPLES, float > >::type >, Antioch::ArrheniusRate< Scalar >, Antioch::ArrheniusRate< typename Antioch::value_type< std::valarray< Scalar > >::type >, Antioch::ArrheniusRate< double >, Antioch::ArrheniusRate< float >, Antioch::ArrheniusRate< typename Antioch::value_type< vex::vector< double > >::type >, Antioch::ArrheniusRate< typename Antioch::value_type< std::valarray< float > >::type >, Antioch::ArrheniusRate< typename Antioch::value_type< std::valarray< long double > >::type >, Antioch::ArrheniusRate< typename Antioch::value_type< Eigen::Array< long double, 2 *ANTIOCH_N_TUPLES, 1 > >::type >, Antioch::ArrheniusRate< typename Antioch::value_type< Eigen::Array< float, 2 *ANTIOCH_N_TUPLES, 1 > >::type >, Antioch::ArrheniusRate< typename Antioch::value_type< std::valarray< double > >::type >, Antioch::ArrheniusRate< typename Antioch::value_type< PairScalars >::type >, Antioch::ArrheniusRate< typename Antioch::value_type< vex::vector< float > >::type >, Antioch::ArrheniusRate< long double >, Antioch::ArrheniusRate< typename Antioch::value_type< Eigen::Array< double, 2 *ANTIOCH_N_TUPLES, 1 > >::type >, Antioch::ArrheniusRate< typename Antioch::value_type< Eigen::Array< Scalar, 2 *ANTIOCH_N_TUPLES, 1 > >::type >, Antioch::BerthelotHercourtEssenRate< CoeffType >, Antioch::HercourtEssenRate< CoeffType >, Antioch::BerthelotRate< CoeffType >, Antioch::ConstantRate< CoeffType >, and Antioch::PhotochemicalRate< CoeffType, VectorCoeffType >.
template<typename CoeffType , typename VectorCoeffType > template<typename StateType , typename VectorStateType > StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::operator() (const KineticsConditions< StateType, VectorStateType > & conditions) const inline
Definition at line 182 of file kinetics_type.h.
References antioch_error, Antioch::KineticsModel::ARRHENIUS, Antioch::KineticsModel::BERTHELOT, Antioch::KineticsModel::BHE, Antioch::KineticsModel::CONSTANT, Antioch::KineticsModel::HERCOURT_ESSEN, Antioch::KineticsModel::KOOIJ, Antioch::KineticsConditions< StateType, VectorStateType >::particle_flux(), Antioch::KineticsModel::PHOTOCHEM, Antioch::KineticsConditions< StateType, VectorStateType >::T(), Antioch::KineticsModel::VANTHOFF, and Antioch::zero_clone().
   {
     switch(my_type)
       {
       case(KineticsModel::CONSTANT):
         {
           return (static_cast<const ConstantRate<CoeffType>*>(this))->rate(conditions);
         }
         break;
       case(KineticsModel::HERCOURT_ESSEN):
         {
           return (static_cast<const HercourtEssenRate<CoeffType>*>(this))->rate(conditions);
         }
         break;
       case(KineticsModel::BERTHELOT):
         {
           return (static_cast<const BerthelotRate<CoeffType>*>(this))->rate(conditions);
         }
         break;
       case(KineticsModel::ARRHENIUS):
         {
           return (static_cast<const ArrheniusRate<CoeffType>*>(this))->rate(conditions);
         }
         break;
       case(KineticsModel::BHE):
         {
           return (static_cast<const BerthelotHercourtEssenRate<CoeffType>*>(this))->rate(conditions);
         }
         break;
       case(KineticsModel::KOOIJ):
         {
           return (static_cast<const KooijRate<CoeffType>*>(this))->rate(conditions);
         }
         break;
       case(KineticsModel::VANTHOFF):
         {
           return (static_cast<const VantHoffRate<CoeffType>*>(this))->rate(conditions);
         }
         break;
       case(KineticsModel::PHOTOCHEM):
         {
           return (static_cast<const PhotochemicalRate<CoeffType,VectorCoeffType>*>(this))->rate(conditions.particle_flux(my_index));
         }
         break;
       default:
         {
           antioch_error();
         }
       } // switch(my_type)
     // Dummy
     return zero_clone(conditions.T());
   }
template<typename CoeffType , typename VectorCoeffType > template<typename StateType > StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::operator() (const StateType & temp) const inline
Definition at line 249 of file kinetics_type.h.
References antioch_deprecated.
   {
     antioch_deprecated();
     return operator()
       (KineticsConditions<StateType>(temp) );
   }
template<typename CoeffType , typename VectorCoeffType > void Antioch::KineticsType< CoeffType, VectorCoeffType >::print (std::ostream & os = std::cout) const inline
Formatted print, by default to std::cout.
Definition at line 144 of file kinetics_type.h.
   {
     os << numeric();
   }
template<typename CoeffType , typename VectorCoeffType > void Antioch::KineticsType< CoeffType, VectorCoeffType >::set_index (unsigned int nr) inline
Definition at line 174 of file kinetics_type.h.
   {
     my_index = nr;
   }
template<typename CoeffType , typename VectorCoeffType > KineticsModel::KineticsModel Antioch::KineticsType< CoeffType, VectorCoeffType >::type () const inline
Definition at line 160 of file kinetics_type.h.
Referenced by Antioch::reset_parameter_of_rate(), and Antioch::reset_rate().
   {
     return my_type;
   }
Friends And Related Function Documentation
template<typename CoeffType, typename VectorCoeffType = std::vector<CoeffType>> std::ostream& operator<< (std::ostream & os, const KineticsType< CoeffType, VectorCoeffType > & rate) friend
Formatted print.
Definition at line 130 of file kinetics_type.h.
     {
       rate.print(os);
       return os;
     }
Member Data Documentation
template<typename CoeffType, typename VectorCoeffType = std::vector<CoeffType>> unsigned int Antioch::KineticsType< CoeffType, VectorCoeffType >::my_index private
Definition at line 138 of file kinetics_type.h.
template<typename CoeffType, typename VectorCoeffType = std::vector<CoeffType>> KineticsModel::KineticsModel Antioch::KineticsType< CoeffType, VectorCoeffType >::my_type private
Definition at line 137 of file kinetics_type.h.
The documentation for this class was generated from the following file:
src/kinetics/include/antioch/kinetics_type.h