antioch-0.4.0: Antioch::IdealGasMicroThermo< MacroThermo, CoeffType > Class Template Reference
Antioch::IdealGasMicroThermo< MacroThermo, CoeffType > Class Template Reference
#include <ascii_parser.h>
Public Member Functions
IdealGasMicroThermo (const MacroThermo &ext_thermo, const ChemicalMixture< CoeffType > &chem_mix)
~IdealGasMicroThermo ()
template<typename StateType >
const ANTIOCH_AUTO (StateType) cv_vib(unsigned int s
cv_vib
const const StateType &T const ANTIOCH_AUTOFUNC (StateType,(_chem_mix.chemical_species()[s]->n_tr_dofs()< CoeffType(2.))?zero_clone(T):_ext_therm.cv(TempCache< StateType >(T), s)-this->cv_tr(s)) template< typename StateType > const ANTIOCH_AUTO(StateType) cv_vib_over_R(unsigned int s
cv_vib/R
const const StateType &T const
const StateType &T const ANTIOCH_AUTOFUNC (StateType,(_chem_mix.chemical_species()[s]->n_tr_dofs()< CoeffType(2.))?zero_clone(T):_ext_therm.cv_over_R(TempCache< StateType >(T), s)-this->cv_tr_over_R(s)) const CoeffType cv_rot(unsigned int s) const
cv_rot
const CoeffType cv_rot_over_R (unsigned int s) const
cv_rot/R
const CoeffType cv_trans (unsigned int s) const
cv_trans
const CoeffType cv_trans_over_R (unsigned int s) const
cv_trans/R
const CoeffType cv_tr (unsigned int s) const
cv_trans-rot
const CoeffType cv_tr_over_R (unsigned int s) const
cv_trans_rot/R
Private Attributes
const ChemicalMixture
< CoeffType > & _chem_mix
const MacroThermo & _ext_therm
Detailed Description
template<typename MacroThermo, typename CoeffType = double>
class Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >
Definition at line 85 of file ascii_parser.h.
Constructor & Destructor Documentation
template<typename MacroThermo , typename CoeffType > Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::IdealGasMicroThermo (const MacroThermo & ext_thermo, const ChemicalMixture< CoeffType > & chem_mix) inline
Definition at line 86 of file ideal_gas_micro_thermo.h.
                                                                                                                                             :
     _chem_mix(chem_mix),
     _ext_therm(ext_therm)
   {
      return;
   }
template<typename MacroThermo , typename CoeffType > Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::~IdealGasMicroThermo () inline
Definition at line 95 of file ideal_gas_micro_thermo.h.
   {
      return;
   }
Member Function Documentation
template<typename MacroThermo, typename CoeffType = double> template<typename StateType > const Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::ANTIOCH_AUTO (StateType)
cv_vib
template<typename MacroThermo, typename CoeffType = double> const const StateType& T const Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::ANTIOCH_AUTOFUNC (StateType , (_chem_mix.chemical_species()[s]->n_tr_dofs()< CoeffType(2.))?zero_clone(T):_ext_therm.cv(TempCache< StateType >(T), s)-this->cv_tr(s)) const
cv_vib/R
template<typename MacroThermo, typename CoeffType = double> const const StateType& T const const StateType& T const Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::ANTIOCH_AUTOFUNC (StateType , (_chem_mix.chemical_species()[s]->n_tr_dofs()< CoeffType(2.))?zero_clone(T):_ext_therm.cv_over_R(TempCache< StateType >(T), s)-this->cv_tr_over_R(s)) const
cv_rot
template<typename MacroThermo , typename CoeffType > const CoeffType Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_rot_over_R (unsigned int s) const inline
cv_rot/R
Definition at line 125 of file ideal_gas_micro_thermo.h.
References Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_tr_over_R(), Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_trans_over_R(), and std::max().
   {
     return std::max(this->cv_tr_over_R(s) - this->cv_trans_over_R(s), CoeffType(0) );
   }
template<typename MacroThermo , typename CoeffType > const CoeffType Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_tr (unsigned int s) const inline
cv_trans-rot
Definition at line 109 of file ideal_gas_micro_thermo.h.
References Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::_chem_mix.
   {
     return _chem_mix.R(s) * (_chem_mix.chemical_species()[s])->n_tr_dofs();
   }
template<typename MacroThermo , typename CoeffType > const CoeffType Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_tr_over_R (unsigned int s) const inline
cv_trans_rot/R
Definition at line 102 of file ideal_gas_micro_thermo.h.
References Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::_chem_mix.
Referenced by Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_rot_over_R().
   {
      return _chem_mix.chemical_species()[s]->n_tr_dofs();
   }
template<typename MacroThermo , typename CoeffType > const CoeffType Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_trans (unsigned int s) const inline
cv_trans
Definition at line 132 of file ideal_gas_micro_thermo.h.
References Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::_chem_mix.
   {
     return CoeffType(1.5)*_chem_mix.R(species);
   }
template<typename MacroThermo , typename CoeffType > const CoeffType Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_trans_over_R (unsigned int s) const inline
cv_trans/R
Definition at line 139 of file ideal_gas_micro_thermo.h.
Referenced by Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_rot_over_R().
   {
     return CoeffType(1.5);
   }
Member Data Documentation
template<typename MacroThermo, typename CoeffType = double> const ChemicalMixture<CoeffType>& Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::_chem_mix private
Definition at line 80 of file ideal_gas_micro_thermo.h.
Referenced by Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_tr(), Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_tr_over_R(), and Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_trans().
template<typename MacroThermo, typename CoeffType = double> const MacroThermo& Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::_ext_therm private
Definition at line 81 of file ideal_gas_micro_thermo.h.
The documentation for this class was generated from the following files:
src/parsing/include/antioch/ascii_parser.h
src/thermo/include/antioch/ideal_gas_micro_thermo.h