antioch-0.4.0: Antioch::Converter< T > Class Template Reference
Antioch::Converter< T > Class Template Reference
Class to deal with the conversion between units.
#include <converter.h>
Public Member Functions
Converter ()
Default constructor, defaults values are (1.,0.)
Converter (const T &coef, const T &trans)
Constructor.
template<typename P >
Converter (const Converter< P > &rhs)
Copy constructor, uses Converter & operator=(const Converter&)
~Converter ()
Default constructor.
template<typename P = T>
const P geta () const
Multiplicative factor getter.
template<typename P = T>
const P getb () const
Translationnal factor getter.
void clear ()
Set the values to (1.,0.)
template<typename P >
bool operator== (const Converter< P > &rhs) const
Comparison operator, equal if the two values are equal.
template<typename P >
bool operator!= (const Converter< P > &rhs) const
Comparison operator, not equal is not "equal".
template<typename P >
Converter & operator= (const Converter< P > &rhs)
Assignement operator, equalize the two values.
template<typename P >
Converter & operator*= (const Converter< P > &rhs)
Multiplying operator.
template<typename P >
Converter & operator/= (const Converter< P > &rhs)
Dividing operator.
template<typename P >
Converter & operator+= (const Converter< P > &rhs)
Adding operator.
template<typename P >
Converter operator/ (const Converter< P > &rhs) const
Dividing operator, same operations as Converter &operator/=(const Converter&)
template<typename P >
Converter operator* (const Converter< P > &rhs) const
Multiplying operator, same operations as Converter &operator*=(const Converter&)
template<typename P >
Converter & operator*= (const P &coef)
Multiplying operator with a scalar, only multiply the multiplicative value.
template<typename P >
Converter & operator/= (const P &coef)
Dividing operator with a double, only divide the multiplicative value.
template<typename P >
Converter operator* (const P &coef) const
Multiplying operator with a scalar, only multiply the multiplicative value.
template<typename P >
Converter operator/ (const P &coef) const
Dividing operator with a scalar, only divide the multiplicative value.
template<typename P >
Converter< T > & operator= (const Converter< P > &rhs)
template<typename P >
Converter< T > & operator*= (const P &coef)
template<typename P >
Converter< T > & operator/= (const P &coef)
template<typename P >
Converter< T > & operator*= (const Converter< P > &rhs)
template<typename P >
Converter< T > & operator/= (const Converter< P > &rhs)
template<typename P >
Converter< T > & operator+= (const Converter< P > &rhs)
template<typename P >
Converter< T > operator* (const P &coef) const
template<typename P >
Converter< T > operator/ (const P &coef) const
template<typename P >
Converter< T > operator/ (const Converter< P > &rhs) const
template<typename P >
Converter< T > operator* (const Converter< P > &rhs) const
Private Attributes
T a
Two double for a multiplicative and translationnal part of a coefficient.
T b
Friends
std::ostream & operator<< (std::ostream &out, const Converter< T > &rhs)
<< operator, to show the coef as a complex number (a,b)
Detailed Description
template<typename T = double>
class Antioch::Converter< T >
Class to deal with the conversion between units.
This class keeps track of the conversion factor between the unit and the base unit. To be general, this is a couple of double, one for the multiplication part and another one for the translationnal part (mainly for temperature, but it should not be used).
Definition at line 47 of file converter.h.
Constructor & Destructor Documentation
template<typename T > Antioch::Converter< T >::Converter () inline
Default constructor, defaults values are (1.,0.)
Definition at line 148 of file converter.h.
 {
   clear();
   return;
 }
template<typename T > Antioch::Converter< T >::Converter (const T & coef, const T & trans) inline
Constructor.
Definition at line 156 of file converter.h.
References Antioch::constant_clone().
 {
   a = Antioch::constant_clone(a,coef);
   b = Antioch::constant_clone(b,tran);
   return;
 }
template<typename T = double> template<typename P > Antioch::Converter< T >::Converter (const Converter< P > & rhs) inline
Copy constructor, uses Converter & operator=(const Converter&)
Definition at line 55 of file converter.h.
 {*this = rhs;}
template<typename T = double> Antioch::Converter< T >::~Converter () inline
Default constructor.
Definition at line 57 of file converter.h.
 {}
Member Function Documentation
template<typename T = double> void Antioch::Converter< T >::clear () inline
Set the values to (1.,0.)
Definition at line 66 of file converter.h.
References Antioch::Converter< T >::a, Antioch::Converter< T >::b, and Antioch::set_zero().
 {a = 1.L; Antioch::set_zero(b);}
template<typename T = double> template<typename P = T> const P Antioch::Converter< T >::geta () const inline
Multiplicative factor getter.
Definition at line 61 of file converter.h.
References Antioch::Converter< T >::a.
Referenced by Antioch::Converter< T >::operator*(), Antioch::Converter< T >::operator*=(), Antioch::Converter< T >::operator+=(), Antioch::Converter< T >::operator/(), Antioch::Converter< T >::operator/=(), Antioch::Converter< T >::operator=(), and Antioch::Units< T >::raise().
 {return (P)a;} //only scalar type
template<typename T = double> template<typename P = T> const P Antioch::Converter< T >::getb () const inline
Translationnal factor getter.
Definition at line 64 of file converter.h.
References Antioch::Converter< T >::b.
Referenced by Antioch::Converter< T >::operator*(), Antioch::Converter< T >::operator*=(), Antioch::Converter< T >::operator+=(), Antioch::Converter< T >::operator/(), Antioch::Converter< T >::operator/=(), Antioch::Converter< T >::operator=(), and Antioch::Units< T >::raise().
 {return (P)b;} //only scalar type
template<typename T = double> template<typename P > bool Antioch::Converter< T >::operator!= (const Converter< P > & rhs) const inline
Comparison operator, not equal is not "equal".
Definition at line 80 of file converter.h.
 {return !(*this == rhs);}
template<typename T = double> template<typename P > Converter Antioch::Converter< T >::operator* (const Converter< P > & rhs) const
Multiplying operator, same operations as Converter &operator*=(const Converter&)
template<typename T = double> template<typename P > Converter Antioch::Converter< T >::operator* (const P & coef) const
Multiplying operator with a scalar, only multiply the multiplicative value.
template<typename T = double> template<typename P > Converter<T> Antioch::Converter< T >::operator* (const P & coef) const inline
Definition at line 226 of file converter.h.
 {
   return Converter<T>(a*coef,b);
 }
template<typename T = double> template<typename P > Converter<T> Antioch::Converter< T >::operator* (const Converter< P > & rhs) const inline
Definition at line 250 of file converter.h.
References Antioch::Converter< T >::geta(), and Antioch::Converter< T >::getb().
 {
   return Converter<T>(a * rhs.geta() , (b + rhs.getb())/rhs.geta());
 }
template<typename T = double> template<typename P > Converter& Antioch::Converter< T >::operator*= (const Converter< P > & rhs)
Multiplying operator.
The operations performed for the mutiplication of (a,b) and (c,d) are:
template<typename T = double> template<typename P > Converter& Antioch::Converter< T >::operator*= (const P & coef)
Multiplying operator with a scalar, only multiply the multiplicative value.
template<typename T = double> template<typename P > Converter<T>& Antioch::Converter< T >::operator*= (const P & coef) inline
Definition at line 178 of file converter.h.
 {
   a *= coef;
   return *this;
 }
template<typename T = double> template<typename P > Converter<T>& Antioch::Converter< T >::operator*= (const Converter< P > & rhs) inline
Definition at line 196 of file converter.h.
References Antioch::Converter< T >::geta(), and Antioch::Converter< T >::getb().
 {
   a *= rhs.geta();
   b  = (b + rhs.getb())/rhs.geta();
   return *this;
 }
template<typename T = double> template<typename P > Converter& Antioch::Converter< T >::operator+= (const Converter< P > & rhs)
Adding operator.
The operations performed for the addition of (a,b) and (c,d) are:
template<typename T = double> template<typename P > Converter<T>& Antioch::Converter< T >::operator+= (const Converter< P > & rhs) inline
Definition at line 216 of file converter.h.
References Antioch::Converter< T >::geta(), and Antioch::Converter< T >::getb().
 {
   a *= rhs.geta();
   b += rhs.getb();
   return *this;
 }
template<typename T = double> template<typename P > Converter Antioch::Converter< T >::operator/ (const Converter< P > & rhs) const
Dividing operator, same operations as Converter &operator/=(const Converter&)
template<typename T = double> template<typename P > Converter Antioch::Converter< T >::operator/ (const P & coef) const
Dividing operator with a scalar, only divide the multiplicative value.
template<typename T = double> template<typename P > Converter<T> Antioch::Converter< T >::operator/ (const P & coef) const inline
Definition at line 234 of file converter.h.
 {
   return Converter<T>(a/coef,b);
 }
template<typename T = double> template<typename P > Converter<T> Antioch::Converter< T >::operator/ (const Converter< P > & rhs) const inline
Definition at line 242 of file converter.h.
References Antioch::Converter< T >::geta(), and Antioch::Converter< T >::getb().
 {
   return Converter(a/rhs.geta(),(b-rhs.getb())/rhs.geta());
 }
template<typename T = double> template<typename P > Converter& Antioch::Converter< T >::operator/= (const Converter< P > & rhs)
Dividing operator.
The operations performed for the division of (a,b) and (c,d) are:
template<typename T = double> template<typename P > Converter& Antioch::Converter< T >::operator/= (const P & coef)
Dividing operator with a double, only divide the multiplicative value.
template<typename T = double> template<typename P > Converter<T>& Antioch::Converter< T >::operator/= (const P & coef) inline
Definition at line 187 of file converter.h.
 {
   a /= coef;
   return *this;
 }
template<typename T = double> template<typename P > Converter<T>& Antioch::Converter< T >::operator/= (const Converter< P > & rhs) inline
Definition at line 206 of file converter.h.
References Antioch::Converter< T >::geta(), and Antioch::Converter< T >::getb().
 {
   a /= rhs.geta();
   b  = (b - rhs.getb())/rhs.geta();
   return *this;
 }
template<typename T = double> template<typename P > Converter& Antioch::Converter< T >::operator= (const Converter< P > & rhs)
Assignement operator, equalize the two values.
template<typename T = double> template<typename P > Converter<T>& Antioch::Converter< T >::operator= (const Converter< P > & rhs) inline
Definition at line 167 of file converter.h.
References Antioch::constant_clone(), Antioch::Converter< T >::geta(), and Antioch::Converter< T >::getb().
 {
  // if(this == static_cast<Converter<T>*>(&rhs)){return *this;}
   a = Antioch::constant_clone(a,rhs.geta());
   b = Antioch::constant_clone(b,rhs.getb());
   return *this;
 }
template<typename T = double> template<typename P > bool Antioch::Converter< T >::operator== (const Converter< P > & rhs) const
Comparison operator, equal if the two values are equal.
Friends And Related Function Documentation
template<typename T = double> std::ostream& operator<< (std::ostream & out, const Converter< T > & rhs) friend
<< operator, to show the coef as a complex number (a,b)
Definition at line 69 of file converter.h.
         {
           out << "(" << rhs.geta() << "," << rhs.getb() << ")";
           return out;
         }
Member Data Documentation
template<typename T = double> T Antioch::Converter< T >::a private
Two double for a multiplicative and translationnal part of a coefficient.
Definition at line 141 of file converter.h.
Referenced by Antioch::Converter< T >::clear(), and Antioch::Converter< T >::geta().
template<typename T = double> T Antioch::Converter< T >::b private
Definition at line 142 of file converter.h.
Referenced by Antioch::Converter< T >::clear(), and Antioch::Converter< T >::getb().
The documentation for this class was generated from the following file:
src/units/include/antioch/converter.h