antioch-0.4.0: Antioch::ASCIIParser< NumericType > Singleton Reference
Antioch::ASCIIParser< NumericType > Singleton Reference
#include <ascii_parser.h>
Public Member Functions
ASCIIParser (const std::string &file, bool verbose=true)
~ASCIIParser ()
void change_file (const std::string &filename)
bool initialize ()
void set_ignored_columns (const std::vector< unsigned int > &ignored)
set the indexes of to-be-ignored columns
const std::vector< std::string > species_list ()
read species list
void read_chemical_species (ChemicalMixture< NumericType > &chem_mixture)
read the mandatory data
void read_vibrational_data (ChemicalMixture< NumericType > &chem_mixture)
read the vibrational data
void read_electronic_data (ChemicalMixture< NumericType > &chem_mixture)
read the electronic data
void read_transport_data (TransportMixture< NumericType > &transport_mixture)
reads the transport data, not valid in xml && chemkin
void read_thermodynamic_data (NASAThermoMixture< NumericType, NASA7CurveFit< NumericType > > &)
reads the thermo, NASA generalist, no templates for virtual
void read_thermodynamic_data (NASAThermoMixture< NumericType, NASA9CurveFit< NumericType > > &)
reads the thermo, NASA generalist, no templates for virtual
void read_thermodynamic_data (NASAThermoMixture< NumericType, CEACurveFit< NumericType > > &thermo)
reads the thermo, NASA generalist, no templates for virtual
void read_thermodynamic_data (CEAThermodynamics< NumericType > &)
read the thermodynamic data, deprecated object
virtual bool reaction ()
reaction
virtual bool rate_constant (const std::string &)
go to next rate constant
virtual bool Troe () const
virtual const std::string reaction_id () const
virtual const std::string reaction_equation () const
virtual const std::string reaction_chemical_process () const
virtual const std::string reaction_kinetics_model (const std::vector< std::string > &) const
virtual bool reaction_reversible () const
virtual bool reactants_pairs (std::vector< std::pair< std::string, int > > &) const
virtual bool products_pairs (std::vector< std::pair< std::string, int > > &) const
virtual const std::map
< std::string, NumericType > reactants_orders () const
return a map between reactants' name and found partial orders
virtual const std::map
< std::string, NumericType > products_orders () const
return a map between products' name and found partial orders
virtual bool is_k0 (unsigned int, const std::string &) const
virtual unsigned int where_is_k0 (const std::string &) const
virtual bool rate_constant_preexponential_parameter (NumericType &, std::string &, std::string &) const
virtual bool rate_constant_power_parameter (NumericType &, std::string &, std::string &) const
virtual bool rate_constant_activation_energy_parameter (NumericType &, std::string &, std::string &) const
virtual bool rate_constant_Berthelot_coefficient_parameter (NumericType &, std::string &, std::string &) const
virtual bool rate_constant_Tref_parameter (NumericType &, std::string &, std::string &) const
virtual bool rate_constant_lambda_parameter (std::vector< NumericType > &, std::string &, std::string &) const
virtual bool rate_constant_cross_section_parameter (std::vector< NumericType > &, std::string &, std::string &) const
virtual bool verify_Kooij_in_place_of_Arrhenius () const
virtual bool efficiencies (std::vector< std::pair< std::string, NumericType > > &) const
virtual bool Troe_alpha_parameter (NumericType &, std::string &, std::string &) const
virtual bool Troe_T1_parameter (NumericType &, std::string &, std::string &) const
virtual bool Troe_T2_parameter (NumericType &, std::string &, std::string &) const
virtual bool Troe_T3_parameter (NumericType &, std::string &, std::string &) const
const std::string file () const
const std::string type () const
bool verbose () const
ParsingType enum_type () const
Protected Member Functions
void skip_comments (std::istream &doc)
Protected Attributes
std::string _type
std::string _file
bool _verbose
std::string _comments
std::string _not_implemented
Private Member Functions
template<typename CurveType >
void read_thermodynamic_data_root (NASAThermoMixture< NumericType, CurveType > &thermo)
read the thermodynamic data
template<typename Mixture >
void read_transport_data_root (Mixture &transport)
read the thermodynamic data
void find_first (unsigned int &index, unsigned int n_data) const
find the index of the wanted data
void check_warn_for_species_with_untrusted_hf (const std::string &name) const
Warn about species for which Antioch default mixture file has untrusted H_f values.
ASCIIParser ()
not allowed
Private Attributes
std::ifstream _doc
std::map< ParsingUnit,
std::string > _unit_map
std::vector< unsigned int > _ignored
const unsigned int _n_columns_chemical_species
const unsigned int _n_columns_vib_data
const unsigned int _n_columns_el_data
const unsigned int _n_columns_transport_species
bool _is_antioch_default_mixture_file
Needed to be able to warn about using not-trusted enthalpies of formation.
Detailed Description
template<typename NumericType>
singleton Antioch::ASCIIParser< NumericType >
Definition at line 88 of file ascii_parser.h.
Constructor & Destructor Documentation
template<typename NumericType > Antioch::ASCIIParser< NumericType >::ASCIIParser (const std::string & file, bool verbose = true)
Definition at line 44 of file ascii_parser.C.
References Antioch::ASCIIParser< NumericType >::_doc, Antioch::ASCIIParser< NumericType >::_is_antioch_default_mixture_file, Antioch::ASCIIParser< NumericType >::_unit_map, antioch_error, Antioch::DefaultSourceFilename::chemical_mixture(), Antioch::DefaultInstallFilename::chemical_mixture(), Antioch::MASS_ENTHALPY, Antioch::MOL_WEIGHT, Antioch::ParserBase< NumericType >::skip_comments(), and Antioch::ParserBase< NumericType >::verbose().
     : ParserBase<NumericType>("ascii",file,verbose,"#!"),
     _doc(file.c_str()),
     _n_columns_chemical_species(4), // Spec.     Mol. Wt.,     Hform (0K),  cfs,   zns
     _n_columns_vib_data(2),  // Species     Theta_v  degeneracy
     _n_columns_el_data(2),  // Species     ThetaE     edg  #elevels
     _n_columns_transport_species(5), // Species, eps/kB (K), sigma (ang), alpha (D), alpha (ang^3), Zrot@298 K
     _is_antioch_default_mixture_file(false)
   {
     if(!_doc.is_open())
       {
         std::cerr << "ERROR: unable to load file " << file << std::endl;
         antioch_error();
       }
     if( file == DefaultSourceFilename::chemical_mixture() ||
         file == DefaultInstallFilename::chemical_mixture() )
       _is_antioch_default_mixture_file = true;
     if(this->verbose())std::cout << "Having opened file " << file << std::endl;
     this->skip_comments(_doc);
     _unit_map[MOL_WEIGHT]    = "g/mol";
     _unit_map[MASS_ENTHALPY] = "J/kg";
   }
template<typename NumericType > Antioch::ASCIIParser< NumericType >::~ASCIIParser ()
Definition at line 72 of file ascii_parser.C.
   {
      _doc.close();
   }
template<typename NumericType> Antioch::ASCIIParser< NumericType >::ASCIIParser () private
not allowed
Member Function Documentation
template<typename NumericType > void Antioch::ASCIIParser< NumericType >::change_file (const std::string & filename) virtual
Implements Antioch::ParserBase< NumericType >.
Definition at line 78 of file ascii_parser.C.
References antioch_error, Antioch::DefaultSourceFilename::chemical_mixture(), and Antioch::DefaultInstallFilename::chemical_mixture().
Referenced by Antioch::ChemicalMixture< CoeffType >::ChemicalMixture().
   {
     _doc.close();
     _doc.open(filename.c_str());
     ParserBase<NumericType>::_file = filename;
     if(!_doc.is_open())
       {
         std::cerr << "ERROR: unable to load file " << filename << std::endl;
         antioch_error();
       }
     if( filename == DefaultSourceFilename::chemical_mixture() ||
         filename == DefaultInstallFilename::chemical_mixture() )
       _is_antioch_default_mixture_file = true;
     if(this->verbose())std::cout << "Having opened file " << filename << std::endl;
     this->skip_comments(_doc);
   }
template<typename NumericType > void Antioch::ASCIIParser< NumericType >::check_warn_for_species_with_untrusted_hf (const std::string & name) const private
Warn about species for which Antioch default mixture file has untrusted H_f values.
Definition at line 483 of file ascii_parser.C.
   {
     std::vector<std::string> species_with_unknown_Hf(9);
     species_with_unknown_Hf[0] = "CH2O";
     species_with_unknown_Hf[1] = "HCCO";
     species_with_unknown_Hf[2] = "HCCOH";
     species_with_unknown_Hf[3] = "H2CN";
     species_with_unknown_Hf[4] = "HCNN";
     species_with_unknown_Hf[5] = "HCNO";
     species_with_unknown_Hf[6] = "HOCN";
     species_with_unknown_Hf[7] = "C3H7";
     species_with_unknown_Hf[8] = "CH2CHO";
     std::vector<std::string>::const_iterator it = std::search_n( species_with_unknown_Hf.begin(),
                                                                  species_with_unknown_Hf.end(),
                                                                  1, name );
     if( it != species_with_unknown_Hf.end() )
       {
         std::cout << "WARNING: Detected that you're using Antioch's default chemical mixture file" << std::endl
                   << "         and using species " << name <<". The Enthaply of formation of this" << std::endl
                   << "         species is currently NOT TRUSTED. BE AWARE THAT USING StatMechThermodynamics"
                   << std::endl
                   << "         WILL LIKELY GIVE INACCURATE RESULTS! All other calculations are unaffected."
                   << std::endl;
       }
   }
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::efficiencies (std::vector< std::pair< std::string, NumericType > > &) const inline virtual inherited
Returns
true if efficiencies are found
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 227 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType > ParsingType Antioch::ParserBase< NumericType >::enum_type () const inherited
Returns
enum
Definition at line 63 of file parser_base.C.
References antioch_parsing_error, Antioch::ASCII, Antioch::CHEMKIN, and Antioch::XML.
   {
     ParsingType PType(ASCII);
     if(_type == "ascii")
       {
         PType = ASCII;
       }
     else if(_type == "ChemKin")
       {
         PType = CHEMKIN;
       }
     else if(_type == "XML")
       {
         PType = XML;
       }
     else
       {
         antioch_parsing_error(std::string("unknown parser type!!! " + _type));
       }
     return PType;
   }
template<typename NumericType> const std::string Antioch::ParserBase< NumericType >::file () const inline inherited
Returns
name of file
Definition at line 242 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_file.
Referenced by Antioch::read_species_data(), Antioch::read_species_electronic_data(), Antioch::read_species_vibrational_data(), and Antioch::read_transport_species_data().
 {return _file;}
template<typename NumericType > void Antioch::ASCIIParser< NumericType >::find_first (unsigned int & index, unsigned int n_data) const private
find the index of the wanted data
Definition at line 99 of file ascii_parser.C.
References antioch_parsing_error.
   {
     // slow algorithm so whatever order of ignored column is fine
     bool find(true);
     while(find)
       {
         find = false;
         for(unsigned int ii = 0; ii < _ignored.size(); ii++)
           {
             if(index == _ignored[ii])
               {
                 find = true;
                 index++;
                 break;
               }
           }
       }
     if(index > n_data)
       {
         std::cerr << "Error while reading " << this->file() << std::endl
                   << "Total number of columns provided is " << n_data
                   << " with " << _ignored.size() << " ignored column." << std::endl
                   << "The provided ignored index are:\n";
         for(unsigned int i = 0; i < _ignored.size(); i++)
           {
             std::cerr << _ignored[i] << std::endl;
           }
         std::cerr << "Indexes start at zero, maybe try decreasing them?" << std::endl;
         antioch_parsing_error("Error in ASCII parser");
       }
   }
template<typename NumericType> bool Antioch::ASCIIParser< NumericType >::initialize () inline virtual
Implements Antioch::ParserBase< NumericType >.
Definition at line 96 of file ascii_parser.h.
 {return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::is_k0 (unsigned int , const std::string &) const inline virtual inherited
Returns
true if "name" attribute is found with value "k0"
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 197 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual const std::map<std::string,NumericType> Antioch::ParserBase< NumericType >::products_orders () const inline virtual inherited
return a map between products' name and found partial orders
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 194 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return std::map<std::string,NumericType>();}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::products_pairs (std::vector< std::pair< std::string, int > > &) const inline virtual inherited
Returns
pairs of products and stoichiometric coefficients
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 188 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::rate_constant (const std::string &) inline virtual inherited
go to next rate constant
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 162 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::rate_constant_activation_energy_parameter (NumericType & , std::string & , std::string &) const inline virtual inherited
Returns
true if activation energie
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 209 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::rate_constant_Berthelot_coefficient_parameter (NumericType & , std::string & , std::string &) const inline virtual inherited
Returns
true if D coefficient
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 212 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::rate_constant_cross_section_parameter (std::vector< NumericType > & , std::string & , std::string &) const inline virtual inherited
Returns
true if sigma
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 221 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::rate_constant_lambda_parameter (std::vector< NumericType > & , std::string & , std::string &) const inline virtual inherited
Returns
true if lambda
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 218 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::rate_constant_power_parameter (NumericType & , std::string & , std::string &) const inline virtual inherited
Returns
true if beta coefficient
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 206 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::rate_constant_preexponential_parameter (NumericType & , std::string & , std::string &) const inline virtual inherited
Returns
true if pre exponentiel coefficient
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 203 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::rate_constant_Tref_parameter (NumericType & , std::string & , std::string &) const inline virtual inherited
Returns
true if Tref
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 215 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual const std::map<std::string,NumericType> Antioch::ParserBase< NumericType >::reactants_orders () const inline virtual inherited
return a map between reactants' name and found partial orders
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 191 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return std::map<std::string,NumericType>();}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::reactants_pairs (std::vector< std::pair< std::string, int > > &) const inline virtual inherited
Returns
pairs of reactants and stoichiometric coefficients
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 185 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::reaction () inline virtual inherited
reaction
read & store current reaction and go to next reaction
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 159 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual const std::string Antioch::ParserBase< NumericType >::reaction_chemical_process () const inline virtual inherited
Returns
reaction chemical process
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 176 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return std::string();}
template<typename NumericType> virtual const std::string Antioch::ParserBase< NumericType >::reaction_equation () const inline virtual inherited
Returns
reaction equation
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 173 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return std::string();}
template<typename NumericType> virtual const std::string Antioch::ParserBase< NumericType >::reaction_id () const inline virtual inherited
Returns
reaction id, 0 if not provided
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 170 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return std::string();}
template<typename NumericType> virtual const std::string Antioch::ParserBase< NumericType >::reaction_kinetics_model (const std::vector< std::string > &) const inline virtual inherited
Returns
reaction kinetics model
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 179 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return std::string();}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::reaction_reversible () const inline virtual inherited
Returns
reversible state
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 182 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType > void Antioch::ASCIIParser< NumericType >::read_chemical_species (ChemicalMixture< NumericType > & chem_mixture) virtual
read the mandatory data
Reimplemented from Antioch::ParserBase< NumericType >.
Definition at line 178 of file ascii_parser.C.
References Antioch::ChemicalMixture< CoeffType >::add_species(), std::int, Antioch::MASS_ENTHALPY, Antioch::MOL_WEIGHT, Antioch::ChemicalMixture< CoeffType >::species_list(), and Antioch::ChemicalMixture< CoeffType >::species_name_map().
   {
     std::string name;
     NumericType mol_wght, h_form, n_tr_dofs;
     int charge;
     NumericType mw_unit = Units<NumericType>(_unit_map.at(MOL_WEIGHT)).get_SI_factor();
     NumericType ef_unit = Units<NumericType>(_unit_map.at(MASS_ENTHALPY)).get_SI_factor();
     const unsigned int n_data = _n_columns_chemical_species + _ignored.size(); // we read all those columns
     unsigned int imw(0);
     this->find_first(imw,n_data);
     unsigned int ihf(imw+1);
     this->find_first(ihf,n_data);
     unsigned int itrdofs(ihf+1);
     this->find_first(itrdofs,n_data);
     unsigned int ic(itrdofs+1);
     this->find_first(ic,n_data);
     std::vector<NumericType> read(n_data,0.);
     if(this->verbose())std::cout << "Reading species characteristics in file " << this->file() << std::endl;
     while (_doc.good())
       {
         this->skip_comments(_doc); // if comment in the middle
         _doc >> name;      // Species Name
         for(unsigned int i = 0; i < n_data; i++)_doc >> read[i];
         mol_wght  = read[imw];     // molecular weight (kg/kmol)
         h_form    = read[ihf];     // heat of formation at Ok (J/kg)
         n_tr_dofs = read[itrdofs]; // number of translational/rotational DOFs
         charge    = int(read[ic]); // charge number
         mol_wght *= mw_unit; // to SI (kg/mol)
         h_form *= ef_unit; // to SI (J/kg)
         // If we are still good, we have a valid set of thermodynamic
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (_doc.good())
           {
             // If we do not have this species, just go on
             if (!chem_mixture.species_name_map().count(name))continue;
             Species species = chem_mixture.species_name_map().at(name);
             // using default comparison:
             std::vector<Species>::const_iterator it = std::search_n( chem_mixture.species_list().begin(),
                                                                      chem_mixture.species_list().end(),
                                                                      1, species);
             if( it != chem_mixture.species_list().end() )
               {
                 unsigned int index = static_cast<unsigned int>(it - chem_mixture.species_list().begin());
                 chem_mixture.add_species( index, name, mol_wght, h_form, n_tr_dofs, charge );
                 if(this->verbose())
                   {
                     std::cout << "Adding " << name << " informations:\n\t"
                               << "molecular weight: "             << mol_wght << " kg/mol\n\t"
                               << "formation enthalpy @0 K: "      << h_form << " J/mol\n\t"
                               << "trans-rot degrees of freedom: " << n_tr_dofs << "\n\t"
                               << "charge: "                       << charge << std::endl;
                   }
                 if(_is_antioch_default_mixture_file)
                   this->check_warn_for_species_with_untrusted_hf(name);
               }
           }
       }
   }
template<typename NumericType > void Antioch::ASCIIParser< NumericType >::read_electronic_data (ChemicalMixture< NumericType > & chem_mixture) virtual
read the electronic data
Reimplemented from Antioch::ParserBase< NumericType >.
Definition at line 300 of file ascii_parser.C.
References Antioch::ChemicalMixture< CoeffType >::add_species_electronic_data(), antioch_assert_equal_to, Antioch::ChemicalMixture< CoeffType >::chemical_species(), std::int, and Antioch::ChemicalMixture< CoeffType >::species_name_map().
   {
     std::string name;
     NumericType theta_e;
     unsigned int n_degeneracies;
     const unsigned int n_data = _n_columns_el_data + _ignored.size(); // we read all those columns
     unsigned int ite(0);
     this->find_first(ite,n_data);
     unsigned int ide(ite+1);
     this->find_first(ide,n_data);
     std::vector<NumericType> read(n_data,0);
     if(this->verbose())std::cout << "Reading electronic data in file " << this->file() << std::endl;
     while (_doc.good())
       {
         _doc >> name;           // Species Name
         for(unsigned int i = 0; i < n_data; i++)_doc >> read[i];
         theta_e        = read[ite];                 // characteristic electronic temperature (K)
         n_degeneracies = (unsigned int)(read[ide]); // number of degeneracies for this level
         // If we are still good, we have a valid set of thermodynamic
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (_doc.good())
           {
             // If we do not have this species, just go on
             if (!chem_mixture.species_name_map().count(name))continue;
             // ... otherwise we add the data
             const unsigned int s =
               chem_mixture.species_name_map().find(name)->second;
             antioch_assert_equal_to((chem_mixture.chemical_species()[s])->species(), name);
             chem_mixture.add_species_electronic_data(s, theta_e, n_degeneracies);
             if(this->verbose())
               {
                 std::cout << "Adding electronic data of species " << name << "\n\t"
                           << "electronic temperature: " << theta_e << " K\n\t"
                           << "degeneracy: "             << n_degeneracies << std::endl;
               }
           }
       }
   }
template<typename NumericType> void Antioch::ASCIIParser< NumericType >::read_thermodynamic_data (NASAThermoMixture< NumericType, NASA7CurveFit< NumericType > > &) inline virtual
reads the thermo, NASA generalist, no templates for virtual
Reimplemented from Antioch::ParserBase< NumericType >.
Definition at line 126 of file ascii_parser.h.
References antioch_error_msg.
Referenced by Antioch::read_cea_mixture_data_ascii().
     {antioch_error_msg("ERROR: ASCIIParsing only supports parsing for CEACurveFit!");}
template<typename NumericType> void Antioch::ASCIIParser< NumericType >::read_thermodynamic_data (NASAThermoMixture< NumericType, NASA9CurveFit< NumericType > > &) inline virtual
reads the thermo, NASA generalist, no templates for virtual
Reimplemented from Antioch::ParserBase< NumericType >.
Definition at line 130 of file ascii_parser.h.
References antioch_error_msg.
     {antioch_error_msg("ERROR: ASCIIParsing only supports parsing for CEACurveFit!");}
template<typename NumericType> void Antioch::ASCIIParser< NumericType >::read_thermodynamic_data (NASAThermoMixture< NumericType, CEACurveFit< NumericType > > & thermo) inline virtual
reads the thermo, NASA generalist, no templates for virtual
Reimplemented from Antioch::ParserBase< NumericType >.
Definition at line 134 of file ascii_parser.h.
References Antioch::ASCIIParser< NumericType >::read_thermodynamic_data_root().
     {this->read_thermodynamic_data_root(thermo);}
template<typename NumericType > void Antioch::ASCIIParser< NumericType >::read_thermodynamic_data (CEAThermodynamics< NumericType > & thermo) virtual
read the thermodynamic data, deprecated object
Reimplemented from Antioch::ParserBase< NumericType >.
Definition at line 394 of file ascii_parser.C.
References Antioch::CEAThermodynamics< CoeffType >::add_curve_fit(), Antioch::CEAThermodynamics< CoeffType >::chemical_mixture(), and Antioch::ChemicalMixture< CoeffType >::species_name_map().
   {
     std::string name;
     unsigned int n_int;
     std::vector<NumericType> coeffs;
     NumericType h_form, val;
     const ChemicalMixture<NumericType>& chem_mixture = thermo.chemical_mixture();
 // \todo: only cea, should do NASA
     while (_doc.good())
       {
         this->skip_comments(_doc);
         _doc >> name;   // Species Name
         _doc >> n_int;  // Number of T intervals: [200-1000], [1000-6000], ([6000-20000])
         _doc >> h_form; // Formation Enthalpy @ 298.15 K
         coeffs.clear();
         for (unsigned int interval=0; interval<n_int; interval++)
           {
             for (unsigned int n=0; n<10; n++)
               {
                 _doc >> val, coeffs.push_back(val);
               }
           }
         // If we are still good, we have a valid set of thermodynamic
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (_doc.good())
           {
             // Check if this is a species we want.
             if( chem_mixture.species_name_map().find(name) !=
                 chem_mixture.species_name_map().end() )
               {
                 thermo.add_curve_fit(name, coeffs);
               }
           }
       } // end while
   }
template<typename NumericType > template<typename CurveType > void Antioch::ASCIIParser< NumericType >::read_thermodynamic_data_root (NASAThermoMixture< NumericType, CurveType > & thermo) private
read the thermodynamic data
Definition at line 349 of file ascii_parser.C.
References Antioch::NASAThermoMixture< CoeffType, NASAFit >::add_curve_fit(), Antioch::NASAThermoMixture< CoeffType, NASAFit >::chemical_mixture(), and Antioch::ChemicalMixture< CoeffType >::species_name_map().
Referenced by Antioch::ASCIIParser< NumericType >::read_thermodynamic_data().
   {
     std::string name;
     unsigned int n_int;
     std::vector<NumericType> coeffs;
     NumericType h_form, val;
     const ChemicalMixture<NumericType>& chem_mixture = thermo.chemical_mixture();
 // \todo: only cea, should do NASA
     while (_doc.good())
       {
         this->skip_comments(_doc);
         _doc >> name;   // Species Name
         _doc >> n_int;  // Number of T intervals: [200-1000], [1000-6000], ([6000-20000])
         _doc >> h_form; // Formation Enthalpy @ 298.15 K
         coeffs.clear();
         for (unsigned int interval=0; interval<n_int; interval++)
           {
             for (unsigned int n=0; n<10; n++)
               {
                 _doc >> val, coeffs.push_back(val);
               }
           }
         // If we are still good, we have a valid set of thermodynamic
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (_doc.good())
           {
             // Check if this is a species we want.
             if( chem_mixture.species_name_map().find(name) !=
                 chem_mixture.species_name_map().end() )
               {
                 if(this->verbose())std::cout << "Adding curve fit " << name << std::endl;
                 thermo.add_curve_fit(name, coeffs);
               }
           }
       } // end while
   }
template<typename NumericType> void Antioch::ASCIIParser< NumericType >::read_transport_data (TransportMixture< NumericType > & transport_mixture) inline virtual
reads the transport data, not valid in xml && chemkin
Reimplemented from Antioch::ParserBase< NumericType >.
Definition at line 117 of file ascii_parser.h.
References Antioch::ASCIIParser< NumericType >::read_transport_data_root().
 {this->read_transport_data_root(transport_mixture);}
template<typename NumericType > template<typename Mixture > void Antioch::ASCIIParser< NumericType >::read_transport_data_root (Mixture & transport) private
read the thermodynamic data
Definition at line 438 of file ascii_parser.C.
Referenced by Antioch::ASCIIParser< NumericType >::read_transport_data().
   {
     std::string name;
     NumericType LJ_eps_kB;
     NumericType LJ_sigma;
     NumericType dipole_moment;
     NumericType pol;
     NumericType Zrot;
     const unsigned int n_data = _n_columns_transport_species + _ignored.size(); // we read all those columns
     unsigned int iLJeps(0);
     this->find_first(iLJeps,n_data);
     unsigned int iLJsig(iLJeps+1);
     this->find_first(iLJsig,n_data);
     unsigned int idip(iLJsig+1);
     this->find_first(idip,n_data);
     unsigned int ipol(idip+1);
     this->find_first(ipol,n_data);
     unsigned int irot(ipol+1);
     this->find_first(irot,n_data);
     std::vector<NumericType> read(n_data,0.);
     while (_doc.good())
       {
         this->skip_comments(_doc);
         _doc >> name;
         for(unsigned int i = 0; i < n_data; i++)_doc >> read[i];
         LJ_eps_kB     = read[iLJeps];
         LJ_sigma      = read[iLJsig];
         dipole_moment = read[idip];
         pol           = read[ipol];
         Zrot          = read[irot];
         if(transport.chemical_mixture().species_name_map().count(name))
           {
             unsigned int place = transport.chemical_mixture().species_name_map().at(name);
             NumericType mass = transport.chemical_mixture().M(place);
             // adding species in mixture
             transport.add_species(place,LJ_eps_kB,LJ_sigma,dipole_moment,pol,Zrot,mass);
           }
       }
   }
template<typename NumericType > void Antioch::ASCIIParser< NumericType >::read_vibrational_data (ChemicalMixture< NumericType > & chem_mixture) virtual
read the vibrational data
Reimplemented from Antioch::ParserBase< NumericType >.
Definition at line 249 of file ascii_parser.C.
References Antioch::ChemicalMixture< CoeffType >::add_species_vibrational_data(), antioch_assert_equal_to, Antioch::ChemicalMixture< CoeffType >::chemical_species(), std::int, and Antioch::ChemicalMixture< CoeffType >::species_name_map().
   {
     std::string name;
     NumericType theta_v;
     unsigned int n_degeneracies;
     const unsigned int n_data = _n_columns_vib_data + _ignored.size(); // we read all those columns
     unsigned int itv(0);
     this->find_first(itv,n_data);
     unsigned int ide(itv+1);
     this->find_first(ide,n_data);
     std::vector<NumericType> read(n_data,0);
     if(this->verbose())std::cout << "Reading vibrational data in file " << this->file() << std::endl;
     while (_doc.good())
       {
         this->skip_comments(_doc); // if comment in the middle
         _doc >> name;           // Species Name
         for(unsigned int i = 0; i < n_data; i++)_doc >> read[i];
         theta_v        = read[itv];                 // characteristic vibrational temperature (K)
         n_degeneracies = (unsigned int)(read[ide]); // degeneracy of the mode
         // If we are still good, we have a valid set of thermodynamic
         // data for this species. Otherwise, we read past end-of-file
         // in the section above
         if (_doc.good())
           {
             // If we do not have this species, just keep going
             if (!chem_mixture.species_name_map().count(name))continue;
             // ... otherwise we add the data
             const unsigned int s =
               chem_mixture.species_name_map().find(name)->second;
             antioch_assert_equal_to((chem_mixture.chemical_species()[s])->species(), name);
             chem_mixture.add_species_vibrational_data(s, theta_v, n_degeneracies);
             if(this->verbose())
               {
                 std::cout << "Adding vibrational data of species " << name << "\n\t"
                           << "vibrational temperature: " << theta_v << " K\n\t"
                           << "degeneracy: "              << n_degeneracies << std::endl;
               }
           }
       }
   }
template<typename NumericType > void Antioch::ASCIIParser< NumericType >::set_ignored_columns (const std::vector< unsigned int > & ignored)
set the indexes of to-be-ignored columns
Definition at line 133 of file ascii_parser.C.
Referenced by tester().
   {
       _ignored = ignored;
   }
template<typename NumericType > void Antioch::ParserBase< NumericType >::skip_comments (std::istream & doc) protected inherited
Definition at line 54 of file parser_base.C.
References Antioch::skip_comment_lines().
Referenced by Antioch::ASCIIParser< NumericType >::ASCIIParser().
   {
     for(unsigned int c = 0; c < _comments.size(); c++)
       {
         skip_comment_lines(doc, _comments[c]);
       }
   }
template<typename NumericType > const std::vector< std::string > Antioch::ASCIIParser< NumericType >::species_list () virtual
read species list
Reimplemented from Antioch::ParserBase< NumericType >.
Definition at line 139 of file ascii_parser.C.
   {
     std::vector<std::string> species_list;
     std::string spec;
     while(_doc.good())
       {
         this->skip_comments(_doc); // if comments in the middle
         _doc >> spec;
         if(!_doc.good())break; // read successful?
         // checking doublon
         bool doublon(false);
         for(unsigned int s = 0; s < species_list.size(); s++)
           {
             if(spec == species_list[s])
               {
                 doublon = true;
                 break;
               }
             if(doublon)
               {
                 std::cerr << "Multiple declaration of " << spec
                           << ", skipping doublon" << std::endl;
                 continue;
               }
             // adding
           }
         if(this->verbose())std::cout << spec << std::endl;
         species_list.push_back(spec);
       }
     if(this->verbose())std::cout << "Found " << species_list.size() << " species\n\n" << std::endl;
     return species_list;
   }
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::Troe () const inline virtual inherited
Returns
true if there's a Troe block
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 167 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::Troe_alpha_parameter (NumericType & , std::string & , std::string &) const inline virtual inherited
Returns
true is alpha
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 230 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::Troe_T1_parameter (NumericType & , std::string & , std::string &) const inline virtual inherited
Returns
true is alpha
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 233 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::Troe_T2_parameter (NumericType & , std::string & , std::string &) const inline virtual inherited
Returns
true is alpha
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 236 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::Troe_T3_parameter (NumericType & , std::string & , std::string &) const inline virtual inherited
Returns
true is alpha
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 239 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> const std::string Antioch::ParserBase< NumericType >::type () const inline inherited
Returns
type of parser
Definition at line 245 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_type.
 {return _type;}
template<typename NumericType> bool Antioch::ParserBase< NumericType >::verbose () const inline inherited
Returns
verbosity
Definition at line 248 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_verbose.
Referenced by Antioch::ASCIIParser< NumericType >::ASCIIParser(), Antioch::ChemKinParser< NumericType >::ChemKinParser(), and Antioch::XMLParser< NumericType >::XMLParser().
 {return _verbose;}
template<typename NumericType> virtual bool Antioch::ParserBase< NumericType >::verify_Kooij_in_place_of_Arrhenius () const inline virtual inherited
Returns
true if a Kooij is called Arrhenuis
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 224 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return false;}
template<typename NumericType> virtual unsigned int Antioch::ParserBase< NumericType >::where_is_k0 (const std::string &) const inline virtual inherited
Returns
index of k0 (0 or 1)
Reimplemented in Antioch::ChemKinParser< NumericType >, and Antioch::XMLParser< NumericType >.
Definition at line 200 of file parser_base.h.
References Antioch::ParserBase< NumericType >::_not_implemented, and antioch_not_implemented_msg.
Referenced by Antioch::read_reaction_set_data().
 {antioch_not_implemented_msg(_not_implemented); return -1;}
Member Data Documentation
template<typename NumericType> std::string Antioch::ParserBase< NumericType >::_comments protected inherited
Definition at line 261 of file parser_base.h.
template<typename NumericType> std::ifstream Antioch::ASCIIParser< NumericType >::_doc private
Definition at line 161 of file ascii_parser.h.
Referenced by Antioch::ASCIIParser< NumericType >::ASCIIParser().
template<typename NumericType> std::string Antioch::ParserBase< NumericType >::_file protected inherited
Definition at line 259 of file parser_base.h.
Referenced by Antioch::ParserBase< NumericType >::file(), and Antioch::ParserBase< NumericType >::ParserBase().
template<typename NumericType> std::vector<unsigned int> Antioch::ASCIIParser< NumericType >::_ignored private
Definition at line 164 of file ascii_parser.h.
template<typename NumericType> bool Antioch::ASCIIParser< NumericType >::_is_antioch_default_mixture_file private
Needed to be able to warn about using not-trusted enthalpies of formation.
Definition at line 171 of file ascii_parser.h.
Referenced by Antioch::ASCIIParser< NumericType >::ASCIIParser().
template<typename NumericType> const unsigned int Antioch::ASCIIParser< NumericType >::_n_columns_chemical_species private
Definition at line 165 of file ascii_parser.h.
template<typename NumericType> const unsigned int Antioch::ASCIIParser< NumericType >::_n_columns_el_data private
Definition at line 167 of file ascii_parser.h.
template<typename NumericType> const unsigned int Antioch::ASCIIParser< NumericType >::_n_columns_transport_species private
Definition at line 168 of file ascii_parser.h.
template<typename NumericType> const unsigned int Antioch::ASCIIParser< NumericType >::_n_columns_vib_data private
Definition at line 166 of file ascii_parser.h.
template<typename NumericType> std::string Antioch::ParserBase< NumericType >::_not_implemented protected inherited
Definition at line 263 of file parser_base.h.
Referenced by Antioch::ParserBase< NumericType >::efficiencies(), Antioch::ParserBase< NumericType >::is_k0(), Antioch::ParserBase< NumericType >::ParserBase(), Antioch::ParserBase< NumericType >::products_orders(), Antioch::ParserBase< NumericType >::products_pairs(), Antioch::ParserBase< NumericType >::rate_constant(), Antioch::ParserBase< NumericType >::rate_constant_activation_energy_parameter(), Antioch::ParserBase< NumericType >::rate_constant_Berthelot_coefficient_parameter(), Antioch::ParserBase< NumericType >::rate_constant_cross_section_parameter(), Antioch::ParserBase< NumericType >::rate_constant_lambda_parameter(), Antioch::ParserBase< NumericType >::rate_constant_power_parameter(), Antioch::ParserBase< NumericType >::rate_constant_preexponential_parameter(), Antioch::ParserBase< NumericType >::rate_constant_Tref_parameter(), Antioch::ParserBase< NumericType >::reactants_orders(), Antioch::ParserBase< NumericType >::reactants_pairs(), Antioch::ParserBase< NumericType >::reaction(), Antioch::ParserBase< NumericType >::reaction_chemical_process(), Antioch::ParserBase< NumericType >::reaction_equation(), Antioch::ParserBase< NumericType >::reaction_id(), Antioch::ParserBase< NumericType >::reaction_kinetics_model(), Antioch::ParserBase< NumericType >::reaction_reversible(), Antioch::ParserBase< NumericType >::read_chemical_species(), Antioch::ParserBase< NumericType >::read_electronic_data(), Antioch::ParserBase< NumericType >::read_thermodynamic_data(), Antioch::ParserBase< NumericType >::read_transport_data(), Antioch::ParserBase< NumericType >::read_vibrational_data(), Antioch::ParserBase< NumericType >::species_list(), Antioch::ParserBase< NumericType >::Troe(), Antioch::ParserBase< NumericType >::Troe_alpha_parameter(), Antioch::ParserBase< NumericType >::Troe_T1_parameter(), Antioch::ParserBase< NumericType >::Troe_T2_parameter(), Antioch::ParserBase< NumericType >::Troe_T3_parameter(), Antioch::ParserBase< NumericType >::verify_Kooij_in_place_of_Arrhenius(), and Antioch::ParserBase< NumericType >::where_is_k0().
template<typename NumericType> std::string Antioch::ParserBase< NumericType >::_type protected inherited
Definition at line 258 of file parser_base.h.
Referenced by Antioch::ParserBase< NumericType >::ParserBase(), and Antioch::ParserBase< NumericType >::type().
template<typename NumericType> std::map<ParsingUnit,std::string> Antioch::ASCIIParser< NumericType >::_unit_map private
Definition at line 162 of file ascii_parser.h.
Referenced by Antioch::ASCIIParser< NumericType >::ASCIIParser().
template<typename NumericType> bool Antioch::ParserBase< NumericType >::_verbose protected inherited
Definition at line 260 of file parser_base.h.
Referenced by Antioch::ParserBase< NumericType >::verbose().
The documentation for this singleton was generated from the following files:
src/parsing/include/antioch/ascii_parser.h
src/parsing/src/ascii_parser.C