antioch-0.4.0: Antioch::MixtureAveragedTransportMixture< CoeffType > Class Template Reference
Antioch::MixtureAveragedTransportMixture< CoeffType > Class Template Reference
Mixture object for MixtureAveragedTransport model.
#include <mixture_averaged_transport_mixture.h>
Public Member Functions
MixtureAveragedTransportMixture (const TransportMixture< CoeffType > &mixture)
~MixtureAveragedTransportMixture ()
CoeffType Mr_Ms_to_the_one_fourth (const unsigned int r, const unsigned int s) const
CoeffType denominator (const unsigned int r, const unsigned int s) const
const ChemicalMixture
< CoeffType > & chem_mixture () const
chemical mixture, mostly for backward compatibility
const TransportMixture
< CoeffType > & transport_mixture () const
transport mixture
Protected Attributes
const TransportMixture
< CoeffType > & _mixture
std::vector< std::vector
< CoeffType > > _Mr_Ms_to_the_one_fourth
Cache for numerator term.
std::vector< std::vector
< CoeffType > > _denom
Cache for denominator term.
Detailed Description
template<class CoeffType = double>
class Antioch::MixtureAveragedTransportMixture< CoeffType >
Mixture object for MixtureAveragedTransport model.
This object is meant to live for the life of the program and contains data that is reused by the MixtureAveragedTransportEvaluator object. In particular, there are two terms for species indices r and s:
These terms appear in the mixing formulae used in MixtureAveragedTransportEvaluator.
Definition at line 59 of file mixture_averaged_transport_mixture.h.
Constructor & Destructor Documentation
template<class CoeffType > Antioch::MixtureAveragedTransportMixture< CoeffType >::MixtureAveragedTransportMixture (const TransportMixture< CoeffType > & mixture)
Definition at line 96 of file mixture_averaged_transport_mixture.h.
References Antioch::MixtureAveragedTransportMixture< CoeffType >::_denom, Antioch::MixtureAveragedTransportMixture< CoeffType >::_Mr_Ms_to_the_one_fourth, Antioch::TransportMixture< CoeffType >::chemical_mixture(), Antioch::TransportMixture< CoeffType >::n_species(), and std::pow().
     : _mixture(mixture),
       _Mr_Ms_to_the_one_fourth(mixture.n_species()),
       _denom(mixture.n_species())
   {
     using std::pow;
     for( unsigned int r = 0; r < mixture.n_species(); r++ )
       {
         _Mr_Ms_to_the_one_fourth[r].resize(mixture.n_species());
         _denom[r].resize(mixture.n_species());
         for( unsigned int s = 0; s < mixture.n_species(); s++ )
           {
             const CoeffType Mr = mixture.chemical_mixture().M(r);
             const CoeffType Ms = mixture.chemical_mixture().M(s);
             _Mr_Ms_to_the_one_fourth[r][s] = pow( Mr/Ms, CoeffType(0.25) );
             _denom[r][s] = std::sqrt(8.0*(1.0+Ms/Mr));
           }
       }
   }
template<class CoeffType = double> Antioch::MixtureAveragedTransportMixture< CoeffType >::~MixtureAveragedTransportMixture () inline
Definition at line 65 of file mixture_averaged_transport_mixture.h.
 {};
Member Function Documentation
template<class CoeffType > const ChemicalMixture< CoeffType > & Antioch::MixtureAveragedTransportMixture< CoeffType >::chem_mixture () const inline
chemical mixture, mostly for backward compatibility
Definition at line 138 of file mixture_averaged_transport_mixture.h.
   {
     return _mixture.chemical_mixture();
   }
template<class CoeffType > CoeffType Antioch::MixtureAveragedTransportMixture< CoeffType >::denominator (const unsigned int r, const unsigned int s) const inline
Definition at line 130 of file mixture_averaged_transport_mixture.h.
   {
     return _denom[r][s];
   }
template<class CoeffType > CoeffType Antioch::MixtureAveragedTransportMixture< CoeffType >::Mr_Ms_to_the_one_fourth (const unsigned int r, const unsigned int s) const inline
Definition at line 121 of file mixture_averaged_transport_mixture.h.
   {
     return _Mr_Ms_to_the_one_fourth[r][s];
   }
template<class CoeffType > const TransportMixture< CoeffType > & Antioch::MixtureAveragedTransportMixture< CoeffType >::transport_mixture () const inline
transport mixture
Definition at line 145 of file mixture_averaged_transport_mixture.h.
   {
     return _mixture;
   }
Member Data Documentation
template<class CoeffType = double> std::vector<std::vector<CoeffType> > Antioch::MixtureAveragedTransportMixture< CoeffType >::_denom protected
Cache for denominator term.
Todo:
We should use a more efficient data structure
Definition at line 91 of file mixture_averaged_transport_mixture.h.
Referenced by Antioch::MixtureAveragedTransportMixture< CoeffType >::MixtureAveragedTransportMixture().
template<class CoeffType = double> const TransportMixture<CoeffType>& Antioch::MixtureAveragedTransportMixture< CoeffType >::_mixture protected
Definition at line 83 of file mixture_averaged_transport_mixture.h.
template<class CoeffType = double> std::vector<std::vector<CoeffType> > Antioch::MixtureAveragedTransportMixture< CoeffType >::_Mr_Ms_to_the_one_fourth protected
Cache for numerator term.
Todo:
We should use a more efficient data structure
Definition at line 87 of file mixture_averaged_transport_mixture.h.
Referenced by Antioch::MixtureAveragedTransportMixture< CoeffType >::MixtureAveragedTransportMixture().
The documentation for this class was generated from the following file:
src/transport/include/antioch/mixture_averaged_transport_mixture.h