antioch-0.4.0: Antioch::LindemannFalloff< CoeffType > Class Template Reference
Antioch::LindemannFalloff< CoeffType > Class Template Reference
Simplest falloff model ()
#include <lindemann_falloff.h>
Public Member Functions
LindemannFalloff (const unsigned int nspec)
~LindemannFalloff ()
template<typename StateType >
StateType value (const StateType &T, const StateType &M, const StateType &k0, const StateType &kinf) const
template<typename StateType >
StateType operator() (const StateType &T, const StateType &M, const StateType &k0, const StateType &kinf) const
template<typename StateType , typename VectorStateType >
void F_and_derivatives (const StateType &T, const StateType &M, const StateType &k0, const StateType &dk0_dT, const StateType &kinf, const StateType &dkinf_dT, StateType &F, StateType &dF_dT, VectorStateType &dF_dX) const
Private Attributes
unsigned int n_spec
Detailed Description
template<typename CoeffType = double>
class Antioch::LindemannFalloff< CoeffType >
Simplest falloff model ()
The Lindemann model is the simplest falloff model:
From which we derive:
Definition at line 52 of file lindemann_falloff.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::LindemannFalloff< CoeffType >::LindemannFalloff (const unsigned int nspec) inline
Definition at line 135 of file lindemann_falloff.h.
                                                                        :n_spec(nspec)
   {
     return;
   }
template<typename CoeffType > Antioch::LindemannFalloff< CoeffType >::~LindemannFalloff () inline
Definition at line 142 of file lindemann_falloff.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType > template<typename StateType , typename VectorStateType > void Antioch::LindemannFalloff< CoeffType >::F_and_derivatives (const StateType & T, const StateType & M, const StateType & k0, const StateType & dk0_dT, const StateType & kinf, const StateType & dkinf_dT, StateType & F, StateType & dF_dT, VectorStateType & dF_dX) const inline
Definition at line 113 of file lindemann_falloff.h.
References antioch_assert_equal_to, Antioch::constant_clone(), and Antioch::set_zero().
   {
     //all derived are 0
     Antioch::set_zero(dF_dT);
     antioch_assert_equal_to(dF_dX.size(),n_spec);
     Antioch::set_zero(dF_dX);
     // F = 1
     F = Antioch::constant_clone(T,1);
     return;
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::LindemannFalloff< CoeffType >::operator() (const StateType & T, const StateType & M, const StateType & k0, const StateType & kinf) const inline
Definition at line 89 of file lindemann_falloff.h.
References Antioch::constant_clone().
   {
     return Antioch::constant_clone(T, 1);
   }
template<typename CoeffType > template<typename StateType > StateType Antioch::LindemannFalloff< CoeffType >::value (const StateType & T, const StateType & M, const StateType & k0, const StateType & kinf) const inline
Definition at line 101 of file lindemann_falloff.h.
References Antioch::constant_clone().
   {
     return Antioch::constant_clone(T, 1);
   }
Member Data Documentation
template<typename CoeffType = double> unsigned int Antioch::LindemannFalloff< CoeffType >::n_spec private
Definition at line 81 of file lindemann_falloff.h.
The documentation for this class was generated from the following file:
src/kinetics/include/antioch/lindemann_falloff.h