antioch-0.4.0: tinyxml2::StrPair Class Reference
tinyxml2::StrPair Class Reference
#include <tinyxml2.h>
Public Types
enum {
NEEDS_ENTITY_PROCESSING = 0x01, NEEDS_NEWLINE_NORMALIZATION = 0x02, COLLAPSE_WHITESPACE = 0x04, TEXT_ELEMENT = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
TEXT_ELEMENT_LEAVE_ENTITIES = NEEDS_NEWLINE_NORMALIZATION, ATTRIBUTE_NAME = 0, ATTRIBUTE_VALUE = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION, ATTRIBUTE_VALUE_LEAVE_ENTITIES = NEEDS_NEWLINE_NORMALIZATION,
COMMENT = NEEDS_NEWLINE_NORMALIZATION
}
Public Member Functions
StrPair ()
~StrPair ()
void Set (char *_start, char *_end, int _flags)
const char * GetStr ()
bool Empty () const
void SetInternedStr (const char *str)
void SetStr (const char *str, int flags=0)
char * ParseText (char *in, const char *endTag, int strFlags)
char * ParseName (char *in)
Private Types
enum { NEEDS_FLUSH = 0x100, NEEDS_DELETE = 0x200 }
Private Member Functions
void Reset ()
void CollapseWhitespace ()
Private Attributes
int flags
char * start
char * end
Detailed Description
Definition at line 119 of file tinyxml2.h.
Member Enumeration Documentation
anonymous enum
Enumerator
NEEDS_ENTITY_PROCESSING
NEEDS_NEWLINE_NORMALIZATION
COLLAPSE_WHITESPACE
TEXT_ELEMENT
TEXT_ELEMENT_LEAVE_ENTITIES
ATTRIBUTE_NAME
ATTRIBUTE_VALUE
ATTRIBUTE_VALUE_LEAVE_ENTITIES
COMMENT
Definition at line 122 of file tinyxml2.h.
              {
                 NEEDS_ENTITY_PROCESSING                 = 0x01,
                 NEEDS_NEWLINE_NORMALIZATION             = 0x02,
                 COLLAPSE_WHITESPACE                             = 0x04,
                 TEXT_ELEMENT            = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
                 TEXT_ELEMENT_LEAVE_ENTITIES             = NEEDS_NEWLINE_NORMALIZATION,
                 ATTRIBUTE_NAME          = 0,
                 ATTRIBUTE_VALUE         = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
                 ATTRIBUTE_VALUE_LEAVE_ENTITIES          = NEEDS_NEWLINE_NORMALIZATION,
                 COMMENT                         = NEEDS_NEWLINE_NORMALIZATION
         };
anonymous enum private
Enumerator
NEEDS_FLUSH
NEEDS_DELETE
Definition at line 156 of file tinyxml2.h.
              {
                 NEEDS_FLUSH = 0x100,
                 NEEDS_DELETE = 0x200
         };
Constructor & Destructor Documentation
tinyxml2::StrPair::StrPair () inline
Definition at line 135 of file tinyxml2.h.
 : flags( 0 ), start( 0 ), end( 0 ) {}
StrPair::~StrPair () inline
Definition at line 89 of file tinyxml2_imp.h.
References Reset().
 {
         Reset();
 }
Member Function Documentation
void StrPair::CollapseWhitespace () inline private
Definition at line 168 of file tinyxml2_imp.h.
References tinyxml2::XMLUtil::IsWhiteSpace(), tinyxml2::XMLUtil::SkipWhiteSpace(), and start.
Referenced by GetStr().
 {
         // Trim leading space.
         start = XMLUtil::SkipWhiteSpace( start );
         if ( start && *start ) {
                 char* p = start;        // the read pointer
                 char* q = start;        // the write pointer
                 while( *p ) {
                         if ( XMLUtil::IsWhiteSpace( *p )) {
                                 p = XMLUtil::SkipWhiteSpace( p );
                                 if ( *p == 0 )
                                         break;  // don't write to q; this trims the trailing space.
                                 *q = ' ';
                                 ++q;
                         }
                         *q = *p;
                         ++q;
                         ++p;
                 }
                 *q = 0;
         }
 }
bool tinyxml2::StrPair::Empty () const inline
Definition at line 143 of file tinyxml2.h.
References end, and start.
Referenced by tinyxml2::XMLNode::ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
 { return start == end; }
const char * StrPair::GetStr () inline
Definition at line 195 of file tinyxml2_imp.h.
References COLLAPSE_WHITESPACE, CollapseWhitespace(), end, flags, tinyxml2::XMLUtil::GetCharacterRef(), Entity::length, NEEDS_DELETE, NEEDS_ENTITY_PROCESSING, NEEDS_FLUSH, NEEDS_NEWLINE_NORMALIZATION, start, TIXMLASSERT, and Entity::value.
Referenced by tinyxml2::XMLAttribute::Name(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLNode::Value(), and tinyxml2::XMLAttribute::Value().
 {
         if ( flags & NEEDS_FLUSH ) {
                 *end = 0;
                 flags ^= NEEDS_FLUSH;
                 if ( flags ) {
                         char* p = start;        // the read pointer
                         char* q = start;        // the write pointer
                         while( p < end ) {
                                 if ( (flags & NEEDS_NEWLINE_NORMALIZATION) && *p == CR ) {
                                         // CR-LF pair becomes LF
                                         // CR alone becomes LF
                                         // LF-CR becomes LF
                                         if ( *(p+1) == LF ) {
                                                 p += 2;
                                         }
                                         else {
                                                 ++p;
                                         }
                                         *q++ = LF;
                                 }
                                 else if ( (flags & NEEDS_NEWLINE_NORMALIZATION) && *p == LF ) {
                                         if ( *(p+1) == CR ) {
                                                 p += 2;
                                         }
                                         else {
                                                 ++p;
                                         }
                                         *q++ = LF;
                                 }
                                 else if ( (flags & NEEDS_ENTITY_PROCESSING) && *p == '&' ) {
                                         // Entities handled by tinyXML2:
                                         // - special entities in the entity table [in/out]
                                         // - numeric character reference [in]
                                         //   &#20013; or &#x4e2d;
                                         if ( *(p+1) == '#' ) {
                                                 char buf[10] = { 0 };
                                                 int len;
                                                 p = const_cast<char*>( XMLUtil::GetCharacterRef( p, buf, &len ) );
                                                 for( int i=0; i<len; ++i ) {
                                                         *q++ = buf[i];
                                                 }
                                                 TIXMLASSERT( q <= p );
                                         }
                                         else {
                                                 int i=0;
                                                 for(; i<NUM_ENTITIES; ++i ) {
                                                         if (    strncmp( p+1, entities[i].pattern, entities[i].length ) == 0
                                                                  && *(p+entities[i].length+1) == ';' )
{
                                                                 // Found an entity convert;
                                                                 *q = entities[i].value;
                                                                 ++q;
                                                                 p += entities[i].length + 2;
                                                                 break;
                                                         }
                                                 }
                                                 if ( i == NUM_ENTITIES ) {
                                                         // fixme: treat as error?
                                                         ++p;
                                                         ++q;
                                                 }
                                         }
                                 }
                                 else {
                                         *q = *p;
                                         ++p;
                                         ++q;
                                 }
                         }
                         *q = 0;
                 }
                 // The loop below has plenty going on, and this
                 // is a less useful mode. Break it out.
                 if ( flags & COLLAPSE_WHITESPACE ) {
                         CollapseWhitespace();
                 }
                 flags = (flags & NEEDS_DELETE);
         }
         return start;
 }
char * StrPair::ParseName (char * in) inline
Definition at line 141 of file tinyxml2_imp.h.
References tinyxml2::XMLUtil::IsAlphaNum(), Set(), and start.
Referenced by tinyxml2::XMLAttribute::ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
 {
         char* start = p;
         if ( !start || !(*start) ) {
                 return 0;
         }
         while( *p && (
                            XMLUtil::IsAlphaNum( (unsigned char) *p )
                         || *p == '_'
                         || *p == ':'
                         || (*p == '-' && p>start )              // can be in a name, but not lead it.
                         || (*p == '.' && p>start ) ))   // can be in a name, but not lead it.
         {
                 ++p;
         }
         if ( p > start ) {
                 Set( start, p, 0 );
                 return p;
         }
         return 0;
 }
char * StrPair::ParseText (char * in, const char * endTag, int strFlags) inline
Definition at line 120 of file tinyxml2_imp.h.
References Set(), start, and TIXMLASSERT.
Referenced by tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), and tinyxml2::XMLAttribute::ParseDeep().
 {
         TIXMLASSERT( endTag && *endTag );
         char* start = p;        // fixme: hides a member
         char  endChar = *endTag;
         size_t length = strlen( endTag );
         // Inner loop of text parsing.
         while ( *p ) {
                 if ( *p == endChar && strncmp( p, endTag, length ) == 0 ) {
                         Set( start, p, strFlags );
                         return p + length;
                 }
                 ++p;
         }
         return 0;
 }
void StrPair::Reset () inline private
Definition at line 96 of file tinyxml2_imp.h.
References end, flags, NEEDS_DELETE, and start.
Referenced by Set(), SetInternedStr(), SetStr(), and ~StrPair().
 {
         if ( flags & NEEDS_DELETE ) {
                 delete [] start;
         }
         flags = 0;
         start = 0;
         end = 0;
 }
void tinyxml2::StrPair::Set (char * _start, char * _end, int _flags) inline
Definition at line 138 of file tinyxml2.h.
References end, flags, NEEDS_FLUSH, Reset(), and start.
Referenced by ParseName(), and ParseText().
{
                 Reset();
                 this->start = _start; this->end = _end; this->flags = _flags | NEEDS_FLUSH;
         }
void tinyxml2::StrPair::SetInternedStr (const char * str) inline
Definition at line 145 of file tinyxml2.h.
References Reset(), and start.
Referenced by tinyxml2::XMLNode::SetValue().
 { Reset(); this->start = const_cast<char*>(str); }
void StrPair::SetStr (const char * str, int flags = 0) inline
Definition at line 108 of file tinyxml2_imp.h.
References end, NEEDS_DELETE, Reset(), and start.
Referenced by tinyxml2::XMLAttribute::SetAttribute(), tinyxml2::XMLAttribute::SetName(), and tinyxml2::XMLNode::SetValue().
 {
         Reset();
         size_t len = strlen( str );
         start = new char[ len+1 ];
         memcpy( start, str, len+1 );
         end = start + len;
         this->flags = flags | NEEDS_DELETE;
 }
Member Data Documentation
char* tinyxml2::StrPair::end private
Definition at line 164 of file tinyxml2.h.
Referenced by Empty(), GetStr(), Reset(), Set(), and SetStr().
int tinyxml2::StrPair::flags private
Definition at line 162 of file tinyxml2.h.
Referenced by GetStr(), Reset(), and Set().
char* tinyxml2::StrPair::start private
Definition at line 163 of file tinyxml2.h.
Referenced by CollapseWhitespace(), Empty(), GetStr(), ParseName(), ParseText(), Reset(), Set(), SetInternedStr(), and SetStr().
The documentation for this class was generated from the following files:
src/parsing/include/antioch/tinyxml2.h
src/parsing/include/antioch/tinyxml2_imp.h