antioch-0.4.0: Antioch::TransportMixture< CoeffType > Class Template Reference
Antioch::TransportMixture< CoeffType > Class Template Reference
Class storing chemical mixture properties.
#include <ascii_parser.h>
Public Member Functions
TransportMixture (const ChemicalMixture< CoeffType > &mixture, const std::string &filename=DefaultFilename::transport_mixture(), bool verbose=true, ParsingType type=ASCII)
TransportMixture (const ChemicalMixture< CoeffType > &mixture, ParserBase< CoeffType > *parser)
~TransportMixture ()
unsigned int n_species () const
ChemicalMixture method.
const std::vector< Species > & species_list () const
ChemicalMixture method.
const std::map< Species,
std::string > & species_inverse_name_map () const
ChemicalMixture method.
const std::map< std::string,
Species > & species_name_map () const
ChemicalMixture method.
const ChemicalMixture
< CoeffType > & chemical_mixture () const
void add_species (const unsigned int index, CoeffType LJ_depth, CoeffType LJ_diameter, CoeffType dipole_moment, CoeffType polarizability, CoeffType rotational_relaxation, CoeffType mass)
const std::vector
< TransportSpecies< CoeffType > * > & transport_species () const
const TransportSpecies
< CoeffType > & transport_species (unsigned int s) const
Protected Attributes
const ChemicalMixture
< CoeffType > & _chemical_mixture
std::vector< TransportSpecies
< CoeffType > * > _transport_species
Private Types
typedef unsigned int Species
Private Member Functions
TransportMixture ()
Detailed Description
template<typename CoeffType = double>
class Antioch::TransportMixture< CoeffType >
Class storing chemical mixture properties.
This class manages the list of TransportSpecies for a requested set of species from input.
Definition at line 55 of file ascii_parser.h.
Member Typedef Documentation
template<typename CoeffType = double> typedef unsigned int Antioch::TransportMixture< CoeffType >::Species private
Definition at line 70 of file transport_mixture.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::TransportMixture< CoeffType >::TransportMixture (const ChemicalMixture< CoeffType > & mixture, const std::string & filename = DefaultFilename::transport_mixture(), bool verbose = true, ParsingType type = ASCII)
Definition at line 39 of file transport_mixture.C.
References Antioch::TransportMixture< CoeffType >::_chemical_mixture, Antioch::TransportMixture< CoeffType >::_transport_species, antioch_parsing_error, Antioch::ASCII, Antioch::CHEMKIN, Antioch::read_transport_species_data(), and Antioch::XML.
     : _chemical_mixture( chem_mix),
       _transport_species(_chemical_mixture.n_species(), NULL )
   {
     ParserBase<CoeffType> * parser(NULL);
     switch(type)
       {
       case ASCII:
         parser = new ASCIIParser<CoeffType>(filename,verbose);
         break;
       case CHEMKIN:
         parser = new ChemKinParser<CoeffType>(filename,verbose);
         break;
       case XML:
         parser = new XMLParser<CoeffType>(filename,verbose);
         break;
       default:
         antioch_parsing_error("unknown type");
       }
     // Now read in transport properties for the requested species and stash
     read_transport_species_data(parser,*this);
     // check we have everyone requested
     for( unsigned int s = 0; s < _transport_species.size(); ++s )
       {
         if(!_transport_species[s]) // it is not mandatory, Blottner or Sutherland are self-sufficient
           {
             std::cerr << "Warning: missing transport data for species "
                       << _chemical_mixture.species_inverse_name_map().at(_chemical_mixture.species_list()[s])
                       << "\n"
                       << "Be sure to use a transport model that does not require the default data"
                       << std::endl;
           }
       }
     delete parser;
   }
template<typename CoeffType > Antioch::TransportMixture< CoeffType >::TransportMixture (const ChemicalMixture< CoeffType > & mixture, ParserBase< CoeffType > * parser)
Definition at line 81 of file transport_mixture.C.
References Antioch::TransportMixture< CoeffType >::_chemical_mixture, Antioch::TransportMixture< CoeffType >::_transport_species, and Antioch::read_transport_species_data().
     : _chemical_mixture( mixture),
       _transport_species(_chemical_mixture.n_species(), NULL )
   {
     // Now read in transport properties for the requested species and stash
     read_transport_species_data(parser,*this);
     // check we have everyone requested
     for( unsigned int s = 0; s < _transport_species.size(); ++s )
       {
         if(!_transport_species[s]) // it is not mandatory, Blottner or Sutherland are self-sufficient
           {
             std::cerr << "Warning: missing transport data for species " << _chemical_mixture.species_inverse_name_map().at(
                                                                                                                            _chemical_mixture.species_list()[s]) << "\n"
                       << "Be sure to use a transport model that does not require the default data"
                       << std::endl;
           }
       }
     return;
   }
template<typename CoeffType > Antioch::TransportMixture< CoeffType >::~TransportMixture ()
Definition at line 106 of file transport_mixture.C.
   {
     // Clean up all the TransportSpecies we stored
     for( typename std::vector<TransportSpecies<CoeffType>* >::iterator it = _transport_species.begin();
          it < _transport_species.end(); ++it )
       {
         delete (*it);
       }
   }
template<typename CoeffType = double> Antioch::TransportMixture< CoeffType >::TransportMixture () private
Member Function Documentation
template<typename CoeffType > void Antioch::TransportMixture< CoeffType >::add_species (const unsigned int index, CoeffType LJ_depth, CoeffType LJ_diameter, CoeffType dipole_moment, CoeffType polarizability, CoeffType rotational_relaxation, CoeffType mass)
Definition at line 117 of file transport_mixture.C.
   {
     Species name_enum = _chemical_mixture.species_list()[index];
     _transport_species[index] = new TransportSpecies<CoeffType>(name_enum,
                                                                 LJ_depth,
                                                                 LJ_diameter,
                                                                 dipole_moment,
                                                                 polarizability,
                                                                 rotational_relaxation,mass);
   }
template<typename CoeffType > const ChemicalMixture< CoeffType > & Antioch::TransportMixture< CoeffType >::chemical_mixture () const inline
Returns
the chemical mixture
Definition at line 150 of file transport_mixture.h.
Referenced by Antioch::MixtureAveragedTransportMixture< CoeffType >::MixtureAveragedTransportMixture().
   {
      return _chemical_mixture;
   }
template<typename CoeffType > unsigned int Antioch::TransportMixture< CoeffType >::n_species () const inline
ChemicalMixture method.
Definition at line 122 of file transport_mixture.h.
Referenced by Antioch::MixtureAveragedTransportMixture< CoeffType >::MixtureAveragedTransportMixture(), and Antioch::read_transport_species_data().
   {
     return _chemical_mixture.n_species();
   }
template<typename CoeffType > const std::map< Species, std::string > & Antioch::TransportMixture< CoeffType >::species_inverse_name_map () const inline
ChemicalMixture method.
Definition at line 136 of file transport_mixture.h.
Referenced by Antioch::read_transport_species_data().
   {
     return _chemical_mixture.species_inverse_name_map();
   }
template<typename CoeffType > const std::vector< Species > & Antioch::TransportMixture< CoeffType >::species_list () const inline
ChemicalMixture method.
Definition at line 129 of file transport_mixture.h.
   {
     return _chemical_mixture.species_list();
   }
template<typename CoeffType > const std::map< std::string, Species > & Antioch::TransportMixture< CoeffType >::species_name_map () const inline
ChemicalMixture method.
Definition at line 143 of file transport_mixture.h.
   {
     return _chemical_mixture.species_name_map();
   }
template<typename CoeffType > const std::vector< TransportSpecies< CoeffType > * > & Antioch::TransportMixture< CoeffType >::transport_species () const inline
Definition at line 157 of file transport_mixture.h.
Referenced by Antioch::read_transport_species_data(), and tester().
   {
     return _transport_species;
   }
template<typename CoeffType > const TransportSpecies< CoeffType > & Antioch::TransportMixture< CoeffType >::transport_species (unsigned int s) const inline
Definition at line 164 of file transport_mixture.h.
References antioch_assert, and antioch_assert_less.
   {
     antioch_assert_less(s,_transport_species.size());
     antioch_assert(_transport_species[s]);
     return (*_transport_species[s]);
   }
Member Data Documentation
template<typename CoeffType = double> const ChemicalMixture<CoeffType>& Antioch::TransportMixture< CoeffType >::_chemical_mixture protected
Definition at line 108 of file transport_mixture.h.
Referenced by Antioch::TransportMixture< CoeffType >::TransportMixture().
template<typename CoeffType = double> std::vector<TransportSpecies<CoeffType>*> Antioch::TransportMixture< CoeffType >::_transport_species protected
Definition at line 110 of file transport_mixture.h.
Referenced by Antioch::TransportMixture< CoeffType >::TransportMixture().
The documentation for this class was generated from the following files:
src/parsing/include/antioch/ascii_parser.h
src/transport/include/antioch/transport_mixture.h
src/transport/src/transport_mixture.C