antioch-0.4.0: Antioch::NASAThermoMixture< CoeffType, NASAFit > Class Template Reference
Antioch::NASAThermoMixture< CoeffType, NASAFit > Class Template Reference
#include <ascii_parser.h>
Public Member Functions
NASAThermoMixture (const ChemicalMixture< CoeffType > &chem_mixture)
virtual ~NASAThermoMixture ()
Destructor.
void add_curve_fit (const std::string &species_name, const std::vector< CoeffType > &coeffs)
void add_curve_fit (const std::string &species_name, const std::vector< CoeffType > &coeffs, const std::vector< CoeffType > &temps)
const NASAFit & curve_fit (unsigned int s) const
CoeffType cp_at_200p1 (unsigned int s) const
bool check () const
Checks that curve fits have been specified for all species in the mixture.
const ChemicalMixture
< CoeffType > & chemical_mixture () const
Protected Attributes
const ChemicalMixture
< CoeffType > & _chem_mixture
std::vector< NASAFit * > _species_curve_fits
std::vector< CoeffType > _cp_at_200p1
Private Member Functions
NASAThermoMixture ()
Default constructor.
Detailed Description
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>>
class Antioch::NASAThermoMixture< CoeffType, NASAFit >
Definition at line 59 of file ascii_parser.h.
Constructor & Destructor Documentation
template<typename CoeffType, typename NASAFit > Antioch::NASAThermoMixture< CoeffType, NASAFit >::NASAThermoMixture (const ChemicalMixture< CoeffType > & chem_mixture)
Definition at line 95 of file nasa_mixture.h.
     : _chem_mixture(chem_mixture),
       _species_curve_fits(chem_mixture.n_species(), NULL),
       _cp_at_200p1( _species_curve_fits.size() )
   {
     return;
   }
template<typename CoeffType , typename NASAFit > Antioch::NASAThermoMixture< CoeffType, NASAFit >::~NASAThermoMixture () virtual
Destructor.
virtual so this can be subclassed by the user.
Definition at line 105 of file nasa_mixture.h.
   {
     // Clean up all the NASAFits we created
     for( typename std::vector<NASAFit* >::iterator it = _species_curve_fits.begin();
          it < _species_curve_fits.end(); ++it )
       {
         delete (*it);
       }
     return;
   }
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> Antioch::NASAThermoMixture< CoeffType, NASAFit >::NASAThermoMixture () private
Default constructor.
Private to force to user to supply a ChemicalMixture object.
Member Function Documentation
template<typename CoeffType, typename NASAFit > void Antioch::NASAThermoMixture< CoeffType, NASAFit >::add_curve_fit (const std::string & species_name, const std::vector< CoeffType > & coeffs) inline
Definition at line 120 of file nasa_mixture.h.
References antioch_assert, antioch_assert_less_equal, and Antioch::NASAEvaluator< CoeffType, NASAFit >::cp().
Referenced by Antioch::ASCIIParser< NumericType >::read_thermodynamic_data_root(), and Antioch::ChemKinParser< NumericType >::read_thermodynamic_data_root().
   {
     antioch_assert( _chem_mixture.species_name_map().find(species_name) !=
                     _chem_mixture.species_name_map().end() );
     unsigned int s = _chem_mixture.species_name_map().find(species_name)->second;
     antioch_assert_less_equal( s, _species_curve_fits.size() );
     antioch_assert( !_species_curve_fits[s] );
     _species_curve_fits[s] = new NASAFit(coeffs);
     NASAEvaluator<CoeffType,NASAFit> evaluator( *this );
     _cp_at_200p1[s] = evaluator.cp( TempCache<CoeffType>(200.1), s );
     return;
   }
template<typename CoeffType, typename NASAFit > void Antioch::NASAThermoMixture< CoeffType, NASAFit >::add_curve_fit (const std::string & species_name, const std::vector< CoeffType > & coeffs, const std::vector< CoeffType > & temps) inline
Definition at line 141 of file nasa_mixture.h.
References antioch_assert, antioch_assert_less_equal, and Antioch::NASAEvaluator< CoeffType, NASAFit >::cp().
   {
     antioch_assert( _chem_mixture.species_name_map().find(species_name) !=
                     _chem_mixture.species_name_map().end() );
     unsigned int s = _chem_mixture.species_name_map().find(species_name)->second;
     antioch_assert_less_equal( s, _species_curve_fits.size() );
     antioch_assert( !_species_curve_fits[s] );
     _species_curve_fits[s] = new NASAFit(coeffs,temps);
     NASAEvaluator<CoeffType,NASAFit> evaluator( *this );
     _cp_at_200p1[s] = evaluator.cp( TempCache<CoeffType>(200.1), s );
     return;
   }
template<typename CoeffType , typename NASAFit > bool Antioch::NASAThermoMixture< CoeffType, NASAFit >::check () const inline
Checks that curve fits have been specified for all species in the mixture.
Definition at line 163 of file nasa_mixture.h.
Referenced by Antioch::read_nasa_mixture_data().
   {
     bool valid = true;
     for( typename std::vector<NASAFit* >::const_iterator it = _species_curve_fits.begin();
          it != _species_curve_fits.end(); ++ it )
       {
         if( !(*it) )
           valid = false;
       }
     return valid;
   }
template<typename CoeffType , typename NASAFit > const ChemicalMixture< CoeffType > & Antioch::NASAThermoMixture< CoeffType, NASAFit >::chemical_mixture () const inline
Definition at line 200 of file nasa_mixture.h.
Referenced by Antioch::ASCIIParser< NumericType >::read_thermodynamic_data_root(), and Antioch::ChemKinParser< NumericType >::read_thermodynamic_data_root().
   {
     return _chem_mixture;
   }
template<typename CoeffType , typename NASAFit > CoeffType Antioch::NASAThermoMixture< CoeffType, NASAFit >::cp_at_200p1 (unsigned int s) const inline
Definition at line 192 of file nasa_mixture.h.
References antioch_assert_less.
   {
     antioch_assert_less( s, _cp_at_200p1.size() );
     return _cp_at_200p1[s];
   }
template<typename CoeffType , typename NASAFit > const NASAFit & Antioch::NASAThermoMixture< CoeffType, NASAFit >::curve_fit (unsigned int s) const inline
Definition at line 179 of file nasa_mixture.h.
References antioch_assert, and antioch_assert_less.
Referenced by AntiochTesting::NASA9XMLParsingTest< long double >::test_supplied_species().
   {
     // Did we allocate for enough species?
     antioch_assert_less( s, _species_curve_fits.size() );
     // Did we read in enough mixture data?
     antioch_assert( _species_curve_fits[s] );
     return *_species_curve_fits[s];
   }
Member Data Documentation
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> const ChemicalMixture<CoeffType>& Antioch::NASAThermoMixture< CoeffType, NASAFit >::_chem_mixture protected
Definition at line 79 of file nasa_mixture.h.
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> std::vector<CoeffType> Antioch::NASAThermoMixture< CoeffType, NASAFit >::_cp_at_200p1 protected
Definition at line 83 of file nasa_mixture.h.
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> std::vector<NASAFit* > Antioch::NASAThermoMixture< CoeffType, NASAFit >::_species_curve_fits protected
Definition at line 81 of file nasa_mixture.h.
The documentation for this class was generated from the following files:
src/parsing/include/antioch/ascii_parser.h
src/thermo/include/antioch/nasa_mixture.h