antioch-0.4.0: Antioch::VantHoffRate< CoeffType > Class Template Reference
Antioch::VantHoffRate< CoeffType > Class Template Reference
Van't Hoff rate equation.
#include <kinetics_type.h>
Public Member Functions
VantHoffRate (const CoeffType Cf=0., const CoeffType eta=0., const CoeffType Ea=0., const CoeffType D=0., const CoeffType Tref=1., const CoeffType rscale=Constants::R_universal< CoeffType >())
~VantHoffRate ()
void set_Cf (const CoeffType Cf)
void set_eta (const CoeffType eta)
void set_Ea (const CoeffType Ea)
set _raw_Ea, unit is known (cal.mol-1, J.mol-1, whatever), _Ea is computed
void reset_Ea (const CoeffType Ea)
set _Ea, unit is K, _raw_Ea is computed
void set_D (const CoeffType D)
void set_Tref (const CoeffType Tref)
void set_rscale (const CoeffType rscale)
void set_parameter (KineticsModel::Parameters parameter, CoeffType new_value)
set one parameter, characterized by enum
CoeffType get_parameter (KineticsModel::Parameters parameter) const
get one parameter, characterized by enum
template<typename VectorCoeffType >
void set_parameter (KineticsModel::Parameters parameter, VectorCoeffType new_value)
for compatibility purpose with photochemistry (particle flux reactions)
template<typename VectorCoeffType >
void reset_coefs (const VectorCoeffType &coefficients)
reset the coeffs
CoeffType Cf () const
CoeffType eta () const
CoeffType Ea () const
CoeffType Ea_K () const
CoeffType D () const
CoeffType Tref () const
CoeffType rscale () const
template<typename StateType >
rate (const StateType &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_pow (T, _eta)*ant_exp(-_Ea/T+_D *T))) template< typename StateType > operator()(const StateType &T) const template< typename StateType > derivative(const StateType &T) const ANTIOCH_AUTOFUNC(StateType
template<typename StateType , typename VectorStateType >
rate (const KineticsConditions< StateType, VectorStateType > &T) const ANTIOCH_AUTOFUNC(StateType
_Cf * ant_exp (_eta *T.temp_cache().lnT-_Ea/T.T()+_D *T.T())) template< typename StateType
_Cf VectorStateType operator() (const KineticsConditions< StateType, VectorStateType > &T) const template< typename StateType
_Cf VectorStateType VectorStateType derivative (const KineticsConditions< StateType, VectorStateType > &T) const ANTIOCH_AUTOFUNC(StateType
const std::string numeric () const
print equation
KineticsModel::KineticsModel type () const
StateType operator() (const StateType &temp) const
StateType derivative (const StateType &conditions) const
CoeffType get_parameter (KineticsModel::Parameters parameter, int l) const
get one parameter, characterized by enum, for vectorized parameter
void compute_rate_and_derivative (const KineticsConditions< StateType, VectorStateType > &conditions, StateType &rate, StateType &drate_dT) const
void compute_rate_and_derivative (const StateType &temp, StateType &rate, StateType &drate_dT) const
void set_index (unsigned int nr)
void print (std::ostream &os=std::cout) const
Formatted print, by default to std::cout.
Public Attributes
_Cf(* this)(T)*(_D+_eta/T+_Ea/(T *T))) template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
_Cf(*) StateType rate)
_Cf(*) StateType StateType &drate_d const)
_Cf VectorStateType
VectorStateType(* this)(T)*(_D+_eta/T.T()+_Ea/(T.temp_cache().T2))) template< typename StateType
Simultaneously evaluate the rate and its derivative at T.
_Cf VectorStateType
VectorStateType(*)
VectorStateType voi rate_and_derivative)(const KineticsConditions< StateType, VectorStateType > &T, StateType &rate, StateType &drate_dT) const
Private Member Functions
void compute_cf ()
Private Attributes
CoeffType _raw_Cf
CoeffType _Cf
CoeffType _eta
CoeffType _raw_Ea
CoeffType _Ea
CoeffType _D
CoeffType _Tref
CoeffType _rscale
Detailed Description
template<typename CoeffType = double>
class Antioch::VantHoffRate< CoeffType >
Van't Hoff rate equation.
The Van't Hoff kinetics model is of the form:
thus
Internally, we use the reduced pre-exponential parameter and the reduced activation energy
Definition at line 62 of file kinetics_type.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::VantHoffRate< CoeffType >::VantHoffRate (const CoeffType Cf = 0., const CoeffType eta = 0., const CoeffType Ea = 0., const CoeffType D = 0., const CoeffType Tref = 1., const CoeffType rscale = Constants::R_universal<CoeffType>())
Definition at line 180 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_rscale, and Antioch::VantHoffRate< CoeffType >::compute_cf().
     : KineticsType<CoeffType>(KineticsModel::VANTHOFF),
       _raw_Cf(Cf),
       _eta(eta),
       _raw_Ea(Ea),
       _D(D),
       _Tref(Tref),
       _rscale(rscale)
   {
     _Ea = _raw_Ea / _rscale;
     this->compute_cf();
     return;
   }
template<typename CoeffType > Antioch::VantHoffRate< CoeffType >::~VantHoffRate ()
Definition at line 196 of file vanthoff_rate.h.
   {
     return;
   }
Member Function Documentation
template<typename CoeffType = double> _Cf* Antioch::VantHoffRate< CoeffType >::ant_exp (_eta *T. temp_cache).lnT-_Ea/T.T()+_D *T.T()
Returns
the rate evaluated at T.
template<typename CoeffType = double> _Cf* Antioch::VantHoffRate< CoeffType >::ant_pow (T , _eta) const
Returns
the rate evaluated at T.
the derivative with respect to temperature evaluated at T.
Referenced by Antioch::VantHoffRate< CoeffType >::compute_cf().
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::Cf () const inline
Definition at line 390 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_Cf.
Referenced by Antioch::VantHoffRate< CoeffType >::get_parameter(), and Antioch::VantHoffRate< CoeffType >::set_Cf().
   { return _Cf; }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::compute_cf () inline private
Definition at line 449 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::ant_pow().
Referenced by Antioch::VantHoffRate< CoeffType >::set_Cf(), Antioch::VantHoffRate< CoeffType >::set_eta(), Antioch::VantHoffRate< CoeffType >::set_Tref(), and Antioch::VantHoffRate< CoeffType >::VantHoffRate().
   {
     _Cf = _raw_Cf * ant_pow(KineticsModel::Tref<CoeffType>()/_Tref,_eta);
     return;
   }
void Antioch::KineticsType< CoeffType, VectorCoeffType >::compute_rate_and_derivative (const KineticsConditions< StateType, VectorStateType > & conditions, StateType & rate, StateType & drate_dT) const inherited
void Antioch::KineticsType< CoeffType, VectorCoeffType >::compute_rate_and_derivative (const StateType & temp, StateType & rate, StateType & drate_dT) const inherited
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::D () const inline
Definition at line 410 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_D.
Referenced by Antioch::VantHoffRate< CoeffType >::get_parameter(), and Antioch::VantHoffRate< CoeffType >::set_D().
   { return _D; }
StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::derivative (const StateType & conditions) const inherited
template<typename CoeffType = double> _Cf VectorStateType VectorStateType Antioch::VantHoffRate< CoeffType >::derivative (const KineticsConditions< StateType, VectorStateType > & T) const
Referenced by test_values(), and vectester().
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::Ea () const inline
Definition at line 400 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_raw_Ea.
Referenced by Antioch::VantHoffRate< CoeffType >::get_parameter(), Antioch::VantHoffRate< CoeffType >::reset_Ea(), and Antioch::VantHoffRate< CoeffType >::set_Ea().
   { return _raw_Ea; }
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::Ea_K () const inline
Definition at line 405 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_Ea.
   { return _Ea; }
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::eta () const inline
Definition at line 395 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_eta.
Referenced by Antioch::VantHoffRate< CoeffType >::get_parameter(), and Antioch::VantHoffRate< CoeffType >::set_eta().
   { return _eta; }
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::get_parameter (KineticsModel::Parameters parameter) const inline
get one parameter, characterized by enum
Definition at line 344 of file vanthoff_rate.h.
References Antioch::KineticsModel::A, antioch_error, Antioch::KineticsModel::B, Antioch::VantHoffRate< CoeffType >::Cf(), Antioch::KineticsModel::D, Antioch::VantHoffRate< CoeffType >::D(), Antioch::KineticsModel::E, Antioch::VantHoffRate< CoeffType >::Ea(), Antioch::VantHoffRate< CoeffType >::eta(), Antioch::KineticsModel::R_SCALE, Antioch::VantHoffRate< CoeffType >::rscale(), Antioch::KineticsModel::T_REF, and Antioch::VantHoffRate< CoeffType >::Tref().
   {
     switch(parameter)
     {
       case KineticsModel::Parameters::R_SCALE:
       {
          return this->rscale();
       }
        break;
       case KineticsModel::Parameters::T_REF:
       {
          return this->Tref();
       }
        break;
       case KineticsModel::Parameters::A:
       {
          return this->Cf();
       }
         break;
       case KineticsModel::Parameters::B:
       {
          return this->eta();
       }
         break;
       case KineticsModel::Parameters::E:
       {
          return this->Ea();
       }
         break;
       case KineticsModel::Parameters::D:
       {
         return this->D();
       }
         break;
       default:
       {
         antioch_error();
       }
        break;
     }
     return 0;
   }
CoeffType Antioch::KineticsType< CoeffType, VectorCoeffType >::get_parameter (KineticsModel::Parameters parameter, int l) const inherited
get one parameter, characterized by enum, for vectorized parameter
template<typename CoeffType > const std::string Antioch::VantHoffRate< CoeffType >::numeric () const virtual
print equation
Implements Antioch::KineticsType< CoeffType >.
Definition at line 202 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_eta, and Antioch::VantHoffRate< CoeffType >::_raw_Cf.
   {
     std::stringstream os;
     os << _raw_Cf;
     if (_eta != 0.) os << "*(T/" << _Tref << ")^" << _eta;
     os << "*exp(-" << _raw_Ea << "/(R*T) + " << _D << "*T)";
     return os.str();
   }
StateType Antioch::KineticsType< CoeffType, VectorCoeffType >::operator() (const StateType & temp) const inherited
template<typename CoeffType = double> _Cf VectorStateType Antioch::VantHoffRate< CoeffType >::operator() (const KineticsConditions< StateType, VectorStateType > & T) const
Returns
the derivative with respect to temperature evaluated at T.
void Antioch::KineticsType< CoeffType, VectorCoeffType >::print (std::ostream & os = std::cout) const inherited
Formatted print, by default to std::cout.
template<typename CoeffType = double> template<typename StateType > Antioch::VantHoffRate< CoeffType >::rate (const StateType & T) const
Returns
the rate evaluated at T.
template<typename CoeffType = double> template<typename StateType , typename VectorStateType > Antioch::VantHoffRate< CoeffType >::rate (const KineticsConditions< StateType, VectorStateType > & T) const
Returns
the rate evaluated at T.
template<typename CoeffType > template<typename VectorCoeffType > void Antioch::VantHoffRate< CoeffType >::reset_coefs (const VectorCoeffType & coefficients) inline
reset the coeffs
Two ways of modifying your rate:
you change totally the rate, thus you require exactly six parameters, the order assumed is Cf, eta, Ea, D, Tref, rscale
you just change the value, thus Tref and rscale are not modified. You require exactly four parameters, the order assumed is Cf, eta, Ea, D
Definition at line 280 of file vanthoff_rate.h.
References antioch_assert_greater, antioch_assert_less, antioch_assert_not_equal_to, Antioch::VantHoffRate< CoeffType >::set_Cf(), Antioch::VantHoffRate< CoeffType >::set_D(), Antioch::VantHoffRate< CoeffType >::set_Ea(), Antioch::VantHoffRate< CoeffType >::set_eta(), Antioch::VantHoffRate< CoeffType >::set_rscale(), and Antioch::VantHoffRate< CoeffType >::set_Tref().
Referenced by tester().
   {
        // 4 or 6
      antioch_assert_greater(coefficients.size(),3);
      antioch_assert_less(coefficients.size(),7);
      antioch_assert_not_equal_to(coefficients.size(),5);
      if(coefficients.size() == 6)
      {
         this->set_rscale(coefficients[5]);
         this->set_Tref(coefficients[4]);
      }
      this->set_Cf(coefficients[0]);
      this->set_eta(coefficients[1]);
      this->set_Ea(coefficients[2]);
      this->set_D(coefficients[3]);
   }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::reset_Ea (const CoeffType Ea) inline
set _Ea, unit is K, _raw_Ea is computed
Definition at line 253 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_rscale, and Antioch::VantHoffRate< CoeffType >::Ea().
Referenced by Antioch::VantHoffRate< CoeffType >::set_parameter().
   {
     _Ea = Ea;
     _raw_Ea = _Ea * _rscale;
     return;
   }
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::rscale () const inline
Definition at line 420 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_rscale.
Referenced by Antioch::VantHoffRate< CoeffType >::get_parameter(), and Antioch::VantHoffRate< CoeffType >::set_rscale().
   { return _rscale; }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_Cf (const CoeffType Cf) inline
Definition at line 215 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::Cf(), and Antioch::VantHoffRate< CoeffType >::compute_cf().
Referenced by Antioch::VantHoffRate< CoeffType >::reset_coefs(), Antioch::VantHoffRate< CoeffType >::set_parameter(), and tester().
   {
     _raw_Cf = Cf;
     this->compute_cf();
     return;
   }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_D (const CoeffType D) inline
Definition at line 271 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::D().
Referenced by Antioch::VantHoffRate< CoeffType >::reset_coefs(), Antioch::VantHoffRate< CoeffType >::set_parameter(), and tester().
   {
     _D = D;
     return;
   }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_Ea (const CoeffType Ea) inline
set _raw_Ea, unit is known (cal.mol-1, J.mol-1, whatever), _Ea is computed
Definition at line 244 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_rscale, and Antioch::VantHoffRate< CoeffType >::Ea().
Referenced by Antioch::VantHoffRate< CoeffType >::reset_coefs(), and tester().
   {
     _raw_Ea = Ea;
     _Ea = _raw_Ea / _rscale;
     return;
   }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_eta (const CoeffType eta) inline
Definition at line 235 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::compute_cf(), and Antioch::VantHoffRate< CoeffType >::eta().
Referenced by Antioch::VantHoffRate< CoeffType >::reset_coefs(), Antioch::VantHoffRate< CoeffType >::set_parameter(), and tester().
   {
     _eta = eta;
     this->compute_cf();
     return;
   }
void Antioch::KineticsType< CoeffType, VectorCoeffType >::set_index (unsigned int nr) inherited
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_parameter (KineticsModel::Parameters parameter, CoeffType new_value) inline
set one parameter, characterized by enum
Definition at line 300 of file vanthoff_rate.h.
References Antioch::KineticsModel::A, antioch_error, Antioch::KineticsModel::B, Antioch::KineticsModel::D, Antioch::KineticsModel::E, Antioch::KineticsModel::R_SCALE, Antioch::VantHoffRate< CoeffType >::reset_Ea(), Antioch::VantHoffRate< CoeffType >::set_Cf(), Antioch::VantHoffRate< CoeffType >::set_D(), Antioch::VantHoffRate< CoeffType >::set_eta(), Antioch::VantHoffRate< CoeffType >::set_rscale(), Antioch::VantHoffRate< CoeffType >::set_Tref(), and Antioch::KineticsModel::T_REF.
   {
     switch(parameter)
     {
       case KineticsModel::Parameters::R_SCALE:
       {
         this->set_rscale(new_value);
       }
        break;
       case KineticsModel::Parameters::T_REF:
       {
         this->set_Tref(new_value);
       }
        break;
       case KineticsModel::Parameters::A:
       {
         this->set_Cf(new_value);
       }
         break;
       case KineticsModel::Parameters::B:
       {
         this->set_eta(new_value);
       }
         break;
       case KineticsModel::Parameters::E:
       {
         this->reset_Ea(new_value);
       }
         break;
       case KineticsModel::Parameters::D:
       {
         this->set_D(new_value);
       }
         break;
       default:
       {
         antioch_error();
       }
        break;
     }
   }
template<typename CoeffType = double> template<typename VectorCoeffType > void Antioch::VantHoffRate< CoeffType >::set_parameter (KineticsModel::Parameters parameter, VectorCoeffType new_value) inline
for compatibility purpose with photochemistry (particle flux reactions)
Definition at line 101 of file vanthoff_rate.h.
References antioch_error.
 {antioch_error();}
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_rscale (const CoeffType rscale) inline
Definition at line 262 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_rscale, and Antioch::VantHoffRate< CoeffType >::rscale().
Referenced by Antioch::VantHoffRate< CoeffType >::reset_coefs(), Antioch::VantHoffRate< CoeffType >::set_parameter(), and tester().
   {
     _rscale = rscale;
     _Ea = _raw_Ea / _rscale;
     return;
   }
template<typename CoeffType > void Antioch::VantHoffRate< CoeffType >::set_Tref (const CoeffType Tref) inline
Definition at line 225 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::compute_cf(), and Antioch::VantHoffRate< CoeffType >::Tref().
Referenced by Antioch::VantHoffRate< CoeffType >::reset_coefs(), Antioch::VantHoffRate< CoeffType >::set_parameter(), and tester().
   {
     _Tref = Tref;
     this->compute_cf();
     return;
   }
template<typename CoeffType > CoeffType Antioch::VantHoffRate< CoeffType >::Tref () const inline
Definition at line 415 of file vanthoff_rate.h.
References Antioch::VantHoffRate< CoeffType >::_Tref.
Referenced by Antioch::VantHoffRate< CoeffType >::get_parameter(), and Antioch::VantHoffRate< CoeffType >::set_Tref().
   { return _Tref; }
KineticsModel::KineticsModel Antioch::KineticsType< CoeffType, VectorCoeffType >::type () const inherited
Member Data Documentation
template<typename CoeffType = double> CoeffType Antioch::VantHoffRate< CoeffType >::_Cf private
Definition at line 65 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::Cf().
template<typename CoeffType = double> CoeffType Antioch::VantHoffRate< CoeffType >::_D private
Definition at line 69 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::D().
template<typename CoeffType = double> CoeffType Antioch::VantHoffRate< CoeffType >::_Ea private
Definition at line 68 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::Ea_K().
template<typename CoeffType = double> CoeffType Antioch::VantHoffRate< CoeffType >::_eta private
Definition at line 66 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::eta(), and Antioch::VantHoffRate< CoeffType >::numeric().
template<typename CoeffType = double> CoeffType Antioch::VantHoffRate< CoeffType >::_raw_Cf private
Definition at line 64 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::numeric().
template<typename CoeffType = double> CoeffType Antioch::VantHoffRate< CoeffType >::_raw_Ea private
Definition at line 67 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::Ea().
template<typename CoeffType = double> CoeffType Antioch::VantHoffRate< CoeffType >::_rscale private
Definition at line 71 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::reset_Ea(), Antioch::VantHoffRate< CoeffType >::rscale(), Antioch::VantHoffRate< CoeffType >::set_Ea(), Antioch::VantHoffRate< CoeffType >::set_rscale(), and Antioch::VantHoffRate< CoeffType >::VantHoffRate().
template<typename CoeffType = double> CoeffType Antioch::VantHoffRate< CoeffType >::_Tref private
Definition at line 70 of file vanthoff_rate.h.
Referenced by Antioch::VantHoffRate< CoeffType >::Tref().
template<typename CoeffType = double> _Cf(*) StateType StateType& drate_d Antioch::VantHoffRate< CoeffType >::const)
Definition at line 144 of file vanthoff_rate.h.
template<typename CoeffType = double> _Cf(*) StateType Antioch::VantHoffRate< CoeffType >::rate)
Definition at line 144 of file vanthoff_rate.h.
template<typename CoeffType = double> void Antioch::VantHoffRate< CoeffType >::rate_and_derivative inline
Definition at line 168 of file vanthoff_rate.h.
Referenced by test_values(), and vectester().
template<typename CoeffType = double> _Cf(* Antioch::VantHoffRate< CoeffType >::this)(T)*(_D+_eta/T+_Ea/(T *T)))template< typename StateType > void rate_and_derivative(const StateType &T
Simultaneously evaluate the rate and its derivative at T.
Definition at line 140 of file vanthoff_rate.h.
template<typename CoeffType = double> _Cf VectorStateType VectorStateType(* Antioch::VantHoffRate< CoeffType >::this)(T)*(_D+_eta/T.T()+_Ea/(T.temp_cache().T2)))template< typename StateType
Simultaneously evaluate the rate and its derivative at T.
Definition at line 164 of file vanthoff_rate.h.
The documentation for this class was generated from the following files:
src/kinetics/include/antioch/kinetics_type.h
src/kinetics/include/antioch/vanthoff_rate.h