antioch-0.4.0: Antioch::NASACurveFitBase< CoeffType > Class Template Reference
Antioch::NASACurveFitBase< CoeffType > Class Template Reference
#include <nasa_curve_fit_base.h>
Public Member Functions
NASACurveFitBase (const std::vector< CoeffType > &coeffs, const std::vector< CoeffType > &temp)
~NASACurveFitBase ()
unsigned int n_intervals () const
The number of intervals for this NASA9 curve fit.
template<typename StateType >
Antioch::rebind< StateType,
unsigned int >::type interval (const StateType &T) const
The interval the input temperature lies in.
const CoeffType * coefficients (const unsigned int interval) const
The ordering/packing of the coefficients will depend on the subclass.
template<typename StateType >
Antioch::rebind< StateType,
unsigned int >::type interval (const StateType &T) const
Protected Member Functions
NASACurveFitBase ()
void check_coeff_size () const
void check_temp_coeff_size_consistency () const
Protected Attributes
unsigned int _n_coeffs
The number of coefficients in each interval.
std::vector< CoeffType > _coefficients
The coefficient data.
std::vector< CoeffType > _temp
The temperatures.
Detailed Description
template<typename CoeffType = double>
class Antioch::NASACurveFitBase< CoeffType >
Definition at line 42 of file nasa_curve_fit_base.h.
Constructor & Destructor Documentation
template<typename CoeffType > Antioch::NASACurveFitBase< CoeffType >::NASACurveFitBase (const std::vector< CoeffType > & coeffs, const std::vector< CoeffType > & temp) inline
Definition at line 97 of file nasa_curve_fit_base.h.
     : _n_coeffs(0),
       _coefficients(coeffs),
       _temp(temp)
   {}
template<typename CoeffType = double> Antioch::NASACurveFitBase< CoeffType >::~NASACurveFitBase () inline
Definition at line 48 of file nasa_curve_fit_base.h.
 {};
template<typename CoeffType = double> Antioch::NASACurveFitBase< CoeffType >::NASACurveFitBase () inline protected
Definition at line 70 of file nasa_curve_fit_base.h.
 {};
Member Function Documentation
template<typename CoeffType > void Antioch::NASACurveFitBase< CoeffType >::check_coeff_size () const inline protected
Definition at line 143 of file nasa_curve_fit_base.h.
References antioch_error_msg.
Referenced by Antioch::CEACurveFit< CoeffType >::CEACurveFit(), Antioch::NASA7CurveFit< CoeffType >::NASA7CurveFit(), and Antioch::NASA9CurveFit< CoeffType >::NASA9CurveFit().
   {
     if( this->_coefficients.size()%this->_n_coeffs != 0 )
       {
         std::stringstream ncs;
         ncs << this->_n_coeffs;
         std::stringstream css;
         css << this->_coefficients.size()%this->_n_coeffs;
         std::string msg = "ERROR: coeffs size must be a multiple of "+ncs.str()+"\n";
         msg += "       Found "+css.str()+"\n";
         antioch_error_msg(msg);
       }
   }
template<typename CoeffType > void Antioch::NASACurveFitBase< CoeffType >::check_temp_coeff_size_consistency () const inline protected
Definition at line 161 of file nasa_curve_fit_base.h.
References antioch_error_msg.
Referenced by Antioch::CEACurveFit< CoeffType >::CEACurveFit(), Antioch::NASA7CurveFit< CoeffType >::NASA7CurveFit(), and Antioch::NASA9CurveFit< CoeffType >::NASA9CurveFit().
   {
     if( this->_temp.size() != this->_coefficients.size()/this->_n_coeffs + 1 )
       {
         std::stringstream tss;
         tss << this->_temp.size();
         std::stringstream css;
         css << this->_coefficients.size();
         std::stringstream cssd;
         cssd << this->_n_coeffs*(this->_temp.size()-1);
         std::string msg = "ERROR: Inconsistency in temp and coeff size.\n";
         msg += "       Found temp size of "+tss.str()+"\n";
         msg += "       Found coeff size of "+css.str()+"\n";
         msg += "       Expected coeff size of "+cssd.str()+"\n";
         antioch_error_msg(msg);
       }
   }
template<typename CoeffType > const CoeffType * Antioch::NASACurveFitBase< CoeffType >::coefficients (const unsigned int interval) const inline
The ordering/packing of the coefficients will depend on the subclass.
Returns
a pointer to the coefficients in the interval specified.
Definition at line 133 of file nasa_curve_fit_base.h.
References antioch_assert_less, and antioch_assert_less_equal.
Referenced by AntiochTesting::NASA7XMLParsingTest< long double >::check_curve_fits(), and AntiochTesting::NASA9XMLParsingTest< long double >::test_supplied_species().
   {
     antioch_assert_less( interval, this->n_intervals() );
     antioch_assert_less_equal( _n_coeffs*(interval+1), _coefficients.size() );
     return &_coefficients[_n_coeffs*interval];
   }
template<typename CoeffType = double> template<typename StateType > Antioch::rebind<StateType, unsigned int>::type Antioch::NASACurveFitBase< CoeffType >::interval (const StateType & T) const
The interval the input temperature lies in.
Returns
which curve fit interval the input temperature lies in.
template<typename CoeffType = double> template<typename StateType > Antioch::rebind<StateType, unsigned int>::type Antioch::NASACurveFitBase< CoeffType >::interval (const StateType & T) const inline
Definition at line 113 of file nasa_curve_fit_base.h.
References Antioch::constant_clone(), Antioch::if_else(), and Antioch::zero_clone().
   {
     typedef typename
       Antioch::rebind<StateType, unsigned int>::type UIntType;
     UIntType interval;
     Antioch::zero_clone(interval, T);
     for(unsigned int i = 1; i < _temp.size(); ++i)
     {
         interval = Antioch::if_else
           (T > _temp[i-1] && T < _temp[i],
            Antioch::constant_clone(interval, i-1),
            interval );
     }
     return interval;
   }
template<typename CoeffType > unsigned int Antioch::NASACurveFitBase< CoeffType >::n_intervals () const inline
The number of intervals for this NASA9 curve fit.
Definition at line 106 of file nasa_curve_fit_base.h.
Referenced by AntiochTesting::NASA7XMLParsingTest< long double >::check_curve_fits(), and AntiochTesting::NASA9XMLParsingTest< long double >::test_supplied_species().
   { return _coefficients.size() / _n_coeffs; }
Member Data Documentation
template<typename CoeffType = double> std::vector<CoeffType> Antioch::NASACurveFitBase< CoeffType >::_coefficients protected
The coefficient data.
The coeffcients are packed in linear ordering. That is, a0-a9 for the first interval, a0-a9 for the second interval, and so on.
Definition at line 85 of file nasa_curve_fit_base.h.
Referenced by Antioch::CEACurveFit< CoeffType >::CEACurveFit().
template<typename CoeffType = double> unsigned int Antioch::NASACurveFitBase< CoeffType >::_n_coeffs protected
The number of coefficients in each interval.
Definition at line 77 of file nasa_curve_fit_base.h.
Referenced by Antioch::CEACurveFit< CoeffType >::CEACurveFit(), Antioch::NASA7CurveFit< CoeffType >::NASA7CurveFit(), and Antioch::NASA9CurveFit< CoeffType >::NASA9CurveFit().
template<typename CoeffType = double> std::vector<CoeffType> Antioch::NASACurveFitBase< CoeffType >::_temp protected
The temperatures.
The temperature defining the intervals
Definition at line 91 of file nasa_curve_fit_base.h.
Referenced by Antioch::CEACurveFit< CoeffType >::CEACurveFit(), and Antioch::NASA7CurveFit< CoeffType >::NASA7CurveFit().
The documentation for this class was generated from the following file:
src/thermo/include/antioch/nasa_curve_fit_base.h