antioch-0.4.0: AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar > Class Template Reference
AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar > Class Template Reference abstract
#include <reaction_rate_test_base.h>
Public Member Functions
void test_rate (const ReactionRate &reaction_rate, Scalar tol)
void test_deriv (const ReactionRate &reaction_rate, Scalar tol)
void test_rate_and_deriv (const ReactionRate &reaction_rate, Scalar tol)
Protected Member Functions
virtual Scalar exact_rate (Scalar T)=0
virtual Scalar exact_deriv (Scalar T)=0
Detailed Description
template<typename ReactionRate, typename Scalar>
class AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar >
Definition at line 40 of file reaction_rate_test_base.h.
Member Function Documentation
template<typename ReactionRate, typename Scalar> virtual Scalar AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar >::exact_deriv (Scalar T) protected pure virtual
Implemented in AntiochTesting::ArrheniusRateTest< Scalar >, AntiochTesting::ArrheniusRateTest< double >, AntiochTesting::ArrheniusRateTest< float >, and AntiochTesting::ArrheniusRateTest< long double >.
Referenced by AntiochTesting::ReactionRateTestBase< Antioch::ArrheniusRate< float >, float >::test_deriv(), and AntiochTesting::ReactionRateTestBase< Antioch::ArrheniusRate< float >, float >::test_rate_and_deriv().
template<typename ReactionRate, typename Scalar> virtual Scalar AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar >::exact_rate (Scalar T) protected pure virtual
Implemented in AntiochTesting::ArrheniusRateTest< Scalar >, AntiochTesting::ArrheniusRateTest< double >, AntiochTesting::ArrheniusRateTest< float >, and AntiochTesting::ArrheniusRateTest< long double >.
Referenced by AntiochTesting::ReactionRateTestBase< Antioch::ArrheniusRate< float >, float >::test_rate(), and AntiochTesting::ReactionRateTestBase< Antioch::ArrheniusRate< float >, float >::test_rate_and_deriv().
template<typename ReactionRate, typename Scalar> void AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar >::test_deriv (const ReactionRate & reaction_rate, Scalar tol) inline
Definition at line 70 of file reaction_rate_test_base.h.
     {
       for(Scalar T = 300.1; T <= 2500.1; T += 10.)
         {
           {
             Scalar deriv = reaction_rate.derivative(T);
             Scalar exact_deriv = this->exact_deriv(T);
             CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv,
                                           exact_deriv,
                                           tol );
           }
           {
             Antioch::KineticsConditions<Scalar> cond(T);
             Scalar deriv = reaction_rate.derivative(cond);
             Scalar exact_deriv = this->exact_deriv(T);
             CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv,
                                           exact_deriv,
                                           tol );
           }
         }
     }
template<typename ReactionRate, typename Scalar> void AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar >::test_rate (const ReactionRate & reaction_rate, Scalar tol) inline
Definition at line 43 of file reaction_rate_test_base.h.
     {
       for(Scalar T = 300.1; T <= 2500.1; T += 10.)
         {
           {
             Scalar rate = reaction_rate(T);
             Scalar exact_rate = this->exact_rate(T);
             CPPUNIT_ASSERT_DOUBLES_EQUAL( rate,
                                           exact_rate,
                                           tol );
           }
           {
             Antioch::KineticsConditions<Scalar> cond(T);
             Scalar rate = reaction_rate(cond);
             Scalar exact_rate = this->exact_rate(T);
             CPPUNIT_ASSERT_DOUBLES_EQUAL( rate,
                                           exact_rate,
                                           tol );
           }
         }
     }
template<typename ReactionRate, typename Scalar> void AntiochTesting::ReactionRateTestBase< ReactionRate, Scalar >::test_rate_and_deriv (const ReactionRate & reaction_rate, Scalar tol) inline
Definition at line 96 of file reaction_rate_test_base.h.
     {
       for(Scalar T = 300.1; T <= 2500.1; T += 10.)
         {
           {
             Scalar rate;
             Scalar deriv;
             Antioch::KineticsConditions<Scalar> cond(T);
             reaction_rate.rate_and_derivative(cond,rate,deriv);
             Scalar exact_rate = this->exact_rate(T);
             Scalar exact_deriv = this->exact_deriv(T);
             CPPUNIT_ASSERT_DOUBLES_EQUAL( rate,
                                           exact_rate,
                                           tol );
             CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv,
                                           exact_deriv,
                                           tol );
           }
         }
     }
The documentation for this class was generated from the following file:
test/standard_unit/reaction_rate_test_base.h