antioch-0.4.0: AntiochTesting::ReactionRateVectorTestBase< ReactionRate, PairScalars > Class Template Reference
AntiochTesting::ReactionRateVectorTestBase< ReactionRate, PairScalars > Class Template Reference abstract
#include <reaction_rate_vector_test_base.h>
Public Member Functions
void test_rate (const ReactionRate &reaction_rate, const PairScalars &T, typename Antioch::value_type< PairScalars >::typetol)
void test_deriv (const ReactionRate &reaction_rate, const PairScalars &T, typename Antioch::value_type< PairScalars >::typetol)
void test_rate_and_deriv (const ReactionRate &reaction_rate, const PairScalars &T, typename Antioch::value_type< PairScalars >::typetol)
Protected Member Functions
PairScalars setup_T (const PairScalars &example)
virtual PairScalars exact_rate (PairScalars T)=0
virtual PairScalars exact_deriv (PairScalars T)=0
Protected Attributes
PairScalars * _example
Detailed Description
template<typename ReactionRate, typename PairScalars>
class AntiochTesting::ReactionRateVectorTestBase< ReactionRate, PairScalars >
Definition at line 40 of file reaction_rate_vector_test_base.h.
Member Function Documentation
template<typename ReactionRate, typename PairScalars> virtual PairScalars AntiochTesting::ReactionRateVectorTestBase< ReactionRate, PairScalars >::exact_deriv (PairScalars T) protected pure virtual
Implemented in AntiochTesting::ArrheniusRateVectorTestBase< PairScalars >, AntiochTesting::ArrheniusRateVectorTestBase< MetaPhysicL::NumberArray< 2 *ANTIOCH_N_TUPLES, float > >, AntiochTesting::ArrheniusRateVectorTestBase< std::valarray< long double > >, AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >, AntiochTesting::ArrheniusRateVectorTestBase< std::valarray< float > >, AntiochTesting::ArrheniusRateVectorTestBase< std::valarray< Scalar > >, AntiochTesting::ArrheniusRateVectorTestBase< std::valarray< double > >, AntiochTesting::ArrheniusRateVectorTestBase< Eigen::Array< long double, 2 *ANTIOCH_N_TUPLES, 1 > >, AntiochTesting::ArrheniusRateVectorTestBase< Eigen::Array< double, 2 *ANTIOCH_N_TUPLES, 1 > >, AntiochTesting::ArrheniusRateVectorTestBase< Eigen::Array< float, 2 *ANTIOCH_N_TUPLES, 1 > >, AntiochTesting::ArrheniusRateVectorTestBase< Eigen::Array< Scalar, 2 *ANTIOCH_N_TUPLES, 1 > >, and AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< float > >.
Referenced by AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< Eigen::Array< float, 2 *ANTIOCH_N_TUPLES, 1 > >::type >, Eigen::Array< float, 2 *ANTIOCH_N_TUPLES, 1 > >::test_deriv(), and AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< Eigen::Array< float, 2 *ANTIOCH_N_TUPLES, 1 > >::type >, Eigen::Array< float, 2 *ANTIOCH_N_TUPLES, 1 > >::test_rate_and_deriv().
template<typename ReactionRate, typename PairScalars> virtual PairScalars AntiochTesting::ReactionRateVectorTestBase< ReactionRate, PairScalars >::exact_rate (PairScalars T) protected pure virtual
Implemented in AntiochTesting::ArrheniusRateVectorTestBase< PairScalars >, AntiochTesting::ArrheniusRateVectorTestBase< MetaPhysicL::NumberArray< 2 *ANTIOCH_N_TUPLES, float > >, AntiochTesting::ArrheniusRateVectorTestBase< std::valarray< long double > >, AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< double > >, AntiochTesting::ArrheniusRateVectorTestBase< std::valarray< float > >, AntiochTesting::ArrheniusRateVectorTestBase< std::valarray< Scalar > >, AntiochTesting::ArrheniusRateVectorTestBase< std::valarray< double > >, AntiochTesting::ArrheniusRateVectorTestBase< Eigen::Array< long double, 2 *ANTIOCH_N_TUPLES, 1 > >, AntiochTesting::ArrheniusRateVectorTestBase< Eigen::Array< double, 2 *ANTIOCH_N_TUPLES, 1 > >, AntiochTesting::ArrheniusRateVectorTestBase< Eigen::Array< float, 2 *ANTIOCH_N_TUPLES, 1 > >, AntiochTesting::ArrheniusRateVectorTestBase< Eigen::Array< Scalar, 2 *ANTIOCH_N_TUPLES, 1 > >, and AntiochTesting::ArrheniusRateVectorTestBase< vex::vector< float > >.
Referenced by AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< Eigen::Array< float, 2 *ANTIOCH_N_TUPLES, 1 > >::type >, Eigen::Array< float, 2 *ANTIOCH_N_TUPLES, 1 > >::test_rate(), and AntiochTesting::ReactionRateVectorTestBase< Antioch::ArrheniusRate< Antioch::value_type< Eigen::Array< float, 2 *ANTIOCH_N_TUPLES, 1 > >::type >, Eigen::Array< float, 2 *ANTIOCH_N_TUPLES, 1 > >::test_rate_and_deriv().
template<typename ReactionRate, typename PairScalars> PairScalars AntiochTesting::ReactionRateVectorTestBase< ReactionRate, PairScalars >::setup_T (const PairScalars & example) inline protected
Definition at line 123 of file reaction_rate_vector_test_base.h.
     {
       // Construct from example to avoid resizing issues
       PairScalars T = example;
       for (unsigned int tuple=0; tuple != ANTIOCH_N_TUPLES; ++tuple)
         {
           T[2*tuple]   = 1500.1;
           T[2*tuple+1] = 1600.1;
         }
       return T;
     }
template<typename ReactionRate, typename PairScalars> void AntiochTesting::ReactionRateVectorTestBase< ReactionRate, PairScalars >::test_deriv (const ReactionRate & reaction_rate, const PairScalars & T, typename Antioch::value_type< PairScalars >::type tol) inline
Definition at line 64 of file reaction_rate_vector_test_base.h.
     {
       const PairScalars deriv = reaction_rate.derivative(T);
       const PairScalars exact_deriv = this->exact_deriv(T);
       for (unsigned int tuple=0; tuple != ANTIOCH_N_TUPLES; ++tuple)
         {
           CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv[2*tuple],
                                         exact_deriv[0],
                                         tol );
           CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv[2*tuple+1],
                                         exact_deriv[1],
                                         tol );
         }
     }
template<typename ReactionRate, typename PairScalars> void AntiochTesting::ReactionRateVectorTestBase< ReactionRate, PairScalars >::test_rate (const ReactionRate & reaction_rate, const PairScalars & T, typename Antioch::value_type< PairScalars >::type tol) inline
Definition at line 44 of file reaction_rate_vector_test_base.h.
     {
       const PairScalars rate = reaction_rate(T);
       const PairScalars exact_rate = this->exact_rate(T);
       for (unsigned int tuple=0; tuple != ANTIOCH_N_TUPLES; ++tuple)
         {
           CPPUNIT_ASSERT_DOUBLES_EQUAL( rate[2*tuple],
                                         exact_rate[0],
                                         tol );
           CPPUNIT_ASSERT_DOUBLES_EQUAL( rate[2*tuple+1],
                                         exact_rate[1],
                                         tol );
         }
     }
template<typename ReactionRate, typename PairScalars> void AntiochTesting::ReactionRateVectorTestBase< ReactionRate, PairScalars >::test_rate_and_deriv (const ReactionRate & reaction_rate, const PairScalars & T, typename Antioch::value_type< PairScalars >::type tol) inline
Definition at line 84 of file reaction_rate_vector_test_base.h.
     {
       // Init using T as the "example"
       PairScalars rate = T;
       PairScalars deriv = T;
       reaction_rate.rate_and_derivative(T,rate,deriv);
       const PairScalars exact_rate = this->exact_rate(T);
       const PairScalars exact_deriv = this->exact_deriv(T);
       for (unsigned int tuple=0; tuple != ANTIOCH_N_TUPLES; ++tuple)
         {
           CPPUNIT_ASSERT_DOUBLES_EQUAL( rate[2*tuple],
                                         exact_rate[0],
                                         tol );
           CPPUNIT_ASSERT_DOUBLES_EQUAL( rate[2*tuple+1],
                                         exact_rate[1],
                                         tol );
           CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv[2*tuple],
                                         exact_deriv[0],
                                         tol );
           CPPUNIT_ASSERT_DOUBLES_EQUAL( deriv[2*tuple+1],
                                         exact_deriv[1],
                                         tol );
         }
     }
Member Data Documentation
template<typename ReactionRate, typename PairScalars> PairScalars* AntiochTesting::ReactionRateVectorTestBase< ReactionRate, PairScalars >::_example protected
Definition at line 121 of file reaction_rate_vector_test_base.h.
The documentation for this class was generated from the following file:
test/standard_unit/reaction_rate_vector_test_base.h