antioch-0.4.0: Antioch::NASAEvaluator< CoeffType, NASAFit > Singleton Reference
Antioch::NASAEvaluator< CoeffType, NASAFit > Singleton Reference
#include <ascii_parser.h>
Public Member Functions
NASAEvaluator (const NASAThermoMixture< CoeffType, NASAFit > &cea_mixture)
~NASAEvaluator ()
const NASAThermoMixture
< CoeffType, NASAFit > & cea_mixture () const
template<typename StateType >
StateType cp (const TempCache< StateType > &cache, unsigned int species) const
We currently need different specializations for scalar vs vector inputs here.
template<typename StateType , typename VectorStateType >
enable_if_c< has_size
< VectorStateType >::value,
StateType >::type cp (const TempCache< StateType > &cache, const VectorStateType &mass_fractions) const
template<typename StateType >
cv (const TempCache< StateType > &cache, unsigned int species) const ANTIOCH_AUTOFUNC(StateType
this cp (cache, species)-this-> chem_mixture().R(species)) template< typename StateType, typename VectorStateType >typename enable_if_c< has_size< VectorStateType >::value, StateType >::typecv(const TempCache< StateType > &cache, const VectorStateType &mass_fractions) const
template<typename StateType >
h (const TempCache< StateType > &cache, unsigned int species) const ANTIOCH_AUTOFUNC(StateType
this chem_mixture ().R(species)*cache.T *this-> h_over_RT(cache, species)) template< typename StateType, typename VectorStateType >typename enable_if_c< has_size< VectorStateType >::value, void >::typeh(const TempCache< StateType > &cache, VectorStateType &h) const
template<typename StateType >
StateType h_RT_minus_s_R (const TempCache< StateType > &cache, unsigned int species) const
We currently need different specializations for scalar vs vector inputs here.
template<typename StateType , typename VectorStateType >
enable_if_c< has_size
< VectorStateType >::value,
void >::type h_RT_minus_s_R (const TempCache< StateType > &cache, VectorStateType &h_RT_minus_s_R) const
template<typename StateType >
StateType dh_RT_minus_s_R_dT (const TempCache< StateType > &cache, unsigned int species) const
template<typename StateType , typename VectorStateType >
enable_if_c< has_size
< VectorStateType >::value,
void >::type dh_RT_minus_s_R_dT (const TempCache< StateType > &cache, VectorStateType &h_RT_minus_s_R) const
template<typename StateType >
StateType cp_over_R (const TempCache< StateType > &cache, unsigned int species) const
Cp over R, directly from the curve fit.
template<typename StateType >
StateType cv_over_R (const TempCache< StateType > &cache, unsigned int species) const
Cv over R, from ideal gas,.
template<typename StateType >
StateType h_over_RT (const TempCache< StateType > &cache, unsigned int species) const
h over RT, directly from the curve fit
template<typename StateType >
StateType s_over_R (const TempCache< StateType > &cache, unsigned int species) const
s over R, directly from the curve fit
template<typename StateType , typename VectorStateType >
enable_if_c< has_size
< VectorStateType >::value,
StateType >::type cp (const TempCache< StateType > &cache, const VectorStateType &mass_fractions) const
template<typename StateType , typename VectorStateType >
enable_if_c< has_size
< VectorStateType >::value,
void >::type h_RT_minus_s_R (const TempCache< StateType > &cache, VectorStateType &h_RT_minus_s_R) const
template<typename StateType , typename VectorStateType >
enable_if_c< has_size
< VectorStateType >::value,
void >::type dh_RT_minus_s_R_dT (const TempCache< StateType > &cache, VectorStateType &dh_RT_minus_s_R_dT) const
Protected Member Functions
unsigned int n_species () const
Convenience function.
const ChemicalMixture
< CoeffType > & chem_mixture () const
Convenience function.
Protected Attributes
const NASAThermoMixture
< CoeffType, NASAFit > & _nasa_mixture
Private Member Functions
NASAEvaluator ()
Default constructor.
Detailed Description
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>>
singleton Antioch::NASAEvaluator< CoeffType, NASAFit >
Definition at line 62 of file ascii_parser.h.
Constructor & Destructor Documentation
template<typename CoeffType, typename NASAFit> Antioch::NASAEvaluator< CoeffType, NASAFit >::NASAEvaluator (const NASAThermoMixture< CoeffType, NASAFit > & cea_mixture)
Definition at line 151 of file nasa_evaluator.h.
     : _nasa_mixture(cea_mixture)
   {
     return;
   }
template<typename CoeffType , typename NASAFit > Antioch::NASAEvaluator< CoeffType, NASAFit >::~NASAEvaluator ()
Definition at line 158 of file nasa_evaluator.h.
   {
     return;
   }
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> Antioch::NASAEvaluator< CoeffType, NASAFit >::NASAEvaluator () private
Default constructor.
Private to force to user to supply a NASAThermoMixture object.
Member Function Documentation
template<typename CoeffType , typename NASAFit > const NASAThermoMixture< CoeffType, NASAFit > & Antioch::NASAEvaluator< CoeffType, NASAFit >::cea_mixture () const inline
Definition at line 166 of file nasa_evaluator.h.
References Antioch::NASAEvaluator< CoeffType, NASAFit >::_nasa_mixture.
   {
     return _nasa_mixture;
   }
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> this Antioch::NASAEvaluator< CoeffType, NASAFit >::chem_mixture () -> h_over_RT(cache, species)) template< typename StateType, typename VectorStateType >typename enable_if_c< has_size< VectorStateType >::value, void >::typeh(const TempCache< StateType > &cache, VectorStateType &h) const
Referenced by Antioch::NASAEvaluator< CoeffType, NASAFit >::cp(), Antioch::NASAEvaluator< CoeffType, NASAFit >::cv(), and Antioch::NASAEvaluator< CoeffType, NASAFit >::h().
template<typename CoeffType , typename NASAFit > const ChemicalMixture< CoeffType > & Antioch::NASAEvaluator< CoeffType, NASAFit >::chem_mixture () const inline protected
Convenience function.
Definition at line 180 of file nasa_evaluator.h.
References Antioch::NASAEvaluator< CoeffType, NASAFit >::_nasa_mixture.
   {
     return _nasa_mixture.chemical_mixture();
   }
template<typename CoeffType , typename NASAFit > template<typename StateType > StateType Antioch::NASAEvaluator< CoeffType, NASAFit >::cp (const TempCache< StateType > & cache, unsigned int species) const inline
We currently need different specializations for scalar vs vector inputs here.
Definition at line 189 of file nasa_evaluator.h.
References Antioch::NASAEvaluator< CoeffType, NASAFit >::_nasa_mixture, Antioch::NASAEvaluator< CoeffType, NASAFit >::chem_mixture(), Antioch::constant_clone(), Antioch::NASAEvaluator< CoeffType, NASAFit >::cp_over_R(), Antioch::if_else(), and Antioch::TempCache< StateType >::T.
Referenced by Antioch::NASAThermoMixture< CoeffType, NASAFit >::add_curve_fit(), Antioch::NASAEvaluator< CoeffType, NASAFit >::cp(), Antioch::NASAEvaluator< CoeffType, NASAFit >::cv(), test_cp(), and tester().
   {
     typedef typename Antioch::value_type<StateType>::type ScalarType;
     // T < 200.1 ? cp_at_200p1 : R * cp_over_R
     return
       Antioch::if_else
         (cache.T < ScalarType(200.1),
          Antioch::constant_clone
            (cache.T,_nasa_mixture.cp_at_200p1(species)),
          StateType
            (this->chem_mixture().R(species) *
             this->cp_over_R(cache, species)));
   }
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> template<typename StateType , typename VectorStateType > enable_if_c< has_size<VectorStateType>::value, StateType >::type Antioch::NASAEvaluator< CoeffType, NASAFit >::cp (const TempCache< StateType > & cache, const VectorStateType & mass_fractions) const
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> this Antioch::NASAEvaluator< CoeffType, NASAFit >::cp (cache , species) -> chem_mixture().R(species)) template< typename StateType, typename VectorStateType >typename enable_if_c< has_size< VectorStateType >::value, StateType >::typecv(const TempCache< StateType > &cache, const VectorStateType &mass_fractions) const
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> template<typename StateType , typename VectorStateType > enable_if_c< has_size<VectorStateType>::value, StateType >::type Antioch::NASAEvaluator< CoeffType, NASAFit >::cp (const TempCache< StateType > & cache, const VectorStateType & mass_fractions) const inline
Definition at line 210 of file nasa_evaluator.h.
References antioch_assert_equal_to, antioch_assert_greater, Antioch::NASAEvaluator< CoeffType, NASAFit >::cp(), and Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species().
   {
     antioch_assert_equal_to( mass_fractions.size(), this->n_species() );
     antioch_assert_greater( mass_fractions.size(), 0 );
     StateType cp = mass_fractions[0]*this->cp(cache,0);
     for( unsigned int s = 1; s < this->n_species(); s++ )
       {
         cp += mass_fractions[s]*this->cp(cache,s);
       }
     return cp;
   }
template<typename CoeffType , typename NASAFit > template<typename StateType > StateType Antioch::NASAEvaluator< CoeffType, NASAFit >::cp_over_R (const TempCache< StateType > & cache, unsigned int species) const inline
Cp over R, directly from the curve fit.
Definition at line 250 of file nasa_evaluator.h.
References Antioch::NASAEvaluator< CoeffType, NASAFit >::_nasa_mixture, antioch_assert_less, and Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species().
Referenced by Antioch::NASAEvaluator< CoeffType, NASAFit >::cp().
   {
     antioch_assert_less( species, this->n_species() );
     // FIXME - we need assert_less to be vectorizable
     // antioch_assert_less( _nasa_mixture.curve_fit(species).interval(cache.T),
     //                      _nasa_mixture.curve_fit(species).n_intervals() );
     return this->_nasa_mixture.curve_fit(species).cp_over_R(cache);
   }
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> template<typename StateType > enable_if_c< has_size< VectorStateType >::value, StateType >::type Antioch::NASAEvaluator< CoeffType, NASAFit >::cv (const TempCache< StateType > & cache, unsigned int species) const inline
Definition at line 376 of file nasa_evaluator.h.
References Antioch::NASAEvaluator< CoeffType, NASAFit >::chem_mixture(), and Antioch::NASAEvaluator< CoeffType, NASAFit >::cp().
     {
       return this->cp(cache,mass_fractions) - this->chem_mixture().R(mass_fractions);
     }
template<typename CoeffType , typename NASAFit > template<typename StateType > StateType Antioch::NASAEvaluator< CoeffType, NASAFit >::cv_over_R (const TempCache< StateType > & cache, unsigned int species) const inline
Cv over R, from ideal gas,.
Definition at line 264 of file nasa_evaluator.h.
References Antioch::NASAEvaluator< CoeffType, NASAFit >::_nasa_mixture, antioch_assert_less, and Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species().
Referenced by tester().
   {
     antioch_assert_less( species, this->n_species() );
     // FIXME - we need assert_less to be vectorizable
     // antioch_assert_less( _nasa_mixture.curve_fit(species).interval(cache.T),
     //                      _nasa_mixture.curve_fit(species).n_intervals() );
     return this->_nasa_mixture.curve_fit(species).cp_over_R(cache) - StateType(1.L);
   }
template<typename CoeffType , typename NASAFit > template<typename StateType > StateType Antioch::NASAEvaluator< CoeffType, NASAFit >::dh_RT_minus_s_R_dT (const TempCache< StateType > & cache, unsigned int species) const inline
Definition at line 339 of file nasa_evaluator.h.
References Antioch::NASAEvaluator< CoeffType, NASAFit >::_nasa_mixture, antioch_assert_less, and Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species().
Referenced by Antioch::NASAEvaluator< CoeffType, NASAFit >::dh_RT_minus_s_R_dT().
   {
     antioch_assert_less( species, this->n_species() );
     // FIXME - we need assert_less to be vectorizable
     // antioch_assert_less( _nasa_mixture.curve_fit(species).interval(cache.T),
     //                      _nasa_mixture.curve_fit(species).n_intervals() );
     return this->_nasa_mixture.curve_fit(species).dh_RT_minus_s_R_dT(cache);
   }
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> template<typename StateType , typename VectorStateType > enable_if_c< has_size<VectorStateType>::value, void >::type Antioch::NASAEvaluator< CoeffType, NASAFit >::dh_RT_minus_s_R_dT (const TempCache< StateType > & cache, VectorStateType & h_RT_minus_s_R) const
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> template<typename StateType , typename VectorStateType > enable_if_c< has_size<VectorStateType>::value, void >::type Antioch::NASAEvaluator< CoeffType, NASAFit >::dh_RT_minus_s_R_dT (const TempCache< StateType > & cache, VectorStateType & dh_RT_minus_s_R_dT) const inline
Definition at line 356 of file nasa_evaluator.h.
References antioch_assert_equal_to, Antioch::NASAEvaluator< CoeffType, NASAFit >::dh_RT_minus_s_R_dT(), and Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species().
   {
     antioch_assert_equal_to( dh_RT_minus_s_R_dT.size(), this->n_species() );
     for( unsigned int s = 0; s < this->n_species(); s++ )
       {
         dh_RT_minus_s_R_dT[s] = this->dh_RT_minus_s_R_dT(cache,s);
       }
     return;
   }
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> template<typename StateType > enable_if_c< has_size< VectorStateType >::value, void >::type Antioch::NASAEvaluator< CoeffType, NASAFit >::h (const TempCache< StateType > & cache, unsigned int species) const inline
Definition at line 233 of file nasa_evaluator.h.
References antioch_assert_equal_to, Antioch::NASAEvaluator< CoeffType, NASAFit >::chem_mixture(), Antioch::NASAEvaluator< CoeffType, NASAFit >::h_over_RT(), Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species(), and Antioch::TempCache< StateType >::T.
Referenced by test_h().
   {
     antioch_assert_equal_to( h.size(), this->n_species() );
     for( unsigned int s = 0; s < this->n_species(); s++ )
       {
         h[s] = this->chem_mixture().R(s)*cache.T*this->h_over_RT(cache,s);
       }
     return;
   }
template<typename CoeffType , typename NASAFit > template<typename StateType > StateType Antioch::NASAEvaluator< CoeffType, NASAFit >::h_over_RT (const TempCache< StateType > & cache, unsigned int species) const inline
h over RT, directly from the curve fit
Definition at line 276 of file nasa_evaluator.h.
References Antioch::NASAEvaluator< CoeffType, NASAFit >::_nasa_mixture, antioch_assert_less, Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species(), and Antioch::TempCache< StateType >::T.
Referenced by Antioch::NASAEvaluator< CoeffType, NASAFit >::h(), and test_g().
   {
     antioch_assert_less( species, this->n_species() );
     antioch_assert_less( _nasa_mixture.curve_fit(species).interval(cache.T),
                          _nasa_mixture.curve_fit(species).n_intervals() );
     return this->_nasa_mixture.curve_fit(species).h_over_RT(cache);
   }
template<typename CoeffType , typename NASAFit > template<typename StateType > StateType Antioch::NASAEvaluator< CoeffType, NASAFit >::h_RT_minus_s_R (const TempCache< StateType > & cache, unsigned int species) const inline
We currently need different specializations for scalar vs vector inputs here.
Definition at line 303 of file nasa_evaluator.h.
References Antioch::NASAEvaluator< CoeffType, NASAFit >::_nasa_mixture, antioch_assert_less, and Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species().
Referenced by Antioch::NASAEvaluator< CoeffType, NASAFit >::h_RT_minus_s_R(), and test_type().
   {
     antioch_assert_less( species, this->n_species() );
     // FIXME - we need assert_less to be vectorizable
     // antioch_assert_less( _nasa_mixture.curve_fit(species).interval(cache.T),
     //                      _nasa_mixture.curve_fit(species).n_intervals() );
     return this->_nasa_mixture.curve_fit(species).h_RT_minus_s_R(cache);
   }
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> template<typename StateType , typename VectorStateType > enable_if_c< has_size<VectorStateType>::value, void >::type Antioch::NASAEvaluator< CoeffType, NASAFit >::h_RT_minus_s_R (const TempCache< StateType > & cache, VectorStateType & h_RT_minus_s_R) const
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> template<typename StateType , typename VectorStateType > enable_if_c< has_size<VectorStateType>::value, void >::type Antioch::NASAEvaluator< CoeffType, NASAFit >::h_RT_minus_s_R (const TempCache< StateType > & cache, VectorStateType & h_RT_minus_s_R) const inline
Definition at line 320 of file nasa_evaluator.h.
References antioch_assert_equal_to, Antioch::NASAEvaluator< CoeffType, NASAFit >::h_RT_minus_s_R(), and Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species().
   {
     antioch_assert_equal_to( h_RT_minus_s_R.size(), this->n_species() );
     for( unsigned int s = 0; s < this->n_species(); s++ )
       {
         h_RT_minus_s_R[s] = this->h_RT_minus_s_R(cache,s);
       }
     return;
   }
template<typename CoeffType , typename NASAFit > unsigned int Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species () const inline protected
Convenience function.
Definition at line 173 of file nasa_evaluator.h.
References Antioch::NASAEvaluator< CoeffType, NASAFit >::_nasa_mixture.
Referenced by Antioch::NASAEvaluator< CoeffType, NASAFit >::cp(), Antioch::NASAEvaluator< CoeffType, NASAFit >::cp_over_R(), Antioch::NASAEvaluator< CoeffType, NASAFit >::cv_over_R(), Antioch::NASAEvaluator< CoeffType, NASAFit >::dh_RT_minus_s_R_dT(), Antioch::NASAEvaluator< CoeffType, NASAFit >::h(), Antioch::NASAEvaluator< CoeffType, NASAFit >::h_over_RT(), Antioch::NASAEvaluator< CoeffType, NASAFit >::h_RT_minus_s_R(), and Antioch::NASAEvaluator< CoeffType, NASAFit >::s_over_R().
   {
     return _nasa_mixture.chemical_mixture().n_species();
   }
template<typename CoeffType , typename NASAFit > template<typename StateType > StateType Antioch::NASAEvaluator< CoeffType, NASAFit >::s_over_R (const TempCache< StateType > & cache, unsigned int species) const inline
s over R, directly from the curve fit
Definition at line 289 of file nasa_evaluator.h.
References Antioch::NASAEvaluator< CoeffType, NASAFit >::_nasa_mixture, antioch_assert_less, Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species(), and Antioch::TempCache< StateType >::T.
Referenced by test_g(), and test_s().
   {
     antioch_assert_less( species, this->n_species() );
     antioch_assert_less( _nasa_mixture.curve_fit(species).interval(cache.T),
                          _nasa_mixture.curve_fit(species).n_intervals() );
     return this->_nasa_mixture.curve_fit(species).s_over_R(cache);
   }
Member Data Documentation
template<typename CoeffType = double, typename NASAFit = NASA9CurveFit<CoeffType>> const NASAThermoMixture<CoeffType,NASAFit>& Antioch::NASAEvaluator< CoeffType, NASAFit >::_nasa_mixture protected
Definition at line 133 of file nasa_evaluator.h.
Referenced by Antioch::NASAEvaluator< CoeffType, NASAFit >::cea_mixture(), Antioch::NASAEvaluator< CoeffType, NASAFit >::chem_mixture(), Antioch::NASAEvaluator< CoeffType, NASAFit >::cp(), Antioch::NASAEvaluator< CoeffType, NASAFit >::cp_over_R(), Antioch::NASAEvaluator< CoeffType, NASAFit >::cv_over_R(), Antioch::NASAEvaluator< CoeffType, NASAFit >::dh_RT_minus_s_R_dT(), Antioch::NASAEvaluator< CoeffType, NASAFit >::h_over_RT(), Antioch::NASAEvaluator< CoeffType, NASAFit >::h_RT_minus_s_R(), Antioch::NASAEvaluator< CoeffType, NASAFit >::n_species(), and Antioch::NASAEvaluator< CoeffType, NASAFit >::s_over_R().
The documentation for this singleton was generated from the following files:
src/parsing/include/antioch/ascii_parser.h
src/thermo/include/antioch/nasa_evaluator.h