antioch-0.4.0: Antioch::WilkeMixture< CoeffType > Class Template Reference
Antioch::WilkeMixture< CoeffType > Class Template Reference
#include <wilke_mixture.h>
Public Member Functions
WilkeMixture (const ChemicalMixture< CoeffType > &mixture)
~WilkeMixture ()
CoeffType Mr_Ms_to_the_one_fourth (const unsigned int r, const unsigned int s) const
CoeffType denominator (const unsigned int r, const unsigned int s) const
const ChemicalMixture
< CoeffType > & chem_mixture () const
chemical mixture, mostly for backward compatibility
const ChemicalMixture
< CoeffType > & transport_mixture () const
chemical mixture, for backward compatibility
Protected Attributes
const ChemicalMixture
< CoeffType > & _mixture
std::vector< std::vector
< CoeffType > > _Mr_Ms_to_the_one_fourth
Cache for numerator term.
std::vector< std::vector
< CoeffType > > _denom
Cache for denominator term.
Detailed Description
template<class CoeffType = double>
class Antioch::WilkeMixture< CoeffType >
Definition at line 51 of file wilke_mixture.h.
Constructor & Destructor Documentation
template<class CoeffType > Antioch::WilkeMixture< CoeffType >::WilkeMixture (const ChemicalMixture< CoeffType > & mixture)
Definition at line 84 of file wilke_mixture.h.
References Antioch::WilkeMixture< CoeffType >::_denom, Antioch::WilkeMixture< CoeffType >::_Mr_Ms_to_the_one_fourth, antioch_deprecated, Antioch::ChemicalMixture< CoeffType >::chemical_mixture(), Antioch::ChemicalMixture< CoeffType >::n_species(), and std::pow().
     : _mixture(mixture),
       _Mr_Ms_to_the_one_fourth(mixture.n_species()),
       _denom(mixture.n_species())
   {
     antioch_deprecated();
     using std::pow;
     for( unsigned int r = 0; r < mixture.n_species(); r++ )
       {
         _Mr_Ms_to_the_one_fourth[r].resize(mixture.n_species());
         _denom[r].resize(mixture.n_species());
         for( unsigned int s = 0; s < mixture.n_species(); s++ )
           {
             const CoeffType Mr = mixture.chemical_mixture().M(r);
             const CoeffType Ms = mixture.chemical_mixture().M(s);
             _Mr_Ms_to_the_one_fourth[r][s] = pow( Mr/Ms, CoeffType(0.25) );
             _denom[r][s] = std::sqrt(8.0*(1.0+Ms/Mr));
           }
       }
     return;
   }
template<class CoeffType > Antioch::WilkeMixture< CoeffType >::~WilkeMixture ()
Definition at line 111 of file wilke_mixture.h.
   {
     return;
   }
Member Function Documentation
template<class CoeffType > const ChemicalMixture< CoeffType > & Antioch::WilkeMixture< CoeffType >::chem_mixture () const inline
chemical mixture, mostly for backward compatibility
Definition at line 135 of file wilke_mixture.h.
   {
     return _mixture;
   }
template<class CoeffType > CoeffType Antioch::WilkeMixture< CoeffType >::denominator (const unsigned int r, const unsigned int s) const inline
Definition at line 127 of file wilke_mixture.h.
   {
     return _denom[r][s];
   }
template<class CoeffType > CoeffType Antioch::WilkeMixture< CoeffType >::Mr_Ms_to_the_one_fourth (const unsigned int r, const unsigned int s) const inline
Definition at line 118 of file wilke_mixture.h.
   {
     return _Mr_Ms_to_the_one_fourth[r][s];
   }
template<class CoeffType > const ChemicalMixture< CoeffType > & Antioch::WilkeMixture< CoeffType >::transport_mixture () const inline
chemical mixture, for backward compatibility
Definition at line 142 of file wilke_mixture.h.
   {
     return _mixture;
   }
Member Data Documentation
template<class CoeffType = double> std::vector<std::vector<CoeffType> > Antioch::WilkeMixture< CoeffType >::_denom protected
Cache for denominator term.
Definition at line 78 of file wilke_mixture.h.
Referenced by Antioch::WilkeMixture< CoeffType >::WilkeMixture().
template<class CoeffType = double> const ChemicalMixture<CoeffType>& Antioch::WilkeMixture< CoeffType >::_mixture protected
Definition at line 72 of file wilke_mixture.h.
template<class CoeffType = double> std::vector<std::vector<CoeffType> > Antioch::WilkeMixture< CoeffType >::_Mr_Ms_to_the_one_fourth protected
Cache for numerator term.
Definition at line 75 of file wilke_mixture.h.
Referenced by Antioch::WilkeMixture< CoeffType >::WilkeMixture().
The documentation for this class was generated from the following file:
src/transport/include/antioch/wilke_mixture.h