antioch-0.4.0: Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType > Class Template Reference
Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType > Class Template Reference
Deprecated. Use MixtureAveragedTransportEvaluator instead.
#include <wilke_evaluator.h>
Public Member Functions
WilkeEvaluator (const WilkeMixture< CoeffType > &mixture, const MixtureViscosity &viscosity, const ThermalConductivity &conductivity)
~WilkeEvaluator ()
template<typename StateType , typename VectorStateType >
StateType mu (const StateType &T, const VectorStateType &mass_fractions) const
template<typename StateType , typename VectorStateType >
StateType k (const StateType &T, const VectorStateType &mass_fractions) const
template<typename StateType , typename VectorStateType >
void mu_and_k (const StateType &T, const VectorStateType &mass_fractions, StateType &mu, StateType &k) const
template<typename StateType , typename VectorStateType >
void compute_mu_chi (const StateType &T, const VectorStateType &mass_fractions, VectorStateType &mu, VectorStateType &chi) const
Helper function to reduce code duplication.
template<typename VectorStateType >
Antioch::value_type
< VectorStateType >::type compute_phi (const VectorStateType &mu, const VectorStateType &chi, const unsigned int s) const
Helper function to reduce code duplication.
template<typename VectorStateType >
Antioch::value_type
< VectorStateType >::type compute_phi (const VectorStateType &mu, const VectorStateType &chi, const unsigned int s) const
Private Types
typedef
MixtureAveragedTransportEvaluator
< ConstantLewisDiffusivity
< CoeffType >, typename
MixtureViscosity::species_viscosity_type,
ThermalConductivity, CoeffType > Evaluator
Private Member Functions
WilkeEvaluator ()
Private Attributes
TransportMixture< CoeffType > * _transport_mixture
MixtureAveragedTransportMixture
< CoeffType > * _wilke_mixture
MixtureDiffusion
< ConstantLewisDiffusivity
< CoeffType >, CoeffType > * _diffusion
This is dummy.
MixtureConductivity
< ThermalConductivity,
CoeffType > * _conductivity
ThermalConductivity::micro_thermo_type * _micro_thermo
Evaluator * _wilke_eval
Detailed Description
template<class MixtureViscosity, class ThermalConductivity, class CoeffType = double>
class Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >
Deprecated. Use MixtureAveragedTransportEvaluator instead.
Definition at line 47 of file wilke_evaluator.h.
Member Typedef Documentation
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> typedef MixtureAveragedTransportEvaluator<ConstantLewisDiffusivity<CoeffType>, typename MixtureViscosity::species_viscosity_type, ThermalConductivity, CoeffType> Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::Evaluator private
Definition at line 111 of file wilke_evaluator.h.
Constructor & Destructor Documentation
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::WilkeEvaluator (const WilkeMixture< CoeffType > & mixture, const MixtureViscosity & viscosity, const ThermalConductivity & conductivity)
template<class Viscosity , class ThermalConductivity , class CoeffType > Antioch::WilkeEvaluator< Viscosity, ThermalConductivity, CoeffType >::~WilkeEvaluator ()
Definition at line 133 of file wilke_evaluator.h.
   {
     delete _wilke_eval;
     delete _micro_thermo;
     delete _conductivity;
     delete _diffusion;
     delete _wilke_mixture;
     delete _transport_mixture;
     return;
   }
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::WilkeEvaluator () private
Member Function Documentation
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> template<typename StateType , typename VectorStateType > void Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::compute_mu_chi (const StateType & T, const VectorStateType & mass_fractions, VectorStateType & mu, VectorStateType & chi) const inline
Helper function to reduce code duplication.
Populates species viscosities and the intermediate variable needed for Wilke's mixing rule.
Definition at line 75 of file wilke_evaluator.h.
References Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::_wilke_eval, and Antioch::MixtureAveragedTransportEvaluator< Diffusion, Viscosity, ThermalConductivity, CoeffType >::compute_mu_chi().
                                                             {_wilke_eval->compute_mu_chi(T,mass_fractions,mu,chi);}
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> template<typename VectorStateType > Antioch::value_type<VectorStateType>::type Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::compute_phi (const VectorStateType & mu, const VectorStateType & chi, const unsigned int s) const
Helper function to reduce code duplication.
Computes the intermediate variable needed for Wilke's mixing rule.
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> template<typename VectorStateType > Antioch::value_type<VectorStateType>::type Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::compute_phi (const VectorStateType & mu, const VectorStateType & chi, const unsigned int s) const
Definition at line 149 of file wilke_evaluator.h.
References Antioch::init_constant().
   {
     typename Antioch::rebind<VectorStateType,VectorStateType>::type mu_mu_sqrt(mu.size());
     Antioch::init_constant(mu_mu_sqrt,mu);
     _wilke_eval->compute_mu_mu_sqrt( mu, mu_mu_sqrt);
     return _wilke_eval->compute_phi( mu_mu_sqrt, chi, s );
   }
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> template<typename StateType , typename VectorStateType > StateType Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::k (const StateType & T, const VectorStateType & mass_fractions) const inline
Definition at line 63 of file wilke_evaluator.h.
References Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::_wilke_eval, and Antioch::MixtureAveragedTransportEvaluator< Diffusion, Viscosity, ThermalConductivity, CoeffType >::k().
                                                                {return _wilke_eval->k(T,mass_fractions);}
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> template<typename StateType , typename VectorStateType > StateType Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::mu (const StateType & T, const VectorStateType & mass_fractions) const inline
Definition at line 59 of file wilke_evaluator.h.
References Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::_wilke_eval, and Antioch::MixtureAveragedTransportEvaluator< Diffusion, Viscosity, ThermalConductivity, CoeffType >::mu().
                                                                 {return _wilke_eval->mu(T,mass_fractions);}
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> template<typename StateType , typename VectorStateType > void Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::mu_and_k (const StateType & T, const VectorStateType & mass_fractions, StateType & mu, StateType & k) const inline
Definition at line 67 of file wilke_evaluator.h.
References Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::_wilke_eval, and Antioch::MixtureAveragedTransportEvaluator< Diffusion, Viscosity, ThermalConductivity, CoeffType >::mu_and_k().
                                                        {_wilke_eval->mu_and_k(T,mass_fractions,mu,k);}
Member Data Documentation
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> MixtureConductivity<ThermalConductivity,CoeffType>* Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::_conductivity private
Definition at line 104 of file wilke_evaluator.h.
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> MixtureDiffusion<ConstantLewisDiffusivity<CoeffType>,CoeffType>* Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::_diffusion private
This is dummy.
WilkeEvaluator doesn't support diffusion, but the new MixtureAveragedTransportEvaluator does so we create a dummy diffusion class, don't bother building it and pass it along to MixtureAveragedTransportEvaluator.
Definition at line 102 of file wilke_evaluator.h.
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> ThermalConductivity::micro_thermo_type* Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::_micro_thermo private
Definition at line 106 of file wilke_evaluator.h.
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> TransportMixture<CoeffType>* Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::_transport_mixture private
Definition at line 94 of file wilke_evaluator.h.
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> Evaluator* Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::_wilke_eval private
Definition at line 113 of file wilke_evaluator.h.
Referenced by Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::compute_mu_chi(), Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::k(), Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::mu(), and Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::mu_and_k().
template<class MixtureViscosity , class ThermalConductivity , class CoeffType = double> MixtureAveragedTransportMixture<CoeffType>* Antioch::WilkeEvaluator< MixtureViscosity, ThermalConductivity, CoeffType >::_wilke_mixture private
Definition at line 96 of file wilke_evaluator.h.
The documentation for this class was generated from the following file:
src/transport/include/antioch/wilke_evaluator.h