antioch-0.4.0: tinyxml2::XMLElement Class Reference
tinyxml2::XMLElement Class Reference
#include <tinyxml2.h>
Public Types
enum { OPEN, CLOSED, CLOSING }
Public Member Functions
const char * Name () const
Get the name of an element (which is the Value() of the node.)
void SetName (const char *str, bool staticMem=false)
Set the name of the element.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual const XMLElement * ToElement () const
virtual bool Accept (XMLVisitor *visitor) const
const char * Attribute (const char *name, const char *value=0) const
int IntAttribute (const char *name) const
unsigned UnsignedAttribute (const char *name) const
See IntAttribute()
bool BoolAttribute (const char *name) const
See IntAttribute()
double DoubleAttribute (const char *name) const
See IntAttribute()
float FloatAttribute (const char *name) const
See IntAttribute()
int QueryIntAttribute (const char *name, int *_value) const
int QueryUnsignedAttribute (const char *name, unsigned int *_value) const
See QueryIntAttribute()
int QueryBoolAttribute (const char *name, bool *_value) const
See QueryIntAttribute()
int QueryDoubleAttribute (const char *name, double *_value) const
See QueryIntAttribute()
int QueryFloatAttribute (const char *name, float *_value) const
See QueryIntAttribute()
void SetAttribute (const char *name, const char *_value)
Sets the named attribute to value.
void SetAttribute (const char *name, int _value)
Sets the named attribute to value.
void SetAttribute (const char *name, unsigned _value)
Sets the named attribute to value.
void SetAttribute (const char *name, bool _value)
Sets the named attribute to value.
void SetAttribute (const char *name, double _value)
Sets the named attribute to value.
void DeleteAttribute (const char *name)
const XMLAttribute * FirstAttribute () const
Return the first attribute in the list.
const XMLAttribute * FindAttribute (const char *name) const
Query a specific attribute in the list.
const char * GetText () const
int QueryIntText (int *_value) const
int QueryUnsignedText (unsigned *_value) const
See QueryIntText()
int QueryBoolText (bool *_value) const
See QueryIntText()
int QueryDoubleText (double *_value) const
See QueryIntText()
int QueryFloatText (float *_value) const
See QueryIntText()
int ClosingType () const
char * ParseDeep (char *p, StrPair *endTag)
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual const XMLText * ToText () const
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual const XMLComment * ToComment () const
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual const XMLDocument * ToDocument () const
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual const XMLDeclaration * ToDeclaration () const
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *value=0) const
XMLElement * FirstChildElement (const char *_value=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *value=0) const
XMLElement * LastChildElement (const char *_value=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *value=0) const
Get the previous (left) sibling element of this node, with an opitionally supplied name.
XMLElement * PreviousSiblingElement (const char *_value=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *value=0) const
Get the next (right) sibling element of this node, with an opitionally supplied name.
XMLElement * NextSiblingElement (const char *_value=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
Protected Attributes
XMLDocument * document
XMLNode * parent
StrPair value
XMLNode * firstChild
XMLNode * lastChild
XMLNode * prev
XMLNode * next
Private Member Functions
XMLElement (XMLDocument *doc)
virtual ~XMLElement ()
XMLElement (const XMLElement &)
void operator= (const XMLElement &)
XMLAttribute * FindAttribute (const char *name)
XMLAttribute * FindOrCreateAttribute (const char *name)
char * ParseAttributes (char *p)
Private Attributes
int closingType
XMLAttribute * rootAttribute
Friends
class XMLBase
class XMLDocument
Detailed Description
The element is a container class. It has a value, the element name, and can contain other elements, text, comments, and unknowns. Elements also contain an arbitrary number of attributes.
Definition at line 855 of file tinyxml2.h.
Member Enumeration Documentation
anonymous enum
Enumerator
OPEN
CLOSED
CLOSING
Definition at line 1020 of file tinyxml2.h.
              {
                 OPEN,           // <foo>
                 CLOSED,         // <foo/>
                 CLOSING         // </foo>
         };
Constructor & Destructor Documentation
XMLElement::XMLElement (XMLDocument * doc) inline private
Definition at line 1217 of file tinyxml2_imp.h.
                                          : XMLNode( doc ),
         closingType( 0 ),
         rootAttribute( 0 )
 {
 }
XMLElement::~XMLElement () inline private virtual
Definition at line 1225 of file tinyxml2_imp.h.
References DELETE_ATTRIBUTE, tinyxml2::XMLNode::next, tinyxml2::XMLAttribute::next, and rootAttribute.
 {
         while( rootAttribute ) {
                 XMLAttribute* next = rootAttribute->next;
                 DELETE_ATTRIBUTE( rootAttribute );
                 rootAttribute = next;
         }
 }
tinyxml2::XMLElement::XMLElement (const XMLElement &) private
Member Function Documentation
bool XMLElement::Accept (XMLVisitor * visitor) const inline virtual
Accept a hierarchical visit of the nodes in the TinyXML DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the TiXmlVisitor interface.
This is essentially a SAX interface for TinyXML. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
    TiXmlPrinter printer;
    tinyxmlDoc.Accept( &printer );
    const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode.
Definition at line 1530 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::NextSibling(), rootAttribute, tinyxml2::XMLVisitor::VisitEnter(), and tinyxml2::XMLVisitor::VisitExit().
 {
         if ( visitor->VisitEnter( *this, rootAttribute ) )
         {
                 for ( const XMLNode* node=FirstChild(); node; node=node->NextSibling() )
                 {
                         if ( !node->Accept( visitor ) )
                                 break;
                 }
         }
         return visitor->VisitExit( *this );
 }
const char * XMLElement::Attribute (const char * name, const char * value = 0) const inline
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists. For example:
    const char* value = ele->Attribute( "foo" );
The 'value' parameter is normally null. However, if specified, the attribute will only be returned if the 'name' and 'value' match. This allow you to write code:
    if ( ele->Attribute( "foo", "bar" ) ) callFooIsBar();
rather than:
    if ( ele->Attribute( "foo" ) ) {
        if ( strcmp( ele->Attribute( "foo" ), "bar" ) == 0 ) callFooIsBar();
    }
Definition at line 1260 of file tinyxml2_imp.h.
References FindAttribute(), tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLNode::value, and tinyxml2::XMLAttribute::Value().
Referenced by Antioch::XMLParser< NumericType >::find_element_with_attribute(), ParseAttributes(), Antioch::XMLParser< NumericType >::read_thermodynamic_data_root(), and Antioch::XMLParser< NumericType >::where_is_k0().
 {
         const XMLAttribute* a = FindAttribute( name );
         if ( !a )
                 return 0;
         if ( !value || XMLUtil::StringEqual( a->Value(), value ))
                 return a->Value();
         return 0;
 }
bool tinyxml2::XMLElement::BoolAttribute (const char * name) const inline
See IntAttribute()
Definition at line 903 of file tinyxml2.h.
References QueryBoolAttribute().
 { bool b=false; QueryBoolAttribute( name, &b );         return b; }
int tinyxml2::XMLElement::ClosingType () const inline
Definition at line 1025 of file tinyxml2.h.
References closingType.
Referenced by tinyxml2::XMLNode::ParseDeep().
 { return closingType; }
void XMLElement::DeleteAttribute (const char * name) inline
Delete an attribute.
Definition at line 1381 of file tinyxml2_imp.h.
References DELETE_ATTRIBUTE, tinyxml2::XMLAttribute::next, tinyxml2::XMLNode::prev, rootAttribute, and tinyxml2::XMLUtil::StringEqual().
 {
         XMLAttribute* prev = 0;
         for( XMLAttribute* a=rootAttribute; a; a=a->next ) {
                 if ( XMLUtil::StringEqual( name, a->Name() ) ) {
                         if ( prev ) {
                                 prev->next = a->next;
                         }
                         else {
                                 rootAttribute = a->next;
                         }
                         DELETE_ATTRIBUTE( a );
                         break;
                 }
                 prev = a;
         }
 }
void XMLNode::DeleteChild (XMLNode * node) inline inherited
Delete a child of this node.
Definition at line 661 of file tinyxml2_imp.h.
References DELETE_NODE, tinyxml2::XMLNode::parent, and TIXMLASSERT.
Referenced by tinyxml2::XMLDocument::DeleteNode().
 {
         TIXMLASSERT( node->parent == this );
         DELETE_NODE( node );
 }
void XMLNode::DeleteChildren () inline inherited
Delete all the children of this node.
Definition at line 629 of file tinyxml2_imp.h.
References DELETE_NODE, tinyxml2::XMLNode::firstChild, tinyxml2::XMLNode::lastChild, and tinyxml2::XMLNode::Unlink().
Referenced by tinyxml2::XMLDocument::LoadFile(), tinyxml2::XMLDocument::Parse(), tinyxml2::XMLDocument::~XMLDocument(), and tinyxml2::XMLNode::~XMLNode().
 {
         while( firstChild ) {
                 XMLNode* node = firstChild;
                 Unlink( node );
                 DELETE_NODE( node );
         }
         firstChild = lastChild = 0;
 }
double tinyxml2::XMLElement::DoubleAttribute (const char * name) const inline
See IntAttribute()
Definition at line 905 of file tinyxml2.h.
References QueryDoubleAttribute().
 { double d=0;   QueryDoubleAttribute( name, &d );       return d; }
const XMLAttribute * XMLElement::FindAttribute (const char * name) const inline
Query a specific attribute in the list.
Definition at line 1248 of file tinyxml2_imp.h.
References tinyxml2::XMLAttribute::Name(), tinyxml2::XMLAttribute::next, rootAttribute, and tinyxml2::XMLUtil::StringEqual().
Referenced by Attribute(), QueryBoolAttribute(), QueryDoubleAttribute(), QueryFloatAttribute(), QueryIntAttribute(), and QueryUnsignedAttribute().
 {
         XMLAttribute* a = 0;
         for( a=rootAttribute; a; a = a->next ) {
                 if ( XMLUtil::StringEqual( a->Name(), name ) )
                         return a;
         }
         return 0;
 }
XMLAttribute * XMLElement::FindAttribute (const char * name) inline private
Definition at line 1236 of file tinyxml2_imp.h.
References tinyxml2::XMLAttribute::Name(), tinyxml2::XMLAttribute::next, rootAttribute, and tinyxml2::XMLUtil::StringEqual().
 {
         XMLAttribute* a = 0;
         for( a=rootAttribute; a; a = a->next ) {
                 if ( XMLUtil::StringEqual( a->Name(), name ) )
                         return a;
         }
         return 0;
 }
XMLAttribute * XMLElement::FindOrCreateAttribute (const char * name) inline private
Definition at line 1353 of file tinyxml2_imp.h.
References tinyxml2::XMLDocument::attributePool, tinyxml2::XMLNode::document, tinyxml2::XMLAttribute::memPool, tinyxml2::XMLAttribute::next, rootAttribute, tinyxml2::XMLAttribute::SetName(), and tinyxml2::XMLUtil::StringEqual().
Referenced by SetAttribute().
 {
         XMLAttribute* last = 0;
         XMLAttribute* attrib = 0;
         for( attrib = rootAttribute;
                  attrib;
                  last = attrib, attrib = attrib->next )
         {
                 if ( XMLUtil::StringEqual( attrib->Name(), name ) ) {
                         break;
                 }
         }
         if ( !attrib ) {
                 attrib = new (document->attributePool.Alloc() ) XMLAttribute();
                 attrib->memPool = &document->attributePool;
                 if ( last ) {
                         last->next = attrib;
                 }
                 else {
                         rootAttribute = attrib;
                 }
                 attrib->SetName( name );
         }
         return attrib;
 }
const XMLAttribute* tinyxml2::XMLElement::FirstAttribute () const inline
Return the first attribute in the list.
Definition at line 949 of file tinyxml2.h.
References rootAttribute.
Referenced by ShallowClone(), and ShallowEqual().
 { return rootAttribute; }
const XMLNode* tinyxml2::XMLNode::FirstChild () const inline inherited
Get the first child node, or null if none exists.
Definition at line 496 of file tinyxml2.h.
References tinyxml2::XMLNode::firstChild.
Referenced by Accept(), tinyxml2::XMLDocument::Accept(), tinyxml2::XMLHandle::FirstChild(), tinyxml2::XMLConstHandle::FirstChild(), GetText(), QueryBoolText(), QueryDoubleText(), QueryFloatText(), QueryIntText(), and QueryUnsignedText().
 { return firstChild; }
XMLNode* tinyxml2::XMLNode::FirstChild () inline inherited
Definition at line 497 of file tinyxml2.h.
References tinyxml2::XMLNode::firstChild.
 { return firstChild; }
const XMLElement * XMLNode::FirstChildElement (const char * value = 0) const inline inherited
Get the first child element, or optionally the first child element with the specified name.
Definition at line 740 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::firstChild, Name(), tinyxml2::XMLNode::next, tinyxml2::XMLUtil::StringEqual(), ToElement(), and tinyxml2::XMLNode::value.
Referenced by Antioch::XMLParser< NumericType >::efficiencies(), tinyxml2::XMLHandle::FirstChildElement(), tinyxml2::XMLConstHandle::FirstChildElement(), Antioch::XMLParser< NumericType >::get_parameter(), Antioch::XMLParser< NumericType >::products_orders(), Antioch::XMLParser< NumericType >::products_pairs(), Antioch::XMLParser< NumericType >::reactants_orders(), Antioch::XMLParser< NumericType >::reactants_pairs(), Antioch::XMLParser< NumericType >::reaction_kinetics_model(), Antioch::XMLParser< NumericType >::read_thermodynamic_data_root(), tinyxml2::XMLDocument::RootElement(), Antioch::XMLParser< NumericType >::verify_Kooij_in_place_of_Arrhenius(), and Antioch::XMLParser< NumericType >::where_is_k0().
 {
         for( XMLNode* node=firstChild; node; node=node->next ) {
                 XMLElement* element = node->ToElement();
                 if ( element ) {
                         if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                                 return element;
                         }
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::FirstChildElement (const char * _value = 0) inline inherited
Definition at line 502 of file tinyxml2.h.
References tinyxml2::XMLNode::FirstChildElement().
Referenced by tinyxml2::XMLNode::FirstChildElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->FirstChildElement( _value )); }
float tinyxml2::XMLElement::FloatAttribute (const char * name) const inline
See IntAttribute()
Definition at line 907 of file tinyxml2.h.
References QueryFloatAttribute().
 { float f=0;    QueryFloatAttribute( name, &f );        return f; }
const XMLDocument* tinyxml2::XMLNode::GetDocument () const inline inherited
Get the XMLDocument that owns this XMLNode.
Definition at line 455 of file tinyxml2.h.
References tinyxml2::XMLNode::document.
 { return document; }
XMLDocument* tinyxml2::XMLNode::GetDocument () inline inherited
Get the XMLDocument that owns this XMLNode.
Definition at line 457 of file tinyxml2.h.
References tinyxml2::XMLNode::document.
 { return document; }
const char * XMLElement::GetText () const inline
Convenience function for easy access to the text inside an element. Although easy and concise, GetText() is limited compared to getting the TiXmlText child and accessing it directly.
If the first child of 'this' is a TiXmlText, the GetText() returns the character string of the Text node, else null is returned.
This is a convenient method for getting the text of simple contained text:
    <foo>This is text</foo>
        const char* str = fooElement->GetText();
'str' will be a pointer to "This is text".
Note that this function can be misleading. If the element foo was created from this XML:
        <foo><b>This is text</b></foo>
then the value of str would be null. The first child node isn't a text node, it is another element. From this XML:
        <foo>This is <b>text</b></foo>
GetText() will return "This is ".
Definition at line 1272 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::ToText(), and tinyxml2::XMLNode::Value().
Referenced by Antioch::XMLParser< NumericType >::molecules_pairs(), and Antioch::XMLParser< NumericType >::read_thermodynamic_data_root().
 {
         if ( FirstChild() && FirstChild()->ToText() ) {
                 return FirstChild()->ToText()->Value();
         }
         return 0;
 }
XMLNode * XMLNode::InsertAfterChild (XMLNode * afterThis, XMLNode * addThis) inline inherited
Add a node after the specified child node.
Definition at line 718 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::next, tinyxml2::XMLNode::parent, tinyxml2::XMLNode::prev, and TIXMLASSERT.
 {
         TIXMLASSERT( afterThis->parent == this );
         if ( afterThis->parent != this )
                 return 0;
         if ( afterThis->next == 0 ) {
                 // The last node or the only node.
                 return InsertEndChild( addThis );
         }
         addThis->prev = afterThis;
         addThis->next = afterThis->next;
         afterThis->next->prev = addThis;
         afterThis->next = addThis;
         addThis->parent = this;
         return addThis;
 }
XMLNode * XMLNode::InsertEndChild (XMLNode * addThis) inline inherited
Add a child node as the last (right) child.
Definition at line 669 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::firstChild, tinyxml2::XMLNode::lastChild, tinyxml2::XMLNode::next, tinyxml2::XMLNode::parent, tinyxml2::XMLNode::prev, and TIXMLASSERT.
Referenced by tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::LinkEndChild(), and tinyxml2::XMLNode::ParseDeep().
 {
         if ( lastChild ) {
                 TIXMLASSERT( firstChild );
                 TIXMLASSERT( lastChild->next == 0 );
                 lastChild->next = addThis;
                 addThis->prev = lastChild;
                 lastChild = addThis;
                 addThis->next = 0;
         }
         else {
                 TIXMLASSERT( firstChild == 0 );
                 firstChild = lastChild = addThis;
                 addThis->prev = 0;
                 addThis->next = 0;
         }
         addThis->parent = this;
         return addThis;
 }
XMLNode * XMLNode::InsertFirstChild (XMLNode * addThis) inline inherited
Add a child node as the first (left) child.
Definition at line 693 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::firstChild, tinyxml2::XMLNode::lastChild, tinyxml2::XMLNode::next, tinyxml2::XMLNode::parent, tinyxml2::XMLNode::prev, and TIXMLASSERT.
 {
         if ( firstChild ) {
                 TIXMLASSERT( lastChild );
                 TIXMLASSERT( firstChild->prev == 0 );
                 firstChild->prev = addThis;
                 addThis->next = firstChild;
                 firstChild = addThis;
                 addThis->prev = 0;
         }
         else {
                 TIXMLASSERT( lastChild == 0 );
                 firstChild = lastChild = addThis;
                 addThis->prev = 0;
                 addThis->next = 0;
         }
         addThis->parent = this;
         return addThis;
 }
int tinyxml2::XMLElement::IntAttribute (const char * name) const inline
Given an attribute name, IntAttribute() returns the value of the attribute interpreted as an integer. 0 will be returned if there is an error. For a method with error checking, see QueryIntAttribute()
Definition at line 899 of file tinyxml2.h.
References QueryIntAttribute().
 { int i=0;              QueryIntAttribute( name, &i );          return i; }
const XMLNode* tinyxml2::XMLNode::LastChild () const inline inherited
Get the last child node, or null if none exists.
Definition at line 505 of file tinyxml2.h.
References tinyxml2::XMLNode::lastChild.
Referenced by tinyxml2::XMLHandle::LastChild(), and tinyxml2::XMLConstHandle::LastChild().
 { return lastChild; }
XMLNode* tinyxml2::XMLNode::LastChild () inline inherited
Definition at line 506 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChild().
Referenced by tinyxml2::XMLNode::LastChild().
 { return const_cast<XMLNode*>(const_cast<const XMLNode*>(this)->LastChild() ); }
const XMLElement * XMLNode::LastChildElement (const char * value = 0) const inline inherited
Get the last child element or optionally the last child element with the specified name.
Definition at line 755 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::lastChild, Name(), tinyxml2::XMLNode::prev, tinyxml2::XMLUtil::StringEqual(), ToElement(), and tinyxml2::XMLNode::value.
Referenced by tinyxml2::XMLHandle::LastChildElement(), and tinyxml2::XMLConstHandle::LastChildElement().
 {
         for( XMLNode* node=lastChild; node; node=node->prev ) {
                 XMLElement* element = node->ToElement();
                 if ( element ) {
                         if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                                 return element;
                         }
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::LastChildElement (const char * _value = 0) inline inherited
Definition at line 512 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChildElement().
Referenced by tinyxml2::XMLNode::LastChildElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->LastChildElement(_value) ); }
XMLNode* tinyxml2::XMLNode::LinkEndChild (XMLNode * addThis) inline inherited
Definition at line 535 of file tinyxml2.h.
References tinyxml2::XMLNode::InsertEndChild().
 { return InsertEndChild( addThis ); }
const char* tinyxml2::XMLElement::Name () const inline
Get the name of an element (which is the Value() of the node.)
Definition at line 861 of file tinyxml2.h.
References tinyxml2::XMLNode::Value().
Referenced by tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::LastChildElement(), ParseAttributes(), and tinyxml2::XMLPrinter::VisitEnter().
 { return Value(); }
const XMLNode* tinyxml2::XMLNode::NextSibling () const inline inherited
Get the next (right) sibling node of this node.
Definition at line 523 of file tinyxml2.h.
References tinyxml2::XMLNode::next.
Referenced by Accept(), tinyxml2::XMLDocument::Accept(), tinyxml2::XMLHandle::NextSibling(), and tinyxml2::XMLConstHandle::NextSibling().
 { return next; }
XMLNode* tinyxml2::XMLNode::NextSibling () inline inherited
Definition at line 524 of file tinyxml2.h.
References tinyxml2::XMLNode::next.
 { return next; }
const XMLElement * XMLNode::NextSiblingElement (const char * value = 0) const inline inherited
Get the next (right) sibling element of this node, with an opitionally supplied name.
Definition at line 770 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::next, tinyxml2::XMLUtil::StringEqual(), and ToElement().
Referenced by Antioch::XMLParser< NumericType >::find_element_with_attribute(), tinyxml2::XMLHandle::NextSiblingElement(), tinyxml2::XMLConstHandle::NextSiblingElement(), Antioch::XMLParser< NumericType >::read_thermodynamic_data_root(), and Antioch::XMLParser< NumericType >::where_is_k0().
 {
         for( XMLNode* element=this->next; element; element = element->next ) {
                 if (    element->ToElement()
                          && (!value || XMLUtil::StringEqual( value, element->Value() )))
                 {
                         return element->ToElement();
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::NextSiblingElement (const char * _value = 0) inline inherited
Definition at line 528 of file tinyxml2.h.
References tinyxml2::XMLNode::NextSiblingElement().
Referenced by tinyxml2::XMLNode::NextSiblingElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->NextSiblingElement( _value ) ); }
bool tinyxml2::XMLNode::NoChildren () const inline inherited
Returns true if this node has no children.
Definition at line 493 of file tinyxml2.h.
References tinyxml2::XMLNode::firstChild.
 { return !firstChild; }
void tinyxml2::XMLElement::operator= (const XMLElement &) private
const XMLNode* tinyxml2::XMLNode::Parent () const inline inherited
Get the parent of this node on the DOM.
Definition at line 489 of file tinyxml2.h.
References tinyxml2::XMLNode::parent.
 { return parent; }
XMLNode* tinyxml2::XMLNode::Parent () inline inherited
Definition at line 490 of file tinyxml2.h.
References tinyxml2::XMLNode::parent.
 { return parent; }
char * XMLElement::ParseAttributes (char * p) inline private
Definition at line 1401 of file tinyxml2_imp.h.
References Attribute(), tinyxml2::XMLDocument::attributePool, CLOSED, closingType, DELETE_ATTRIBUTE, tinyxml2::XMLNode::document, tinyxml2::XMLUtil::IsAlpha(), tinyxml2::XMLAttribute::memPool, tinyxml2::XMLAttribute::Name(), Name(), tinyxml2::XMLAttribute::next, tinyxml2::XMLAttribute::ParseDeep(), tinyxml2::XMLDocument::ProcessEntities(), rootAttribute, tinyxml2::XMLDocument::SetError(), tinyxml2::XMLUtil::SkipWhiteSpace(), tinyxml2::XML_ERROR_PARSING_ATTRIBUTE, and tinyxml2::XML_ERROR_PARSING_ELEMENT.
Referenced by ParseDeep().
 {
         const char* start = p;
         XMLAttribute* prevAttribute = 0;
         // Read the attributes.
         while( p ) {
                 p = XMLUtil::SkipWhiteSpace( p );
                 if ( !p || !(*p) ) {
                         document->SetError( XML_ERROR_PARSING_ELEMENT, start, Name() );
                         return 0;
                 }
                 // attribute.
                 if ( XMLUtil::IsAlpha( *p ) ) {
                         XMLAttribute* attrib = new (document->attributePool.Alloc() ) XMLAttribute();
                         attrib->memPool = &document->attributePool;
                         p = attrib->ParseDeep( p, document->ProcessEntities() );
                         if ( !p || Attribute( attrib->Name() ) ) {
                                 DELETE_ATTRIBUTE( attrib );
                                 document->SetError( XML_ERROR_PARSING_ATTRIBUTE, start, p );
                                 return 0;
                         }
                         // There is a minor bug here: if the attribute in the source xml
                         // document is duplicated, it will not be detected and the
                         // attribute will be doubly added. However, tracking the 'prevAttribute'
                         // avoids re-scanning the attribute list. Preferring performance for
                         // now, may reconsider in the future.
                         if ( prevAttribute ) {
                                 prevAttribute->next = attrib;
                         }
                         else {
                                 rootAttribute = attrib;
                         }
                         prevAttribute = attrib;
                 }
                 // end of the tag
                 else if ( *p == '/' && *(p+1) == '>' ) {
                         closingType = CLOSED;
                         return p+2;     // done; sealed element.
                 }
                 // end of the tag
                 else if ( *p == '>' ) {
                         ++p;
                         break;
                 }
                 else {
                         document->SetError( XML_ERROR_PARSING_ELEMENT, start, p );
                         return 0;
                 }
         }
         return p;
 }
char * XMLElement::ParseDeep (char * p, StrPair * endTag) inline virtual
Reimplemented from tinyxml2::XMLNode.
Definition at line 1462 of file tinyxml2_imp.h.
References CLOSING, closingType, tinyxml2::StrPair::Empty(), ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::StrPair::ParseName(), tinyxml2::XMLUtil::SkipWhiteSpace(), and tinyxml2::XMLNode::value.
 {
         // Read the element name.
         p = XMLUtil::SkipWhiteSpace( p );
         if ( !p ) return 0;
         // The closing element is the </element> form. It is
         // parsed just like a regular element then deleted from
         // the DOM.
         if ( *p == '/' ) {
                 closingType = CLOSING;
                 ++p;
         }
         p = value.ParseName( p );
         if ( value.Empty() ) return 0;
         p = ParseAttributes( p );
         if ( !p || !*p || closingType )
                 return p;
         p = XMLNode::ParseDeep( p, strPair );
         return p;
 }
const XMLNode* tinyxml2::XMLNode::PreviousSibling () const inline inherited
Get the previous (left) sibling node of this node.
Definition at line 515 of file tinyxml2.h.
References tinyxml2::XMLNode::prev.
Referenced by tinyxml2::XMLHandle::PreviousSibling(), and tinyxml2::XMLConstHandle::PreviousSibling().
 { return prev; }
XMLNode* tinyxml2::XMLNode::PreviousSibling () inline inherited
Definition at line 516 of file tinyxml2.h.
References tinyxml2::XMLNode::prev.
 { return prev; }
const XMLElement * XMLNode::PreviousSiblingElement (const char * value = 0) const inline inherited
Get the previous (left) sibling element of this node, with an opitionally supplied name.
Definition at line 784 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::prev, tinyxml2::XMLUtil::StringEqual(), and ToElement().
Referenced by tinyxml2::XMLHandle::PreviousSiblingElement(), and tinyxml2::XMLConstHandle::PreviousSiblingElement().
 {
         for( XMLNode* element=this->prev; element; element = element->prev ) {
                 if (    element->ToElement()
                          && (!value || XMLUtil::StringEqual( value, element->Value() )))
                 {
                         return element->ToElement();
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::PreviousSiblingElement (const char * _value = 0) inline inherited
Definition at line 520 of file tinyxml2.h.
References tinyxml2::XMLNode::PreviousSiblingElement().
Referenced by tinyxml2::XMLNode::PreviousSiblingElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->PreviousSiblingElement( _value ) ); }
int tinyxml2::XMLElement::QueryBoolAttribute (const char * name, bool * _value) const inline
See QueryIntAttribute()
Definition at line 926 of file tinyxml2.h.
References FindAttribute(), tinyxml2::XMLAttribute::QueryBoolValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by BoolAttribute().
 { const XMLAttribute* a = FindAttribute( name ); if ( !a ) return XML_NO_ATTRIBUTE; return a->QueryBoolValue( _value ); }
int XMLElement::QueryBoolText (bool * _value) const inline
See QueryIntText()
Definition at line 1310 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLUtil::ToBool(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
 {
         if ( FirstChild() && FirstChild()->ToText() ) {
                 const char* t = FirstChild()->ToText()->Value();
                 if ( XMLUtil::ToBool( t, _value ) ) {
                         return XML_SUCCESS;
                 }
                 return XML_CAN_NOT_CONVERT_TEXT;
         }
         return XML_NO_TEXT_NODE;
 }
int tinyxml2::XMLElement::QueryDoubleAttribute (const char * name, double * _value) const inline
See QueryIntAttribute()
Definition at line 928 of file tinyxml2.h.
References FindAttribute(), tinyxml2::XMLAttribute::QueryDoubleValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by DoubleAttribute().
 { const XMLAttribute* a = FindAttribute( name ); if ( !a ) return XML_NO_ATTRIBUTE; return a->QueryDoubleValue( _value ); }
int XMLElement::QueryDoubleText (double * _value) const inline
See QueryIntText()
Definition at line 1324 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLUtil::ToDouble(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
 {
         if ( FirstChild() && FirstChild()->ToText() ) {
                 const char* t = FirstChild()->ToText()->Value();
                 if ( XMLUtil::ToDouble( t, _value ) ) {
                         return XML_SUCCESS;
                 }
                 return XML_CAN_NOT_CONVERT_TEXT;
         }
         return XML_NO_TEXT_NODE;
 }
int tinyxml2::XMLElement::QueryFloatAttribute (const char * name, float * _value) const inline
See QueryIntAttribute()
Definition at line 930 of file tinyxml2.h.
References FindAttribute(), tinyxml2::XMLAttribute::QueryFloatValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by FloatAttribute().
 { const XMLAttribute* a = FindAttribute( name ); if ( !a ) return XML_NO_ATTRIBUTE; return a->QueryFloatValue( _value ); }
int XMLElement::QueryFloatText (float * _value) const inline
See QueryIntText()
Definition at line 1338 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLUtil::ToFloat(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
 {
         if ( FirstChild() && FirstChild()->ToText() ) {
                 const char* t = FirstChild()->ToText()->Value();
                 if ( XMLUtil::ToFloat( t, _value ) ) {
                         return XML_SUCCESS;
                 }
                 return XML_CAN_NOT_CONVERT_TEXT;
         }
         return XML_NO_TEXT_NODE;
 }
int tinyxml2::XMLElement::QueryIntAttribute (const char * name, int * _value) const inline
Given an attribute name, QueryIntAttribute() returns XML_NO_ERROR, XML_WRONG_ATTRIBUTE_TYPE if the conversion can't be performed, or XML_NO_ATTRIBUTE if the attribute doesn't exist. If successful, the result of the conversion will be written to 'value'. If not successful, nothing will be written to 'value'. This allows you to provide default value:
    int value = 10;
    QueryIntAttribute( "foo", &value );         // if "foo" isn't found, value will still be 10
Definition at line 922 of file tinyxml2.h.
References FindAttribute(), tinyxml2::XMLAttribute::QueryIntValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by IntAttribute().
 { const XMLAttribute* a = FindAttribute( name ); if ( !a ) return XML_NO_ATTRIBUTE; return a->QueryIntValue( _value ); }
int XMLElement::QueryIntText (int * _value) const inline
Convenience method to query the value of a child text node. This is probably best shown by example. Given you have a document is this form:
        <point>
                <x>1</x>
                <y>1.4</y>
        </point>
The QueryIntText() and similar functions provide a safe and easier way to get to the "value" of x and y.
        int x = 0;
        float y = 0;    // types of x and y are contrived for example
        const XMLElement* xElement = pointElement->FirstChildElement( "x" );
        const XMLElement* yElement = pointElement->FirstChildElement( "y" );
        xElement->QueryIntText( &x );
        yElement->QueryFloatText( &y );
Returns
XML_SUCCESS (0) on success, XML_CAN_NOT_CONVERT_TEXT if the text cannot be converted to the requested type, and XML_NO_TEXT_NODE if there is no child text to query.
Definition at line 1282 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLUtil::ToInt(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
 {
         if ( FirstChild() && FirstChild()->ToText() ) {
                 const char* t = FirstChild()->ToText()->Value();
                 if ( XMLUtil::ToInt( t, _value ) ) {
                         return XML_SUCCESS;
                 }
                 return XML_CAN_NOT_CONVERT_TEXT;
         }
         return XML_NO_TEXT_NODE;
 }
int tinyxml2::XMLElement::QueryUnsignedAttribute (const char * name, unsigned int * _value) const inline
See QueryIntAttribute()
Definition at line 924 of file tinyxml2.h.
References FindAttribute(), tinyxml2::XMLAttribute::QueryUnsignedValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by UnsignedAttribute().
 { const XMLAttribute* a = FindAttribute( name ); if ( !a ) return XML_NO_ATTRIBUTE; return a->QueryUnsignedValue( _value ); }
int XMLElement::QueryUnsignedText (unsigned * _value) const inline
See QueryIntText()
Definition at line 1296 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLUtil::ToUnsigned(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
 {
         if ( FirstChild() && FirstChild()->ToText() ) {
                 const char* t = FirstChild()->ToText()->Value();
                 if ( XMLUtil::ToUnsigned( t, _value ) ) {
                         return XML_SUCCESS;
                 }
                 return XML_CAN_NOT_CONVERT_TEXT;
         }
         return XML_NO_TEXT_NODE;
 }
void tinyxml2::XMLElement::SetAttribute (const char * name, const char * _value) inline
Sets the named attribute to value.
Definition at line 933 of file tinyxml2.h.
References FindOrCreateAttribute(), and tinyxml2::XMLAttribute::SetAttribute().
Referenced by ShallowClone().
 { XMLAttribute* a = FindOrCreateAttribute( name ); a->SetAttribute( _value ); }
void tinyxml2::XMLElement::SetAttribute (const char * name, int _value) inline
Sets the named attribute to value.
Definition at line 935 of file tinyxml2.h.
References FindOrCreateAttribute(), and tinyxml2::XMLAttribute::SetAttribute().
 { XMLAttribute* a = FindOrCreateAttribute( name ); a->SetAttribute( _value ); }
void tinyxml2::XMLElement::SetAttribute (const char * name, unsigned _value) inline
Sets the named attribute to value.
Definition at line 937 of file tinyxml2.h.
References FindOrCreateAttribute(), and tinyxml2::XMLAttribute::SetAttribute().
 { XMLAttribute* a = FindOrCreateAttribute( name ); a->SetAttribute( _value ); }
void tinyxml2::XMLElement::SetAttribute (const char * name, bool _value) inline
Sets the named attribute to value.
Definition at line 939 of file tinyxml2.h.
References FindOrCreateAttribute(), and tinyxml2::XMLAttribute::SetAttribute().
 { XMLAttribute* a = FindOrCreateAttribute( name ); a->SetAttribute( _value ); }
void tinyxml2::XMLElement::SetAttribute (const char * name, double _value) inline
Sets the named attribute to value.
Definition at line 941 of file tinyxml2.h.
References FindOrCreateAttribute(), and tinyxml2::XMLAttribute::SetAttribute().
 { XMLAttribute* a = FindOrCreateAttribute( name ); a->SetAttribute( _value ); }
void tinyxml2::XMLElement::SetName (const char * str, bool staticMem = false) inline
Set the name of the element.
Definition at line 863 of file tinyxml2.h.
References tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLDocument::NewElement().
 { SetValue( str, staticMem ); }
void XMLNode::SetValue (const char * val, bool staticMem = false) inline inherited
Set the Value of an XML node.
See also
Value()
Definition at line 619 of file tinyxml2_imp.h.
References tinyxml2::StrPair::SetInternedStr(), tinyxml2::StrPair::SetStr(), and tinyxml2::XMLNode::value.
Referenced by tinyxml2::XMLDocument::NewComment(), tinyxml2::XMLDocument::NewDeclaration(), tinyxml2::XMLDocument::NewText(), tinyxml2::XMLDocument::NewUnknown(), and SetName().
 {
         if ( staticMem )
                 value.SetInternedStr( str );
         else
                 value.SetStr( str );
 }
XMLNode * XMLElement::ShallowClone (XMLDocument * document) const inline virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode.
Definition at line 1490 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::document, FirstAttribute(), tinyxml2::XMLDocument::NewElement(), tinyxml2::XMLAttribute::Next(), SetAttribute(), and tinyxml2::XMLNode::Value().
 {
         if ( !doc ) {
                 doc = document;
         }
         XMLElement* element = doc->NewElement( Value() );                                       // fixme: this will always allocate memory. Intern?
         for( const XMLAttribute* a=FirstAttribute(); a; a=a->Next() ) {
                 element->SetAttribute( a->Name(), a->Value() );                                 // fixme: this will always allocate memory. Intern?
         }
         return element;
 }
bool XMLElement::ShallowEqual (const XMLNode * compare) const inline virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode.
Definition at line 1504 of file tinyxml2_imp.h.
References FirstAttribute(), tinyxml2::XMLAttribute::Next(), tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLNode::ToElement(), tinyxml2::XMLNode::Value(), and tinyxml2::XMLAttribute::Value().
 {
         const XMLElement* other = compare->ToElement();
         if ( other && XMLUtil::StringEqual( other->Value(), Value() )) {
                 const XMLAttribute* a=FirstAttribute();
                 const XMLAttribute* b=other->FirstAttribute();
                 while ( a && b ) {
                         if ( !XMLUtil::StringEqual( a->Value(), b->Value() ) ) {
                                 return false;
                         }
                         a = a->Next();
                         b = b->Next();
                 }
                 if ( a || b ) {
                         // different count
                         return false;
                 }
                 return true;
         }
         return false;
 }
virtual XMLComment* tinyxml2::XMLNode::ToComment () inline virtual inherited
Safely cast to a Comment, or null.
Reimplemented in tinyxml2::XMLComment.
Definition at line 461 of file tinyxml2.h.
Referenced by tinyxml2::XMLComment::ShallowEqual().
virtual const XMLComment* tinyxml2::XMLNode::ToComment () const inline virtual inherited
Reimplemented in tinyxml2::XMLComment.
Definition at line 468 of file tinyxml2.h.
 { return 0; }
virtual XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () inline virtual inherited
Safely cast to a Declaration, or null.
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 463 of file tinyxml2.h.
Referenced by tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLHandle::ToDeclaration(), and tinyxml2::XMLConstHandle::ToDeclaration().
virtual const XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () const inline virtual inherited
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 470 of file tinyxml2.h.
 { return 0; }
virtual XMLDocument* tinyxml2::XMLNode::ToDocument () inline virtual inherited
Safely cast to a Document, or null.
Reimplemented in tinyxml2::XMLDocument.
Definition at line 462 of file tinyxml2.h.
virtual const XMLDocument* tinyxml2::XMLNode::ToDocument () const inline virtual inherited
Reimplemented in tinyxml2::XMLDocument.
Definition at line 469 of file tinyxml2.h.
 { return 0; }
virtual XMLElement* tinyxml2::XMLElement::ToElement () inline virtual
Safely cast to an Element, or null.
Reimplemented from tinyxml2::XMLNode.
Definition at line 865 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLNode::NextSiblingElement(), and tinyxml2::XMLNode::PreviousSiblingElement().
 { return this; }
virtual const XMLElement* tinyxml2::XMLElement::ToElement () const inline virtual
Reimplemented from tinyxml2::XMLNode.
Definition at line 866 of file tinyxml2.h.
 { return this; }
virtual XMLText* tinyxml2::XMLNode::ToText () inline virtual inherited
Safely cast to Text, or null.
Reimplemented in tinyxml2::XMLText.
Definition at line 460 of file tinyxml2.h.
Referenced by GetText(), QueryBoolText(), QueryDoubleText(), QueryFloatText(), QueryIntText(), QueryUnsignedText(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLHandle::ToText(), and tinyxml2::XMLConstHandle::ToText().
virtual const XMLText* tinyxml2::XMLNode::ToText () const inline virtual inherited
Reimplemented in tinyxml2::XMLText.
Definition at line 467 of file tinyxml2.h.
 { return 0; }
virtual XMLUnknown* tinyxml2::XMLNode::ToUnknown () inline virtual inherited
Safely cast to an Unknown, or null.
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 464 of file tinyxml2.h.
Referenced by tinyxml2::XMLUnknown::ShallowEqual(), tinyxml2::XMLHandle::ToUnknown(), and tinyxml2::XMLConstHandle::ToUnknown().
virtual const XMLUnknown* tinyxml2::XMLNode::ToUnknown () const inline virtual inherited
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 471 of file tinyxml2.h.
 { return 0; }
unsigned tinyxml2::XMLElement::UnsignedAttribute (const char * name) const inline
See IntAttribute()
Definition at line 901 of file tinyxml2.h.
References QueryUnsignedAttribute().
 { unsigned i=0; QueryUnsignedAttribute( name, &i ); return i; }
const char* tinyxml2::XMLNode::Value () const inline inherited
The meaning of 'value' changes for the specific type.
    Document:   empty
    Element:    name of the element
    Comment:    the comment text
    Unknown:    the tag contents
    Text:               the text string
Definition at line 482 of file tinyxml2.h.
References tinyxml2::StrPair::GetStr(), and tinyxml2::XMLNode::value.
Referenced by GetText(), Name(), tinyxml2::XMLNode::ParseDeep(), QueryBoolText(), QueryDoubleText(), QueryFloatText(), QueryIntText(), QueryUnsignedText(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), ShallowClone(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLComment::ShallowEqual(), tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLUnknown::ShallowEqual(), ShallowEqual(), and tinyxml2::XMLPrinter::Visit().
 { return value.GetStr(); }
Friends And Related Function Documentation
friend class XMLBase friend
Definition at line 857 of file tinyxml2.h.
friend class XMLDocument friend
Definition at line 858 of file tinyxml2.h.
Member Data Documentation
int tinyxml2::XMLElement::closingType private
Definition at line 1041 of file tinyxml2.h.
Referenced by ClosingType(), ParseAttributes(), and ParseDeep().
XMLDocument* tinyxml2::XMLNode::document protected inherited
Definition at line 607 of file tinyxml2.h.
Referenced by FindOrCreateAttribute(), tinyxml2::XMLNode::GetDocument(), ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), ShallowClone(), and tinyxml2::XMLDocument::XMLDocument().
XMLNode* tinyxml2::XMLNode::firstChild protected inherited
Definition at line 611 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChildren(), tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::NoChildren(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::lastChild protected inherited
Definition at line 612 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChildren(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::LastChild(), tinyxml2::XMLNode::LastChildElement(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::next protected inherited
Definition at line 615 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::NextSibling(), tinyxml2::XMLNode::NextSiblingElement(), tinyxml2::XMLNode::Unlink(), and ~XMLElement().
XMLNode* tinyxml2::XMLNode::parent protected inherited
Definition at line 608 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChild(), tinyxml2::XMLDocument::DeleteNode(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::Parent(), tinyxml2::XMLNode::Unlink(), and tinyxml2::XMLNode::~XMLNode().
XMLNode* tinyxml2::XMLNode::prev protected inherited
Definition at line 614 of file tinyxml2.h.
Referenced by DeleteAttribute(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLNode::PreviousSibling(), tinyxml2::XMLNode::PreviousSiblingElement(), and tinyxml2::XMLNode::Unlink().
XMLAttribute* tinyxml2::XMLElement::rootAttribute private
Definition at line 1045 of file tinyxml2.h.
Referenced by Accept(), DeleteAttribute(), FindAttribute(), FindOrCreateAttribute(), FirstAttribute(), ParseAttributes(), and ~XMLElement().
StrPair tinyxml2::XMLNode::value mutable protected inherited
Definition at line 609 of file tinyxml2.h.
Referenced by Attribute(), tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), ParseDeep(), tinyxml2::XMLNode::SetValue(), and tinyxml2::XMLNode::Value().
The documentation for this class was generated from the following files:
src/parsing/include/antioch/tinyxml2.h
src/parsing/include/antioch/tinyxml2_imp.h