antioch-0.4.0: tinyxml2::XMLUnknown Class Reference
tinyxml2::XMLUnknown Class Reference
#include <tinyxml2.h>
Public Member Functions
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLUnknown * ToUnknown () const
virtual bool Accept (XMLVisitor *visitor) const
char * ParseDeep (char *, StrPair *endTag)
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual const XMLElement * ToElement () const
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual const XMLText * ToText () const
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual const XMLComment * ToComment () const
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual const XMLDocument * ToDocument () const
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual const XMLDeclaration * ToDeclaration () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *value=0) const
XMLElement * FirstChildElement (const char *_value=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *value=0) const
XMLElement * LastChildElement (const char *_value=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *value=0) const
Get the previous (left) sibling element of this node, with an opitionally supplied name.
XMLElement * PreviousSiblingElement (const char *_value=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *value=0) const
Get the next (right) sibling element of this node, with an opitionally supplied name.
XMLElement * NextSiblingElement (const char *_value=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
Protected Member Functions
XMLUnknown (XMLDocument *doc)
virtual ~XMLUnknown ()
XMLUnknown (const XMLUnknown &)
XMLUnknown & operator= (const XMLUnknown &)
Protected Attributes
XMLDocument * document
XMLNode * parent
StrPair value
XMLNode * firstChild
XMLNode * lastChild
XMLNode * prev
XMLNode * next
Friends
class XMLDocument
Detailed Description
Any tag that tinyXml doesn't recognize is saved as an unknown. It is a tag of text, but should not be modified. It will be written back to the XML, unchanged, when the file is saved.
DTD tags get thrown into TiXmlUnknowns.
Definition at line 729 of file tinyxml2.h.
Constructor & Destructor Documentation
XMLUnknown::XMLUnknown (XMLDocument * doc) inline protected
Definition at line 1039 of file tinyxml2_imp.h.
                                          : XMLNode( doc )
 {
 }
XMLUnknown::~XMLUnknown () inline protected virtual
Definition at line 1045 of file tinyxml2_imp.h.
 {
 }
tinyxml2::XMLUnknown::XMLUnknown (const XMLUnknown &) protected
Member Function Documentation
bool XMLUnknown::Accept (XMLVisitor * visitor) const inline virtual
Accept a hierarchical visit of the nodes in the TinyXML DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the TiXmlVisitor interface.
This is essentially a SAX interface for TinyXML. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
    TiXmlPrinter printer;
    tinyxmlDoc.Accept( &printer );
    const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode.
Definition at line 1083 of file tinyxml2_imp.h.
References tinyxml2::XMLVisitor::Visit().
 {
         return visitor->Visit( *this );
 }
void XMLNode::DeleteChild (XMLNode * node) inline inherited
Delete a child of this node.
Definition at line 661 of file tinyxml2_imp.h.
References DELETE_NODE, tinyxml2::XMLNode::parent, and TIXMLASSERT.
Referenced by tinyxml2::XMLDocument::DeleteNode().
 {
         TIXMLASSERT( node->parent == this );
         DELETE_NODE( node );
 }
void XMLNode::DeleteChildren () inline inherited
Delete all the children of this node.
Definition at line 629 of file tinyxml2_imp.h.
References DELETE_NODE, tinyxml2::XMLNode::firstChild, tinyxml2::XMLNode::lastChild, and tinyxml2::XMLNode::Unlink().
Referenced by tinyxml2::XMLDocument::LoadFile(), tinyxml2::XMLDocument::Parse(), tinyxml2::XMLDocument::~XMLDocument(), and tinyxml2::XMLNode::~XMLNode().
 {
         while( firstChild ) {
                 XMLNode* node = firstChild;
                 Unlink( node );
                 DELETE_NODE( node );
         }
         firstChild = lastChild = 0;
 }
const XMLNode* tinyxml2::XMLNode::FirstChild () const inline inherited
Get the first child node, or null if none exists.
Definition at line 496 of file tinyxml2.h.
References tinyxml2::XMLNode::firstChild.
Referenced by tinyxml2::XMLElement::Accept(), tinyxml2::XMLDocument::Accept(), tinyxml2::XMLHandle::FirstChild(), tinyxml2::XMLConstHandle::FirstChild(), tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), and tinyxml2::XMLElement::QueryUnsignedText().
 { return firstChild; }
XMLNode* tinyxml2::XMLNode::FirstChild () inline inherited
Definition at line 497 of file tinyxml2.h.
References tinyxml2::XMLNode::firstChild.
 { return firstChild; }
const XMLElement * XMLNode::FirstChildElement (const char * value = 0) const inline inherited
Get the first child element, or optionally the first child element with the specified name.
Definition at line 740 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::firstChild, tinyxml2::XMLElement::Name(), tinyxml2::XMLNode::next, tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLElement::ToElement(), and tinyxml2::XMLNode::value.
Referenced by Antioch::XMLParser< NumericType >::efficiencies(), tinyxml2::XMLHandle::FirstChildElement(), tinyxml2::XMLConstHandle::FirstChildElement(), Antioch::XMLParser< NumericType >::get_parameter(), Antioch::XMLParser< NumericType >::products_orders(), Antioch::XMLParser< NumericType >::products_pairs(), Antioch::XMLParser< NumericType >::reactants_orders(), Antioch::XMLParser< NumericType >::reactants_pairs(), Antioch::XMLParser< NumericType >::reaction_kinetics_model(), Antioch::XMLParser< NumericType >::read_thermodynamic_data_root(), tinyxml2::XMLDocument::RootElement(), Antioch::XMLParser< NumericType >::verify_Kooij_in_place_of_Arrhenius(), and Antioch::XMLParser< NumericType >::where_is_k0().
 {
         for( XMLNode* node=firstChild; node; node=node->next ) {
                 XMLElement* element = node->ToElement();
                 if ( element ) {
                         if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                                 return element;
                         }
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::FirstChildElement (const char * _value = 0) inline inherited
Definition at line 502 of file tinyxml2.h.
References tinyxml2::XMLNode::FirstChildElement().
Referenced by tinyxml2::XMLNode::FirstChildElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->FirstChildElement( _value )); }
const XMLDocument* tinyxml2::XMLNode::GetDocument () const inline inherited
Get the XMLDocument that owns this XMLNode.
Definition at line 455 of file tinyxml2.h.
References tinyxml2::XMLNode::document.
 { return document; }
XMLDocument* tinyxml2::XMLNode::GetDocument () inline inherited
Get the XMLDocument that owns this XMLNode.
Definition at line 457 of file tinyxml2.h.
References tinyxml2::XMLNode::document.
 { return document; }
XMLNode * XMLNode::InsertAfterChild (XMLNode * afterThis, XMLNode * addThis) inline inherited
Add a node after the specified child node.
Definition at line 718 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::next, tinyxml2::XMLNode::parent, tinyxml2::XMLNode::prev, and TIXMLASSERT.
 {
         TIXMLASSERT( afterThis->parent == this );
         if ( afterThis->parent != this )
                 return 0;
         if ( afterThis->next == 0 ) {
                 // The last node or the only node.
                 return InsertEndChild( addThis );
         }
         addThis->prev = afterThis;
         addThis->next = afterThis->next;
         afterThis->next->prev = addThis;
         afterThis->next = addThis;
         addThis->parent = this;
         return addThis;
 }
XMLNode * XMLNode::InsertEndChild (XMLNode * addThis) inline inherited
Add a child node as the last (right) child.
Definition at line 669 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::firstChild, tinyxml2::XMLNode::lastChild, tinyxml2::XMLNode::next, tinyxml2::XMLNode::parent, tinyxml2::XMLNode::prev, and TIXMLASSERT.
Referenced by tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::LinkEndChild(), and tinyxml2::XMLNode::ParseDeep().
 {
         if ( lastChild ) {
                 TIXMLASSERT( firstChild );
                 TIXMLASSERT( lastChild->next == 0 );
                 lastChild->next = addThis;
                 addThis->prev = lastChild;
                 lastChild = addThis;
                 addThis->next = 0;
         }
         else {
                 TIXMLASSERT( firstChild == 0 );
                 firstChild = lastChild = addThis;
                 addThis->prev = 0;
                 addThis->next = 0;
         }
         addThis->parent = this;
         return addThis;
 }
XMLNode * XMLNode::InsertFirstChild (XMLNode * addThis) inline inherited
Add a child node as the first (left) child.
Definition at line 693 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::firstChild, tinyxml2::XMLNode::lastChild, tinyxml2::XMLNode::next, tinyxml2::XMLNode::parent, tinyxml2::XMLNode::prev, and TIXMLASSERT.
 {
         if ( firstChild ) {
                 TIXMLASSERT( lastChild );
                 TIXMLASSERT( firstChild->prev == 0 );
                 firstChild->prev = addThis;
                 addThis->next = firstChild;
                 firstChild = addThis;
                 addThis->prev = 0;
         }
         else {
                 TIXMLASSERT( lastChild == 0 );
                 firstChild = lastChild = addThis;
                 addThis->prev = 0;
                 addThis->next = 0;
         }
         addThis->parent = this;
         return addThis;
 }
const XMLNode* tinyxml2::XMLNode::LastChild () const inline inherited
Get the last child node, or null if none exists.
Definition at line 505 of file tinyxml2.h.
References tinyxml2::XMLNode::lastChild.
Referenced by tinyxml2::XMLHandle::LastChild(), and tinyxml2::XMLConstHandle::LastChild().
 { return lastChild; }
XMLNode* tinyxml2::XMLNode::LastChild () inline inherited
Definition at line 506 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChild().
Referenced by tinyxml2::XMLNode::LastChild().
 { return const_cast<XMLNode*>(const_cast<const XMLNode*>(this)->LastChild() ); }
const XMLElement * XMLNode::LastChildElement (const char * value = 0) const inline inherited
Get the last child element or optionally the last child element with the specified name.
Definition at line 755 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::lastChild, tinyxml2::XMLElement::Name(), tinyxml2::XMLNode::prev, tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLElement::ToElement(), and tinyxml2::XMLNode::value.
Referenced by tinyxml2::XMLHandle::LastChildElement(), and tinyxml2::XMLConstHandle::LastChildElement().
 {
         for( XMLNode* node=lastChild; node; node=node->prev ) {
                 XMLElement* element = node->ToElement();
                 if ( element ) {
                         if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                                 return element;
                         }
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::LastChildElement (const char * _value = 0) inline inherited
Definition at line 512 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChildElement().
Referenced by tinyxml2::XMLNode::LastChildElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->LastChildElement(_value) ); }
XMLNode* tinyxml2::XMLNode::LinkEndChild (XMLNode * addThis) inline inherited
Definition at line 535 of file tinyxml2.h.
References tinyxml2::XMLNode::InsertEndChild().
 { return InsertEndChild( addThis ); }
const XMLNode* tinyxml2::XMLNode::NextSibling () const inline inherited
Get the next (right) sibling node of this node.
Definition at line 523 of file tinyxml2.h.
References tinyxml2::XMLNode::next.
Referenced by tinyxml2::XMLElement::Accept(), tinyxml2::XMLDocument::Accept(), tinyxml2::XMLHandle::NextSibling(), and tinyxml2::XMLConstHandle::NextSibling().
 { return next; }
XMLNode* tinyxml2::XMLNode::NextSibling () inline inherited
Definition at line 524 of file tinyxml2.h.
References tinyxml2::XMLNode::next.
 { return next; }
const XMLElement * XMLNode::NextSiblingElement (const char * value = 0) const inline inherited
Get the next (right) sibling element of this node, with an opitionally supplied name.
Definition at line 770 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::next, tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by Antioch::XMLParser< NumericType >::find_element_with_attribute(), tinyxml2::XMLHandle::NextSiblingElement(), tinyxml2::XMLConstHandle::NextSiblingElement(), Antioch::XMLParser< NumericType >::read_thermodynamic_data_root(), and Antioch::XMLParser< NumericType >::where_is_k0().
 {
         for( XMLNode* element=this->next; element; element = element->next ) {
                 if (    element->ToElement()
                          && (!value || XMLUtil::StringEqual( value, element->Value() )))
                 {
                         return element->ToElement();
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::NextSiblingElement (const char * _value = 0) inline inherited
Definition at line 528 of file tinyxml2.h.
References tinyxml2::XMLNode::NextSiblingElement().
Referenced by tinyxml2::XMLNode::NextSiblingElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->NextSiblingElement( _value ) ); }
bool tinyxml2::XMLNode::NoChildren () const inline inherited
Returns true if this node has no children.
Definition at line 493 of file tinyxml2.h.
References tinyxml2::XMLNode::firstChild.
 { return !firstChild; }
XMLUnknown& tinyxml2::XMLUnknown::operator= (const XMLUnknown &) protected
const XMLNode* tinyxml2::XMLNode::Parent () const inline inherited
Get the parent of this node on the DOM.
Definition at line 489 of file tinyxml2.h.
References tinyxml2::XMLNode::parent.
 { return parent; }
XMLNode* tinyxml2::XMLNode::Parent () inline inherited
Definition at line 490 of file tinyxml2.h.
References tinyxml2::XMLNode::parent.
 { return parent; }
char * XMLUnknown::ParseDeep (char * p, StrPair * endTag) inline virtual
Reimplemented from tinyxml2::XMLNode.
Definition at line 1051 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::document, tinyxml2::StrPair::NEEDS_NEWLINE_NORMALIZATION, tinyxml2::StrPair::ParseText(), tinyxml2::XMLDocument::SetError(), tinyxml2::XMLNode::value, and tinyxml2::XML_ERROR_PARSING_UNKNOWN.
 {
         // Unknown parses as text.
         const char* start = p;
         p = value.ParseText( p, ">", StrPair::NEEDS_NEWLINE_NORMALIZATION );
         if ( !p ) {
                 document->SetError( XML_ERROR_PARSING_UNKNOWN, start, 0 );
         }
         return p;
 }
const XMLNode* tinyxml2::XMLNode::PreviousSibling () const inline inherited
Get the previous (left) sibling node of this node.
Definition at line 515 of file tinyxml2.h.
References tinyxml2::XMLNode::prev.
Referenced by tinyxml2::XMLHandle::PreviousSibling(), and tinyxml2::XMLConstHandle::PreviousSibling().
 { return prev; }
XMLNode* tinyxml2::XMLNode::PreviousSibling () inline inherited
Definition at line 516 of file tinyxml2.h.
References tinyxml2::XMLNode::prev.
 { return prev; }
const XMLElement * XMLNode::PreviousSiblingElement (const char * value = 0) const inline inherited
Get the previous (left) sibling element of this node, with an opitionally supplied name.
Definition at line 784 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::prev, tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLHandle::PreviousSiblingElement(), and tinyxml2::XMLConstHandle::PreviousSiblingElement().
 {
         for( XMLNode* element=this->prev; element; element = element->prev ) {
                 if (    element->ToElement()
                          && (!value || XMLUtil::StringEqual( value, element->Value() )))
                 {
                         return element->ToElement();
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::PreviousSiblingElement (const char * _value = 0) inline inherited
Definition at line 520 of file tinyxml2.h.
References tinyxml2::XMLNode::PreviousSiblingElement().
Referenced by tinyxml2::XMLNode::PreviousSiblingElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->PreviousSiblingElement( _value ) ); }
void XMLNode::SetValue (const char * val, bool staticMem = false) inline inherited
Set the Value of an XML node.
See also
Value()
Definition at line 619 of file tinyxml2_imp.h.
References tinyxml2::StrPair::SetInternedStr(), tinyxml2::StrPair::SetStr(), and tinyxml2::XMLNode::value.
Referenced by tinyxml2::XMLDocument::NewComment(), tinyxml2::XMLDocument::NewDeclaration(), tinyxml2::XMLDocument::NewText(), tinyxml2::XMLDocument::NewUnknown(), and tinyxml2::XMLElement::SetName().
 {
         if ( staticMem )
                 value.SetInternedStr( str );
         else
                 value.SetStr( str );
 }
XMLNode * XMLUnknown::ShallowClone (XMLDocument * document) const inline virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode.
Definition at line 1065 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::document, tinyxml2::XMLDocument::NewUnknown(), and tinyxml2::XMLNode::Value().
 {
         if ( !doc ) {
                 doc = document;
         }
         XMLUnknown* text = doc->NewUnknown( Value() );  // fixme: this will always allocate memory. Intern?
         return text;
 }
bool XMLUnknown::ShallowEqual (const XMLNode * compare) const inline virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode.
Definition at line 1076 of file tinyxml2_imp.h.
References tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLNode::ToUnknown(), and tinyxml2::XMLNode::Value().
 {
         return ( compare->ToUnknown() && XMLUtil::StringEqual( compare->ToUnknown()->Value(), Value() ));
 }
virtual XMLComment* tinyxml2::XMLNode::ToComment () inline virtual inherited
Safely cast to a Comment, or null.
Reimplemented in tinyxml2::XMLComment.
Definition at line 461 of file tinyxml2.h.
Referenced by tinyxml2::XMLComment::ShallowEqual().
virtual const XMLComment* tinyxml2::XMLNode::ToComment () const inline virtual inherited
Reimplemented in tinyxml2::XMLComment.
Definition at line 468 of file tinyxml2.h.
 { return 0; }
virtual XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () inline virtual inherited
Safely cast to a Declaration, or null.
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 463 of file tinyxml2.h.
Referenced by tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLHandle::ToDeclaration(), and tinyxml2::XMLConstHandle::ToDeclaration().
virtual const XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () const inline virtual inherited
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 470 of file tinyxml2.h.
 { return 0; }
virtual XMLDocument* tinyxml2::XMLNode::ToDocument () inline virtual inherited
Safely cast to a Document, or null.
Reimplemented in tinyxml2::XMLDocument.
Definition at line 462 of file tinyxml2.h.
virtual const XMLDocument* tinyxml2::XMLNode::ToDocument () const inline virtual inherited
Reimplemented in tinyxml2::XMLDocument.
Definition at line 469 of file tinyxml2.h.
 { return 0; }
virtual XMLElement* tinyxml2::XMLNode::ToElement () inline virtual inherited
Safely cast to an Element, or null.
Reimplemented in tinyxml2::XMLElement.
Definition at line 459 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLElement::ShallowEqual(), tinyxml2::XMLHandle::ToElement(), and tinyxml2::XMLConstHandle::ToElement().
virtual const XMLElement* tinyxml2::XMLNode::ToElement () const inline virtual inherited
Reimplemented in tinyxml2::XMLElement.
Definition at line 466 of file tinyxml2.h.
 { return 0; }
virtual XMLText* tinyxml2::XMLNode::ToText () inline virtual inherited
Safely cast to Text, or null.
Reimplemented in tinyxml2::XMLText.
Definition at line 460 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLHandle::ToText(), and tinyxml2::XMLConstHandle::ToText().
virtual const XMLText* tinyxml2::XMLNode::ToText () const inline virtual inherited
Reimplemented in tinyxml2::XMLText.
Definition at line 467 of file tinyxml2.h.
 { return 0; }
virtual XMLUnknown* tinyxml2::XMLUnknown::ToUnknown () inline virtual
Safely cast to an Unknown, or null.
Reimplemented from tinyxml2::XMLNode.
Definition at line 733 of file tinyxml2.h.
 { return this; }
virtual const XMLUnknown* tinyxml2::XMLUnknown::ToUnknown () const inline virtual
Reimplemented from tinyxml2::XMLNode.
Definition at line 734 of file tinyxml2.h.
 { return this; }
const char* tinyxml2::XMLNode::Value () const inline inherited
The meaning of 'value' changes for the specific type.
    Document:   empty
    Element:    name of the element
    Comment:    the comment text
    Unknown:    the tag contents
    Text:               the text string
Definition at line 482 of file tinyxml2.h.
References tinyxml2::StrPair::GetStr(), and tinyxml2::XMLNode::value.
Referenced by tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::Name(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), ShallowClone(), tinyxml2::XMLElement::ShallowClone(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLComment::ShallowEqual(), tinyxml2::XMLDeclaration::ShallowEqual(), ShallowEqual(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::Visit().
 { return value.GetStr(); }
Friends And Related Function Documentation
friend class XMLDocument friend
Definition at line 731 of file tinyxml2.h.
Member Data Documentation
XMLDocument* tinyxml2::XMLNode::document protected inherited
Definition at line 607 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLNode::GetDocument(), tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), ParseDeep(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), ShallowClone(), tinyxml2::XMLElement::ShallowClone(), and tinyxml2::XMLDocument::XMLDocument().
XMLNode* tinyxml2::XMLNode::firstChild protected inherited
Definition at line 611 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChildren(), tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::NoChildren(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::lastChild protected inherited
Definition at line 612 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChildren(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::LastChild(), tinyxml2::XMLNode::LastChildElement(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::next protected inherited
Definition at line 615 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::NextSibling(), tinyxml2::XMLNode::NextSiblingElement(), tinyxml2::XMLNode::Unlink(), and tinyxml2::XMLElement::~XMLElement().
XMLNode* tinyxml2::XMLNode::parent protected inherited
Definition at line 608 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChild(), tinyxml2::XMLDocument::DeleteNode(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::Parent(), tinyxml2::XMLNode::Unlink(), and tinyxml2::XMLNode::~XMLNode().
XMLNode* tinyxml2::XMLNode::prev protected inherited
Definition at line 614 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::DeleteAttribute(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLNode::PreviousSibling(), tinyxml2::XMLNode::PreviousSiblingElement(), and tinyxml2::XMLNode::Unlink().
StrPair tinyxml2::XMLNode::value mutable protected inherited
Definition at line 609 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::Attribute(), tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), ParseDeep(), tinyxml2::XMLElement::ParseDeep(), tinyxml2::XMLNode::SetValue(), and tinyxml2::XMLNode::Value().
The documentation for this class was generated from the following files:
src/parsing/include/antioch/tinyxml2.h
src/parsing/include/antioch/tinyxml2_imp.h