antioch-0.4.0: tinyxml2::XMLUtil Class Reference
tinyxml2::XMLUtil Class Reference
#include <tinyxml2.h>
Static Public Member Functions
static const char * SkipWhiteSpace (const char *p)
static char * SkipWhiteSpace (char *p)
static bool IsWhiteSpace (char p)
static bool StringEqual (const char *p, const char *q, int nChar=INT_MAX)
static int IsUTF8Continuation (const char p)
static int IsAlphaNum (unsigned char anyByte)
static int IsAlpha (unsigned char anyByte)
static const char * ReadBOM (const char *p, bool *hasBOM)
static const char * GetCharacterRef (const char *p, char *value, int *length)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
static void ToStr (int v, char *buffer, int bufferSize)
static void ToStr (unsigned v, char *buffer, int bufferSize)
static void ToStr (bool v, char *buffer, int bufferSize)
static void ToStr (float v, char *buffer, int bufferSize)
static void ToStr (double v, char *buffer, int bufferSize)
static bool ToInt (const char *str, int *value)
static bool ToUnsigned (const char *str, unsigned *value)
static bool ToBool (const char *str, bool *value)
static bool ToFloat (const char *str, float *value)
static bool ToDouble (const char *str, double *value)
Detailed Description
Definition at line 375 of file tinyxml2.h.
Member Function Documentation
void XMLUtil::ConvertUTF32ToUTF8 (unsigned long input, char * output, int * length) inline static
Definition at line 303 of file tinyxml2_imp.h.
Referenced by GetCharacterRef().
 {
         const unsigned long BYTE_MASK = 0xBF;
         const unsigned long BYTE_MARK = 0x80;
         const unsigned long FIRST_BYTE_MARK[7] = { 0x00, 0x00, 0xC0, 0xE0, 0xF0, 0xF8, 0xFC };
         if (input < 0x80)
                 *length = 1;
         else if ( input < 0x800 )
                 *length = 2;
         else if ( input < 0x10000 )
                 *length = 3;
         else if ( input < 0x200000 )
                 *length = 4;
         else
                 { *length = 0; return; }        // This code won't covert this correctly anyway.
         output += *length;
         // Scary scary fall throughs.
         switch (*length)
         {
                 case 4:
                         --output;
                         *output = (char)((input | BYTE_MARK) & BYTE_MASK);
                         input >>= 6;
                 case 3:
                         --output;
                         *output = (char)((input | BYTE_MARK) & BYTE_MASK);
                         input >>= 6;
                 case 2:
                         --output;
                         *output = (char)((input | BYTE_MARK) & BYTE_MASK);
                         input >>= 6;
                 case 1:
                         --output;
                         *output = (char)(input | FIRST_BYTE_MARK[*length]);
         }
 }
const char * XMLUtil::GetCharacterRef (const char * p, char * value, int * length) inline static
Definition at line 345 of file tinyxml2_imp.h.
References ConvertUTF32ToUTF8().
Referenced by tinyxml2::StrPair::GetStr().
 {
         // Presume an entity, and pull it out.
         *length = 0;
         if ( *(p+1) == '#' && *(p+2) )
         {
                 unsigned long ucs = 0;
                 ptrdiff_t delta = 0;
                 unsigned mult = 1;
                 if ( *(p+2) == 'x' )
                 {
                         // Hexadecimal.
                         if ( !*(p+3) ) return 0;
                         const char* q = p+3;
                         q = strchr( q, ';' );
                         if ( !q || !*q ) return 0;
                         delta = q-p;
                         --q;
                         while ( *q != 'x' )
{
                                 if ( *q >= '0' && *q <= '9' )
                                         ucs += mult * (*q - '0');
                                 else if ( *q >= 'a' && *q <= 'f' )
                                         ucs += mult * (*q - 'a' + 10);
                                 else if ( *q >= 'A' && *q <= 'F' )
                                         ucs += mult * (*q - 'A' + 10 );
                                 else
                                         return 0;
                                 mult *= 16;
                                 --q;
                         }
                 }
                 else
                 {
                         // Decimal.
                         if ( !*(p+2) ) return 0;
                         const char* q = p+2;
                         q = strchr( q, ';' );
                         if ( !q || !*q ) return 0;
                         delta = q-p;
                         --q;
                         while ( *q != '#' )
{
                                 if ( *q >= '0' && *q <= '9' )
                                         ucs += mult * (*q - '0');
                                 else
                                         return 0;
                                 mult *= 10;
                                 --q;
                         }
                 }
                 // convert the UCS to UTF-8
                 ConvertUTF32ToUTF8( ucs, value, length );
                 return p + delta + 1;
         }
         return p+1;
 }
static int tinyxml2::XMLUtil::IsAlpha (unsigned char anyByte) inline static
Definition at line 399 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::ParseAttributes().
 { return ( anyByte < 128 ) ? isalpha( anyByte ) : 1; }
static int tinyxml2::XMLUtil::IsAlphaNum (unsigned char anyByte) inline static
Definition at line 398 of file tinyxml2.h.
Referenced by tinyxml2::StrPair::ParseName().
 { return ( anyByte < 128 ) ? isalnum( anyByte ) : 1; }
static int tinyxml2::XMLUtil::IsUTF8Continuation (const char p) inline static
Definition at line 397 of file tinyxml2.h.
Referenced by IsWhiteSpace(), and SkipWhiteSpace().
 { return p & 0x80; }
static bool tinyxml2::XMLUtil::IsWhiteSpace (char p) inline static
Definition at line 382 of file tinyxml2.h.
References IsUTF8Continuation().
Referenced by tinyxml2::StrPair::CollapseWhitespace().
 { return !IsUTF8Continuation(p) && isspace( static_cast<unsigned char>(p) ); }
const char * XMLUtil::ReadBOM (const char * p, bool * hasBOM) inline static
Definition at line 286 of file tinyxml2_imp.h.
Referenced by tinyxml2::XMLDocument::LoadFile(), and tinyxml2::XMLDocument::Parse().
 {
         *bom = false;
         const unsigned char* pu = reinterpret_cast<const unsigned char*>(p);
         // Check for BOM:
         if (    *(pu+0) == TIXML_UTF_LEAD_0
                  && *(pu+1) == TIXML_UTF_LEAD_1
                  && *(pu+2) == TIXML_UTF_LEAD_2 )
         {
                 *bom = true;
                 p += 3;
         }
         return p;
 }
static const char* tinyxml2::XMLUtil::SkipWhiteSpace (const char * p) inline static
Definition at line 380 of file tinyxml2.h.
References IsUTF8Continuation().
Referenced by tinyxml2::StrPair::CollapseWhitespace(), tinyxml2::XMLDocument::Identify(), tinyxml2::XMLDocument::LoadFile(), tinyxml2::XMLDocument::Parse(), tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLAttribute::ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
 { while( !IsUTF8Continuation(*p) && isspace( *reinterpret_cast<const unsigned char*>(p) ) ) { ++p; } return p; }
static char* tinyxml2::XMLUtil::SkipWhiteSpace (char * p) inline static
Definition at line 381 of file tinyxml2.h.
References IsUTF8Continuation().
 { while( !IsUTF8Continuation(*p) && isspace( *reinterpret_cast<unsigned char*>(p) ) )           { ++p; } return p; }
static bool tinyxml2::XMLUtil::StringEqual (const char * p, const char * q, int nChar = INT_MAX) inline static
Definition at line 384 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::Attribute(), tinyxml2::XMLElement::DeleteAttribute(), tinyxml2::XMLElement::FindAttribute(), tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLDocument::Identify(), tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLNode::NextSiblingElement(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLNode::PreviousSiblingElement(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLComment::ShallowEqual(), tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLUnknown::ShallowEqual(), tinyxml2::XMLElement::ShallowEqual(), and ToBool().
{
                 int n = 0;
                 if ( p == q ) {
                         return true;
                 }
                 while( *p && *q && *p == *q && n<nChar ) {
                         ++p; ++q; ++n;
                 }
                 if ( (n == nChar) || ( *p == 0 && *q == 0 ) ) {
                         return true;
                 }
                 return false;
         }
bool XMLUtil::ToBool (const char * str, bool * value) inline static
Definition at line 466 of file tinyxml2_imp.h.
References StringEqual(), and ToInt().
Referenced by tinyxml2::XMLElement::QueryBoolText(), and tinyxml2::XMLAttribute::QueryBoolValue().
 {
         int ival = 0;
         if ( ToInt( str, &ival )) {
                 *value = (ival==0) ? false : true;
                 return true;
         }
         if ( StringEqual( str, "true" ) ) {
                 *value = true;
                 return true;
         }
         else if ( StringEqual( str, "false" ) ) {
                 *value = false;
                 return true;
         }
         return false;
 }
bool XMLUtil::ToDouble (const char * str, double * value) inline static
Definition at line 495 of file tinyxml2_imp.h.
References TIXML_SSCANF.
Referenced by tinyxml2::XMLElement::QueryDoubleText(), and tinyxml2::XMLAttribute::QueryDoubleValue().
 {
         if ( TIXML_SSCANF( str, "%lf", value ) == 1 ) {
                 return true;
         }
         return false;
 }
bool XMLUtil::ToFloat (const char * str, float * value) inline static
Definition at line 486 of file tinyxml2_imp.h.
References TIXML_SSCANF.
Referenced by tinyxml2::XMLElement::QueryFloatText(), and tinyxml2::XMLAttribute::QueryFloatValue().
 {
         if ( TIXML_SSCANF( str, "%f", value ) == 1 ) {
                 return true;
         }
         return false;
 }
bool XMLUtil::ToInt (const char * str, int * value) inline static
Definition at line 450 of file tinyxml2_imp.h.
References TIXML_SSCANF.
Referenced by tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLAttribute::QueryIntValue(), and ToBool().
 {
         if ( TIXML_SSCANF( str, "%d", value ) == 1 )
                 return true;
         return false;
 }
void XMLUtil::ToStr (int v, char * buffer, int bufferSize) inline static
Definition at line 415 of file tinyxml2_imp.h.
References TIXML_SNPRINTF.
Referenced by tinyxml2::XMLPrinter::PushAttribute(), tinyxml2::XMLPrinter::PushText(), and tinyxml2::XMLAttribute::SetAttribute().
 {
         TIXML_SNPRINTF( buffer, bufferSize, "%d", v );
 }
void XMLUtil::ToStr (unsigned v, char * buffer, int bufferSize) inline static
Definition at line 422 of file tinyxml2_imp.h.
References TIXML_SNPRINTF.
 {
         TIXML_SNPRINTF( buffer, bufferSize, "%u", v );
 }
void XMLUtil::ToStr (bool v, char * buffer, int bufferSize) inline static
Definition at line 429 of file tinyxml2_imp.h.
References TIXML_SNPRINTF.
 {
         TIXML_SNPRINTF( buffer, bufferSize, "%d", v ? 1 : 0 );
 }
void XMLUtil::ToStr (float v, char * buffer, int bufferSize) inline static
Definition at line 436 of file tinyxml2_imp.h.
References TIXML_SNPRINTF.
 {
         TIXML_SNPRINTF( buffer, bufferSize, "%g", v );
 }
void XMLUtil::ToStr (double v, char * buffer, int bufferSize) inline static
Definition at line 443 of file tinyxml2_imp.h.
References TIXML_SNPRINTF.
 {
         TIXML_SNPRINTF( buffer, bufferSize, "%g", v );
 }
bool XMLUtil::ToUnsigned (const char * str, unsigned * value) inline static
Definition at line 458 of file tinyxml2_imp.h.
References TIXML_SSCANF.
Referenced by tinyxml2::XMLElement::QueryUnsignedText(), and tinyxml2::XMLAttribute::QueryUnsignedValue().
 {
         if ( TIXML_SSCANF( str, "%u", value ) == 1 )
                 return true;
         return false;
 }
The documentation for this class was generated from the following files:
src/parsing/include/antioch/tinyxml2.h
src/parsing/include/antioch/tinyxml2_imp.h