antioch-0.4.0: tinyxml2::XMLDocument Class Reference
tinyxml2::XMLDocument Class Reference
#include <tinyxml2.h>
Public Member Functions
XMLDocument (bool processEntities=true, Whitespace=PRESERVE_WHITESPACE)
constructor
~XMLDocument ()
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual const XMLDocument * ToDocument () const
int Parse (const char *xml, size_t nBytes=(size_t)(-1))
int LoadFile (const char *filename)
int LoadFile (FILE *)
int SaveFile (const char *filename, bool compact=false)
int SaveFile (FILE *fp, bool compact=false)
bool ProcessEntities () const
Whitespace WhitespaceMode () const
bool HasBOM () const
void SetBOM (bool useBOM)
XMLElement * RootElement ()
const XMLElement * RootElement () const
void Print (XMLPrinter *streamer=0)
virtual bool Accept (XMLVisitor *visitor) const
XMLElement * NewElement (const char *name)
XMLComment * NewComment (const char *comment)
XMLText * NewText (const char *text)
XMLDeclaration * NewDeclaration (const char *text=0)
XMLUnknown * NewUnknown (const char *text)
void DeleteNode (XMLNode *node)
void SetError (int error, const char *str1, const char *str2)
bool Error () const
Return true if there was an error parsing the document.
int ErrorID () const
Return the errorID.
const char * GetErrorStr1 () const
Return a possibly helpful diagnostic location or string.
const char * GetErrorStr2 () const
Return a possibly helpful secondary diagnostic location or string.
void PrintError () const
If there is an error, print it to stdout.
char * Identify (char *p, XMLNode **node)
virtual XMLNode * ShallowClone (XMLDocument *) const
virtual bool ShallowEqual (const XMLNode *) const
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual const XMLElement * ToElement () const
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual const XMLText * ToText () const
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual const XMLComment * ToComment () const
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual const XMLDeclaration * ToDeclaration () const
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *value=0) const
XMLElement * FirstChildElement (const char *_value=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *value=0) const
XMLElement * LastChildElement (const char *_value=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *value=0) const
Get the previous (left) sibling element of this node, with an opitionally supplied name.
XMLElement * PreviousSiblingElement (const char *_value=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *value=0) const
Get the next (right) sibling element of this node, with an opitionally supplied name.
XMLElement * NextSiblingElement (const char *_value=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
virtual char * ParseDeep (char *, StrPair *)
Protected Attributes
XMLDocument * document
XMLNode * parent
StrPair value
XMLNode * firstChild
XMLNode * lastChild
XMLNode * prev
XMLNode * next
Private Member Functions
XMLDocument (const XMLDocument &)
void operator= (const XMLDocument &)
void InitDocument ()
Private Attributes
bool writeBOM
bool processEntities
int errorID
Whitespace whitespace
const char * errorStr1
const char * errorStr2
char * charBuffer
MemPoolT< sizeof(XMLElement) > elementPool
MemPoolT< sizeof(XMLAttribute) > attributePool
MemPoolT< sizeof(XMLText) > textPool
MemPoolT< sizeof(XMLComment) > commentPool
Friends
class XMLElement
Detailed Description
A Document binds together all the functionality. It can be saved, loaded, and printed to the screen. All Nodes are connected and allocated to a Document. If the Document is deleted, all its Nodes are also deleted.
Definition at line 1060 of file tinyxml2.h.
Constructor & Destructor Documentation
XMLDocument::XMLDocument (bool processEntities = true, Whitespace _whitespace = PRESERVE_WHITESPACE) inline
constructor
Definition at line 1546 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::document.
                                                                         :
         XMLNode( 0 ),
         writeBOM( false ),
         processEntities( _processEntities ),
         errorID( 0 ),
         whitespace( _whitespace ),
         errorStr1( 0 ),
         errorStr2( 0 ),
         charBuffer( 0 )
 {
         document = this;        // avoid warning about 'this' in initializer list
 }
XMLDocument::~XMLDocument () inline
Definition at line 1561 of file tinyxml2_imp.h.
References attributePool, charBuffer, commentPool, tinyxml2::XMLNode::DeleteChildren(), elementPool, textPool, and TIXMLASSERT.
 {
         DeleteChildren();
         delete [] charBuffer;
 #if 0
         textPool.Trace( "text" );
         elementPool.Trace( "element" );
         commentPool.Trace( "comment" );
         attributePool.Trace( "attribute" );
 #endif
         TIXMLASSERT( textPool.CurrentAllocs() == 0 );
         TIXMLASSERT( elementPool.CurrentAllocs() == 0 );
         TIXMLASSERT( commentPool.CurrentAllocs() == 0 );
         TIXMLASSERT( attributePool.CurrentAllocs() == 0 );
 }
tinyxml2::XMLDocument::XMLDocument (const XMLDocument &) private
Member Function Documentation
bool XMLDocument::Accept (XMLVisitor * visitor) const inline virtual
Accept a hierarchical visit of the nodes in the TinyXML DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the TiXmlVisitor interface.
This is essentially a SAX interface for TinyXML. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
    TiXmlPrinter printer;
    tinyxmlDoc.Accept( &printer );
    const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode.
Definition at line 582 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::NextSibling(), tinyxml2::XMLVisitor::VisitEnter(), and tinyxml2::XMLVisitor::VisitExit().
Referenced by Print().
 {
         if ( visitor->VisitEnter( *this ) )
         {
                 for ( const XMLNode* node=FirstChild(); node; node=node->NextSibling() )
                 {
                         if ( !node->Accept( visitor ) )
                                 break;
                 }
         }
         return visitor->VisitExit( *this );
 }
void XMLNode::DeleteChild (XMLNode * node) inline inherited
Delete a child of this node.
Definition at line 661 of file tinyxml2_imp.h.
References DELETE_NODE, tinyxml2::XMLNode::parent, and TIXMLASSERT.
Referenced by DeleteNode().
 {
         TIXMLASSERT( node->parent == this );
         DELETE_NODE( node );
 }
void XMLNode::DeleteChildren () inline inherited
Delete all the children of this node.
Definition at line 629 of file tinyxml2_imp.h.
References DELETE_NODE, tinyxml2::XMLNode::firstChild, tinyxml2::XMLNode::lastChild, and tinyxml2::XMLNode::Unlink().
Referenced by LoadFile(), Parse(), ~XMLDocument(), and tinyxml2::XMLNode::~XMLNode().
 {
         while( firstChild ) {
                 XMLNode* node = firstChild;
                 Unlink( node );
                 DELETE_NODE( node );
         }
         firstChild = lastChild = 0;
 }
void tinyxml2::XMLDocument::DeleteNode (XMLNode * node) inline
Delete a node associated with this document. It will be unlinked from the DOM.
Definition at line 1190 of file tinyxml2.h.
References tinyxml2::XMLNode::DeleteChild(), and tinyxml2::XMLNode::parent.
 { node->parent->DeleteChild( node ); }
bool tinyxml2::XMLDocument::Error () const inline
Return true if there was an error parsing the document.
Definition at line 1195 of file tinyxml2.h.
References errorID, and tinyxml2::XML_NO_ERROR.
Referenced by tinyxml2::XMLNode::ParseDeep().
 { return errorID != XML_NO_ERROR; }
int tinyxml2::XMLDocument::ErrorID () const inline
Return the errorID.
Definition at line 1197 of file tinyxml2.h.
References errorID.
Referenced by Antioch::XMLParser< NumericType >::change_file(), and Antioch::XMLParser< NumericType >::XMLParser().
 { return errorID; }
const XMLNode* tinyxml2::XMLNode::FirstChild () const inline inherited
Get the first child node, or null if none exists.
Definition at line 496 of file tinyxml2.h.
References tinyxml2::XMLNode::firstChild.
Referenced by tinyxml2::XMLElement::Accept(), Accept(), tinyxml2::XMLHandle::FirstChild(), tinyxml2::XMLConstHandle::FirstChild(), tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), and tinyxml2::XMLElement::QueryUnsignedText().
 { return firstChild; }
XMLNode* tinyxml2::XMLNode::FirstChild () inline inherited
Definition at line 497 of file tinyxml2.h.
References tinyxml2::XMLNode::firstChild.
 { return firstChild; }
const XMLElement * XMLNode::FirstChildElement (const char * value = 0) const inline inherited
Get the first child element, or optionally the first child element with the specified name.
Definition at line 740 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::firstChild, tinyxml2::XMLElement::Name(), tinyxml2::XMLNode::next, tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLElement::ToElement(), and tinyxml2::XMLNode::value.
Referenced by Antioch::XMLParser< NumericType >::efficiencies(), tinyxml2::XMLHandle::FirstChildElement(), tinyxml2::XMLConstHandle::FirstChildElement(), Antioch::XMLParser< NumericType >::get_parameter(), Antioch::XMLParser< NumericType >::products_orders(), Antioch::XMLParser< NumericType >::products_pairs(), Antioch::XMLParser< NumericType >::reactants_orders(), Antioch::XMLParser< NumericType >::reactants_pairs(), Antioch::XMLParser< NumericType >::reaction_kinetics_model(), Antioch::XMLParser< NumericType >::read_thermodynamic_data_root(), RootElement(), Antioch::XMLParser< NumericType >::verify_Kooij_in_place_of_Arrhenius(), and Antioch::XMLParser< NumericType >::where_is_k0().
 {
         for( XMLNode* node=firstChild; node; node=node->next ) {
                 XMLElement* element = node->ToElement();
                 if ( element ) {
                         if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                                 return element;
                         }
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::FirstChildElement (const char * _value = 0) inline inherited
Definition at line 502 of file tinyxml2.h.
References tinyxml2::XMLNode::FirstChildElement().
Referenced by tinyxml2::XMLNode::FirstChildElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->FirstChildElement( _value )); }
const XMLDocument* tinyxml2::XMLNode::GetDocument () const inline inherited
Get the XMLDocument that owns this XMLNode.
Definition at line 455 of file tinyxml2.h.
References tinyxml2::XMLNode::document.
 { return document; }
XMLDocument* tinyxml2::XMLNode::GetDocument () inline inherited
Get the XMLDocument that owns this XMLNode.
Definition at line 457 of file tinyxml2.h.
References tinyxml2::XMLNode::document.
 { return document; }
const char* tinyxml2::XMLDocument::GetErrorStr1 () const inline
Return a possibly helpful diagnostic location or string.
Definition at line 1199 of file tinyxml2.h.
References errorStr1.
Referenced by Antioch::XMLParser< NumericType >::XMLParser().
 { return errorStr1; }
const char* tinyxml2::XMLDocument::GetErrorStr2 () const inline
Return a possibly helpful secondary diagnostic location or string.
Definition at line 1201 of file tinyxml2.h.
References errorStr2.
Referenced by Antioch::XMLParser< NumericType >::XMLParser().
 { return errorStr2; }
bool tinyxml2::XMLDocument::HasBOM () const inline
Returns true if this document has a leading Byte Order Mark of UTF8.
Definition at line 1121 of file tinyxml2.h.
References writeBOM.
Referenced by tinyxml2::XMLPrinter::VisitEnter().
 { return writeBOM; }
char * XMLDocument::Identify (char * p, XMLNode ** node) inline
Definition at line 505 of file tinyxml2_imp.h.
References commentPool, elementPool, tinyxml2::XMLNode::memPool, tinyxml2::XMLText::SetCData(), tinyxml2::XMLUtil::SkipWhiteSpace(), tinyxml2::XMLUtil::StringEqual(), textPool, TIXMLASSERT, and XMLElement.
Referenced by tinyxml2::XMLNode::ParseDeep().
 {
         XMLNode* returnNode = 0;
         char* start = p;
         p = XMLUtil::SkipWhiteSpace( p );
         if( !p || !*p )
         {
                 return p;
         }
         // What is this thing?
         // - Elements start with a letter or underscore, but xml is reserved.
         // - Comments: <!--
         // - Decleration: <?
         // - Everthing else is unknown to tinyxml.
         //
         static const char* xmlHeader            = { "<?" };
         static const char* commentHeader        = { "<!--" };
         static const char* dtdHeader            = { "<!" };
         static const char* cdataHeader          = { "<![CDATA[" };
         static const char* elementHeader        = { "<" };      // and a header for everything else; check last.
         static const int xmlHeaderLen           = 2;
         static const int commentHeaderLen       = 4;
         static const int dtdHeaderLen           = 2;
         static const int cdataHeaderLen         = 9;
         static const int elementHeaderLen       = 1;
 #if defined(_MSC_VER)
 #pragma warning ( push )
 #pragma warning ( disable : 4127 )
 #endif
         TIXMLASSERT( sizeof( XMLComment ) == sizeof( XMLUnknown ) );            // use same memory pool
         TIXMLASSERT( sizeof( XMLComment ) == sizeof( XMLDeclaration ) );        // use same memory pool
 #if defined(_MSC_VER)
 #pragma warning (pop)
 #endif
         if ( XMLUtil::StringEqual( p, xmlHeader, xmlHeaderLen ) ) {
                 returnNode = new (commentPool.Alloc()) XMLDeclaration( this );
                 returnNode->memPool = &commentPool;
                 p += xmlHeaderLen;
         }
         else if ( XMLUtil::StringEqual( p, commentHeader, commentHeaderLen ) ) {
                 returnNode = new (commentPool.Alloc()) XMLComment( this );
                 returnNode->memPool = &commentPool;
                 p += commentHeaderLen;
         }
         else if ( XMLUtil::StringEqual( p, cdataHeader, cdataHeaderLen ) ) {
                 XMLText* text = new (textPool.Alloc()) XMLText( this );
                 returnNode = text;
                 returnNode->memPool = &textPool;
                 p += cdataHeaderLen;
                 text->SetCData( true );
         }
         else if ( XMLUtil::StringEqual( p, dtdHeader, dtdHeaderLen ) ) {
                 returnNode = new (commentPool.Alloc()) XMLUnknown( this );
                 returnNode->memPool = &commentPool;
                 p += dtdHeaderLen;
         }
         else if ( XMLUtil::StringEqual( p, elementHeader, elementHeaderLen ) ) {
                 returnNode = new (elementPool.Alloc()) XMLElement( this );
                 returnNode->memPool = &elementPool;
                 p += elementHeaderLen;
         }
         else {
                 returnNode = new (textPool.Alloc()) XMLText( this );
                 returnNode->memPool = &textPool;
                 p = start;      // Back it up, all the text counts.
         }
         *node = returnNode;
         return p;
 }
void XMLDocument::InitDocument () inline private
Definition at line 1581 of file tinyxml2_imp.h.
References charBuffer, errorID, errorStr1, errorStr2, and tinyxml2::XML_NO_ERROR.
Referenced by LoadFile(), and Parse().
 {
         errorID = XML_NO_ERROR;
         errorStr1 = 0;
         errorStr2 = 0;
         delete [] charBuffer;
         charBuffer = 0;
 }
XMLNode * XMLNode::InsertAfterChild (XMLNode * afterThis, XMLNode * addThis) inline inherited
Add a node after the specified child node.
Definition at line 718 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::next, tinyxml2::XMLNode::parent, tinyxml2::XMLNode::prev, and TIXMLASSERT.
 {
         TIXMLASSERT( afterThis->parent == this );
         if ( afterThis->parent != this )
                 return 0;
         if ( afterThis->next == 0 ) {
                 // The last node or the only node.
                 return InsertEndChild( addThis );
         }
         addThis->prev = afterThis;
         addThis->next = afterThis->next;
         afterThis->next->prev = addThis;
         afterThis->next = addThis;
         addThis->parent = this;
         return addThis;
 }
XMLNode * XMLNode::InsertEndChild (XMLNode * addThis) inline inherited
Add a child node as the last (right) child.
Definition at line 669 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::firstChild, tinyxml2::XMLNode::lastChild, tinyxml2::XMLNode::next, tinyxml2::XMLNode::parent, tinyxml2::XMLNode::prev, and TIXMLASSERT.
Referenced by tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::LinkEndChild(), and tinyxml2::XMLNode::ParseDeep().
 {
         if ( lastChild ) {
                 TIXMLASSERT( firstChild );
                 TIXMLASSERT( lastChild->next == 0 );
                 lastChild->next = addThis;
                 addThis->prev = lastChild;
                 lastChild = addThis;
                 addThis->next = 0;
         }
         else {
                 TIXMLASSERT( firstChild == 0 );
                 firstChild = lastChild = addThis;
                 addThis->prev = 0;
                 addThis->next = 0;
         }
         addThis->parent = this;
         return addThis;
 }
XMLNode * XMLNode::InsertFirstChild (XMLNode * addThis) inline inherited
Add a child node as the first (left) child.
Definition at line 693 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::firstChild, tinyxml2::XMLNode::lastChild, tinyxml2::XMLNode::next, tinyxml2::XMLNode::parent, tinyxml2::XMLNode::prev, and TIXMLASSERT.
 {
         if ( firstChild ) {
                 TIXMLASSERT( lastChild );
                 TIXMLASSERT( firstChild->prev == 0 );
                 firstChild->prev = addThis;
                 addThis->next = firstChild;
                 firstChild = addThis;
                 addThis->prev = 0;
         }
         else {
                 TIXMLASSERT( lastChild == 0 );
                 firstChild = lastChild = addThis;
                 addThis->prev = 0;
                 addThis->next = 0;
         }
         addThis->parent = this;
         return addThis;
 }
const XMLNode* tinyxml2::XMLNode::LastChild () const inline inherited
Get the last child node, or null if none exists.
Definition at line 505 of file tinyxml2.h.
References tinyxml2::XMLNode::lastChild.
Referenced by tinyxml2::XMLHandle::LastChild(), and tinyxml2::XMLConstHandle::LastChild().
 { return lastChild; }
XMLNode* tinyxml2::XMLNode::LastChild () inline inherited
Definition at line 506 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChild().
Referenced by tinyxml2::XMLNode::LastChild().
 { return const_cast<XMLNode*>(const_cast<const XMLNode*>(this)->LastChild() ); }
const XMLElement * XMLNode::LastChildElement (const char * value = 0) const inline inherited
Get the last child element or optionally the last child element with the specified name.
Definition at line 755 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::lastChild, tinyxml2::XMLElement::Name(), tinyxml2::XMLNode::prev, tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLElement::ToElement(), and tinyxml2::XMLNode::value.
Referenced by tinyxml2::XMLHandle::LastChildElement(), and tinyxml2::XMLConstHandle::LastChildElement().
 {
         for( XMLNode* node=lastChild; node; node=node->prev ) {
                 XMLElement* element = node->ToElement();
                 if ( element ) {
                         if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                                 return element;
                         }
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::LastChildElement (const char * _value = 0) inline inherited
Definition at line 512 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChildElement().
Referenced by tinyxml2::XMLNode::LastChildElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->LastChildElement(_value) ); }
XMLNode* tinyxml2::XMLNode::LinkEndChild (XMLNode * addThis) inline inherited
Definition at line 535 of file tinyxml2.h.
References tinyxml2::XMLNode::InsertEndChild().
 { return InsertEndChild( addThis ); }
int XMLDocument::LoadFile (const char * filename) inline
Load an XML file from disk. Returns XML_NO_ERROR (0) on success, or an errorID.
Definition at line 1644 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::DeleteChildren(), errorID, InitDocument(), SetError(), and tinyxml2::XML_ERROR_FILE_NOT_FOUND.
Referenced by Antioch::XMLParser< NumericType >::XMLParser().
 {
         DeleteChildren();
         InitDocument();
         FILE* fp = 0;
         #if defined(_MSC_VER) && (_MSC_VER >= 1400 )
                 errno_t err = fopen_s(&fp, filename, "rb" );
                 if ( !fp || err) {
         #else
                 fp = fopen( filename, "rb" );
                 if ( !fp) {
         #endif
                 SetError( XML_ERROR_FILE_NOT_FOUND, filename, 0 );
                 return errorID;
         }
         LoadFile( fp );
         fclose( fp );
         return errorID;
 }
int XMLDocument::LoadFile (FILE * fp) inline
Load an XML file from disk. You are responsible for providing and closing the FILE*.
Returns XML_NO_ERROR (0) on success, or an errorID.
Definition at line 1667 of file tinyxml2_imp.h.
References charBuffer, tinyxml2::XMLNode::DeleteChildren(), errorID, InitDocument(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLUtil::ReadBOM(), SetError(), tinyxml2::XMLUtil::SkipWhiteSpace(), writeBOM, tinyxml2::XML_ERROR_EMPTY_DOCUMENT, and tinyxml2::XML_ERROR_FILE_READ_ERROR.
 {
         DeleteChildren();
         InitDocument();
         fseek( fp, 0, SEEK_END );
         unsigned size = ftell( fp );
         fseek( fp, 0, SEEK_SET );
         if ( size == 0 ) {
                 return errorID;
         }
         charBuffer = new char[size+1];
         size_t read = fread( charBuffer, 1, size, fp );
         if ( read != size ) {
                 SetError( XML_ERROR_FILE_READ_ERROR, 0, 0 );
                 return errorID;
         }
         charBuffer[size] = 0;
         const char* p = charBuffer;
         p = XMLUtil::SkipWhiteSpace( p );
         p = XMLUtil::ReadBOM( p, &writeBOM );
         if ( !p || !*p ) {
                 SetError( XML_ERROR_EMPTY_DOCUMENT, 0, 0 );
                 return errorID;
         }
         ParseDeep( charBuffer + (p-charBuffer), 0 );
         return errorID;
 }
XMLComment * XMLDocument::NewComment (const char * comment) inline
Create a new Comment associated with this Document. The memory for the Comment is managed by the Document.
Definition at line 1604 of file tinyxml2_imp.h.
References commentPool, and tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLComment::ShallowClone().
 {
         XMLComment* comment = new (commentPool.Alloc()) XMLComment( this );
         comment->memPool = &commentPool;
         comment->SetValue( str );
         return comment;
 }
XMLDeclaration * XMLDocument::NewDeclaration (const char * text = 0) inline
Create a new Declaration associated with this Document. The memory for the object is managed by the Document.
If the 'text' param is null, the standard declaration is used.:
        <?xml version="1.0" encoding="UTF-8"?>
Definition at line 1624 of file tinyxml2_imp.h.
References commentPool, and tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLDeclaration::ShallowClone().
 {
         XMLDeclaration* dec = new (commentPool.Alloc()) XMLDeclaration( this );
         dec->memPool = &commentPool;
         dec->SetValue( str ? str : "xml version=\"1.0\" encoding=\"UTF-8\"" );
         return dec;
 }
XMLElement * XMLDocument::NewElement (const char * name) inline
Create a new Element associated with this Document. The memory for the Element is managed by the Document.
Definition at line 1594 of file tinyxml2_imp.h.
References elementPool, tinyxml2::XMLElement::SetName(), and XMLElement.
Referenced by tinyxml2::XMLElement::ShallowClone().
 {
         XMLElement* ele = new (elementPool.Alloc()) XMLElement( this );
         ele->memPool = &elementPool;
         ele->SetName( name );
         return ele;
 }
XMLText * XMLDocument::NewText (const char * text) inline
Create a new Text associated with this Document. The memory for the Text is managed by the Document.
Definition at line 1614 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::SetValue(), and textPool.
Referenced by tinyxml2::XMLText::ShallowClone().
 {
         XMLText* text = new (textPool.Alloc()) XMLText( this );
         text->memPool = &textPool;
         text->SetValue( str );
         return text;
 }
XMLUnknown * XMLDocument::NewUnknown (const char * text) inline
Create a new Unknown associated with this Document. The memory for the object is managed by the Document.
Definition at line 1634 of file tinyxml2_imp.h.
References commentPool, and tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLUnknown::ShallowClone().
 {
         XMLUnknown* unk = new (commentPool.Alloc()) XMLUnknown( this );
         unk->memPool = &commentPool;
         unk->SetValue( str );
         return unk;
 }
const XMLNode* tinyxml2::XMLNode::NextSibling () const inline inherited
Get the next (right) sibling node of this node.
Definition at line 523 of file tinyxml2.h.
References tinyxml2::XMLNode::next.
Referenced by tinyxml2::XMLElement::Accept(), Accept(), tinyxml2::XMLHandle::NextSibling(), and tinyxml2::XMLConstHandle::NextSibling().
 { return next; }
XMLNode* tinyxml2::XMLNode::NextSibling () inline inherited
Definition at line 524 of file tinyxml2.h.
References tinyxml2::XMLNode::next.
 { return next; }
const XMLElement * XMLNode::NextSiblingElement (const char * value = 0) const inline inherited
Get the next (right) sibling element of this node, with an opitionally supplied name.
Definition at line 770 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::next, tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by Antioch::XMLParser< NumericType >::find_element_with_attribute(), tinyxml2::XMLHandle::NextSiblingElement(), tinyxml2::XMLConstHandle::NextSiblingElement(), Antioch::XMLParser< NumericType >::read_thermodynamic_data_root(), and Antioch::XMLParser< NumericType >::where_is_k0().
 {
         for( XMLNode* element=this->next; element; element = element->next ) {
                 if (    element->ToElement()
                          && (!value || XMLUtil::StringEqual( value, element->Value() )))
                 {
                         return element->ToElement();
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::NextSiblingElement (const char * _value = 0) inline inherited
Definition at line 528 of file tinyxml2.h.
References tinyxml2::XMLNode::NextSiblingElement().
Referenced by tinyxml2::XMLNode::NextSiblingElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->NextSiblingElement( _value ) ); }
bool tinyxml2::XMLNode::NoChildren () const inline inherited
Returns true if this node has no children.
Definition at line 493 of file tinyxml2.h.
References tinyxml2::XMLNode::firstChild.
 { return !firstChild; }
void tinyxml2::XMLDocument::operator= (const XMLDocument &) private
const XMLNode* tinyxml2::XMLNode::Parent () const inline inherited
Get the parent of this node on the DOM.
Definition at line 489 of file tinyxml2.h.
References tinyxml2::XMLNode::parent.
 { return parent; }
XMLNode* tinyxml2::XMLNode::Parent () inline inherited
Definition at line 490 of file tinyxml2.h.
References tinyxml2::XMLNode::parent.
 { return parent; }
int XMLDocument::Parse (const char * xml, size_t nBytes = (size_t)(-1)) inline
Parse an XML file from a character string. Returns XML_NO_ERROR (0) on success, or an errorID.
You may optionally pass in the 'nBytes', which is the number of bytes which will be parsed. If not specified, TinyXML will assume 'xml' points to a null terminated string.
Definition at line 1732 of file tinyxml2_imp.h.
References charBuffer, tinyxml2::XMLNode::DeleteChildren(), errorID, InitDocument(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLUtil::ReadBOM(), SetError(), tinyxml2::XMLUtil::SkipWhiteSpace(), writeBOM, and tinyxml2::XML_ERROR_EMPTY_DOCUMENT.
 {
         DeleteChildren();
         InitDocument();
         if ( !p || !*p ) {
                 SetError( XML_ERROR_EMPTY_DOCUMENT, 0, 0 );
                 return errorID;
         }
         if ( len == (size_t)(-1) ) {
                 len = strlen( p );
         }
         charBuffer = new char[ len+1 ];
         memcpy( charBuffer, p, len );
         charBuffer[len] = 0;
         p = XMLUtil::SkipWhiteSpace( p );
         p = XMLUtil::ReadBOM( p, &writeBOM );
         if ( !p || !*p ) {
                 SetError( XML_ERROR_EMPTY_DOCUMENT, 0, 0 );
                 return errorID;
         }
         ParseDeep( charBuffer, 0 );
         return errorID;
 }
char * XMLNode::ParseDeep (char * p, StrPair * parentEnd) inline virtual inherited
Reimplemented in tinyxml2::XMLElement, tinyxml2::XMLUnknown, tinyxml2::XMLDeclaration, tinyxml2::XMLComment, and tinyxml2::XMLText.
Definition at line 798 of file tinyxml2_imp.h.
References tinyxml2::XMLElement::CLOSING, tinyxml2::XMLElement::ClosingType(), DELETE_NODE, tinyxml2::XMLNode::document, tinyxml2::StrPair::Empty(), Error(), tinyxml2::StrPair::GetStr(), Identify(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLElement::OPEN, tinyxml2::XMLNode::ParseDeep(), SetError(), tinyxml2::XMLUtil::StringEqual(), tinyxml2::XMLNode::ToElement(), tinyxml2::XMLNode::Value(), tinyxml2::XMLNode::value, tinyxml2::XML_ERROR_MISMATCHED_ELEMENT, and tinyxml2::XML_ERROR_PARSING.
Referenced by LoadFile(), Parse(), tinyxml2::XMLNode::ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
 {
         // This is a recursive method, but thinking about it "at the current level"
         // it is a pretty simple flat list:
         //              <foo/>
         //              <!-- comment -->
         //
         // With a special case:
         //              <foo>
         //              </foo>
         //              <!-- comment -->
         //
         // Where the closing element (/foo) *must* be the next thing after the opening
         // element, and the names must match. BUT the tricky bit is that the closing
         // element will be read by the child.
         //
         // 'endTag' is the end tag for this node, it is returned by a call to a child.
         // 'parentEnd' is the end tag for the parent, which is filled in and returned.
         while( p && *p ) {
                 XMLNode* node = 0;
                 p = document->Identify( p, &node );
                 if ( p == 0 || node == 0 ) {
                         break;
                 }
                 StrPair endTag;
                 p = node->ParseDeep( p, &endTag );
                 if ( !p ) {
                         DELETE_NODE( node );
                         node = 0;
                         if ( !document->Error() ) {
                                 document->SetError( XML_ERROR_PARSING, 0, 0 );
                         }
                         break;
                 }
                 // We read the end tag. Return it to the parent.
                 if ( node->ToElement() && node->ToElement()->ClosingType() == XMLElement::CLOSING ) {
                         if ( parentEnd ) {
                                 *parentEnd = static_cast<XMLElement*>(node)->value;
                         }
                         DELETE_NODE( node );
                         return p;
                 }
                 // Handle an end tag returned to this level.
                 // And handle a bunch of annoying errors.
                 XMLElement* ele = node->ToElement();
                 if ( ele ) {
                         if ( endTag.Empty() && ele->ClosingType() == XMLElement::OPEN ) {
                                 document->SetError( XML_ERROR_MISMATCHED_ELEMENT, node->Value(), 0 );
                                 p = 0;
                         }
                         else if ( !endTag.Empty() && ele->ClosingType() != XMLElement::OPEN ) {
                                 document->SetError( XML_ERROR_MISMATCHED_ELEMENT, node->Value(), 0 );
                                 p = 0;
                         }
                         else if ( !endTag.Empty() ) {
                                 if ( !XMLUtil::StringEqual( endTag.GetStr(), node->Value() )) {
                                         document->SetError( XML_ERROR_MISMATCHED_ELEMENT, node->Value(), 0 );
                                         p = 0;
                                 }
                         }
                 }
                 if ( p == 0 ) {
                         DELETE_NODE( node );
                         node = 0;
                 }
                 if ( node ) {
                         this->InsertEndChild( node );
                 }
         }
         return 0;
 }
const XMLNode* tinyxml2::XMLNode::PreviousSibling () const inline inherited
Get the previous (left) sibling node of this node.
Definition at line 515 of file tinyxml2.h.
References tinyxml2::XMLNode::prev.
Referenced by tinyxml2::XMLHandle::PreviousSibling(), and tinyxml2::XMLConstHandle::PreviousSibling().
 { return prev; }
XMLNode* tinyxml2::XMLNode::PreviousSibling () inline inherited
Definition at line 516 of file tinyxml2.h.
References tinyxml2::XMLNode::prev.
 { return prev; }
const XMLElement * XMLNode::PreviousSiblingElement (const char * value = 0) const inline inherited
Get the previous (left) sibling element of this node, with an opitionally supplied name.
Definition at line 784 of file tinyxml2_imp.h.
References tinyxml2::XMLNode::prev, tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLElement::ToElement().
Referenced by tinyxml2::XMLHandle::PreviousSiblingElement(), and tinyxml2::XMLConstHandle::PreviousSiblingElement().
 {
         for( XMLNode* element=this->prev; element; element = element->prev ) {
                 if (    element->ToElement()
                          && (!value || XMLUtil::StringEqual( value, element->Value() )))
                 {
                         return element->ToElement();
                 }
         }
         return 0;
 }
XMLElement* tinyxml2::XMLNode::PreviousSiblingElement (const char * _value = 0) inline inherited
Definition at line 520 of file tinyxml2.h.
References tinyxml2::XMLNode::PreviousSiblingElement().
Referenced by tinyxml2::XMLNode::PreviousSiblingElement().
 { return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->PreviousSiblingElement( _value ) ); }
void XMLDocument::Print (XMLPrinter * streamer = 0) inline
Print the Document. If the Printer is not provided, it will print to stdout. If you provide Printer, this can print to a file:
    XMLPrinter printer( fp );
    doc.Print( &printer );
Or you can use a printer to print to memory:
    XMLPrinter printer;
    doc->Print( &printer );
    // printer.CStr() has a const char* to the XML
Definition at line 1761 of file tinyxml2_imp.h.
References Accept().
Referenced by SaveFile().
 {
         XMLPrinter stdStreamer( stdout );
         if ( !streamer )
                 streamer = &stdStreamer;
         Accept( streamer );
 }
void XMLDocument::PrintError () const inline
If there is an error, print it to stdout.
Definition at line 1780 of file tinyxml2_imp.h.
References errorID, errorStr1, errorStr2, and TIXML_SNPRINTF.
 {
         if ( errorID ) {
                 static const int LEN = 20;
                 char buf1[LEN] = { 0 };
                 char buf2[LEN] = { 0 };
                 if ( errorStr1 ) {
                         TIXML_SNPRINTF( buf1, LEN, "%s", errorStr1 );
                 }
                 if ( errorStr2 ) {
                         TIXML_SNPRINTF( buf2, LEN, "%s", errorStr2 );
                 }
                 printf( "XMLDocument error id=%d str1=%s str2=%s\n",
                             errorID, buf1, buf2 );
         }
 }
bool tinyxml2::XMLDocument::ProcessEntities () const inline
Definition at line 1115 of file tinyxml2.h.
References processEntities.
Referenced by tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLText::ParseDeep(), and tinyxml2::XMLPrinter::VisitEnter().
 { return processEntities; }
XMLElement* tinyxml2::XMLDocument::RootElement () inline
Return the root element of DOM. Equivalent to FirstChildElement(). To get the first node, use FirstChild().
Definition at line 1129 of file tinyxml2.h.
References tinyxml2::XMLNode::FirstChildElement().
 { return FirstChildElement(); }
const XMLElement* tinyxml2::XMLDocument::RootElement () const inline
Definition at line 1130 of file tinyxml2.h.
References tinyxml2::XMLNode::FirstChildElement().
 { return FirstChildElement(); }
int XMLDocument::SaveFile (const char * filename, bool compact = false) inline
Save the XML file to disk. Returns XML_NO_ERROR (0) on success, or an errorID.
Definition at line 1703 of file tinyxml2_imp.h.
References errorID, SetError(), and tinyxml2::XML_ERROR_FILE_COULD_NOT_BE_OPENED.
 {
         FILE* fp = 0;
         #if defined(_MSC_VER) && (_MSC_VER >= 1400 )
                 errno_t err = fopen_s(&fp, filename, "w" );
                 if ( !fp || err) {
         #else
                 fp = fopen( filename, "w" );
                 if ( !fp) {
         #endif
                 SetError( XML_ERROR_FILE_COULD_NOT_BE_OPENED, filename, 0 );
                 return errorID;
         }
         SaveFile(fp, compact);
         fclose( fp );
         return errorID;
 }
int XMLDocument::SaveFile (FILE * fp, bool compact = false) inline
Save the XML file to disk. You are responsible for providing and closing the FILE*.
Returns XML_NO_ERROR (0) on success, or an errorID.
Definition at line 1723 of file tinyxml2_imp.h.
References errorID, and Print().
 {
         XMLPrinter stream( fp, compact );
         Print( &stream );
         return errorID;
 }
void tinyxml2::XMLDocument::SetBOM (bool useBOM) inline
Sets whether to write the BOM when writing the file.
Definition at line 1124 of file tinyxml2.h.
References writeBOM.
 { writeBOM = useBOM; }
void XMLDocument::SetError (int error, const char * str1, const char * str2) inline
Definition at line 1771 of file tinyxml2_imp.h.
References errorID, errorStr1, and errorStr2.
Referenced by LoadFile(), Parse(), tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), and SaveFile().
 {
         errorID = error;
         errorStr1 = str1;
         errorStr2 = str2;
 }
void XMLNode::SetValue (const char * val, bool staticMem = false) inline inherited
Set the Value of an XML node.
See also
Value()
Definition at line 619 of file tinyxml2_imp.h.
References tinyxml2::StrPair::SetInternedStr(), tinyxml2::StrPair::SetStr(), and tinyxml2::XMLNode::value.
Referenced by NewComment(), NewDeclaration(), NewText(), NewUnknown(), and tinyxml2::XMLElement::SetName().
 {
         if ( staticMem )
                 value.SetInternedStr( str );
         else
                 value.SetStr( str );
 }
virtual XMLNode* tinyxml2::XMLDocument::ShallowClone (XMLDocument * document) const inline virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode.
Definition at line 1208 of file tinyxml2.h.
 { return 0; }
virtual bool tinyxml2::XMLDocument::ShallowEqual (const XMLNode * compare) const inline virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode.
Definition at line 1209 of file tinyxml2.h.
 { return false; }
virtual XMLComment* tinyxml2::XMLNode::ToComment () inline virtual inherited
Safely cast to a Comment, or null.
Reimplemented in tinyxml2::XMLComment.
Definition at line 461 of file tinyxml2.h.
Referenced by tinyxml2::XMLComment::ShallowEqual().
virtual const XMLComment* tinyxml2::XMLNode::ToComment () const inline virtual inherited
Reimplemented in tinyxml2::XMLComment.
Definition at line 468 of file tinyxml2.h.
 { return 0; }
virtual XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () inline virtual inherited
Safely cast to a Declaration, or null.
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 463 of file tinyxml2.h.
Referenced by tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLHandle::ToDeclaration(), and tinyxml2::XMLConstHandle::ToDeclaration().
virtual const XMLDeclaration* tinyxml2::XMLNode::ToDeclaration () const inline virtual inherited
Reimplemented in tinyxml2::XMLDeclaration.
Definition at line 470 of file tinyxml2.h.
 { return 0; }
virtual XMLDocument* tinyxml2::XMLDocument::ToDocument () inline virtual
Safely cast to a Document, or null.
Reimplemented from tinyxml2::XMLNode.
Definition at line 1068 of file tinyxml2.h.
 { return this; }
virtual const XMLDocument* tinyxml2::XMLDocument::ToDocument () const inline virtual
Reimplemented from tinyxml2::XMLNode.
Definition at line 1069 of file tinyxml2.h.
 { return this; }
virtual XMLElement* tinyxml2::XMLNode::ToElement () inline virtual inherited
Safely cast to an Element, or null.
Reimplemented in tinyxml2::XMLElement.
Definition at line 459 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLElement::ShallowEqual(), tinyxml2::XMLHandle::ToElement(), and tinyxml2::XMLConstHandle::ToElement().
virtual const XMLElement* tinyxml2::XMLNode::ToElement () const inline virtual inherited
Reimplemented in tinyxml2::XMLElement.
Definition at line 466 of file tinyxml2.h.
 { return 0; }
virtual XMLText* tinyxml2::XMLNode::ToText () inline virtual inherited
Safely cast to Text, or null.
Reimplemented in tinyxml2::XMLText.
Definition at line 460 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLHandle::ToText(), and tinyxml2::XMLConstHandle::ToText().
virtual const XMLText* tinyxml2::XMLNode::ToText () const inline virtual inherited
Reimplemented in tinyxml2::XMLText.
Definition at line 467 of file tinyxml2.h.
 { return 0; }
virtual XMLUnknown* tinyxml2::XMLNode::ToUnknown () inline virtual inherited
Safely cast to an Unknown, or null.
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 464 of file tinyxml2.h.
Referenced by tinyxml2::XMLUnknown::ShallowEqual(), tinyxml2::XMLHandle::ToUnknown(), and tinyxml2::XMLConstHandle::ToUnknown().
virtual const XMLUnknown* tinyxml2::XMLNode::ToUnknown () const inline virtual inherited
Reimplemented in tinyxml2::XMLUnknown.
Definition at line 471 of file tinyxml2.h.
 { return 0; }
const char* tinyxml2::XMLNode::Value () const inline inherited
The meaning of 'value' changes for the specific type.
    Document:   empty
    Element:    name of the element
    Comment:    the comment text
    Unknown:    the tag contents
    Text:               the text string
Definition at line 482 of file tinyxml2.h.
References tinyxml2::StrPair::GetStr(), and tinyxml2::XMLNode::value.
Referenced by tinyxml2::XMLElement::GetText(), tinyxml2::XMLElement::Name(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLElement::QueryBoolText(), tinyxml2::XMLElement::QueryDoubleText(), tinyxml2::XMLElement::QueryFloatText(), tinyxml2::XMLElement::QueryIntText(), tinyxml2::XMLElement::QueryUnsignedText(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), tinyxml2::XMLElement::ShallowClone(), tinyxml2::XMLText::ShallowEqual(), tinyxml2::XMLComment::ShallowEqual(), tinyxml2::XMLDeclaration::ShallowEqual(), tinyxml2::XMLUnknown::ShallowEqual(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::Visit().
 { return value.GetStr(); }
Whitespace tinyxml2::XMLDocument::WhitespaceMode () const inline
Definition at line 1116 of file tinyxml2.h.
References whitespace.
Referenced by tinyxml2::XMLText::ParseDeep().
 { return whitespace; }
Friends And Related Function Documentation
friend class XMLElement friend
Definition at line 1062 of file tinyxml2.h.
Referenced by Identify(), and NewElement().
Member Data Documentation
MemPoolT< sizeof(XMLAttribute) > tinyxml2::XMLDocument::attributePool private
Definition at line 1225 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLElement::ParseAttributes(), and ~XMLDocument().
char* tinyxml2::XMLDocument::charBuffer private
Definition at line 1222 of file tinyxml2.h.
Referenced by InitDocument(), LoadFile(), Parse(), and ~XMLDocument().
MemPoolT< sizeof(XMLComment) > tinyxml2::XMLDocument::commentPool private
Definition at line 1227 of file tinyxml2.h.
Referenced by Identify(), NewComment(), NewDeclaration(), NewUnknown(), and ~XMLDocument().
XMLDocument* tinyxml2::XMLNode::document protected inherited
Definition at line 607 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLNode::GetDocument(), tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), tinyxml2::XMLText::ShallowClone(), tinyxml2::XMLComment::ShallowClone(), tinyxml2::XMLDeclaration::ShallowClone(), tinyxml2::XMLUnknown::ShallowClone(), tinyxml2::XMLElement::ShallowClone(), and XMLDocument().
MemPoolT< sizeof(XMLElement) > tinyxml2::XMLDocument::elementPool private
Definition at line 1224 of file tinyxml2.h.
Referenced by Identify(), NewElement(), and ~XMLDocument().
int tinyxml2::XMLDocument::errorID private
Definition at line 1218 of file tinyxml2.h.
Referenced by Error(), ErrorID(), InitDocument(), LoadFile(), Parse(), PrintError(), SaveFile(), and SetError().
const char* tinyxml2::XMLDocument::errorStr1 private
Definition at line 1220 of file tinyxml2.h.
Referenced by GetErrorStr1(), InitDocument(), PrintError(), and SetError().
const char* tinyxml2::XMLDocument::errorStr2 private
Definition at line 1221 of file tinyxml2.h.
Referenced by GetErrorStr2(), InitDocument(), PrintError(), and SetError().
XMLNode* tinyxml2::XMLNode::firstChild protected inherited
Definition at line 611 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChildren(), tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::NoChildren(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::lastChild protected inherited
Definition at line 612 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChildren(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::LastChild(), tinyxml2::XMLNode::LastChildElement(), and tinyxml2::XMLNode::Unlink().
XMLNode* tinyxml2::XMLNode::next protected inherited
Definition at line 615 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::NextSibling(), tinyxml2::XMLNode::NextSiblingElement(), tinyxml2::XMLNode::Unlink(), and tinyxml2::XMLElement::~XMLElement().
XMLNode* tinyxml2::XMLNode::parent protected inherited
Definition at line 608 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::DeleteChild(), DeleteNode(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::Parent(), tinyxml2::XMLNode::Unlink(), and tinyxml2::XMLNode::~XMLNode().
XMLNode* tinyxml2::XMLNode::prev protected inherited
Definition at line 614 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::DeleteAttribute(), tinyxml2::XMLNode::InsertAfterChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLNode::PreviousSibling(), tinyxml2::XMLNode::PreviousSiblingElement(), and tinyxml2::XMLNode::Unlink().
bool tinyxml2::XMLDocument::processEntities private
Definition at line 1217 of file tinyxml2.h.
Referenced by ProcessEntities().
MemPoolT< sizeof(XMLText) > tinyxml2::XMLDocument::textPool private
Definition at line 1226 of file tinyxml2.h.
Referenced by Identify(), NewText(), and ~XMLDocument().
StrPair tinyxml2::XMLNode::value mutable protected inherited
Definition at line 609 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::Attribute(), tinyxml2::XMLNode::FirstChildElement(), tinyxml2::XMLNode::LastChildElement(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), tinyxml2::XMLElement::ParseDeep(), tinyxml2::XMLNode::SetValue(), and tinyxml2::XMLNode::Value().
Whitespace tinyxml2::XMLDocument::whitespace private
Definition at line 1219 of file tinyxml2.h.
Referenced by WhitespaceMode().
bool tinyxml2::XMLDocument::writeBOM private
Definition at line 1216 of file tinyxml2.h.
Referenced by HasBOM(), LoadFile(), Parse(), and SetBOM().
The documentation for this class was generated from the following files:
src/parsing/include/antioch/tinyxml2.h
src/parsing/include/antioch/tinyxml2_imp.h