antioch-0.4.0: tinyxml2::XMLAttribute Class Reference
tinyxml2::XMLAttribute Class Reference
#include <tinyxml2.h>
Public Member Functions
const char * Name () const
The name of the attribute.
const char * Value () const
The value of the attribute.
const XMLAttribute * Next () const
The next attribute in the list.
int IntValue () const
unsigned UnsignedValue () const
Query as an unsigned integer. See IntAttribute()
bool BoolValue () const
Query as a boolean. See IntAttribute()
double DoubleValue () const
Query as a double. See IntAttribute()
float FloatValue () const
Query as a float. See IntAttribute()
int QueryIntValue (int *value) const
int QueryUnsignedValue (unsigned int *value) const
See QueryIntAttribute.
int QueryBoolValue (bool *value) const
See QueryIntAttribute.
int QueryDoubleValue (double *value) const
See QueryIntAttribute.
int QueryFloatValue (float *value) const
See QueryIntAttribute.
void SetAttribute (const char *value)
Set the attribute to a string value.
void SetAttribute (int value)
Set the attribute to value.
void SetAttribute (unsigned value)
Set the attribute to value.
void SetAttribute (bool value)
Set the attribute to value.
void SetAttribute (double value)
Set the attribute to value.
void SetAttribute (float value)
Set the attribute to value.
Private Types
enum { BUF_SIZE = 200 }
Private Member Functions
XMLAttribute ()
virtual ~XMLAttribute ()
XMLAttribute (const XMLAttribute &)
void operator= (const XMLAttribute &)
void SetName (const char *name)
char * ParseDeep (char *p, bool processEntities)
Private Attributes
StrPair name
StrPair value
XMLAttribute * next
MemPool * memPool
Friends
class XMLElement
Detailed Description
An attribute is a name-value pair. Elements have an arbitrary number of attributes, each with a unique name.
Note
The attributes are not XMLNodes. You may only query the Next() attribute in a list.
Definition at line 784 of file tinyxml2.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
BUF_SIZE
Definition at line 834 of file tinyxml2.h.
 { BUF_SIZE = 200 };
Constructor & Destructor Documentation
tinyxml2::XMLAttribute::XMLAttribute () inline private
Definition at line 836 of file tinyxml2.h.
 : next( 0 ) {}
virtual tinyxml2::XMLAttribute::~XMLAttribute () inline private virtual
Definition at line 837 of file tinyxml2.h.
 {}
tinyxml2::XMLAttribute::XMLAttribute (const XMLAttribute &) private
Member Function Documentation
bool tinyxml2::XMLAttribute::BoolValue () const inline
Query as a boolean. See IntAttribute()
Definition at line 800 of file tinyxml2.h.
References QueryBoolValue().
 { bool b=false; QueryBoolValue( &b );           return b; }
double tinyxml2::XMLAttribute::DoubleValue () const inline
Query as a double. See IntAttribute()
Definition at line 802 of file tinyxml2.h.
References QueryDoubleValue().
 { double d=0;   QueryDoubleValue( &d );         return d; }
float tinyxml2::XMLAttribute::FloatValue () const inline
Query as a float. See IntAttribute()
Definition at line 804 of file tinyxml2.h.
References QueryFloatValue().
 { float f=0;    QueryFloatValue( &f );          return f; }
int tinyxml2::XMLAttribute::IntValue () const inline
IntAttribute interprets the attribute as an integer, and returns the value. If the value isn't an integer, 0 will be returned. There is no error checking; use QueryIntAttribute() if you need error checking.
Definition at line 796 of file tinyxml2.h.
References QueryIntValue().
 { int i=0;              QueryIntValue( &i );            return i; }
const char* tinyxml2::XMLAttribute::Name () const inline
The name of the attribute.
Definition at line 788 of file tinyxml2.h.
References tinyxml2::StrPair::GetStr(), and name.
Referenced by tinyxml2::XMLElement::FindAttribute(), tinyxml2::XMLElement::ParseAttributes(), and tinyxml2::XMLPrinter::VisitEnter().
const XMLAttribute* tinyxml2::XMLAttribute::Next () const inline
The next attribute in the list.
Definition at line 790 of file tinyxml2.h.
References next.
Referenced by tinyxml2::XMLElement::ShallowClone(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::VisitEnter().
void tinyxml2::XMLAttribute::operator= (const XMLAttribute &) private
char * XMLAttribute::ParseDeep (char * p, bool processEntities) inline private
Definition at line 1090 of file tinyxml2_imp.h.
References tinyxml2::StrPair::ATTRIBUTE_VALUE, tinyxml2::StrPair::ATTRIBUTE_VALUE_LEAVE_ENTITIES, name, tinyxml2::StrPair::ParseName(), tinyxml2::StrPair::ParseText(), tinyxml2::XMLUtil::SkipWhiteSpace(), and value.
Referenced by tinyxml2::XMLElement::ParseAttributes().
 {
         // Parse using the name rules: bug fix, was using ParseText before
         p = name.ParseName( p );
         if ( !p || !*p ) return 0;
         // Skip white space before =
         p = XMLUtil::SkipWhiteSpace( p );
         if ( !p || *p != '=' ) return 0;
         ++p;    // move up to opening quote
         p = XMLUtil::SkipWhiteSpace( p );
         if ( *p != '\"' && *p != '\'' ) return 0;
         char endTag[2] = { *p, 0 };
         ++p;    // move past opening quote
         p = value.ParseText( p, endTag, processEntities ? StrPair::ATTRIBUTE_VALUE : StrPair::ATTRIBUTE_VALUE_LEAVE_ENTITIES );
         return p;
 }
int XMLAttribute::QueryBoolValue (bool * value) const inline
See QueryIntAttribute.
Definition at line 1138 of file tinyxml2_imp.h.
References tinyxml2::XMLUtil::ToBool(), Value(), tinyxml2::XML_NO_ERROR, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by BoolValue(), and tinyxml2::XMLElement::QueryBoolAttribute().
 {
         if ( XMLUtil::ToBool( Value(), value )) {
                 return XML_NO_ERROR;
         }
         return XML_WRONG_ATTRIBUTE_TYPE;
 }
int XMLAttribute::QueryDoubleValue (double * value) const inline
See QueryIntAttribute.
Definition at line 1157 of file tinyxml2_imp.h.
References tinyxml2::XMLUtil::ToDouble(), Value(), tinyxml2::XML_NO_ERROR, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by DoubleValue(), and tinyxml2::XMLElement::QueryDoubleAttribute().
 {
         if ( XMLUtil::ToDouble( Value(), value ))
                 return XML_NO_ERROR;
         return XML_WRONG_ATTRIBUTE_TYPE;
 }
int XMLAttribute::QueryFloatValue (float * value) const inline
See QueryIntAttribute.
Definition at line 1148 of file tinyxml2_imp.h.
References tinyxml2::XMLUtil::ToFloat(), Value(), tinyxml2::XML_NO_ERROR, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by FloatValue(), and tinyxml2::XMLElement::QueryFloatAttribute().
 {
         if ( XMLUtil::ToFloat( Value(), value ))
                 return XML_NO_ERROR;
         return XML_WRONG_ATTRIBUTE_TYPE;
 }
int XMLAttribute::QueryIntValue (int * value) const inline
QueryIntAttribute interprets the attribute as an integer, and returns the value in the provided paremeter. The function will return XML_NO_ERROR on success, and XML_WRONG_ATTRIBUTE_TYPE if the conversion is not successful.
Definition at line 1120 of file tinyxml2_imp.h.
References tinyxml2::XMLUtil::ToInt(), Value(), tinyxml2::XML_NO_ERROR, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by IntValue(), and tinyxml2::XMLElement::QueryIntAttribute().
 {
         if ( XMLUtil::ToInt( Value(), value ))
                 return XML_NO_ERROR;
         return XML_WRONG_ATTRIBUTE_TYPE;
 }
int XMLAttribute::QueryUnsignedValue (unsigned int * value) const inline
See QueryIntAttribute.
Definition at line 1129 of file tinyxml2_imp.h.
References tinyxml2::XMLUtil::ToUnsigned(), Value(), tinyxml2::XML_NO_ERROR, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryUnsignedAttribute(), and UnsignedValue().
 {
         if ( XMLUtil::ToUnsigned( Value(), value ))
                 return XML_NO_ERROR;
         return XML_WRONG_ATTRIBUTE_TYPE;
 }
void XMLAttribute::SetAttribute (const char * value) inline
Set the attribute to a string value.
Definition at line 1166 of file tinyxml2_imp.h.
References tinyxml2::StrPair::SetStr(), and value.
Referenced by tinyxml2::XMLElement::SetAttribute().
 {
         value.SetStr( v );
 }
void XMLAttribute::SetAttribute (int value) inline
Set the attribute to value.
Definition at line 1173 of file tinyxml2_imp.h.
References BUF_SIZE, tinyxml2::StrPair::SetStr(), tinyxml2::XMLUtil::ToStr(), and value.
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( v, buf, BUF_SIZE );
         value.SetStr( buf );
 }
void XMLAttribute::SetAttribute (unsigned value) inline
Set the attribute to value.
Definition at line 1182 of file tinyxml2_imp.h.
References BUF_SIZE, tinyxml2::StrPair::SetStr(), tinyxml2::XMLUtil::ToStr(), and value.
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( v, buf, BUF_SIZE );
         value.SetStr( buf );
 }
void XMLAttribute::SetAttribute (bool value) inline
Set the attribute to value.
Definition at line 1191 of file tinyxml2_imp.h.
References BUF_SIZE, tinyxml2::StrPair::SetStr(), tinyxml2::XMLUtil::ToStr(), and value.
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( v, buf, BUF_SIZE );
         value.SetStr( buf );
 }
void XMLAttribute::SetAttribute (double value) inline
Set the attribute to value.
Definition at line 1199 of file tinyxml2_imp.h.
References BUF_SIZE, tinyxml2::StrPair::SetStr(), tinyxml2::XMLUtil::ToStr(), and value.
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( v, buf, BUF_SIZE );
         value.SetStr( buf );
 }
void XMLAttribute::SetAttribute (float value) inline
Set the attribute to value.
Definition at line 1207 of file tinyxml2_imp.h.
References BUF_SIZE, tinyxml2::StrPair::SetStr(), tinyxml2::XMLUtil::ToStr(), and value.
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( v, buf, BUF_SIZE );
         value.SetStr( buf );
 }
void XMLAttribute::SetName (const char * name) inline private
Definition at line 1113 of file tinyxml2_imp.h.
References name, and tinyxml2::StrPair::SetStr().
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute().
 {
         name.SetStr( n );
 }
unsigned tinyxml2::XMLAttribute::UnsignedValue () const inline
Query as an unsigned integer. See IntAttribute()
Definition at line 798 of file tinyxml2.h.
References QueryUnsignedValue().
 { unsigned i=0; QueryUnsignedValue( &i );       return i; }
const char* tinyxml2::XMLAttribute::Value () const inline
The value of the attribute.
Definition at line 789 of file tinyxml2.h.
References tinyxml2::StrPair::GetStr(), and value.
Referenced by tinyxml2::XMLElement::Attribute(), QueryBoolValue(), QueryDoubleValue(), QueryFloatValue(), QueryIntValue(), QueryUnsignedValue(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::VisitEnter().
Friends And Related Function Documentation
friend class XMLElement friend
Definition at line 786 of file tinyxml2.h.
Member Data Documentation
MemPool* tinyxml2::XMLAttribute::memPool private
Definition at line 847 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute(), and tinyxml2::XMLElement::ParseAttributes().
StrPair tinyxml2::XMLAttribute::name mutable private
Definition at line 844 of file tinyxml2.h.
Referenced by Name(), ParseDeep(), and SetName().
XMLAttribute* tinyxml2::XMLAttribute::next private
Definition at line 846 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::DeleteAttribute(), tinyxml2::XMLElement::FindAttribute(), tinyxml2::XMLElement::FindOrCreateAttribute(), Next(), tinyxml2::XMLElement::ParseAttributes(), and tinyxml2::XMLElement::~XMLElement().
StrPair tinyxml2::XMLAttribute::value mutable private
Definition at line 845 of file tinyxml2.h.
Referenced by ParseDeep(), SetAttribute(), and Value().
The documentation for this class was generated from the following files:
src/parsing/include/antioch/tinyxml2.h
src/parsing/include/antioch/tinyxml2_imp.h