antioch-0.4.0: tinyxml2::XMLConstHandle Class Reference
tinyxml2::XMLConstHandle Class Reference
#include <tinyxml2.h>
Public Member Functions
XMLConstHandle (const XMLNode *_node)
XMLConstHandle (const XMLNode &_node)
XMLConstHandle (const XMLConstHandle &ref)
XMLConstHandle & operator= (const XMLConstHandle &ref)
const XMLConstHandle FirstChild () const
const XMLConstHandle FirstChildElement (const char *value=0) const
const XMLConstHandle LastChild () const
const XMLConstHandle LastChildElement (const char *_value=0) const
const XMLConstHandle PreviousSibling () const
const XMLConstHandle PreviousSiblingElement (const char *_value=0) const
const XMLConstHandle NextSibling () const
const XMLConstHandle NextSiblingElement (const char *_value=0) const
const XMLNode * ToNode () const
const XMLElement * ToElement () const
const XMLText * ToText () const
const XMLUnknown * ToUnknown () const
const XMLDeclaration * ToDeclaration () const
Private Attributes
const XMLNode * node
Detailed Description
A variant of the XMLHandle class for working with const XMLNodes and Documents. It is the same in all regards, except for the 'const' qualifiers. See XMLHandle for API.
Definition at line 1335 of file tinyxml2.h.
Constructor & Destructor Documentation
tinyxml2::XMLConstHandle::XMLConstHandle (const XMLNode * _node) inline
Definition at line 1338 of file tinyxml2.h.
References node.
Referenced by FirstChild(), FirstChildElement(), LastChild(), LastChildElement(), NextSibling(), NextSiblingElement(), PreviousSibling(), and PreviousSiblingElement().
 { node = _node; }
tinyxml2::XMLConstHandle::XMLConstHandle (const XMLNode & _node) inline
Definition at line 1339 of file tinyxml2.h.
References node.
 { node = &_node; }
tinyxml2::XMLConstHandle::XMLConstHandle (const XMLConstHandle & ref) inline
Definition at line 1340 of file tinyxml2.h.
References node.
 { node = ref.node; }
Member Function Documentation
const XMLConstHandle tinyxml2::XMLConstHandle::FirstChild () const inline
Definition at line 1344 of file tinyxml2.h.
References tinyxml2::XMLNode::FirstChild(), node, and XMLConstHandle().
 { return XMLConstHandle( node ? node->FirstChild() : 0 ); }
const XMLConstHandle tinyxml2::XMLConstHandle::FirstChildElement (const char * value = 0) const inline
Definition at line 1345 of file tinyxml2.h.
References tinyxml2::XMLNode::FirstChildElement(), node, and XMLConstHandle().
 { return XMLConstHandle( node ? node->FirstChildElement( value ) : 0 ); }
const XMLConstHandle tinyxml2::XMLConstHandle::LastChild () const inline
Definition at line 1346 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChild(), node, and XMLConstHandle().
 { return XMLConstHandle( node ? node->LastChild() : 0 ); }
const XMLConstHandle tinyxml2::XMLConstHandle::LastChildElement (const char * _value = 0) const inline
Definition at line 1347 of file tinyxml2.h.
References tinyxml2::XMLNode::LastChildElement(), node, and XMLConstHandle().
 { return XMLConstHandle( node ? node->LastChildElement( _value ) : 0 ); }
const XMLConstHandle tinyxml2::XMLConstHandle::NextSibling () const inline
Definition at line 1350 of file tinyxml2.h.
References tinyxml2::XMLNode::NextSibling(), node, and XMLConstHandle().
 { return XMLConstHandle( node ? node->NextSibling() : 0 ); }
const XMLConstHandle tinyxml2::XMLConstHandle::NextSiblingElement (const char * _value = 0) const inline
Definition at line 1351 of file tinyxml2.h.
References tinyxml2::XMLNode::NextSiblingElement(), node, and XMLConstHandle().
 { return XMLConstHandle( node ? node->NextSiblingElement( _value ) : 0 ); }
XMLConstHandle& tinyxml2::XMLConstHandle::operator= (const XMLConstHandle & ref) inline
Definition at line 1342 of file tinyxml2.h.
References node.
 { node = ref.node; return *this; }
const XMLConstHandle tinyxml2::XMLConstHandle::PreviousSibling () const inline
Definition at line 1348 of file tinyxml2.h.
References node, tinyxml2::XMLNode::PreviousSibling(), and XMLConstHandle().
 { return XMLConstHandle( node ? node->PreviousSibling() : 0 ); }
const XMLConstHandle tinyxml2::XMLConstHandle::PreviousSiblingElement (const char * _value = 0) const inline
Definition at line 1349 of file tinyxml2.h.
References node, tinyxml2::XMLNode::PreviousSiblingElement(), and XMLConstHandle().
 { return XMLConstHandle( node ? node->PreviousSiblingElement( _value ) : 0 ); }
const XMLDeclaration* tinyxml2::XMLConstHandle::ToDeclaration () const inline
Definition at line 1358 of file tinyxml2.h.
References node, and tinyxml2::XMLNode::ToDeclaration().
 { return ( ( node && node->ToDeclaration() ) ? node->ToDeclaration() : 0 ); }
const XMLElement* tinyxml2::XMLConstHandle::ToElement () const inline
Definition at line 1355 of file tinyxml2.h.
References node, and tinyxml2::XMLNode::ToElement().
 { return ( ( node && node->ToElement() ) ? node->ToElement() : 0 ); }
const XMLNode* tinyxml2::XMLConstHandle::ToNode () const inline
Definition at line 1354 of file tinyxml2.h.
References node.
 { return node; }
const XMLText* tinyxml2::XMLConstHandle::ToText () const inline
Definition at line 1356 of file tinyxml2.h.
References node, and tinyxml2::XMLNode::ToText().
 { return ( ( node && node->ToText() ) ? node->ToText() : 0 ); }
const XMLUnknown* tinyxml2::XMLConstHandle::ToUnknown () const inline
Definition at line 1357 of file tinyxml2.h.
References node, and tinyxml2::XMLNode::ToUnknown().
 { return ( ( node && node->ToUnknown() ) ? node->ToUnknown() : 0 ); }
Member Data Documentation
const XMLNode* tinyxml2::XMLConstHandle::node private
Definition at line 1361 of file tinyxml2.h.
Referenced by FirstChild(), FirstChildElement(), LastChild(), LastChildElement(), NextSibling(), NextSiblingElement(), operator=(), PreviousSibling(), PreviousSiblingElement(), ToDeclaration(), ToElement(), ToNode(), ToText(), ToUnknown(), and XMLConstHandle().
The documentation for this class was generated from the following file:
src/parsing/include/antioch/tinyxml2.h