antioch-0.4.0: tinyxml2::XMLPrinter Class Reference
tinyxml2::XMLPrinter Class Reference
#include <tinyxml2.h>
Public Member Functions
XMLPrinter (FILE *file=0, bool compact=false)
~XMLPrinter ()
void PushHeader (bool writeBOM, bool writeDeclaration)
void OpenElement (const char *name)
void PushAttribute (const char *name, const char *value)
If streaming, add an attribute to an open element.
void PushAttribute (const char *name, int value)
void PushAttribute (const char *name, unsigned value)
void PushAttribute (const char *name, bool value)
void PushAttribute (const char *name, double value)
void CloseElement ()
If streaming, close the Element.
void PushText (const char *text, bool cdata=false)
Add a text node.
void PushText (int value)
Add a text node from an integer.
void PushText (unsigned value)
Add a text node from an unsigned.
void PushText (bool value)
Add a text node from a bool.
void PushText (float value)
Add a text node from a float.
void PushText (double value)
Add a text node from a double.
void PushComment (const char *comment)
Add a comment.
void PushDeclaration (const char *value)
void PushUnknown (const char *value)
virtual bool VisitEnter (const XMLDocument &)
Visit a document.
virtual bool VisitExit (const XMLDocument &)
Visit a document.
virtual bool VisitEnter (const XMLElement &element, const XMLAttribute *attribute)
Visit an element.
virtual bool VisitExit (const XMLElement &element)
Visit an element.
virtual bool Visit (const XMLText &text)
Visit a text node.
virtual bool Visit (const XMLComment &comment)
Visit a comment node.
virtual bool Visit (const XMLDeclaration &declaration)
Visit a declaration.
virtual bool Visit (const XMLUnknown &unknown)
Visit an unknown node.
const char * CStr () const
int CStrSize () const
Private Types
enum { ENTITY_RANGE = 64, BUF_SIZE = 200 }
Private Member Functions
void SealElement ()
void PrintSpace (int depth)
void PrintString (const char *, bool restrictedEntitySet)
void Print (const char *format,...)
Private Attributes
bool elementJustOpened
bool firstElement
FILE * fp
int depth
int textDepth
bool processEntities
bool compactMode
bool entityFlag [ENTITY_RANGE]
bool restrictedEntityFlag [ENTITY_RANGE]
DynArray< const char *, 10 > stack
DynArray< char, 20 > buffer
Detailed Description
Printing functionality. The XMLPrinter gives you more options than the XMLDocument::Print() method.
It can:
Print to memory.
Print to a file you provide.
Print XML without a XMLDocument.
Print to Memory
XMLPrinter printer;
doc->Print(&printer);
SomeFunction(printer.CStr());
Print to a File
You provide the file pointer.
XMLPrinter printer(fp);
doc.Print(&printer);
Print without a XMLDocument
When loading, an XML parser is very useful. However, sometimes when saving, it just gets in the way. The code is often set up for streaming, and constructing the DOM is just overhead.
The Printer supports the streaming case. The following code prints out a trivially simple XML file without ever creating an XML document.
XMLPrinter printer(fp);
printer.OpenElement("foo");
printer.PushAttribute("foo", "bar");
printer.CloseElement();
Definition at line 1407 of file tinyxml2.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
ENTITY_RANGE
BUF_SIZE
Definition at line 1490 of file tinyxml2.h.
              {
                 ENTITY_RANGE = 64,
                 BUF_SIZE = 200
         };
Constructor & Destructor Documentation
XMLPrinter::XMLPrinter (FILE * file = 0, bool compact = false) inline
Construct the printer. If the FILE* is specified, this will print to the FILE. Else it will print to memory, and the result is available in CStr(). If 'compact' is set to true, then output is created with only required whitespace and newlines.
Definition at line 1801 of file tinyxml2_imp.h.
References buffer, ENTITY_RANGE, entityFlag, std::int, tinyxml2::DynArray< T, INIT >::Push(), restrictedEntityFlag, and TIXMLASSERT.
                                                  :
         elementJustOpened( false ),
         firstElement( true ),
         fp( file ),
         depth( 0 ),
         textDepth( -1 ),
         processEntities( true ),
         compactMode( compact )
 {
         for( int i=0; i<ENTITY_RANGE; ++i ) {
                 entityFlag[i] = false;
                 restrictedEntityFlag[i] = false;
         }
         for( int i=0; i<NUM_ENTITIES; ++i ) {
                 TIXMLASSERT( entities[i].value < ENTITY_RANGE );
                 if ( entities[i].value < ENTITY_RANGE ) {
                         entityFlag[ (int)entities[i].value ] = true;
                 }
         }
         restrictedEntityFlag[(int)'&'] = true;
         restrictedEntityFlag[(int)'<'] = true;
         restrictedEntityFlag[(int)'>'] = true;  // not required, but consistency is nice
         buffer.Push( 0 );
 }
tinyxml2::XMLPrinter::~XMLPrinter () inline
Definition at line 1417 of file tinyxml2.h.
 {}
Member Function Documentation
void XMLPrinter::CloseElement () inline
If streaming, close the Element.
Definition at line 1992 of file tinyxml2_imp.h.
References compactMode, depth, elementJustOpened, tinyxml2::DynArray< T, INIT >::Pop(), Print(), PrintSpace(), stack, and textDepth.
Referenced by VisitExit().
 {
         --depth;
         const char* name = stack.Pop();
         if ( elementJustOpened ) {
                 Print( "/>" );
         }
         else {
                 if ( textDepth < 0 && !compactMode) {
                         Print( "\n" );
                         PrintSpace( depth );
                 }
                 Print( "</%s>", name );
         }
         if ( textDepth == depth )
                 textDepth = -1;
         if ( depth == 0 && !compactMode)
                 Print( "\n" );
         elementJustOpened = false;
 }
const char* tinyxml2::XMLPrinter::CStr () const inline
If in print to memory mode, return a pointer to the XML file in memory.
Definition at line 1468 of file tinyxml2.h.
References buffer, and tinyxml2::DynArray< T, INIT >::Mem().
 { return buffer.Mem(); }
int tinyxml2::XMLPrinter::CStrSize () const inline
If in print to memory mode, return the size of the XML file in memory. (Note the size returned includes the terminating null.)
Definition at line 1474 of file tinyxml2.h.
References buffer, and tinyxml2::DynArray< T, INIT >::Size().
 { return buffer.Size(); }
void XMLPrinter::OpenElement (const char * name) inline
If streaming, start writing an element. The element must be closed with CloseElement()
Definition at line 1926 of file tinyxml2_imp.h.
References compactMode, depth, elementJustOpened, firstElement, Print(), PrintSpace(), tinyxml2::DynArray< T, INIT >::Push(), SealElement(), stack, and textDepth.
Referenced by VisitEnter().
 {
         if ( elementJustOpened ) {
                 SealElement();
         }
         stack.Push( name );
         if ( textDepth < 0 && !firstElement && !compactMode ) {
                 Print( "\n" );
                 PrintSpace( depth );
         }
         Print( "<%s", name );
         elementJustOpened = true;
         firstElement = false;
         ++depth;
 }
void XMLPrinter::Print (const char * format, ...) inline private
Definition at line 1828 of file tinyxml2_imp.h.
References buffer, and tinyxml2::DynArray< T, INIT >::PushArr().
Referenced by CloseElement(), OpenElement(), PrintSpace(), PrintString(), PushAttribute(), PushComment(), PushDeclaration(), PushHeader(), PushText(), PushUnknown(), and SealElement().
 {
     va_list     va;
     va_start( va, format );
         if ( fp ) {
                 vfprintf( fp, format, va );
         }
         else {
                 // This seems brutally complex. Haven't figured out a better
                 // way on windows.
                 #ifdef _MSC_VER
                         int len = -1;
                         int expand = 1000;
                         while ( len < 0 ) {
                                 len = vsnprintf_s( accumulator.Mem(), accumulator.Capacity(), _TRUNCATE, format, va );
                                 if ( len < 0 ) {
                                         expand *= 3/2;
                                         accumulator.PushArr( expand );
                                 }
                         }
                         char* p = buffer.PushArr( len ) - 1;
                         memcpy( p, accumulator.Mem(), len+1 );
                 #else
                         int len = vsnprintf( 0, 0, format, va );
                         // Close out and re-start the va-args
                         va_end( va );
                         va_start( va, format );
                         char* p = buffer.PushArr( len ) - 1;
                         vsnprintf( p, len+1, format, va );
                 #endif
         }
     va_end( va );
 }
void XMLPrinter::PrintSpace (int depth) inline private
Definition at line 1865 of file tinyxml2_imp.h.
References depth, and Print().
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), and PushUnknown().
 {
         for( int i=0; i<depth; ++i ) {
                 Print( "    " );
         }
 }
void XMLPrinter::PrintString (const char * p, bool restrictedEntitySet) inline private
Definition at line 1874 of file tinyxml2_imp.h.
References ENTITY_RANGE, entityFlag, Print(), processEntities, and restrictedEntityFlag.
Referenced by PushAttribute(), and PushText().
 {
         // Look for runs of bytes between entities to print.
         const char* q = p;
         const bool* flag = restricted ? restrictedEntityFlag : entityFlag;
         if ( processEntities ) {
                 while ( *q ) {
                         // Remember, char is sometimes signed. (How many times has that bitten me?)
                         if ( *q > 0 && *q < ENTITY_RANGE ) {
                                 // Check for entities. If one is found, flush
                                 // the stream up until the entity, write the
                                 // entity, and keep looking.
                                 if ( flag[(unsigned)(*q)] ) {
                                         while ( p < q ) {
                                                 Print( "%c", *p );
                                                 ++p;
                                         }
                                         for( int i=0; i<NUM_ENTITIES; ++i ) {
                                                 if ( entities[i].value == *q ) {
                                                         Print( "&%s;", entities[i].pattern );
                                                         break;
                                                 }
                                         }
                                         ++p;
                                 }
                         }
                         ++q;
                 }
         }
         // Flush the remaining string. This will be the entire
         // string if an entity wasn't found.
         if ( !processEntities || (q-p > 0) ) {
                 Print( "%s", p );
         }
 }
void XMLPrinter::PushAttribute (const char * name, const char * value) inline
If streaming, add an attribute to an open element.
Definition at line 1946 of file tinyxml2_imp.h.
References elementJustOpened, Print(), PrintString(), and TIXMLASSERT.
Referenced by PushAttribute(), and VisitEnter().
 {
         TIXMLASSERT( elementJustOpened );
         Print( " %s=\"", name );
         PrintString( value, false );
         Print( "\"" );
 }
void XMLPrinter::PushAttribute (const char * name, int value) inline
Definition at line 1956 of file tinyxml2_imp.h.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( v, buf, BUF_SIZE );
         PushAttribute( name, buf );
 }
void XMLPrinter::PushAttribute (const char * name, unsigned value) inline
Definition at line 1965 of file tinyxml2_imp.h.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( v, buf, BUF_SIZE );
         PushAttribute( name, buf );
 }
void XMLPrinter::PushAttribute (const char * name, bool value) inline
Definition at line 1974 of file tinyxml2_imp.h.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( v, buf, BUF_SIZE );
         PushAttribute( name, buf );
 }
void XMLPrinter::PushAttribute (const char * name, double value) inline
Definition at line 1983 of file tinyxml2_imp.h.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( v, buf, BUF_SIZE );
         PushAttribute( name, buf );
 }
void XMLPrinter::PushComment (const char * comment) inline
Add a comment.
Definition at line 2089 of file tinyxml2_imp.h.
References compactMode, depth, elementJustOpened, firstElement, Print(), PrintSpace(), SealElement(), and textDepth.
Referenced by Visit().
 {
         if ( elementJustOpened ) {
                 SealElement();
         }
         if ( textDepth < 0 && !firstElement && !compactMode) {
                 Print( "\n" );
                 PrintSpace( depth );
         }
         firstElement = false;
         Print( "<!--%s-->", comment );
 }
void XMLPrinter::PushDeclaration (const char * value) inline
Definition at line 2104 of file tinyxml2_imp.h.
References compactMode, depth, elementJustOpened, firstElement, Print(), PrintSpace(), SealElement(), and textDepth.
Referenced by PushHeader(), and Visit().
 {
         if ( elementJustOpened ) {
                 SealElement();
         }
         if ( textDepth < 0 && !firstElement && !compactMode) {
                 Print( "\n" );
                 PrintSpace( depth );
         }
         firstElement = false;
         Print( "<?%s?>", value );
 }
void XMLPrinter::PushHeader (bool writeBOM, bool writeDeclaration) inline
If streaming, write the BOM and declaration.
Definition at line 1913 of file tinyxml2_imp.h.
References Print(), and PushDeclaration().
Referenced by VisitEnter().
 {
         static const unsigned char bom[] = { TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, TIXML_UTF_LEAD_2, 0 };
         if ( writeBOM ) {
                 Print( "%s", bom );
         }
         if ( writeDec ) {
                 PushDeclaration( "xml version=\"1.0\"" );
         }
 }
void XMLPrinter::PushText (const char * text, bool cdata = false) inline
Add a text node.
Definition at line 2025 of file tinyxml2_imp.h.
References depth, elementJustOpened, Print(), PrintString(), SealElement(), and textDepth.
Referenced by PushText(), and Visit().
 {
         textDepth = depth-1;
         if ( elementJustOpened ) {
                 SealElement();
         }
         if ( cdata ) {
                 Print( "<![CDATA[" );
                 Print( "%s", text );
                 Print( "]]>" );
         }
         else {
                 PrintString( text, true );
         }
 }
void XMLPrinter::PushText (int value) inline
Add a text node from an integer.
Definition at line 2044 of file tinyxml2_imp.h.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( value, buf, BUF_SIZE );
         PushText( buf, false );
 }
void XMLPrinter::PushText (unsigned value) inline
Add a text node from an unsigned.
Definition at line 2053 of file tinyxml2_imp.h.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( value, buf, BUF_SIZE );
         PushText( buf, false );
 }
void XMLPrinter::PushText (bool value) inline
Add a text node from a bool.
Definition at line 2062 of file tinyxml2_imp.h.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( value, buf, BUF_SIZE );
         PushText( buf, false );
 }
void XMLPrinter::PushText (float value) inline
Add a text node from a float.
Definition at line 2071 of file tinyxml2_imp.h.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( value, buf, BUF_SIZE );
         PushText( buf, false );
 }
void XMLPrinter::PushText (double value) inline
Add a text node from a double.
Definition at line 2080 of file tinyxml2_imp.h.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
 {
         char buf[BUF_SIZE];
         XMLUtil::ToStr( value, buf, BUF_SIZE );
         PushText( buf, false );
 }
void XMLPrinter::PushUnknown (const char * value) inline
Definition at line 2119 of file tinyxml2_imp.h.
References compactMode, depth, elementJustOpened, firstElement, Print(), PrintSpace(), SealElement(), and textDepth.
Referenced by Visit().
 {
         if ( elementJustOpened ) {
                 SealElement();
         }
         if ( textDepth < 0 && !firstElement && !compactMode) {
                 Print( "\n" );
                 PrintSpace( depth );
         }
         firstElement = false;
         Print( "<!%s>", value );
 }
void XMLPrinter::SealElement () inline private
Definition at line 2017 of file tinyxml2_imp.h.
References elementJustOpened, and Print().
Referenced by OpenElement(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
 {
         elementJustOpened = false;
         Print( ">" );
 }
bool XMLPrinter::Visit (const XMLText &) inline virtual
Visit a text node.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2165 of file tinyxml2_imp.h.
References tinyxml2::XMLText::CData(), PushText(), and tinyxml2::XMLNode::Value().
 {
         PushText( text.Value(), text.CData() );
         return true;
 }
bool XMLPrinter::Visit (const XMLComment &) inline virtual
Visit a comment node.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2173 of file tinyxml2_imp.h.
References PushComment(), and tinyxml2::XMLNode::Value().
 {
         PushComment( comment.Value() );
         return true;
 }
bool XMLPrinter::Visit (const XMLDeclaration &) inline virtual
Visit a declaration.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2180 of file tinyxml2_imp.h.
References PushDeclaration(), and tinyxml2::XMLNode::Value().
 {
         PushDeclaration( declaration.Value() );
         return true;
 }
bool XMLPrinter::Visit (const XMLUnknown &) inline virtual
Visit an unknown node.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2188 of file tinyxml2_imp.h.
References PushUnknown(), and tinyxml2::XMLNode::Value().
 {
         PushUnknown( unknown.Value() );
         return true;
 }
bool XMLPrinter::VisitEnter (const XMLDocument &) inline virtual
Visit a document.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2134 of file tinyxml2_imp.h.
References tinyxml2::XMLDocument::HasBOM(), tinyxml2::XMLDocument::ProcessEntities(), processEntities, and PushHeader().
 {
         processEntities = doc.ProcessEntities();
         if ( doc.HasBOM() ) {
                 PushHeader( true, false );
         }
         return true;
 }
bool XMLPrinter::VisitEnter (const XMLElement & , const XMLAttribute *) inline virtual
Visit an element.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2145 of file tinyxml2_imp.h.
References tinyxml2::XMLAttribute::Name(), tinyxml2::XMLElement::Name(), tinyxml2::XMLAttribute::Next(), OpenElement(), PushAttribute(), and tinyxml2::XMLAttribute::Value().
 {
         OpenElement( element.Name() );
         while ( attribute ) {
                 PushAttribute( attribute->Name(), attribute->Value() );
                 attribute = attribute->Next();
         }
         return true;
 }
virtual bool tinyxml2::XMLPrinter::VisitExit (const XMLDocument &) inline virtual
Visit a document.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 1454 of file tinyxml2.h.
 { return true; }
bool XMLPrinter::VisitExit (const XMLElement &) inline virtual
Visit an element.
Reimplemented from tinyxml2::XMLVisitor.
Definition at line 2157 of file tinyxml2_imp.h.
References CloseElement().
 {
         CloseElement();
         return true;
 }
Member Data Documentation
DynArray< char, 20 > tinyxml2::XMLPrinter::buffer private
Definition at line 1498 of file tinyxml2.h.
Referenced by CStr(), CStrSize(), Print(), and XMLPrinter().
bool tinyxml2::XMLPrinter::compactMode private
Definition at line 1488 of file tinyxml2.h.
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), and PushUnknown().
int tinyxml2::XMLPrinter::depth private
Definition at line 1485 of file tinyxml2.h.
Referenced by CloseElement(), OpenElement(), PrintSpace(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
bool tinyxml2::XMLPrinter::elementJustOpened private
Definition at line 1482 of file tinyxml2.h.
Referenced by CloseElement(), OpenElement(), PushAttribute(), PushComment(), PushDeclaration(), PushText(), PushUnknown(), and SealElement().
bool tinyxml2::XMLPrinter::entityFlag[ENTITY_RANGE] private
Definition at line 1494 of file tinyxml2.h.
Referenced by PrintString(), and XMLPrinter().
bool tinyxml2::XMLPrinter::firstElement private
Definition at line 1483 of file tinyxml2.h.
Referenced by OpenElement(), PushComment(), PushDeclaration(), and PushUnknown().
FILE* tinyxml2::XMLPrinter::fp private
Definition at line 1484 of file tinyxml2.h.
bool tinyxml2::XMLPrinter::processEntities private
Definition at line 1487 of file tinyxml2.h.
Referenced by PrintString(), and VisitEnter().
bool tinyxml2::XMLPrinter::restrictedEntityFlag[ENTITY_RANGE] private
Definition at line 1495 of file tinyxml2.h.
Referenced by PrintString(), and XMLPrinter().
DynArray< const char*, 10 > tinyxml2::XMLPrinter::stack private
Definition at line 1497 of file tinyxml2.h.
Referenced by CloseElement(), and OpenElement().
int tinyxml2::XMLPrinter::textDepth private
Definition at line 1486 of file tinyxml2.h.
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
The documentation for this class was generated from the following files:
src/parsing/include/antioch/tinyxml2.h
src/parsing/include/antioch/tinyxml2_imp.h