antioch-0.4.0: tinyxml2::XMLVisitor Class Reference
tinyxml2::XMLVisitor Class Reference
#include <tinyxml2.h>
Public Member Functions
virtual ~XMLVisitor ()
virtual bool VisitEnter (const XMLDocument &)
Visit a document.
virtual bool VisitExit (const XMLDocument &)
Visit a document.
virtual bool VisitEnter (const XMLElement &, const XMLAttribute *)
Visit an element.
virtual bool VisitExit (const XMLElement &)
Visit an element.
virtual bool Visit (const XMLDeclaration &)
Visit a declaration.
virtual bool Visit (const XMLText &)
Visit a text node.
virtual bool Visit (const XMLComment &)
Visit a comment node.
virtual bool Visit (const XMLUnknown &)
Visit an unknown node.
Detailed Description
Implements the interface to the "Visitor pattern" (see the Accept() method.) If you call the Accept() method, it requires being passed a XMLVisitor class to handle callbacks. For nodes that contain other nodes (Document, Element) you will get called with a VisitEnter/VisitExit pair. Nodes that are always leafs are simply called with Visit().
If you return 'true' from a Visit method, recursive parsing will continue. If you return false, no children of this node or its sibilings will be visited.
All flavors of Visit methods have a default implementation that returns 'true' (continue visiting). You need to only override methods that are interesting to you.
Generally Accept() is called on the TiXmlDocument, although all nodes support visiting.
You should never change the document from a callback.
See also
XMLNode::Accept()
Definition at line 346 of file tinyxml2.h.
Constructor & Destructor Documentation
virtual tinyxml2::XMLVisitor::~XMLVisitor () inline virtual
Definition at line 349 of file tinyxml2.h.
 {}
Member Function Documentation
virtual bool tinyxml2::XMLVisitor::Visit (const XMLDeclaration &) inline virtual
Visit a declaration.
Reimplemented in tinyxml2::XMLPrinter.
Definition at line 362 of file tinyxml2.h.
Referenced by tinyxml2::XMLText::Accept(), tinyxml2::XMLComment::Accept(), tinyxml2::XMLDeclaration::Accept(), and tinyxml2::XMLUnknown::Accept().
 { return true; }
virtual bool tinyxml2::XMLVisitor::Visit (const XMLText &) inline virtual
Visit a text node.
Reimplemented in tinyxml2::XMLPrinter.
Definition at line 364 of file tinyxml2.h.
 { return true; }
virtual bool tinyxml2::XMLVisitor::Visit (const XMLComment &) inline virtual
Visit a comment node.
Reimplemented in tinyxml2::XMLPrinter.
Definition at line 366 of file tinyxml2.h.
 { return true; }
virtual bool tinyxml2::XMLVisitor::Visit (const XMLUnknown &) inline virtual
Visit an unknown node.
Reimplemented in tinyxml2::XMLPrinter.
Definition at line 368 of file tinyxml2.h.
 { return true; }
virtual bool tinyxml2::XMLVisitor::VisitEnter (const XMLDocument &) inline virtual
Visit a document.
Reimplemented in tinyxml2::XMLPrinter.
Definition at line 352 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::Accept(), and tinyxml2::XMLDocument::Accept().
 { return true; }
virtual bool tinyxml2::XMLVisitor::VisitEnter (const XMLElement & , const XMLAttribute *) inline virtual
Visit an element.
Reimplemented in tinyxml2::XMLPrinter.
Definition at line 357 of file tinyxml2.h.
 { return true; }
virtual bool tinyxml2::XMLVisitor::VisitExit (const XMLDocument &) inline virtual
Visit a document.
Reimplemented in tinyxml2::XMLPrinter.
Definition at line 354 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::Accept(), and tinyxml2::XMLDocument::Accept().
 { return true; }
virtual bool tinyxml2::XMLVisitor::VisitExit (const XMLElement &) inline virtual
Visit an element.
Reimplemented in tinyxml2::XMLPrinter.
Definition at line 359 of file tinyxml2.h.
 { return true; }
The documentation for this class was generated from the following file:
src/parsing/include/antioch/tinyxml2.h