antioch-0.4.0: test/berthelothercourtessen_rate_unit.C File Reference
berthelothercourtessen_rate_unit.C File Reference
#include <limits>
#include <vector>
#include "antioch/berthelothercourtessen_rate.h"
Functions
template<typename Scalar >
int check_rate_and_derivative (const Scalar &rate_exact, const Scalar &derive_exact, const Scalar &rate, const Scalar &derive, const Scalar &T)
template<typename Scalar >
int test_values (const Scalar &Cf, const Scalar &eta, const Scalar &D, const Scalar &Tref, const Antioch::BerthelotHercourtEssenRate< Scalar > &berthelothercourtessen_rate)
template<typename Scalar >
int tester ()
int main ()
Function Documentation
template<typename Scalar > int check_rate_and_derivative (const Scalar & rate_exact, const Scalar & derive_exact, const Scalar & rate, const Scalar & derive, const Scalar & T)
Definition at line 35 of file berthelothercourtessen_rate_unit.C.
Referenced by test_values().
 {
     const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 2;
     int return_flag(0);
     if( abs( (rate - rate_exact)/rate_exact ) > tol )
       {
         std::cout << std::scientific << std::setprecision(16)
                   << "Error: Mismatch in rate values." << std::endl
                   << "T = " << T << " K" << std::endl
                   << "rate(T) = " << rate << std::endl
                   << "rate_exact = " << rate_exact << std::endl
                   << "relative difference = " <<  abs( (rate - rate_exact)/rate_exact ) << std::endl
                   << "tolerance = " <<  tol << std::endl;
         return_flag = 1;
       }
     if( abs( (derive - derive_exact)/derive_exact ) > tol )
       {
         std::cout << std::scientific << std::setprecision(16)
                   << "Error: Mismatch in rate derivative values." << std::endl
                   << "T = " << T << " K" << std::endl
                   << "drate_dT(T) = " << derive << std::endl
                   << "derive_exact = " << derive_exact << std::endl
                   << "relative difference = " <<  abs( (derive - derive_exact)/derive_exact ) << std::endl
                   << "tolerance = " <<  tol << std::endl;
         return_flag = 1;
       }
      return return_flag;
 }
int main ()
Definition at line 159 of file berthelothercourtessen_rate_unit.C.
 {
   return (tester<double>() ||
           tester<long double>() ||
           tester<float>());
 }
template<typename Scalar > int test_values (const Scalar & Cf, const Scalar & eta, const Scalar & D, const Scalar & Tref, const Antioch::BerthelotHercourtEssenRate< Scalar > & berthelothercourtessen_rate)
Definition at line 69 of file berthelothercourtessen_rate_unit.C.
References check_rate_and_derivative(), Antioch::BerthelotHercourtEssenRate< CoeffType >::derivative(), std::pow(), and Antioch::BerthelotHercourtEssenRate< CoeffType >::rate_and_derivative.
Referenced by tester().
 {
   using std::abs;
   using std::exp;
   using std::pow;
   int return_flag = 0;
   for(Scalar T = 300.1L; T <= 2500.1L; T += 10.L)
   {
     const Scalar rate_exact = Cf*pow(T/Tref,eta)*exp(D*T);
     const Scalar derive_exact = Cf * pow(T/Tref,eta) * exp(D*T) * (D + eta/T);
     Antioch::KineticsConditions<Scalar> cond(T);
 // KineticsConditions
     Scalar rate = berthelothercourtessen_rate(cond);
     Scalar deriveRate = berthelothercourtessen_rate.derivative(cond);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
     berthelothercourtessen_rate.rate_and_derivative(cond,rate,deriveRate);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
 // T
     rate = berthelothercourtessen_rate(T);
     deriveRate = berthelothercourtessen_rate.derivative(T);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
     berthelothercourtessen_rate.rate_and_derivative(T,rate,deriveRate);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
   }
   return return_flag;
 }
template<typename Scalar > int tester ()
Definition at line 109 of file berthelothercourtessen_rate_unit.C.
References Antioch::KineticsModel::D, Antioch::BerthelotHercourtEssenRate< CoeffType >::reset_coefs(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Cf(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_D(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_eta(), Antioch::BerthelotHercourtEssenRate< CoeffType >::set_Tref(), test_values(), and Antioch::KineticsModel::Tref().
 {
   Scalar Cf  = 1.4L;
   Scalar eta = 1.2L;
   Scalar D   = -5.0L;
   Scalar Tref   = 1.0L;
   Antioch::BerthelotHercourtEssenRate<Scalar> berthelothercourtessen_rate(Cf,eta,D);
   int return_flag = test_values(Cf,eta,D,Tref,berthelothercourtessen_rate);
   Cf  = 1e-7L;
   eta = 0.6L;
   D   = 1e-3L;
   Tref   = 298.0L;
   berthelothercourtessen_rate.set_Cf(Cf);
   berthelothercourtessen_rate.set_eta(eta);
   berthelothercourtessen_rate.set_D(D);
   berthelothercourtessen_rate.set_Tref(Tref);
   return_flag = test_values(Cf,eta,D,Tref,berthelothercourtessen_rate) || return_flag;
   Cf  = 2.1e-7L;
   eta = 0.35L;
   D   = 8.1e-3L;
   std::vector<Scalar> values(3);
   values[0] = Cf;
   values[1] = eta;
   values[2] = D;
   berthelothercourtessen_rate.reset_coefs(values);
   return_flag = test_values(Cf,eta,D,Tref,berthelothercourtessen_rate) || return_flag;
   Cf  = 2.1e-11L;
   eta = -0.35L;
   D   = -2.1;
   Tref   = 300.L;
   values.resize(4);
   values[0] = Cf;
   values[1] = eta;
   values[2] = D;
   values[3] = Tref;
   berthelothercourtessen_rate.reset_coefs(values);
   return_flag = test_values(Cf,eta,D,Tref,berthelothercourtessen_rate) || return_flag;
   return return_flag;
 }