antioch-0.4.0: test/berthelot_rate_unit.C File Reference
berthelot_rate_unit.C File Reference
#include <limits>
#include <vector>
#include "antioch/berthelot_rate.h"
Functions
template<typename Scalar >
int check_rate_and_derivative (const Scalar &rate_exact, const Scalar &derive_exact, const Scalar &rate, const Scalar &derive, const Scalar &T)
template<typename Scalar >
int test_values (const Scalar &Cf, const Scalar &D, const Antioch::BerthelotRate< Scalar > &berthelot_rate)
template<typename Scalar >
int tester ()
int main ()
Function Documentation
template<typename Scalar > int check_rate_and_derivative (const Scalar & rate_exact, const Scalar & derive_exact, const Scalar & rate, const Scalar & derive, const Scalar & T)
Definition at line 34 of file berthelot_rate_unit.C.
Referenced by test_values().
 {
     const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 2;
     int return_flag(0);
     if( abs( (rate - rate_exact)/rate_exact ) > tol )
       {
         std::cout << std::scientific << std::setprecision(16)
                   << "Error: Mismatch in rate values." << std::endl
                   << "T = " << T << " K" << std::endl
                   << "rate(T) = " << rate << std::endl
                   << "rate_exact = " << rate_exact << std::endl
                   << "relative difference = " <<  abs( (rate - rate_exact)/rate_exact ) << std::endl
                   << "tolerance = " <<  tol << std::endl;
         return_flag = 1;
       }
     if( abs( (derive - derive_exact)/derive_exact ) > tol )
       {
         std::cout << std::scientific << std::setprecision(16)
                   << "Error: Mismatch in rate derivative values." << std::endl
                   << "T = " << T << " K" << std::endl
                   << "drate_dT(T) = " << derive << std::endl
                   << "derive_exact = " << derive_exact << std::endl
                   << "relative difference = " <<  abs( (derive - derive_exact)/derive_exact ) << std::endl
                   << "tolerance = " <<  tol << std::endl;
         return_flag = 1;
       }
      return return_flag;
 }
int main ()
Definition at line 132 of file berthelot_rate_unit.C.
 {
   return (tester<double>() ||
           tester<long double>() ||
           tester<float>());
 }
template<typename Scalar > int test_values (const Scalar & Cf, const Scalar & D, const Antioch::BerthelotRate< Scalar > & berthelot_rate)
Definition at line 68 of file berthelot_rate_unit.C.
References check_rate_and_derivative(), Antioch::BerthelotRate< CoeffType >::derivative(), and Antioch::BerthelotRate< CoeffType >::rate_and_derivative.
Referenced by tester().
 {
   using std::abs;
   using std::exp;
   int return_flag = 0;
   for(Scalar T = 300.1; T <= 2500.1; T += 10.)
   {
     const Scalar rate_exact = Cf*exp(D*T);
     const Scalar derive_exact = D * Cf * exp(D*T);
     Antioch::KineticsConditions<Scalar> cond(T);
 //KineticsConditions
     Scalar rate = berthelot_rate(cond);
     Scalar deriveRate = berthelot_rate.derivative(cond);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
     berthelot_rate.rate_and_derivative(cond,rate,deriveRate);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
 // T
     rate = berthelot_rate(T);
     deriveRate = berthelot_rate.derivative(T);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
     berthelot_rate.rate_and_derivative(T,rate,deriveRate);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
   }
   return return_flag;
 }
template<typename Scalar > int tester ()
Definition at line 105 of file berthelot_rate_unit.C.
References Antioch::KineticsModel::D, Antioch::BerthelotRate< CoeffType >::reset_coefs(), Antioch::BerthelotRate< CoeffType >::set_Cf(), Antioch::BerthelotRate< CoeffType >::set_D(), and test_values().
 {
   Scalar Cf = 1.4;
   Scalar D  = -5.0;
   Antioch::BerthelotRate<Scalar> berthelot_rate(Cf,D);
   int return_flag = test_values(Cf,D,berthelot_rate);
   Cf = 1e-7;
   D = 1e-3;
   berthelot_rate.set_Cf(Cf);
   berthelot_rate.set_D(D);
   return_flag = test_values(Cf,D,berthelot_rate) || return_flag;
   Cf = 2.1e-11;
   D = -1.2;
   std::vector<Scalar> values(2);
   values[0] = Cf;
   values[1] = D;
   berthelot_rate.reset_coefs(values);
   return_flag = test_values(Cf,D,berthelot_rate) || return_flag;
   return return_flag;
 }