antioch-0.4.0: test/blottner_viscosity_unit.C File Reference
blottner_viscosity_unit.C File Reference
#include <iostream>
#include <cmath>
#include "antioch/blottner_viscosity.h"
Functions
template<typename Scalar >
int test_viscosity (const Scalar mu, const Scalar mu_exact, const Scalar tol)
template<typename Scalar >
int tester ()
int main ()
Function Documentation
int main ()
Definition at line 97 of file blottner_viscosity_unit.C.
 {
   return (tester<double>() ||
           tester<long double>() ||
           tester<float>());
 }
template<typename Scalar > int test_viscosity (const Scalar mu, const Scalar mu_exact, const Scalar tol)
Definition at line 40 of file blottner_viscosity_unit.C.
Referenced by tester().
 {
   using std::abs;
   int return_flag = 0;
   const double rel_error = abs( (mu - mu_exact)/mu_exact);
   if( rel_error  > tol )
     {
       std::cerr << "Error: Mismatch in viscosity" << std::endl
                 << "mu(T)    = " << mu << std::endl
                 << "mu_exact = " << mu_exact << std::endl
                 << "rel_error = " << rel_error << std::endl
                 << "tol = " << tol << std::endl;
       return_flag = 1;
     }
   return return_flag;
 }
template<typename Scalar > int tester ()
Definition at line 62 of file blottner_viscosity_unit.C.
References Antioch::BlottnerViscosity< CoeffType >::reset_coeffs(), and test_viscosity().
 {
   const Scalar a = 3.14e-3;
   const Scalar b = 2.71e-2;
   const Scalar c = 42.0e-5;
   Antioch::BlottnerViscosity<Scalar> mu(a,b,c);
   std::cout << mu << std::endl;
   const Scalar T = 1521.2;
   // octave gives
   const Scalar mu_exact = 0.144422234167703;
   int return_flag = 0;
   const Scalar tol = 1.0e-14;
   return_flag = test_viscosity( mu(T), mu_exact, tol );
   const Scalar a2 = 1e-3;
   const Scalar b2 = 2e-2;
   const Scalar c2 = 3e-5;
   mu.reset_coeffs( a2, b2, c2 );
   // octave gives
   const Scalar mu_exact2 = 0.122172495548880;
   return_flag = test_viscosity( mu(T), mu_exact2, tol );
   return return_flag;
 }