antioch-0.4.0: test/hercourtessen_rate_unit.C File Reference
hercourtessen_rate_unit.C File Reference
#include <limits>
#include <vector>
#include "antioch/hercourtessen_rate.h"
Functions
template<typename Scalar >
int check_rate_and_derivative (const Scalar &rate_exact, const Scalar &derive_exact, const Scalar &rate, const Scalar &derive, const Scalar &T)
template<typename Scalar >
int test_values (const Scalar &Cf, const Scalar &eta, const Scalar &Tref, const Antioch::HercourtEssenRate< Scalar > &hercourtessen_rate)
template<typename Scalar >
int tester ()
int main ()
Function Documentation
template<typename Scalar > int check_rate_and_derivative (const Scalar & rate_exact, const Scalar & derive_exact, const Scalar & rate, const Scalar & derive, const Scalar & T)
Definition at line 34 of file hercourtessen_rate_unit.C.
Referenced by test_values().
 {
     const Scalar tol = std::numeric_limits<Scalar>::epsilon() * 2;
     int return_flag(0);
     if( abs( (rate - rate_exact)/rate_exact ) > tol )
       {
         std::cout << std::scientific << std::setprecision(16)
                   << "Error: Mismatch in rate values." << std::endl
                   << "T = " << T << " K" << std::endl
                   << "rate(T) = " << rate << std::endl
                   << "rate_exact = " << rate_exact << std::endl
                   << "relative difference = " <<  abs( (rate - rate_exact)/rate_exact ) << std::endl
                   << "tolerance = " <<  tol << std::endl;
         return_flag = 1;
       }
     if( abs( (derive - derive_exact)/derive_exact ) > tol )
       {
         std::cout << std::scientific << std::setprecision(16)
                   << "Error: Mismatch in rate derivative values." << std::endl
                   << "T = " << T << " K" << std::endl
                   << "drate_dT(T) = " << derive << std::endl
                   << "derive_exact = " << derive_exact << std::endl
                   << "relative difference = " <<  abs( (derive - derive_exact)/derive_exact ) << std::endl
                   << "tolerance = " <<  tol << std::endl;
         return_flag = 1;
       }
      return return_flag;
 }
int main ()
Definition at line 143 of file hercourtessen_rate_unit.C.
 {
   return (tester<double>() ||
           tester<long double>() ||
           tester<float>());
 }
template<typename Scalar > int test_values (const Scalar & Cf, const Scalar & eta, const Scalar & Tref, const Antioch::HercourtEssenRate< Scalar > & hercourtessen_rate)
Definition at line 68 of file hercourtessen_rate_unit.C.
References check_rate_and_derivative(), Antioch::HercourtEssenRate< CoeffType >::derivative(), std::pow(), and Antioch::HercourtEssenRate< CoeffType >::rate_and_derivative.
Referenced by tester().
 {
   using std::abs;
   using std::pow;
   int return_flag = 0;
   for(Scalar T = 300.1L; T <= 2500.1L; T += 10.L)
   {
     const Scalar rate_exact = Cf * pow(T/Tref,eta);
     const Scalar derive_exact = Cf * eta * pow(T/Tref,eta)/T;
     Antioch::KineticsConditions<Scalar> cond(T);
 // KineticsConditions
     Scalar rate = hercourtessen_rate(cond);
     Scalar deriveRate = hercourtessen_rate.derivative(cond);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
     hercourtessen_rate.rate_and_derivative(cond,rate,deriveRate);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
 // T
     rate = hercourtessen_rate(T);
     deriveRate = hercourtessen_rate.derivative(T);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
     hercourtessen_rate.rate_and_derivative(T,rate,deriveRate);
     return_flag = check_rate_and_derivative(rate_exact,derive_exact,rate,deriveRate,T) || return_flag;
   }
   return return_flag;
 }
template<typename Scalar > int tester ()
Definition at line 106 of file hercourtessen_rate_unit.C.
References Antioch::HercourtEssenRate< CoeffType >::reset_coefs(), Antioch::HercourtEssenRate< CoeffType >::set_Cf(), Antioch::HercourtEssenRate< CoeffType >::set_eta(), Antioch::HercourtEssenRate< CoeffType >::set_Tref(), test_values(), and Antioch::KineticsModel::Tref().
 {
   Scalar Cf = 1.4L;
   Scalar eta = 1.2L;
   Scalar Tref = 1.L;
   Antioch::HercourtEssenRate<Scalar> hercourtessen_rate(Cf,eta); // default
   int return_flag = test_values(Cf,eta,Tref,hercourtessen_rate);
   Cf = 1e-7L;
   eta = 0.7L;
   Tref = 300.L;
   hercourtessen_rate.set_Cf(Cf);
   hercourtessen_rate.set_eta(eta);
   hercourtessen_rate.set_Tref(Tref);
   return_flag = test_values(Cf,eta,Tref,hercourtessen_rate) || return_flag;
   Cf = 2.1e-11L;
   eta = -2.3L;
   std::vector<Scalar> values(2);
   values[0] = Cf;
   values[1] = eta;
   hercourtessen_rate.reset_coefs(values);
   return_flag = test_values(Cf,eta,Tref,hercourtessen_rate) || return_flag;
   Tref = 298.L;
   values.resize(3);
   values[0] = Cf;
   values[1] = eta;
   values[2] = Tref;
   hercourtessen_rate.reset_coefs(values);
   return_flag = test_values(Cf,eta,Tref,hercourtessen_rate) || return_flag;
   return return_flag;
 }