antioch-0.4.0: std Namespace Reference
std Namespace Reference
Functions
template<template< typename, int, int, int, int, int > class _Matrix, typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols>
max (const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > &a, const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > &b) ANTIOCH_AUTOFUNC(_Matrix< _Scalar ANTIOCH_COMMA _Rows ANTIOCH_COMMA _Cols ANTIOCH_COMMA _Options ANTIOCH_COMMA _MaxRows ANTIOCH_COMMA _MaxCols >
a array ().max(b.array())) template< template< typename
typename _Scalar int _Rows int
_Cols int _Options int
_MaxRows int _MaxCols inline min (const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > &a, const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > &b) ANTIOCH_AUTOFUNC(_Matrix< _Scalar ANTIOCH_COMMA _Rows ANTIOCH_COMMA _Cols ANTIOCH_COMMA _Options ANTIOCH_COMMA _MaxRows ANTIOCH_COMMA _MaxCols >
template<typename T >
Antioch::enable_if_c
< Antioch::is_valarray< T >
::value, std::ostream & >
::type operator<< (std::ostream &output, const T &a)
template<typename T , typename T2 >
Antioch::enable_if_c
< Antioch::is_valarray< T >
::value, typename
Antioch::state_type< T >::type >
::type pow (const T &in, const T2 &n)
template<typename T >
std::valarray< T > max (const std::valarray< T > &a, const std::valarray< T > &b)
template<typename T >
std::valarray< T > min (const std::valarray< T > &a, const std::valarray< T > &b)
template<typename T >
std::ostream & operator<< (std::ostream &output, const std::vector< T > &a)
template<typename T >
std::vector< T > operator* (const std::vector< T > &src, const T &mul)
template<typename T >
std::vector< T > operator/ (const std::vector< T > &src, const T &mul)
Variables
a int
Function Documentation
a std::array ()
template<template< typename, int, int, int, int, int > class _Matrix, typename _Scalar , int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> std::max (const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & a, const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & b) inline
Referenced by Antioch::SigmaBinConverter< VectorCoeffType >::custom_bin_value(), Antioch::StatMechThermodynamics< CoeffType >::cv_rot(), Antioch::IdealGasMicroThermo< MacroThermo, CoeffType >::cv_rot_over_R(), Antioch::StatMechThermodynamics< CoeffType >::cv_rot_over_R(), Antioch::ReactionSet< CoeffType >::get_parameter_of_reaction(), Antioch::max(), max(), Antioch::ReactionSet< CoeffType >::set_parameter_of_reaction(), Antioch::StatMechThermodynamics< CoeffType >::T_from_e_tot(), and vec_compare().
template<typename T > std::valarray< T > std::max (const std::valarray< T > & a, const std::valarray< T > & b) inline
Definition at line 83 of file valarray_utils.h.
References max().
 {
   using std::max;
   const size_t size = a.size();
   std::valarray<T> out(size);
   for (size_t i=0; i != size; ++i)
     out[i] = max(a[i], b[i]);
   return out;
 }
std::min (const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & a, const _Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > & b) inline
Referenced by Antioch::SigmaBinConverter< VectorCoeffType >::custom_bin_value(), Antioch::min(), min(), and Antioch::StatMechThermodynamics< CoeffType >::T_from_e_tot().
template<typename T > std::valarray< T > std::min (const std::valarray< T > & a, const std::valarray< T > & b) inline
Definition at line 98 of file valarray_utils.h.
References min().
 {
   using std::min;
   const size_t size = a.size();
   std::valarray<T> out(size);
   for (size_t i=0; i != size; ++i)
     out[i] = min(a[i], b[i]);
   return out;
 }
template<typename T > std::vector< T > std::operator* (const std::vector< T > & src, const T & mul) inline
Definition at line 67 of file vector_utils.h.
 {
   std::vector<T> output(src);
   const std::size_t size = src.size();
   for (std::size_t i=1; i<size; ++i)
     output[i] = src[i] * mul;
   return output;
 }
template<typename T > std::vector< T > std::operator/ (const std::vector< T > & src, const T & mul) inline
Definition at line 80 of file vector_utils.h.
 {
   std::vector<T> output(src);
   const std::size_t size = src.size();
   for (std::size_t i=1; i<size; ++i)
     output[i] = src[i] / mul;
   return output;
 }
template<typename T > std::ostream & std::operator<< (std::ostream & output, const std::vector< T > & a) inline
Definition at line 52 of file vector_utils.h.
 {
   output << '{';
   const std::size_t size = a.size();
   if (size)
     output << a[0];
   for (std::size_t i=1; i<size; ++i)
     output << ',' << a[i];
   output << '}';
   return output;
 }
template<typename T > Antioch::enable_if_c< Antioch::is_valarray< T >::value, std::ostream & >::type std::operator<< (std::ostream & output, const T & a) inline
Definition at line 54 of file valarray_utils.h.
 {
   output << '{';
   const std::size_t size = a.size();
   if (size)
     output << a[0];
   for (std::size_t i=1; i<size; ++i)
     output << ',' << a[i];
   output << '}';
   return output;
 }
template<typename T , typename T2 > Antioch::enable_if_c< Antioch::is_valarray< T >::value, typename Antioch::state_type< T >::type >::type std::pow (const T & in, const T2 & n) inline
Definition at line 71 of file valarray_utils.h.
Referenced by Antioch::Units< T >::add_SI(), BHE(), Antioch::build_rate(), Antioch::Units< T >::develop_symbol(), F(), FTroe(), Antioch::ReactionSet< CoeffType >::get_reactive_scheme(), HE(), Kooij(), Antioch::MixtureAveragedTransportMixture< CoeffType >::MixtureAveragedTransportMixture(), Antioch::Units< T >::raise(), test_values(), tester(), vectester(), VH(), and Antioch::WilkeMixture< CoeffType >::WilkeMixture().
 {
   typename Antioch::state_type<T>::type out=in;
   const size_t size = in.size();
   for (size_t i=0; i != size; ++i)
     out[i] = pow(in[i], n);
   return out;
 }
Variable Documentation
a std::int
Definition at line 67 of file eigen_utils.h.
Referenced by Antioch::ChemKinParser< NumericType >::parse_equation(), Antioch::ASCIIParser< NumericType >::read_chemical_species(), Antioch::ASCIIParser< NumericType >::read_electronic_data(), Antioch::ASCIIParser< NumericType >::read_vibrational_data(), Antioch::UnitBaseConstant::SIPrefixeStore< T >::SIPrefixeStore(), Antioch::SplitString(), Antioch::UnitBaseConstant::UnitBaseStore< T >::UnitBaseStore(), and tinyxml2::XMLPrinter::XMLPrinter().