antioch-0.4.0: test/rotational_relaxation_unit.C File Reference
rotational_relaxation_unit.C File Reference
#include "antioch/rotational_relaxation.h"
#include "antioch/metaprogramming.h"
#include <iostream>
#include <iomanip>
#include <limits>
#include <cmath>
Functions
const long double pi (3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825)
template<typename Scalar >
Scalar F (const Scalar &x)
template<typename Scalar >
Scalar Z (const Scalar &T, const Scalar &eps_kb, const Scalar &z_298)
template<typename Scalar >
int tester ()
int main ()
Function Documentation
template<typename Scalar > Scalar F (const Scalar & x)
Definition at line 40 of file rotational_relaxation_unit.C.
References pi(), and std::pow().
Referenced by tester(), and Z().
 {
   return 1.L + std::pow(pi,1.5)/2.L * std::sqrt(x)
              + (pi*pi/4.L + 2.L) * x
              + std::pow(pi * x,1.5);
 }
int main ()
Definition at line 90 of file rotational_relaxation_unit.C.
 {
   return (tester<double>() ||
           tester<long double>() ||
           tester<float>());
 }
const long double pi (3. 141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825)
Referenced by F().
template<typename Scalar > int tester ()
Definition at line 55 of file rotational_relaxation_unit.C.
References Z(), and z().
 {
   using std::abs;
   int return_flag = 0;
   const Scalar tol = (std::numeric_limits<Scalar>::epsilon() * 10 < 5e-17)?5e-17:
                       std::numeric_limits<Scalar>::epsilon() * 10;
   const Scalar eps_kb = 97.53L; // N2 value
   const Scalar z_298 = 4.0L; // N2 value
   Antioch::RotationalRelaxation<Scalar> rot(z_298,eps_kb);
   for(Scalar T = 300.1; T <= 2500.1; T += 10.)
   {
      Scalar z = rot(T);
      Scalar z_exact = Z(T,eps_kb,z_298);
     if( abs( (z - z_exact)/z_exact) > tol )
       {
           std::cout << std::scientific << std::setprecision(16)
                     << "Error: Mismatch in rotational relaxation values." << std::endl
                     << " T = " << T << std::endl
                     << " z = " << z << std::endl
                     << " z_exact = " << z_exact << std::endl
                     << " relative error = " << std::abs(z - z_exact)/z_exact << std::endl
                     << " tolerance = " << tol << std::endl;
           return_flag = 1;
      }
   }
   return return_flag;
 }
template<typename Scalar > Scalar Z (const Scalar & T, const Scalar & eps_kb, const Scalar & z_298)
Definition at line 48 of file rotational_relaxation_unit.C.
References F().
Referenced by tester(), and vectester().
 {
   return z_298 * F(eps_kb / 298.L) / F(eps_kb / T);
 }