antioch-0.4.0: Antioch::UnitBaseStorage Namespace Reference
Antioch::UnitBaseStorage Namespace Reference
Functions
const
UnitBaseConstant::UnitBaseStore
< long double > known_units ()
const
UnitBaseConstant::SIPrefixeStore
< long double > known_prefixes ()
Variables
const
UnitBaseConstant::UnitBaseStore
< long double > storage_unit
const
UnitBaseConstant::SIPrefixeStore
< long double > storage_prefixe
Function Documentation
const UnitBaseConstant::SIPrefixeStore<long double> Antioch::UnitBaseStorage::known_prefixes () inline
Definition at line 71 of file unit_defs.h.
References storage_prefixe.
Referenced by Antioch::Units< T >::parse_prefix_unit(), and Antioch::Units< T >::parse_single_unit().
 {
   return storage_prefixe;
 }
const UnitBaseConstant::UnitBaseStore<long double> Antioch::UnitBaseStorage::known_units () inline
Definition at line 65 of file unit_defs.h.
References storage_unit.
Referenced by Antioch::Units< T >::get_SI_convenient_symb(), Antioch::Units< T >::indexUnit(), Antioch::Units< T >::parse_prefix_unit(), Antioch::Units< T >::parse_single_unit(), and test_factor().
 {
    return storage_unit;
 }
Variable Documentation
const UnitBaseConstant::SIPrefixeStore<long double> Antioch::UnitBaseStorage::storage_prefixe
Definition at line 62 of file unit_defs.h.
Referenced by known_prefixes().
const UnitBaseConstant::UnitBaseStore<long double> Antioch::UnitBaseStorage::storage_unit
Definition at line 61 of file unit_defs.h.
Referenced by known_units().